# nzi_pro/core/migrations.py
from core.database import db_backend, get_conn
from services.permissions import ensure_permission_schema


def run_migrations():
    with get_conn() as con:
        if db_backend() == "postgres":
            con.execute(
                """
                CREATE TABLE IF NOT EXISTS clients (
                  db_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_name VARCHAR,
                  industry VARCHAR,
                  description_long TEXT,
                  website VARCHAR,
                  year_end_month VARCHAR,
                  company_reg VARCHAR,
                  sic_code VARCHAR,
                  headquarters VARCHAR,
                  addr_line1 VARCHAR,
                  addr_line2 VARCHAR,
                  addr_city VARCHAR,
                  addr_region VARCHAR,
                  addr_postcode VARCHAR,
                  addr_country VARCHAR,
                  logo_url VARCHAR,
                  crm_owner VARCHAR,
                  status VARCHAR DEFAULT 'Active',
                  net_zero_year INTEGER DEFAULT 2050,
                  interim_year INTEGER DEFAULT 2035,
                  interim_s1_pct INTEGER DEFAULT 50,
                  interim_s2_pct INTEGER DEFAULT 50,
                  interim_s3_pct INTEGER DEFAULT 50,
                  portfolio VARCHAR,
                  target_s1_year INTEGER,
                  target_s2_year INTEGER,
                  target_s3_year INTEGER,
                  target_s1_pct INTEGER,
                  target_s2_pct INTEGER,
                  target_s3_pct INTEGER,
                  benchmark_year INTEGER
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS client_contacts (
                  contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_db_id INTEGER,
                  full_name VARCHAR,
                  job_title VARCHAR,
                  email VARCHAR,
                  phone VARCHAR,
                  is_primary BOOLEAN DEFAULT FALSE
                )
                """
            )
            
            # Add columns if they don't exist (for existing databases)
            con.execute(
                """
                ALTER TABLE client_contacts 
                ADD COLUMN IF NOT EXISTS phone VARCHAR
                """
            )
            con.execute(
                """
                ALTER TABLE client_contacts 
                ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT FALSE
                """
            )
            
            # Add logo file upload field and benchmark period dates to clients
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS logo_file VARCHAR")
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS benchmark_period_start DATE")
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS benchmark_period_end DATE")
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS currency VARCHAR DEFAULT 'GBP'")
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS sic_code VARCHAR")
            
            # Create system settings table for NZI logo and other global settings
            con.execute(
                """
                CREATE TABLE IF NOT EXISTS system_settings (
                  setting_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  setting_key VARCHAR UNIQUE NOT NULL,
                  setting_value TEXT,
                  setting_type VARCHAR DEFAULT 'text',
                  description TEXT,
                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  updated_by VARCHAR
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS client_sites (
                  site_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_db_id INTEGER,
                  site_name VARCHAR,
                  location VARCHAR,
                  is_registered_office BOOLEAN NOT NULL DEFAULT FALSE,
                  archived BOOLEAN DEFAULT FALSE,
                  archived_at TIMESTAMP,
                  archived_by VARCHAR
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS client_notes (
                  note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_db_id INTEGER,
                  author VARCHAR,
                  note_text TEXT,
                  created_at TIMESTAMP DEFAULT NOW()
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS datasets (
                  dataset_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR,
                  source VARCHAR,
                  analysis_type VARCHAR,
                  country VARCHAR,
                  region VARCHAR,
                  currency VARCHAR,
                  year INTEGER,
                  version VARCHAR,
                  license VARCHAR,
                  notes TEXT,
                  valid_from DATE,
                  valid_to DATE,
                  created_at TIMESTAMP DEFAULT NOW()
                )
                """
            )
            
            con.execute("ALTER TABLE datasets ADD COLUMN IF NOT EXISTS valid_from DATE")
            con.execute("ALTER TABLE datasets ADD COLUMN IF NOT EXISTS valid_to DATE")
            con.execute("ALTER TABLE datasets ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE datasets ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
            con.execute("ALTER TABLE datasets ADD COLUMN IF NOT EXISTS archived_by VARCHAR")

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS custom_factors (
                  factor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  country VARCHAR,
                  scope VARCHAR,
                  description TEXT,
                  uom VARCHAR,
                  ghg_unit VARCHAR,
                  source VARCHAR,
                  factor_2018 DOUBLE PRECISION,
                  factor_2019 DOUBLE PRECISION,
                  factor_2020 DOUBLE PRECISION,
                  factor_2021 DOUBLE PRECISION,
                  factor_2022 DOUBLE PRECISION,
                  factor_2023 DOUBLE PRECISION,
                  factor_2024 DOUBLE PRECISION,
                  factor_2025 DOUBLE PRECISION,
                  factor_2026 DOUBLE PRECISION,
                  factor_2027 DOUBLE PRECISION,
                  factor_2028 DOUBLE PRECISION,
                  factor_2029 DOUBLE PRECISION,
                  factor_2030 DOUBLE PRECISION,
                  created_by VARCHAR,
                  created_at TIMESTAMP DEFAULT NOW(),
                  updated_by VARCHAR,
                  updated_at TIMESTAMP,
                  archived BOOLEAN DEFAULT FALSE,
                  archived_at TIMESTAMP,
                  archived_by VARCHAR
                )
                """
            )

            # Custom factors: governance + scoping + unlimited years support.
            con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS custom_id VARCHAR")
            con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS report_label VARCHAR")
            con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS category VARCHAR")
            con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS client_db_id INTEGER")
            con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS is_global BOOLEAN DEFAULT TRUE")
            con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE")

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS custom_factor_year_values (
                  factor_id INTEGER NOT NULL REFERENCES custom_factors(factor_id) ON DELETE CASCADE,
                  year INTEGER NOT NULL,
                  factor DOUBLE PRECISION,
                  PRIMARY KEY (factor_id, year)
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS factor_lookup (
                  db_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  dataset_id INTEGER,
                  file_name VARCHAR,
                  year INTEGER,
                  original_id VARCHAR,
                  scope VARCHAR,
                  level_1 VARCHAR,
                  level_2 VARCHAR,
                  level_3 VARCHAR,
                  level_4 VARCHAR,
                  column_text VARCHAR,
                  uom VARCHAR,
                  ghg_unit VARCHAR,
                  factor NUMERIC,
                  source VARCHAR,
                  region VARCHAR,
                  currency VARCHAR,
                  method VARCHAR,
                  valid_from DATE,
                  valid_to DATE,
                  report_label VARCHAR
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS job_types (
                  job_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR UNIQUE,
                  is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """
            )

            con.execute("ALTER TABLE job_types ADD COLUMN IF NOT EXISTS description TEXT")
            con.execute("ALTER TABLE job_types ADD COLUMN IF NOT EXISTS unit_price_ex_vat NUMERIC")
            con.execute("ALTER TABLE job_types ADD COLUMN IF NOT EXISTS vat_rate_id INTEGER")
            con.execute("ALTER TABLE job_types ADD COLUMN IF NOT EXISTS estimated_hours NUMERIC(10,2) DEFAULT 0")
            con.execute("ALTER TABLE job_types ADD COLUMN IF NOT EXISTS is_crp BOOLEAN DEFAULT FALSE")

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS vat_rates_lookup (
                  vat_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name TEXT NOT NULL,
                  rate_pct NUMERIC NOT NULL,
                  is_default BOOLEAN NOT NULL DEFAULT FALSE,
                  is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """
            )

            con.execute(
                """
                INSERT INTO vat_rates_lookup (name, rate_pct, is_default, is_active)
                SELECT '20%% Standard Rate', 20, TRUE, TRUE
                WHERE NOT EXISTS (
                  SELECT 1 FROM vat_rates_lookup WHERE lower(name)=lower('20%% Standard Rate')
                )
                """
            )
            con.execute(
                """
                INSERT INTO vat_rates_lookup (name, rate_pct, is_default, is_active)
                SELECT 'No VAT', 0, FALSE, TRUE
                WHERE NOT EXISTS (
                  SELECT 1 FROM vat_rates_lookup WHERE lower(name)=lower('No VAT')
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS job_statuses_lookup (
                  status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name TEXT UNIQUE,
                  sort_order INTEGER,
                  is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """
            )

            # Insert default job statuses
            default_statuses = [
                ("Open", 10, True),
                ("Data Gathering Phase", 20, True),
                ("Reporting Phase", 30, True),
                ("Awaiting Client Input", 40, True),
                ("Completed", 50, True),
                ("Closed", 60, True),
            ]
            for name, sort_order, is_active in default_statuses:
                con.execute(
                    """
                    INSERT INTO job_statuses_lookup (name, sort_order, is_active)
                    SELECT %s, %s, %s
                    WHERE NOT EXISTS (
                      SELECT 1 FROM job_statuses_lookup WHERE lower(name)=lower(%s)
                    )
                    """,
                    [name, sort_order, is_active, name],
                )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS time_subjects (
                  subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR,
                  is_active BOOLEAN NOT NULL DEFAULT TRUE,
                  budget_hours NUMERIC(10,2) DEFAULT 0
                )
                """
            )
            
            # Add budget_hours column if it doesn't exist (for existing tables)
            try:
                con.execute(
                    """
                    ALTER TABLE time_subjects 
                    ADD COLUMN IF NOT EXISTS budget_hours NUMERIC(10,2) DEFAULT 0
                    """
                )
            except Exception:
                pass  # Column might already exist

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS portfolios_lookup (
                  portfolio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR,
                  is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS feedback_items (
                  feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  feedback_type VARCHAR NOT NULL,
                  title TEXT NOT NULL,
                  details TEXT,
                  process_name VARCHAR,
                  page_path VARCHAR,
                  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
                  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                  created_by VARCHAR NOT NULL,
                  updated_at TIMESTAMP,
                  completed_at TIMESTAMP,
                  completed_by VARCHAR
                )
                """
            )
            con.execute("ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS process_name VARCHAR")
            con.execute("ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS page_path VARCHAR")

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS jobs (
                  job_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  client_db_id INTEGER,
                  job_type_id INTEGER,
                  job_type VARCHAR,
                  job_number VARCHAR,
                  title VARCHAR,
                  reporting_year INTEGER,
                  reporting_period_start DATE,
                  reporting_period_end DATE,
                  crp_id INTEGER,
                  status VARCHAR DEFAULT 'Open',
                  start_date DATE,
                  due_date DATE,
                  created_at TIMESTAMP DEFAULT NOW()
                )
                """
            )
            
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reporting_period_start DATE")
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reporting_period_end DATE")
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS legacy_job_no VARCHAR")

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS job_templates (
                  job_template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  template_key VARCHAR UNIQUE NOT NULL,
                  template_name VARCHAR,
                  excel_template_path VARCHAR,
                  crp_template_path VARCHAR,
                  is_active BOOLEAN NOT NULL DEFAULT TRUE,
                  created_at TIMESTAMP DEFAULT NOW()
                )
                """
            )

            con.execute("ALTER TABLE job_templates ADD COLUMN IF NOT EXISTS template_type VARCHAR DEFAULT 'dataset'")
            con.execute("ALTER TABLE job_templates ADD COLUMN IF NOT EXISTS file_path VARCHAR")
            
            # Insert default Standard UK template
            con.execute(
                """
                INSERT INTO job_templates (template_key, template_name, template_type, excel_template_path, is_active)
                SELECT 'STANDARD_UK', 'NZI Standard UK Template', 'dataset', 
                       'templates/NZI Data Upload Template - Standard UK.xlsx', TRUE
                WHERE NOT EXISTS (
                  SELECT 1 FROM job_templates WHERE template_key = 'STANDARD_UK'
                )
                """
            )
            
            # Deactivate old Basic UK template if it exists
            con.execute(
                """
                UPDATE job_templates 
                SET is_active = FALSE 
                WHERE template_key = 'BASIC_UK' OR excel_template_path ILIKE %s
                """,
                ['%Basic UK%']
            )
            
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_template_id INTEGER")
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS crm_name VARCHAR")

            con.execute(
                """
                DO $$
                BEGIN
                  IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'jobs_job_template_id_fkey'
                  ) THEN
                    ALTER TABLE jobs
                      ADD CONSTRAINT jobs_job_template_id_fkey
                      FOREIGN KEY (job_template_id)
                      REFERENCES job_templates(job_template_id);
                  END IF;
                END $$;
                """
            )

            # Add archive columns to multiple tables
            con.execute("ALTER TABLE job_templates ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE job_templates ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
            con.execute("ALTER TABLE job_templates ADD COLUMN IF NOT EXISTS archived_by VARCHAR")
            
            con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
            con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS archived_by VARCHAR")
            
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS archived_by VARCHAR")
            
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS archived_by VARCHAR")
            con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_crp BOOLEAN DEFAULT FALSE")
            
            con.execute("ALTER TABLE client_sites ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE client_sites ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
            con.execute("ALTER TABLE client_sites ADD COLUMN IF NOT EXISTS archived_by VARCHAR")

            con.execute(
                """
                INSERT INTO job_templates (template_key, template_name, excel_template_path, crp_template_path, is_active)
                SELECT
                  'basic_uk',
                  'NZI Data Upload Template - Basic UK',
                  'templates/NZI Data Upload Template - Basic UK.xlsx',
                  'templates/DEMOCO Carbon Reduction Plan Dec 2025 - Second Year Onwards.docx',
                  TRUE
                WHERE NOT EXISTS (
                  SELECT 1 FROM job_templates WHERE template_key='basic_uk'
                )
                """
            )

            con.execute(
                """
                UPDATE jobs
                SET job_template_id = (
                  SELECT job_template_id FROM job_templates WHERE template_key='basic_uk' LIMIT 1
                )
                WHERE job_template_id IS NULL
                """
            )

            con.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS jobs_job_number_uidx
                ON jobs (job_number)
                """
            )

            con.execute(
                """
                CREATE TABLE IF NOT EXISTS time_logs (
                  time_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  job_id INTEGER,
                  user_id VARCHAR,
                  subject VARCHAR,
                  work_date DATE,
                  minutes INTEGER,
                  notes TEXT,
                  created_at TIMESTAMP DEFAULT NOW()
                )
                """
            )

        # =========================
        # BASE LOOKUPS (legacy)
        # =========================
        con.execute("CREATE TABLE IF NOT EXISTS lookups (type VARCHAR, value VARCHAR)")

        # Migrate legacy job_types -> lookups (if present)
        try:
            has_job_types = con.execute(
                "SELECT COUNT(*) FROM information_schema.tables WHERE table_name='job_types'"
            ).fetchone()[0]
        except Exception:
            has_job_types = 0

        if has_job_types:
            con.execute(
                """
                INSERT INTO lookups (type, value)
                SELECT 'JobType', name
                FROM job_types
                WHERE NOT EXISTS (
                    SELECT 1 FROM lookups l WHERE l.type='JobType' AND l.value=job_types.name
                )
                """
            )

        # =========================
        # AUTH / RBAC (strict provisioning)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS roles_lookup (
                role_name VARCHAR PRIMARY KEY,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
            )
            """
        )

        con.execute(
            """
            INSERT INTO roles_lookup (role_name, is_active)
            VALUES
              ('Admin', TRUE),
              ('Consultant', TRUE),
              ('ReadOnly', TRUE),
              ('CRM', TRUE),
              ('QA', TRUE),
              ('Support', TRUE)
            ON CONFLICT (role_name) DO NOTHING
            """
        )

        con.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                user_id VARCHAR PRIMARY KEY,
                full_name VARCHAR,
                role VARCHAR NOT NULL DEFAULT 'ReadOnly',
                email VARCHAR NOT NULL,
                status VARCHAR NOT NULL DEFAULT 'Active'
            )
            """
        )

        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS position VARCHAR")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_at TIMESTAMP")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_by VARCHAR")
        con.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS invite_expires_at TIMESTAMP")

        con.execute(
            """
            UPDATE users
            SET email = user_id
            WHERE email IS NULL OR TRIM(email) = ''
            """
        )

        con.execute(
            """
            UPDATE users
            SET email = LOWER(TRIM(email))
            WHERE email IS NOT NULL
            """
        )

        con.execute("UPDATE users SET role='ReadOnly' WHERE role IS NULL OR TRIM(role)=''")
        con.execute("UPDATE users SET status='Active' WHERE status IS NULL OR TRIM(status)=''")

        con.execute(
            """
            DELETE FROM users u
            USING users v
            WHERE u.email = v.email
              AND u.ctid < v.ctid
            """
        )

        con.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relkind = 'i'
                      AND c.relname = 'users_email_uidx'
                ) THEN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_index i
                        JOIN pg_class c ON c.oid = i.indexrelid
                        WHERE c.relname = 'users_email_uidx'
                          AND i.indisunique
                    ) THEN
                        EXECUTE 'DROP INDEX IF EXISTS users_email_uidx';
                    END IF;
                END IF;
            END $$;
            """
        )

        con.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS users_email_uidx
            ON users (email)
            """
        )

        # =========================
        # Seed your 3 admins (strict provisioning)
        # =========================
        admins = [
            ("francis@netzero.international", "Francis Doherty", "Admin", "Active"),
            ("david@netzero.international", "David Hawes", "Admin", "Active"),
            ("jennie@netzero.international", "Jennie Davide", "Admin", "Active"),
        ]

        for email, full_name, role, status in admins:
            email_norm = email.strip().lower()
            con.execute(
                """
                INSERT INTO users (user_id, full_name, role, email, status)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (email) DO UPDATE SET
                    full_name = EXCLUDED.full_name,
                    role      = EXCLUDED.role,
                    status    = EXCLUDED.status,
                    user_id   = EXCLUDED.user_id
                """,
                [email_norm, full_name, role, email_norm, status],
            )

        ensure_permission_schema(con)

        # =========================
        # INDUSTRIES LOOKUP
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS industries_lookup (
                industry_id INTEGER PRIMARY KEY,
                name VARCHAR NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
            )
            """
        )

        con.execute(
            """
            CREATE TABLE IF NOT EXISTS positions_lookup (
                position_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR NOT NULL UNIQUE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
            )
            """
        )

        con.execute(
            """
            CREATE TABLE IF NOT EXISTS processes_lookup (
                process_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR NOT NULL UNIQUE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
            )
            """
        )
        for process_name in ["Client Onboarding", "Job Start", "Job Report", "General"]:
            con.execute(
                """
                INSERT INTO processes_lookup (name, is_active)
                SELECT %s, TRUE
                WHERE NOT EXISTS (
                    SELECT 1 FROM processes_lookup WHERE lower(name)=lower(%s)
                )
                """,
                [process_name, process_name],
            )

        try:
            exists = con.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_name='clients'"
            ).fetchone()
        except Exception:
            exists = None
        if exists:
            con.execute("ALTER TABLE clients ADD COLUMN IF NOT EXISTS industry VARCHAR")

        # =========================
        # PAYMENT TERMS LOOKUP (NEW)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS payment_terms_lookup (
                term_id INTEGER PRIMARY KEY,
                name VARCHAR NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
            )
            """
        )

        # Default term: 100% in advance
        con.execute(
            """
            INSERT INTO payment_terms_lookup (term_id, name, is_active)
            VALUES (1, '100%% in advance', TRUE)
            ON CONFLICT (term_id) DO NOTHING
            """
        )

        # =========================
        # CRP JOB DETAILS (NEW) - 1:1 with jobs
        # Reporting Year is REQUIRED even for Benchmark (Benchmark: B)
        # Payment terms is FK to lookup (Payment terms: FK)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS crp_job_details (
              job_id INTEGER PRIMARY KEY,

              reporting_period_from DATE,
              reporting_period_to   DATE,
              is_benchmark BOOLEAN NOT NULL DEFAULT FALSE,
              reporting_year INTEGER NOT NULL,

              is_renewal BOOLEAN NOT NULL DEFAULT FALSE,
              client_order_number VARCHAR,

              client_contact_name  VARCHAR,
              client_contact_email VARCHAR,

              report_signee_name     VARCHAR,
              report_signee_position VARCHAR,

              payment_term_id INTEGER NOT NULL DEFAULT 1
                REFERENCES payment_terms_lookup(term_id),

              free_training_place BOOLEAN NOT NULL DEFAULT FALSE,

              num_employees INTEGER,
              turnover_gbp NUMERIC,
              premises_size_m2 NUMERIC,
              vehicles_owned INTEGER,
              vehicles_leased INTEGER,
              premises_owned INTEGER,
              premises_leased INTEGER,

              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )

        # =========================
        # JOB PLAN MILESTONES (NEW)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS job_plan (
              job_id INTEGER PRIMARY KEY,
              data_collection_due DATE,
              first_draft_due DATE,
              final_report_due DATE,
              override_dates BOOLEAN NOT NULL DEFAULT FALSE,
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )

        # =========================
        # JOB FILES STORAGE
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS job_files (
              file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
              row_id INTEGER,
              file_type VARCHAR NOT NULL,
              file_name VARCHAR NOT NULL,
              file_path TEXT,
              file_size BIGINT,
              mime_type VARCHAR,
              description TEXT,
              uploaded_by VARCHAR,
              uploaded_at TIMESTAMP DEFAULT NOW()
            )
            """
        )
        con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS storage_provider VARCHAR DEFAULT 'local'")
        con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS external_item_id VARCHAR")
        con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS external_web_url TEXT")
        con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS external_path TEXT")

        # =========================
        # SCOPE / DATASET CONFIG (NEW)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS job_scope_config (
              job_id INTEGER NOT NULL,
              scope VARCHAR NOT NULL,
              include_scope BOOLEAN NOT NULL DEFAULT TRUE,
              dataset_id INTEGER,
              factor_method VARCHAR,
              PRIMARY KEY (job_id, scope)
            )
            """
        )

        # =========================
        # FACTOR LOOKUP (existing)
        # =========================
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS original_id VARCHAR")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS year INTEGER")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS level_4 VARCHAR")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS ghg_unit VARCHAR")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS method VARCHAR")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS valid_from DATE")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS valid_to DATE")
        con.execute("ALTER TABLE factor_lookup ADD COLUMN IF NOT EXISTS report_label VARCHAR")

        # =========================
        # CUSTOM CONVERSION FACTORS (NEW)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS custom_conversion_factors (
              custom_factor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              client_db_id INTEGER,                  -- optional: link to specific client
              job_id INTEGER,                        -- optional: link to specific job
              
              custom_id VARCHAR NOT NULL,            -- user-defined ID (e.g., 'CUSTOM-001')
              scope VARCHAR NOT NULL,                -- 'Scope 1' | 'Scope 2' | 'Scope 3'
              category VARCHAR,
              report_label VARCHAR NOT NULL,         -- human-readable label
              
              level_1 VARCHAR,
              level_2 VARCHAR,
              level_3 VARCHAR,
              level_4 VARCHAR,
              
              uom VARCHAR NOT NULL,                  -- unit of measurement
              ghg_unit VARCHAR NOT NULL,             -- e.g., 'kg CO2e'
              factor NUMERIC NOT NULL,               -- conversion factor value
              
              source VARCHAR,                        -- where the factor came from
              method VARCHAR,                        -- 'Activity' | 'Spend' | 'Custom'
              notes TEXT,
              
              is_active BOOLEAN NOT NULL DEFAULT TRUE,
              created_at TIMESTAMP DEFAULT NOW(),
              created_by VARCHAR,
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )
        
        con.execute(
            """
            CREATE INDEX IF NOT EXISTS custom_factors_client_idx
            ON custom_conversion_factors (client_db_id, is_active)
            """
        )
        
        con.execute(
            """
            CREATE INDEX IF NOT EXISTS custom_factors_job_idx
            ON custom_conversion_factors (job_id, is_active)
            """
        )

        # =========================
        # CRP Scope data entries (NEW)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS crp_scope_entries (
              entry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              job_id INTEGER NOT NULL,
              scope VARCHAR NOT NULL,                -- 'Scope 1' | 'Scope 2' | 'Scope 3'

              category VARCHAR,
              subcategory VARCHAR,
              description VARCHAR,

              amount NUMERIC,
              unit VARCHAR,

              dataset_id INTEGER,                    -- copied from job_scope_config at time of entry
              factor_id INTEGER,                     -- optional link to factor_lookup
              factor_value NUMERIC,                  -- store the chosen factor value
              tco2e NUMERIC,                         -- calculated or overridden

              method VARCHAR,                        -- 'Activity' | 'Spend' | 'Custom'
              notes VARCHAR,

              is_archived BOOLEAN NOT NULL DEFAULT FALSE,
              created_at TIMESTAMP DEFAULT NOW(),
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )

        con.execute(
            """
            CREATE INDEX IF NOT EXISTS crp_scope_entries_job_scope_idx
            ON crp_scope_entries (job_id, scope, is_archived)
            """
        )
        
        # Add original_id and qty columns for backward compatibility
        con.execute("ALTER TABLE crp_scope_entries ADD COLUMN IF NOT EXISTS original_id VARCHAR")
        con.execute("ALTER TABLE crp_scope_entries ADD COLUMN IF NOT EXISTS qty NUMERIC")


        # =========================
        # PHASE A: SIMPLIFIED SCOPE ROWS (job_scope_rows)
        # =========================
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS job_scope_rows (
              row_id SERIAL PRIMARY KEY,
              job_id INTEGER NOT NULL REFERENCES jobs(job_id),
              site_id INTEGER REFERENCES client_sites(site_id),
              scope VARCHAR NOT NULL,                 -- 'Scope 1' | 'Scope 2' | 'Scope 3'
        
              dataset_id INTEGER REFERENCES datasets(dataset_id),
              factor_db_id INTEGER REFERENCES factor_lookup(db_id),
              original_id VARCHAR NOT NULL,           -- MUST match factor_lookup.original_id (DESNZ ID)
              category VARCHAR,
        
              level_1 VARCHAR,
              level_2 VARCHAR,
              level_3 VARCHAR,
              level_4 VARCHAR,
              column_text VARCHAR,
        
              report_label VARCHAR,
              notes VARCHAR,
              data_source VARCHAR,
              data_confidence VARCHAR,
              is_custom_entry BOOLEAN DEFAULT FALSE,
        
              enabled BOOLEAN NOT NULL DEFAULT TRUE,
        
              qty NUMERIC,
              uom VARCHAR,
              factor NUMERIC,
              ghg_unit VARCHAR,
              apply_pct NUMERIC DEFAULT 100,
        
              month_1 NUMERIC,
              month_2 NUMERIC,
              month_3 NUMERIC,
              month_4 NUMERIC,
              month_5 NUMERIC,
              month_6 NUMERIC,
              month_7 NUMERIC,
              month_8 NUMERIC,
              month_9 NUMERIC,
              month_10 NUMERIC,
              month_11 NUMERIC,
              month_12 NUMERIC,
        
              calc_tco2e NUMERIC,
              override_tco2e NUMERIC,
              override_reason VARCHAR,
        
              created_at TIMESTAMP DEFAULT NOW(),
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )
        
        con.execute(
            """
            CREATE INDEX IF NOT EXISTS job_scope_rows_job_scope_idx
            ON job_scope_rows (job_id, scope)
            """
        )
        
        con.execute(
            """
            CREATE INDEX IF NOT EXISTS job_scope_rows_job_scope_enabled_idx
            ON job_scope_rows (job_id, scope, enabled)
            """
        )
        
        # Add columns for template structure support
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_1 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_2 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_3 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_4 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_5 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_6 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_7 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_8 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_9 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_10 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_11 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS month_12 NUMERIC")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS apply_pct NUMERIC DEFAULT 100")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS data_source VARCHAR DEFAULT 'Company Data'")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS data_confidence VARCHAR DEFAULT 'M'")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS is_custom_entry BOOLEAN DEFAULT FALSE")
        con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS category VARCHAR")
        
        # Milestone templates system
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS milestone_templates (
              template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              template_name VARCHAR NOT NULL,
              description TEXT,
              is_active BOOLEAN DEFAULT TRUE,
              is_default BOOLEAN DEFAULT FALSE,
              created_at TIMESTAMP DEFAULT NOW(),
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )
        
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS milestone_template_items (
              item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              template_id INTEGER NOT NULL REFERENCES milestone_templates(template_id) ON DELETE CASCADE,
              milestone_name VARCHAR NOT NULL,
              days_offset INTEGER NOT NULL,
              sort_order INTEGER DEFAULT 0,
              created_at TIMESTAMP DEFAULT NOW()
            )
            """
        )
        
        con.execute(
            """
            CREATE INDEX IF NOT EXISTS milestone_template_items_template_idx
            ON milestone_template_items (template_id, sort_order)
            """
        )
        
        # Add milestone_template_id to jobs table
        con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS milestone_template_id INTEGER REFERENCES milestone_templates(template_id)")
        
        # Add unique constraint on template_name to prevent duplicates
        con.execute(
            """
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'milestone_templates_name_unique'
                ) THEN
                    ALTER TABLE milestone_templates 
                    ADD CONSTRAINT milestone_templates_name_unique 
                    UNIQUE (template_name);
                END IF;
            END $$;
            """
        )
        
        # Add unique constraint to prevent duplicate items
        con.execute(
            """
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'milestone_template_items_unique'
                ) THEN
                    ALTER TABLE milestone_template_items 
                    ADD CONSTRAINT milestone_template_items_unique 
                    UNIQUE (template_id, milestone_name, sort_order);
                END IF;
            END $$;
            """
        )
        
        # NOTE: Default template creation removed from migrations to prevent duplicates
        # Run the setup_default_milestone_template() function manually if needed
        
        # Theme settings for centralized color management
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS theme_settings (
              setting_key VARCHAR PRIMARY KEY,
              setting_value VARCHAR NOT NULL,
              setting_type VARCHAR DEFAULT 'color',
              description TEXT,
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )
        
        # Insert default theme colors
        con.execute(
            """
            INSERT INTO theme_settings (setting_key, setting_value, setting_type, description)
            VALUES 
              ('primary_color', '#F26624', 'color', 'Primary brand color for titles and accents'),
              ('button_color', '#F26624', 'color', 'Primary button color'),
              ('secondary_color', '#6B7280', 'color', 'Secondary color for muted elements')
            ON CONFLICT (setting_key) DO NOTHING
            """
        )
        
        # Add milestone completion tracking columns to job_plan
        con.execute("ALTER TABLE job_plan ADD COLUMN IF NOT EXISTS data_collection_completed_at TIMESTAMP")
        con.execute("ALTER TABLE job_plan ADD COLUMN IF NOT EXISTS data_collection_completed_by VARCHAR")
        con.execute("ALTER TABLE job_plan ADD COLUMN IF NOT EXISTS first_draft_completed_at TIMESTAMP")
        con.execute("ALTER TABLE job_plan ADD COLUMN IF NOT EXISTS first_draft_completed_by VARCHAR")
        con.execute("ALTER TABLE job_plan ADD COLUMN IF NOT EXISTS final_report_completed_at TIMESTAMP")
        con.execute("ALTER TABLE job_plan ADD COLUMN IF NOT EXISTS final_report_completed_by VARCHAR")
        
        # Report Templates System
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS report_templates (
              template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              template_key VARCHAR UNIQUE NOT NULL,
              template_name VARCHAR NOT NULL,
              template_type VARCHAR DEFAULT 'carbon_report',
              description TEXT,
              is_active BOOLEAN DEFAULT TRUE,
              created_at TIMESTAMP DEFAULT NOW(),
              updated_at TIMESTAMP DEFAULT NOW()
            )
            """
        )

        # Report template ownership/scope metadata
        con.execute("ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS report_type VARCHAR DEFAULT 'annual_report'")
        con.execute("ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS is_global BOOLEAN DEFAULT TRUE")
        con.execute("ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS client_db_id INTEGER REFERENCES clients(db_id)")
        con.execute("ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
        con.execute("ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
        con.execute("ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS archived_by VARCHAR")

        # Seed core annual report template used by Job > Reporting (idempotent)
        con.execute(
            """
            INSERT INTO report_templates
              (template_key, template_name, template_type, report_type, description, is_active, is_global, archived)
            VALUES
              (%s, %s, %s, %s, %s, TRUE, TRUE, FALSE)
            ON CONFLICT (template_key) DO UPDATE SET
              template_name = EXCLUDED.template_name,
              template_type = EXCLUDED.template_type,
              report_type = EXCLUDED.report_type,
              description = EXCLUDED.description,
              is_active = TRUE,
              updated_at = NOW()
            """,
            [
                "annual_carbon_report",
                "Annual Carbon Report",
                "carbon_report",
                "annual_report",
                "Comprehensive annual carbon footprint report",
            ],
        )

        # Versioned report templates (immutable versions for auditability)
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS report_template_versions (
              version_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              template_id INTEGER NOT NULL REFERENCES report_templates(template_id) ON DELETE CASCADE,
              version_number INTEGER NOT NULL,
              version_label VARCHAR,
              status VARCHAR DEFAULT 'published',
              template_content TEXT,
              created_at TIMESTAMP DEFAULT NOW(),
              created_by VARCHAR,
              UNIQUE(template_id, version_number)
            )
            """
        )
        con.execute(
            """
            CREATE INDEX IF NOT EXISTS report_template_versions_template_idx
            ON report_template_versions (template_id, version_number)
            """
        )

        # Backfill a default published v1 for legacy templates
        con.execute(
            """
            INSERT INTO report_template_versions (template_id, version_number, version_label, status, created_by)
            SELECT rt.template_id, 1, 'v1', 'published', 'system'
            FROM report_templates rt
            WHERE NOT EXISTS (
              SELECT 1 FROM report_template_versions rv WHERE rv.template_id = rt.template_id
            )
            """
        )
        
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS report_template_variables (
              variable_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              template_id INTEGER NOT NULL REFERENCES report_templates(template_id) ON DELETE CASCADE,
              variable_key VARCHAR NOT NULL,
              variable_label VARCHAR NOT NULL,
              variable_type VARCHAR DEFAULT 'text',
              default_value TEXT,
              placeholder TEXT,
              help_text TEXT,
              is_required BOOLEAN DEFAULT FALSE,
              display_order INTEGER DEFAULT 0,
              section VARCHAR,
              created_at TIMESTAMP DEFAULT NOW(),
              UNIQUE(template_id, variable_key)
            )
            """
        )

        # Seed annual report variables (including new activity commentary/toggles)
        annual_template_row = con.execute(
            """
            SELECT template_id
            FROM report_templates
            WHERE template_key = %s
            LIMIT 1
            """,
            ["annual_carbon_report"],
        ).fetchone()

        if annual_template_row:
            annual_template_id = int(annual_template_row[0])
            annual_variables = [
                ("report_title", "Report Title", "text", "Annual Carbon Footprint Report", None, "Title of the report", True, 10, "Cover Page"),
                ("introduction", "Introduction", "textarea", None, "Introduce the purpose and scope of this report...", "Introduction to the carbon footprint report", True, 20, "Introduction"),
                ("methodology", "Methodology", "textarea", None, "Describe the methodology used for carbon accounting...", "Explanation of calculation methodology and standards used", True, 30, "Methodology"),
                ("key_findings", "Key Findings", "textarea", None, "Summarize the key findings from this reporting period...", "Main findings and insights from the carbon footprint", True, 40, "Results"),
                ("recommendations", "Recommendations", "textarea", None, "Provide recommendations for reducing emissions...", "Suggested actions for emissions reduction", False, 50, "Recommendations"),
                ("conclusion", "Conclusion", "textarea", None, "Conclude the report...", "Final summary and next steps", False, 60, "Conclusion"),
                ("activity_narrative_intro", "Activity Analysis Introduction", "textarea", None, "Summarise the key activity drivers for this reporting period...", "Introductory narrative shown above the activity chart", False, 70, "Emissions by Activity"),
                ("activity_energy_commentary", "Energy Commentary", "textarea", None, "Commentary for Energy emissions...", "Narrative shown alongside the Energy activity group", False, 71, "Emissions by Activity"),
                ("activity_business_travel_commentary", "Business Travel Commentary", "textarea", None, "Commentary for Business Travel emissions...", "Narrative shown alongside the Business Travel activity group", False, 72, "Emissions by Activity"),
                ("activity_employee_commuting_commentary", "Employee Commuting Commentary", "textarea", None, "Commentary for Employee Commuting emissions...", "Narrative shown alongside the Employee Commuting activity group", False, 73, "Emissions by Activity"),
                ("activity_pgs_commentary", "Purchased Goods & Services (PG&S) Commentary", "textarea", None, "Commentary for Purchased Goods & Services emissions...", "Narrative shown alongside the PG&S activity group", False, 74, "Emissions by Activity"),
                ("activity_other_commentary", "Other Emissions Commentary", "textarea", None, "Commentary for other emissions activities...", "Narrative shown alongside the Other Emissions activity group", False, 75, "Emissions by Activity"),
                ("activity_show_group_breakdown", "Show Activity Group Breakdown Table", "boolean", "true", None, "Set to false to hide the summary activity-group table", False, 76, "Emissions by Activity"),
                ("activity_show_detail_table", "Show Detailed Activity Table", "boolean", "true", None, "Set to false to hide the detailed emissions-by-activity table", False, 77, "Emissions by Activity"),
            ]

            for (
                variable_key,
                variable_label,
                variable_type,
                default_value,
                placeholder,
                help_text,
                is_required,
                display_order,
                section,
            ) in annual_variables:
                con.execute(
                    """
                    INSERT INTO report_template_variables
                      (template_id, variable_key, variable_label, variable_type,
                       default_value, placeholder, help_text, is_required, display_order, section)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (template_id, variable_key)
                    DO UPDATE SET
                      variable_label = EXCLUDED.variable_label,
                      variable_type = EXCLUDED.variable_type,
                      default_value = EXCLUDED.default_value,
                      placeholder = EXCLUDED.placeholder,
                      help_text = EXCLUDED.help_text,
                      is_required = EXCLUDED.is_required,
                      display_order = EXCLUDED.display_order,
                      section = EXCLUDED.section
                    """,
                    [
                        annual_template_id,
                        variable_key,
                        variable_label,
                        variable_type,
                        default_value,
                        placeholder,
                        help_text,
                        bool(is_required),
                        int(display_order),
                        section,
                    ],
                )
        
        # Legacy storage table is deprecated.
        # Do NOT create it for new deployments. Only reference it for one-way
        # backfill if it already exists in an upgraded environment.
        legacy_job_report_variables_exists = False
        try:
            legacy_job_report_variables_exists = bool(
                con.execute(
                    """
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_name = 'job_report_variables'
                    LIMIT 1
                    """
                ).fetchone()
            )
        except Exception:
            legacy_job_report_variables_exists = False

        # Optional link to template version used when values were entered
        if legacy_job_report_variables_exists:
            con.execute("ALTER TABLE job_report_variables ADD COLUMN IF NOT EXISTS version_id INTEGER")

        # Version-safe storage table (one value per job/template/version/key)
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS job_report_variable_values (
              job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
              template_id INTEGER NOT NULL REFERENCES report_templates(template_id) ON DELETE CASCADE,
              version_id INTEGER REFERENCES report_template_versions(version_id) ON DELETE CASCADE,
              variable_key VARCHAR NOT NULL,
              variable_value TEXT,
              updated_at TIMESTAMP DEFAULT NOW(),
              updated_by VARCHAR,
              PRIMARY KEY (job_id, template_id, version_id, variable_key)
            )
            """
        )

        # Legacy->versioned backfill for rows that already carry version_id
        if legacy_job_report_variables_exists:
            con.execute(
                """
                INSERT INTO job_report_variable_values
                  (job_id, template_id, version_id, variable_key, variable_value, updated_at, updated_by)
                SELECT jrv.job_id, jrv.template_id, jrv.version_id, jrv.variable_key,
                       jrv.variable_value, jrv.updated_at, jrv.updated_by
                FROM job_report_variables jrv
                WHERE jrv.version_id IS NOT NULL
                ON CONFLICT (job_id, template_id, version_id, variable_key)
                DO UPDATE SET
                  variable_value = EXCLUDED.variable_value,
                  updated_at = EXCLUDED.updated_at,
                  updated_by = EXCLUDED.updated_by
                """
            )

        con.execute(
            """
            CREATE INDEX IF NOT EXISTS job_report_variable_values_lookup_idx
            ON job_report_variable_values (job_id, template_id, version_id)
            """
        )

        # Optional compatibility view for legacy readers during deprecation window.
        # IMPORTANT: treat this as read-only and migrate all writes to
        # job_report_variable_values (versioned table).
        con.execute(
            """
            CREATE OR REPLACE VIEW job_report_variables_legacy_view AS
            SELECT
              jrv.job_id,
              jrv.template_id,
              jrv.version_id,
              jrv.variable_key,
              jrv.variable_value,
              jrv.updated_at,
              jrv.updated_by
            FROM job_report_variable_values jrv
            """
        )

        # One active report template assignment per job
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS job_report_template_assignments (
              job_id INTEGER PRIMARY KEY REFERENCES jobs(job_id) ON DELETE CASCADE,
              template_id INTEGER NOT NULL REFERENCES report_templates(template_id) ON DELETE RESTRICT,
              version_id INTEGER REFERENCES report_template_versions(version_id) ON DELETE SET NULL,
              assigned_at TIMESTAMP DEFAULT NOW(),
              assigned_by VARCHAR
            )
            """
        )

        con.execute(
            """
            CREATE INDEX IF NOT EXISTS report_templates_scope_idx
            ON report_templates (is_global, client_db_id)
            """
        )
        
        con.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS intensity_metrics JSONB")
