from __future__ import annotations

import json
import logging
from typing import Any

from core.database import db_backend

logger = logging.getLogger(__name__)

_AI_PROMPT_SCHEMA_READY = False

GLOBAL_TEMPLATE_ORG_ID = "global"


def _json_text(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, default=str)
    except Exception:
        return json.dumps(str(value))


def ensure_ai_prompt_schema(con) -> None:
    global _AI_PROMPT_SCHEMA_READY
    if _AI_PROMPT_SCHEMA_READY:
        return

    if db_backend() != "postgres":
        logger.warning("AI prompt schema helper is intended for Postgres; continuing with DDL.")

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS ai_prompt_templates (
          template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id TEXT NOT NULL DEFAULT 'global',
          prompt_key VARCHAR NOT NULL,
          report_family_key VARCHAR NOT NULL,
          section_key VARCHAR NOT NULL,
          name VARCHAR NOT NULL,
          description TEXT,
          scope VARCHAR NOT NULL DEFAULT 'global',
          system_prompt TEXT NOT NULL,
          user_prompt TEXT NOT NULL,
          variables_json TEXT,
          model_hint VARCHAR,
          temperature DOUBLE PRECISION,
          status VARCHAR NOT NULL DEFAULT 'draft',
          version INTEGER NOT NULL DEFAULT 1,
          parent_template_id INTEGER REFERENCES ai_prompt_templates(template_id) ON DELETE SET NULL,
          created_by_user_id VARCHAR,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW(),
          archived_at TIMESTAMP
        )
        """
    )
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS org_id TEXT NOT NULL DEFAULT 'global'")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS prompt_key VARCHAR")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS report_family_key VARCHAR")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS section_key VARCHAR")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS name VARCHAR")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS description TEXT")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS scope VARCHAR NOT NULL DEFAULT 'global'")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS system_prompt TEXT")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS user_prompt TEXT")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS variables_json TEXT")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS model_hint VARCHAR")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS temperature DOUBLE PRECISION")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS status VARCHAR NOT NULL DEFAULT 'draft'")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS parent_template_id INTEGER")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS created_by_user_id VARCHAR")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE ai_prompt_templates ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
    con.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ai_prompt_templates_org_key_version_idx
        ON ai_prompt_templates (org_id, prompt_key, version)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS ai_prompt_templates_lookup_idx
        ON ai_prompt_templates (org_id, report_family_key, section_key, status, version DESC)
        """
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS ai_client_prompt_profiles (
          profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id TEXT NOT NULL,
          client_db_id INTEGER NOT NULL REFERENCES clients(db_id) ON DELETE CASCADE,
          profile_name VARCHAR NOT NULL,
          industry_context TEXT,
          company_context TEXT,
          tone TEXT,
          audience_notes TEXT,
          preferred_terms_json TEXT,
          forbidden_terms_json TEXT,
          narrative_notes TEXT,
          section_notes_json TEXT,
          status VARCHAR NOT NULL DEFAULT 'draft',
          version INTEGER NOT NULL DEFAULT 1,
          created_by_user_id VARCHAR,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS org_id TEXT NOT NULL")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS client_db_id INTEGER")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS profile_name VARCHAR")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS industry_context TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS company_context TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS tone TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS audience_notes TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS preferred_terms_json TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS forbidden_terms_json TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS narrative_notes TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS section_notes_json TEXT")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS status VARCHAR NOT NULL DEFAULT 'draft'")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS created_by_user_id VARCHAR")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE ai_client_prompt_profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()")
    con.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ai_client_prompt_profiles_org_client_version_idx
        ON ai_client_prompt_profiles (org_id, client_db_id, version)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS ai_client_prompt_profiles_lookup_idx
        ON ai_client_prompt_profiles (org_id, client_db_id, status, version DESC)
        """
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS ai_job_prompt_overrides (
          override_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id TEXT NOT NULL,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          report_family_key VARCHAR NOT NULL,
          section_key VARCHAR NOT NULL,
          override_title VARCHAR NOT NULL,
          instruction_text TEXT,
          variables_json TEXT,
          status VARCHAR NOT NULL DEFAULT 'draft',
          version INTEGER NOT NULL DEFAULT 1,
          created_by_user_id VARCHAR,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS org_id TEXT NOT NULL")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS job_id INTEGER")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS report_family_key VARCHAR")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS section_key VARCHAR")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS override_title VARCHAR")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS instruction_text TEXT")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS variables_json TEXT")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS status VARCHAR NOT NULL DEFAULT 'draft'")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS created_by_user_id VARCHAR")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE ai_job_prompt_overrides ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()")
    con.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ai_job_prompt_overrides_org_job_key_version_idx
        ON ai_job_prompt_overrides (org_id, job_id, report_family_key, section_key, version)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS ai_job_prompt_overrides_lookup_idx
        ON ai_job_prompt_overrides (org_id, job_id, report_family_key, section_key, status, version DESC)
        """
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS ai_prompt_runs (
          run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id TEXT NOT NULL,
          user_id VARCHAR,
          client_db_id INTEGER,
          job_id INTEGER,
          prompt_template_id INTEGER REFERENCES ai_prompt_templates(template_id) ON DELETE SET NULL,
          client_prompt_profile_id INTEGER REFERENCES ai_client_prompt_profiles(profile_id) ON DELETE SET NULL,
          job_prompt_override_id INTEGER REFERENCES ai_job_prompt_overrides(override_id) ON DELETE SET NULL,
          report_family_key VARCHAR NOT NULL,
          section_key VARCHAR NOT NULL,
          provider VARCHAR NOT NULL,
          model_name VARCHAR,
          input_tokens INTEGER,
          output_tokens INTEGER,
          total_tokens INTEGER,
          cost_estimate NUMERIC(14, 6),
          resolved_system_prompt TEXT,
          resolved_user_prompt TEXT,
          input_facts_json TEXT,
          output_text TEXT,
          output_json TEXT,
          status VARCHAR NOT NULL DEFAULT 'queued',
          started_at TIMESTAMP DEFAULT NOW(),
          streaming_at TIMESTAMP,
          completed_at TIMESTAMP,
          created_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS org_id TEXT NOT NULL")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS user_id VARCHAR")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS client_db_id INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS job_id INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS prompt_template_id INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS client_prompt_profile_id INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS job_prompt_override_id INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS report_family_key VARCHAR")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS section_key VARCHAR")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS provider VARCHAR")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS model_name VARCHAR")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS input_tokens INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS output_tokens INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS total_tokens INTEGER")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS cost_estimate NUMERIC(14, 6)")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS resolved_system_prompt TEXT")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS resolved_user_prompt TEXT")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS input_facts_json TEXT")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS output_text TEXT")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS output_json TEXT")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS status VARCHAR NOT NULL DEFAULT 'queued'")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS started_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS streaming_at TIMESTAMP")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP")
    con.execute("ALTER TABLE ai_prompt_runs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()")
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS ai_prompt_runs_lookup_idx
        ON ai_prompt_runs (org_id, client_db_id, job_id, report_family_key, section_key, created_at DESC)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS ai_prompt_runs_template_idx
        ON ai_prompt_runs (org_id, prompt_template_id, created_at DESC)
        """
    )

    _seed_default_ai_prompt_templates(con)

    _AI_PROMPT_SCHEMA_READY = True


def _seed_default_ai_prompt_templates(con) -> None:
    seed_templates = [
        (
            "client_insights.executive_summary",
            "client_insights",
            "executive_summary",
            "Client Insights Summary",
            "Structured client insight output for the dashboard.",
            "global",
            "You are an expert sustainability consultant.",
            (
                "Return ONLY valid JSON (no markdown) using this schema:\n"
                "{\n"
                '  "summary": "string",\n'
                '  "confidence": "low|medium|high",\n'
                '  "top_drivers": [{"title":"string","detail":"string","metric":"string","citation":"string"}],\n'
                '  "risks": [{"title":"string","detail":"string","citation":"string"}],\n'
                '  "recommended_actions": [{"title":"string","owner":"string","effort":"S|M|L","expected_impact":"string","timeframe":"string","rationale":"string","citation":"string"}],\n'
                '  "regulatory_context": [{"title":"string","detail":"string","source":"string"}],\n'
                '  "reduction_roadmap": {"short_term":["string"],"medium_term":["string"],"long_term":["string"]},\n'
                '  "data_gaps": ["string"]\n'
                "}\n"
                "Keep the output concise, specific, and grounded in the supplied facts.\n"
                "Use the facts pack below and do not invent values.\n"
                "Facts:\n{{prompt_facts}}"
            ),
        ),
        (
            "crp.executive_summary",
            "crp",
            "executive_summary",
            "Executive Summary",
            "Opening narrative for a Carbon Reduction Plan.",
            "global",
            "You write concise, board-ready carbon reporting copy.",
            (
                "Write the Executive Summary for {{client_name}}. "
                "Focus on the headline emissions story, the main drivers, the direction of travel, and what it means for the business. "
                "Keep the tone confident, concise, and specific. "
                "Do not invent facts. Use the supplied facts only.\n"
                "Facts:\n{{prompt_facts}}"
            ),
        ),
        (
            "crp.emissions_overview",
            "crp",
            "emissions_overview",
            "Emissions Overview",
            "Summary of the emissions footprint and change.",
            "global",
            "You write concise emissions overview copy.",
            (
                "Explain the current emissions footprint for {{client_name}} using the supplied facts. "
                "Summarise scope mix, totals, notable movements, and caveats. "
                "Be factual and easy to read.\n"
                "Facts:\n{{prompt_facts}}"
            ),
        ),
        (
            "crp.actions",
            "crp",
            "actions",
            "Actions",
            "Practical reduction actions and delivery priorities.",
            "global",
            "You write practical action-led report copy.",
            (
                "Translate the selected actions for {{client_name}} into report-ready narrative. "
                "Highlight priorities, delivery horizon, and practical next steps.\n"
                "Facts:\n{{prompt_facts}}"
            ),
        ),
        (
            "crp.declaration",
            "crp",
            "declaration",
            "Declaration",
            "Formal declaration wording for the report sign-off.",
            "global",
            "You write formal declaration text.",
            (
                "Draft a formal declaration for {{client_name}} that matches the report style and uses the supplied sign-off facts.\n"
                "Facts:\n{{prompt_facts}}"
            ),
        ),
    ]

    for prompt_key, report_family_key, section_key, name, description, scope, system_prompt, user_prompt in seed_templates:
        con.execute(
            """
            INSERT INTO ai_prompt_templates (
                org_id,
                prompt_key,
                report_family_key,
                section_key,
                name,
                description,
                scope,
                system_prompt,
                user_prompt,
                variables_json,
                model_hint,
                temperature,
                status,
                version,
                created_by_user_id,
                created_at,
                updated_at
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), NOW()
            )
            ON CONFLICT (org_id, prompt_key, version) DO NOTHING
            """,
            [
                GLOBAL_TEMPLATE_ORG_ID,
                prompt_key,
                report_family_key,
                section_key,
                name,
                description,
                scope,
                system_prompt,
                user_prompt,
                _json_text(
                    {
                        "client_name": "Client name",
                        "reporting_period": "Reporting period",
                        "current_total_emissions": "Current total emissions",
                        "emissions_change_summary": "Emissions change summary",
                        "selected_actions": "Selected actions",
                    }
                ),
                "anthropic",
                0.2,
                "active",
                1,
                "system",
            ],
        )
