"""Composite/assembly support for the LCA component library.

A component with no rows in lca_component_children is a leaf (a real
material -- today's only shape). A component with children is a
composite/assembly: its "mass" is the sum of its children, recursively,
each child's quantity acting as a multiplier down the tree. This mirrors
how a real multi-level BOM (assemblies referencing other assemblies by
code, each with a quantity) actually works -- see
LCA_ASSEMBLY_HIERARCHY_SCOPE.md for the full design.

Nothing here changes summarize_assessment()/compute_readiness() in
services/lca_engine.py -- resolve_effective_lines() expands any line that
references a composite into flat leaf lines shaped identically to what
those functions already consume, so leaf-only assessments (100% of what
exists today) pass through completely unchanged.
"""
from __future__ import annotations

import json
from typing import Any

from services.lca_engine import safe_float

_schema_seeded = False


def ensure_lca_hierarchy_schema(con) -> None:
    global _schema_seeded
    if _schema_seeded:
        return
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS lca_component_children (
          child_link_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          parent_component_id INTEGER NOT NULL REFERENCES lca_components(component_id) ON DELETE CASCADE,
          child_component_id INTEGER REFERENCES lca_components(component_id),
          line_label VARCHAR NOT NULL,
          material_category_id INTEGER REFERENCES lca_material_categories_lookup(category_id),
          quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
          unit VARCHAR NOT NULL DEFAULT 'kg',
          origin_country VARCHAR,
          mapped_factor_source VARCHAR,
          factor_value DOUBLE PRECISION,
          factor_unit VARCHAR NOT NULL DEFAULT 'kgCO2e/kg',
          data_quality VARCHAR NOT NULL DEFAULT 'secondary',
          is_gap_filled BOOLEAN NOT NULL DEFAULT FALSE,
          sort_order INTEGER NOT NULL DEFAULT 0,
          notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_lca_component_children_parent ON lca_component_children (parent_component_id, sort_order)"
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_lca_component_children_child ON lca_component_children (child_component_id)"
    )
    con.execute(
        "ALTER TABLE lca_assessments ADD COLUMN IF NOT EXISTS resolved_lines_snapshot JSONB"
    )
    _schema_seeded = True


def has_children(con, component_id: int) -> bool:
    row = con.execute(
        "SELECT 1 FROM lca_component_children WHERE parent_component_id = %s LIMIT 1",
        [int(component_id)],
    ).fetchone()
    return bool(row)


def would_create_cycle(con, parent_component_id: int, child_component_id: int) -> bool:
    """True if linking child_component_id under parent_component_id would
    make a component (transitively) contain itself. Must be checked before
    every child insert -- a copy-pasted component code is exactly how a
    real-world library ends up with an accidental cycle."""
    if int(parent_component_id) == int(child_component_id):
        return True
    stack = [int(child_component_id)]
    seen: set[int] = set()
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        if current == int(parent_component_id):
            return True
        rows = con.execute(
            "SELECT child_component_id FROM lca_component_children WHERE parent_component_id = %s",
            [current],
        ).fetchall()
        for r in rows:
            if r[0] is not None:
                stack.append(int(r[0]))
    return False


def _fetch_children(con, component_id: int) -> list[dict[str, Any]]:
    df = con.execute(
        """
        SELECT child_link_id, child_component_id, line_label, material_category_id, quantity, unit,
               factor_value, factor_unit, mapped_factor_source, data_quality, is_gap_filled
        FROM lca_component_children
        WHERE parent_component_id = %s
        ORDER BY sort_order, child_link_id
        """,
        [int(component_id)],
    ).df()
    if df is None or df.empty:
        return []
    df = df.astype(object).where(df.notna(), None)
    return df.to_dict("records")


def resolve_component_to_lines(
    con,
    component_id: int,
    quantity_multiplier: float,
    module_code: str,
    visited: frozenset[int] = frozenset(),
) -> list[dict[str, Any]]:
    """Recursively expand a composite component into flat leaf lines, each
    quantity multiplied through every level above it. Raises ValueError on
    a cycle (should already be prevented at edit time -- this is the
    defensive backstop at calculation time)."""
    if component_id in visited:
        raise ValueError(f"Circular assembly reference detected at component {component_id}")
    visited = visited | {component_id}

    results: list[dict[str, Any]] = []
    for child in _fetch_children(con, component_id):
        child_component_id = child.get("child_component_id")
        effective_qty = safe_float(child.get("quantity")) * quantity_multiplier
        if child_component_id is not None and has_children(con, int(child_component_id)):
            results.extend(
                resolve_component_to_lines(con, int(child_component_id), effective_qty, module_code, visited)
            )
        else:
            results.append(
                {
                    "line_item_id": 0,
                    "component_id": int(child_component_id) if child_component_id is not None else None,
                    "module_code": module_code,
                    "line_label": str(child.get("line_label") or "Unnamed component"),
                    "material_category_id": child.get("material_category_id"),
                    "quantity": effective_qty,
                    "unit": str(child.get("unit") or "kg"),
                    "factor_value": safe_float(child.get("factor_value")),
                    "factor_unit": str(child.get("factor_unit") or "kgCO2e/kg"),
                    "mapped_factor_source": child.get("mapped_factor_source"),
                    "factor_match_confidence": None,
                    "is_gap_filled": bool(child.get("is_gap_filled") or False),
                    "is_placeholder": effective_qty <= 0,
                    "data_quality": str(child.get("data_quality") or "secondary"),
                }
            )
    return results


def resolve_effective_lines(con, lines: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Expand any line referencing a composite component into its flattened
    leaf descendants; every other line passes through unchanged. Output is
    shaped identically to the input, so summarize_assessment()/
    compute_readiness() need no changes at all."""
    effective: list[dict[str, Any]] = []
    for line in lines:
        component_id = line.get("component_id")
        if component_id is not None and has_children(con, int(component_id)):
            effective.extend(
                resolve_component_to_lines(
                    con,
                    int(component_id),
                    safe_float(line.get("quantity"), 1.0),
                    str(line.get("module_code") or "A1"),
                )
            )
        else:
            effective.append(line)
    return effective


def resolved_mass_kg(con, component_id: int) -> float | None:
    """Live total mass of a composite (kg-unit leaf descendants only, same
    convention as the mass-reconciliation check in lca_engine.py). None for
    a leaf component (its mass is just default_unit_mass, already known to
    the caller)."""
    if not has_children(con, component_id):
        return None
    lines = resolve_component_to_lines(con, int(component_id), 1.0, "A1")
    return round(sum(safe_float(l.get("quantity")) for l in lines if str(l.get("unit") or "").strip().lower() in ("kg", "kilogram", "kilograms")), 6)


def snapshot_to_lines(snapshot: Any) -> list[dict[str, Any]] | None:
    """Parse lca_assessments.resolved_lines_snapshot (JSONB, stored as a
    Python list/dict by psycopg or a JSON string depending on driver
    config) back into the flat line-dict shape resolve_effective_lines()
    produces."""
    if snapshot is None:
        return None
    if isinstance(snapshot, str):
        try:
            snapshot = json.loads(snapshot)
        except Exception:
            return None
    if isinstance(snapshot, list):
        return snapshot
    return None
