"""Client portal service layer.

Manages portal user accounts, report reviews, and comment workflows for the
NZInsights client portal (nzinsights.co.uk). All data lives in the same Postgres
database as the main NZI app — no synchronisation required.
"""
from __future__ import annotations

import binascii
import hashlib
import hmac
import os
import secrets
from datetime import datetime, timezone
from typing import Any

from fastapi import HTTPException

from core.database import get_conn

# ---------------------------------------------------------------------------
# Password helpers (same algorithm as core.auth)
# ---------------------------------------------------------------------------

def _hash_password(password: str, iterations: int = 100_000) -> str:
    salt = os.urandom(16)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
    return f"{iterations}${binascii.hexlify(salt).decode()}${binascii.hexlify(dk).decode()}"


def _verify_password(password: str, stored: str) -> bool:
    try:
        parts = stored.split("$")
        if len(parts) != 3:
            return False
        iterations = int(parts[0])
        salt = binascii.unhexlify(parts[1])
        expected = binascii.unhexlify(parts[2])
        dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
        return hmac.compare_digest(dk, expected)
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

_schema_seeded = False


def ensure_portal_schema(con) -> None:
    global _schema_seeded
    if _schema_seeded:
        return

    con.execute("""
        CREATE TABLE IF NOT EXISTS client_portal_users (
          portal_user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          client_db_id    INTEGER NOT NULL REFERENCES clients(db_id) ON DELETE CASCADE,
          contact_id      INTEGER,
          email           VARCHAR NOT NULL,
          full_name       VARCHAR NOT NULL,
          password_hash   VARCHAR,
          is_active       BOOLEAN NOT NULL DEFAULT TRUE,
          created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
          last_login_at   TIMESTAMP,
          created_by      VARCHAR,
          reset_token_hash VARCHAR,
          reset_token_expires TIMESTAMP
        )
    """)
    con.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS ux_portal_users_email
        ON client_portal_users (LOWER(email))
    """)

    con.execute("""
        CREATE TABLE IF NOT EXISTS report_reviews (
          review_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id              INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          status              VARCHAR(32) NOT NULL DEFAULT 'draft',
          sent_for_review_at  TIMESTAMP,
          sent_by             VARCHAR,
          approved_at         TIMESTAMP,
          approved_by_name    VARCHAR,
          approved_by_email   VARCHAR,
          pdf_generated_at    TIMESTAMP,
          created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at          TIMESTAMP NOT NULL DEFAULT NOW()
        )
    """)
    con.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS ux_report_reviews_job_id
        ON report_reviews (job_id)
    """)

    con.execute("""
        CREATE TABLE IF NOT EXISTS report_review_comments (
          comment_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          review_id         INTEGER NOT NULL REFERENCES report_reviews(review_id) ON DELETE CASCADE,
          author_type       VARCHAR(8) NOT NULL DEFAULT 'client',
          author_name       VARCHAR NOT NULL,
          author_email      VARCHAR NOT NULL,
          comment_text      TEXT NOT NULL,
          section_reference VARCHAR,
          status            VARCHAR(16) NOT NULL DEFAULT 'open',
          crm_response      TEXT,
          created_at        TIMESTAMP NOT NULL DEFAULT NOW(),
          addressed_at      TIMESTAMP,
          addressed_by      VARCHAR
        )
    """)
    con.execute("""
        CREATE INDEX IF NOT EXISTS ix_review_comments_review_id
        ON report_review_comments (review_id, created_at)
    """)

    for ddl in (
        "ALTER TABLE client_portal_users ADD COLUMN IF NOT EXISTS contact_id INTEGER",
        "ALTER TABLE client_portal_users ADD COLUMN IF NOT EXISTS reset_token_hash VARCHAR",
        "ALTER TABLE client_portal_users ADD COLUMN IF NOT EXISTS reset_token_expires TIMESTAMP",
        "ALTER TABLE report_reviews ADD COLUMN IF NOT EXISTS sent_for_review_at TIMESTAMP",
        "ALTER TABLE report_reviews ADD COLUMN IF NOT EXISTS pdf_generated_at TIMESTAMP",
        "ALTER TABLE report_reviews ADD COLUMN IF NOT EXISTS portal_version_id BIGINT",
        "ALTER TABLE report_reviews ADD COLUMN IF NOT EXISTS published_at TIMESTAMP",
        "ALTER TABLE report_reviews ADD COLUMN IF NOT EXISTS published_by VARCHAR",
        "ALTER TABLE report_reviews ADD COLUMN IF NOT EXISTS pdf_version_id BIGINT",
    ):
        try:
            con.execute(ddl)
        except Exception:
            pass

    _schema_seeded = True


# ---------------------------------------------------------------------------
# Portal user management
# ---------------------------------------------------------------------------

def _row_to_portal_user(row) -> dict[str, Any]:
    return {
        "portal_user_id": int(row[0]),
        "client_db_id": int(row[1]),
        "contact_id": int(row[2]) if row[2] is not None else None,
        "email": str(row[3] or ""),
        "full_name": str(row[4] or ""),
        "is_active": bool(row[5]),
        "created_at": str(row[6]) if row[6] else None,
        "last_login_at": str(row[7]) if row[7] else None,
        "created_by": str(row[8] or "") or None,
    }


def list_portal_users(client_db_id: int, *, con=None) -> list[dict[str, Any]]:
    if con is None:
        with get_conn() as managed:
            return list_portal_users(client_db_id, con=managed)
    ensure_portal_schema(con)
    rows = con.execute(
        """
        SELECT portal_user_id, client_db_id, contact_id, email, full_name,
               is_active, created_at, last_login_at, created_by
        FROM client_portal_users
        WHERE client_db_id = %s
        ORDER BY full_name ASC
        """,
        [int(client_db_id)],
    ).fetchall()
    return [_row_to_portal_user(r) for r in (rows or [])]


def get_portal_user_by_id(portal_user_id: int, *, con=None) -> dict[str, Any] | None:
    if con is None:
        with get_conn() as managed:
            return get_portal_user_by_id(portal_user_id, con=managed)
    ensure_portal_schema(con)
    row = con.execute(
        """
        SELECT portal_user_id, client_db_id, contact_id, email, full_name,
               is_active, created_at, last_login_at, created_by
        FROM client_portal_users
        WHERE portal_user_id = %s
        """,
        [int(portal_user_id)],
    ).fetchone()
    return _row_to_portal_user(row) if row else None


def get_portal_user_by_email(email: str, *, con=None) -> dict[str, Any] | None:
    """Returns user dict including password_hash (for auth only)."""
    if con is None:
        with get_conn() as managed:
            return get_portal_user_by_email(email, con=managed)
    ensure_portal_schema(con)
    row = con.execute(
        """
        SELECT portal_user_id, client_db_id, contact_id, email, full_name,
               is_active, created_at, last_login_at, created_by, password_hash
        FROM client_portal_users
        WHERE LOWER(email) = LOWER(%s)
        """,
        [str(email or "").strip()],
    ).fetchone()
    if not row:
        return None
    user = _row_to_portal_user(row)
    user["password_hash"] = row[9]
    return user


def create_portal_user(
    *,
    client_db_id: int,
    email: str,
    full_name: str,
    password: str,
    contact_id: int | None = None,
    created_by: str,
    con=None,
) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return create_portal_user(
                client_db_id=client_db_id,
                email=email,
                full_name=full_name,
                password=password,
                contact_id=contact_id,
                created_by=created_by,
                con=managed,
            )
    ensure_portal_schema(con)

    email = str(email or "").strip().lower()
    if not email:
        raise HTTPException(status_code=400, detail="Email is required")
    full_name = str(full_name or "").strip()
    if not full_name:
        raise HTTPException(status_code=400, detail="Full name is required")
    if not password or len(password) < 8:
        raise HTTPException(status_code=400, detail="Password must be at least 8 characters")

    existing = con.execute(
        "SELECT portal_user_id FROM client_portal_users WHERE LOWER(email) = LOWER(%s)",
        [email],
    ).fetchone()
    if existing:
        raise HTTPException(status_code=400, detail="A portal account with this email already exists")

    ph = _hash_password(password)
    row = con.execute(
        """
        INSERT INTO client_portal_users
          (client_db_id, contact_id, email, full_name, password_hash, is_active, created_by)
        VALUES (%s, %s, %s, %s, %s, TRUE, %s)
        RETURNING portal_user_id
        """,
        [int(client_db_id), contact_id, email, full_name, ph, created_by],
    ).fetchone()
    return get_portal_user_by_id(int(row[0]), con=con)


def update_portal_user(
    portal_user_id: int,
    *,
    full_name: str | None = None,
    is_active: bool | None = None,
    con=None,
) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return update_portal_user(portal_user_id, full_name=full_name, is_active=is_active, con=managed)
    ensure_portal_schema(con)
    user = get_portal_user_by_id(portal_user_id, con=con)
    if not user:
        raise HTTPException(status_code=404, detail="Portal user not found")
    next_name = str(full_name or "").strip() or user["full_name"]
    next_active = is_active if is_active is not None else user["is_active"]
    con.execute(
        """
        UPDATE client_portal_users
        SET full_name = %s, is_active = %s, updated_at = NOW()
        WHERE portal_user_id = %s
        """,
        [next_name, next_active, int(portal_user_id)],
    )
    return get_portal_user_by_id(portal_user_id, con=con)


def set_portal_user_password(portal_user_id: int, password: str, *, con=None) -> None:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return set_portal_user_password(portal_user_id, password, con=managed)
    if not password or len(password) < 8:
        raise HTTPException(status_code=400, detail="Password must be at least 8 characters")
    ph = _hash_password(password)
    con.execute(
        "UPDATE client_portal_users SET password_hash = %s, updated_at = NOW(), reset_token_hash = NULL, reset_token_expires = NULL WHERE portal_user_id = %s",
        [ph, int(portal_user_id)],
    )


# ---------------------------------------------------------------------------
# Password reset tokens
# ---------------------------------------------------------------------------

def create_reset_token(email: str, *, con=None) -> str | None:
    """Generate a reset token, store its hash, return the raw token (or None if user not found)."""
    if con is None:
        with get_conn(autocommit=False) as managed:
            return create_reset_token(email, con=managed)
    ensure_portal_schema(con)
    row = con.execute(
        "SELECT portal_user_id FROM client_portal_users WHERE LOWER(email) = LOWER(%s) AND is_active = TRUE",
        [str(email or "").strip()],
    ).fetchone()
    if not row:
        return None
    token = secrets.token_urlsafe(32)
    token_hash = hashlib.sha256(token.encode()).hexdigest()
    con.execute(
        "UPDATE client_portal_users SET reset_token_hash = %s, reset_token_expires = NOW() + INTERVAL '2 hours' WHERE portal_user_id = %s",
        [token_hash, int(row[0])],
    )
    return token


def consume_reset_token(token: str, new_password: str, *, con=None) -> bool:
    """Validate token, set new password, clear token. Returns True on success."""
    if con is None:
        with get_conn(autocommit=False) as managed:
            return consume_reset_token(token, new_password, con=managed)
    ensure_portal_schema(con)
    token_hash = hashlib.sha256(str(token or "").encode()).hexdigest()
    row = con.execute(
        """
        SELECT portal_user_id FROM client_portal_users
        WHERE reset_token_hash = %s
          AND reset_token_expires > NOW()
          AND is_active = TRUE
        """,
        [token_hash],
    ).fetchone()
    if not row:
        return False
    set_portal_user_password(int(row[0]), new_password, con=con)
    return True


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------

def authenticate_portal_user(email: str, password: str, *, con=None) -> dict[str, Any] | None:
    if con is None:
        with get_conn() as managed:
            return authenticate_portal_user(email, password, con=managed)
    ensure_portal_schema(con)
    user = get_portal_user_by_email(email, con=con)
    if not user or not user.get("is_active"):
        return None
    if not user.get("password_hash"):
        return None
    if not _verify_password(password, user["password_hash"]):
        return None
    con.execute(
        "UPDATE client_portal_users SET last_login_at = NOW() WHERE portal_user_id = %s",
        [user["portal_user_id"]],
    )
    user.pop("password_hash", None)
    return user


# ---------------------------------------------------------------------------
# Report reviews
# ---------------------------------------------------------------------------

_REVIEW_SELECT = """
    SELECT review_id, job_id, status, sent_for_review_at, sent_by,
           approved_at, approved_by_name, approved_by_email, pdf_generated_at,
           created_at, updated_at,
           portal_version_id, published_at, published_by, pdf_version_id
    FROM report_reviews
"""


def _row_to_review(row) -> dict[str, Any]:
    return {
        "review_id": int(row[0]),
        "job_id": int(row[1]),
        "status": str(row[2] or "draft"),
        "sent_for_review_at": str(row[3]) if row[3] else None,
        "sent_by": str(row[4] or "") or None,
        "approved_at": str(row[5]) if row[5] else None,
        "approved_by_name": str(row[6] or "") or None,
        "approved_by_email": str(row[7] or "") or None,
        "pdf_generated_at": str(row[8]) if row[8] else None,
        "created_at": str(row[9]) if row[9] else None,
        "updated_at": str(row[10]) if row[10] else None,
        "portal_version_id": int(row[11]) if row[11] is not None else None,
        "published_at": str(row[12]) if row[12] else None,
        "published_by": str(row[13] or "") or None,
        "pdf_version_id": int(row[14]) if row[14] is not None else None,
    }


def get_or_create_review(job_id: int, *, con=None) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return get_or_create_review(job_id, con=managed)
    ensure_portal_schema(con)
    row = con.execute(
        _REVIEW_SELECT + "WHERE job_id = %s",
        [int(job_id)],
    ).fetchone()
    if row:
        return _row_to_review(row)
    new_row = con.execute(
        """
        INSERT INTO report_reviews (job_id, status)
        VALUES (%s, 'draft')
        RETURNING review_id, job_id, status, sent_for_review_at, sent_by,
                  approved_at, approved_by_name, approved_by_email, pdf_generated_at,
                  created_at, updated_at,
                  portal_version_id, published_at, published_by, pdf_version_id
        """,
        [int(job_id)],
    ).fetchone()
    return _row_to_review(new_row)


def send_review_to_client(job_id: int, sent_by: str, *, con=None) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return send_review_to_client(job_id, sent_by, con=managed)
    ensure_portal_schema(con)
    review = get_or_create_review(job_id, con=con)
    if review["status"] == "approved":
        raise HTTPException(status_code=400, detail="This report has already been approved")
    con.execute(
        """
        UPDATE report_reviews
        SET status = 'sent_for_review', sent_for_review_at = NOW(), sent_by = %s, updated_at = NOW()
        WHERE job_id = %s
        """,
        [sent_by, int(job_id)],
    )
    return get_or_create_review(job_id, con=con)


def approve_review(
    job_id: int,
    *,
    approver_name: str,
    approver_email: str,
    con=None,
) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return approve_review(job_id, approver_name=approver_name, approver_email=approver_email, con=managed)
    ensure_portal_schema(con)
    review = get_or_create_review(job_id, con=con)
    if review["status"] == "approved":
        raise HTTPException(status_code=400, detail="This report has already been approved")
    # Block approval if there are open comments
    open_count = con.execute(
        """
        SELECT COUNT(*) FROM report_review_comments
        WHERE review_id = %s AND status = 'open'
        """,
        [review["review_id"]],
    ).fetchone()
    if open_count and int(open_count[0]) > 0:
        raise HTTPException(
            status_code=400,
            detail=f"There are {open_count[0]} open comment(s) that must be addressed before approval",
        )
    con.execute(
        """
        UPDATE report_reviews
        SET status = 'approved', approved_at = NOW(),
            approved_by_name = %s, approved_by_email = %s, updated_at = NOW()
        WHERE job_id = %s
        """,
        [approver_name, approver_email, int(job_id)],
    )
    return get_or_create_review(job_id, con=con)


def mark_pdf_generated(job_id: int, *, con=None) -> None:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return mark_pdf_generated(job_id, con=managed)
    con.execute(
        "UPDATE report_reviews SET pdf_generated_at = NOW(), updated_at = NOW() WHERE job_id = %s",
        [int(job_id)],
    )


def send_to_portal(
    job_id: int,
    sent_by: str,
    portal_version_id: int,
    *,
    con=None,
) -> dict[str, Any]:
    """Record that a frozen snapshot has been sent to the client portal.

    Sets portal_version_id (which snapshot the portal will serve), updates
    status to sent_for_review, and records who sent it and when.
    """
    if con is None:
        with get_conn(autocommit=False) as managed:
            return send_to_portal(job_id, sent_by, portal_version_id, con=managed)
    ensure_portal_schema(con)
    review = get_or_create_review(job_id, con=con)
    if review["status"] == "approved":
        raise HTTPException(status_code=400, detail="This report has already been approved and cannot be re-sent")
    con.execute(
        """
        UPDATE report_reviews
        SET status = 'sent_for_review',
            sent_for_review_at = NOW(),
            sent_by = %s,
            portal_version_id = %s,
            updated_at = NOW()
        WHERE job_id = %s
        """,
        [sent_by, int(portal_version_id), int(job_id)],
    )
    return get_or_create_review(job_id, con=con)


def mark_published(
    job_id: int,
    published_by: str,
    pdf_version_id: int,
    *,
    con=None,
) -> dict[str, Any]:
    """Record that the CRM has published the final PDF for client download."""
    if con is None:
        with get_conn(autocommit=False) as managed:
            return mark_published(job_id, published_by, pdf_version_id, con=managed)
    ensure_portal_schema(con)
    review = get_or_create_review(job_id, con=con)
    if review["status"] != "approved":
        raise HTTPException(status_code=400, detail="Report must be approved by the client before publishing")
    con.execute(
        """
        UPDATE report_reviews
        SET published_at = NOW(),
            published_by = %s,
            pdf_version_id = %s,
            updated_at = NOW()
        WHERE job_id = %s
        """,
        [published_by, int(pdf_version_id), int(job_id)],
    )
    return get_or_create_review(job_id, con=con)


# ---------------------------------------------------------------------------
# Review comments
# ---------------------------------------------------------------------------

def _row_to_comment(row) -> dict[str, Any]:
    return {
        "comment_id": int(row[0]),
        "review_id": int(row[1]),
        "author_type": str(row[2] or "client"),
        "author_name": str(row[3] or ""),
        "author_email": str(row[4] or ""),
        "comment_text": str(row[5] or ""),
        "section_reference": str(row[6] or "") or None,
        "status": str(row[7] or "open"),
        "crm_response": str(row[8] or "") or None,
        "created_at": str(row[9]) if row[9] else None,
        "addressed_at": str(row[10]) if row[10] else None,
        "addressed_by": str(row[11] or "") or None,
    }


def list_comments(review_id: int, *, con=None) -> list[dict[str, Any]]:
    if con is None:
        with get_conn() as managed:
            return list_comments(review_id, con=managed)
    ensure_portal_schema(con)
    rows = con.execute(
        """
        SELECT comment_id, review_id, author_type, author_name, author_email,
               comment_text, section_reference, status, crm_response,
               created_at, addressed_at, addressed_by
        FROM report_review_comments
        WHERE review_id = %s
        ORDER BY created_at ASC
        """,
        [int(review_id)],
    ).fetchall()
    return [_row_to_comment(r) for r in (rows or [])]


def add_comment(
    review_id: int,
    *,
    author_type: str,
    author_name: str,
    author_email: str,
    comment_text: str,
    section_reference: str | None = None,
    con=None,
) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return add_comment(
                review_id,
                author_type=author_type,
                author_name=author_name,
                author_email=author_email,
                comment_text=comment_text,
                section_reference=section_reference,
                con=managed,
            )
    ensure_portal_schema(con)
    if author_type not in ("client", "crm"):
        raise HTTPException(status_code=400, detail="author_type must be client or crm")
    text = str(comment_text or "").strip()
    if not text:
        raise HTTPException(status_code=400, detail="Comment text is required")

    # When client adds a comment, move review to changes_requested if it was sent_for_review
    if author_type == "client":
        con.execute(
            """
            UPDATE report_reviews
            SET status = 'changes_requested', updated_at = NOW()
            WHERE review_id = %s AND status IN ('sent_for_review', 'draft')
            """,
            [int(review_id)],
        )

    row = con.execute(
        """
        INSERT INTO report_review_comments
          (review_id, author_type, author_name, author_email, comment_text, section_reference)
        VALUES (%s, %s, %s, %s, %s, %s)
        RETURNING comment_id, review_id, author_type, author_name, author_email,
                  comment_text, section_reference, status, crm_response,
                  created_at, addressed_at, addressed_by
        """,
        [int(review_id), author_type, author_name, author_email, text, section_reference or None],
    ).fetchone()
    return _row_to_comment(row)


def respond_to_comment(
    comment_id: int,
    *,
    new_status: str,
    crm_response: str | None,
    addressed_by: str,
    con=None,
) -> dict[str, Any]:
    if con is None:
        with get_conn(autocommit=False) as managed:
            return respond_to_comment(
                comment_id,
                new_status=new_status,
                crm_response=crm_response,
                addressed_by=addressed_by,
                con=managed,
            )
    ensure_portal_schema(con)
    if new_status not in ("addressed", "dismissed"):
        raise HTTPException(status_code=400, detail="status must be addressed or dismissed")
    row = con.execute(
        "SELECT comment_id, review_id FROM report_review_comments WHERE comment_id = %s",
        [int(comment_id)],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Comment not found")

    con.execute(
        """
        UPDATE report_review_comments
        SET status = %s, crm_response = %s, addressed_at = NOW(), addressed_by = %s
        WHERE comment_id = %s
        """,
        [new_status, crm_response or None, addressed_by, int(comment_id)],
    )

    # If all comments on this review are now resolved, update review status
    open_count = con.execute(
        "SELECT COUNT(*) FROM report_review_comments WHERE review_id = %s AND status = 'open'",
        [int(row[1])],
    ).fetchone()
    if open_count and int(open_count[0]) == 0:
        con.execute(
            """
            UPDATE report_reviews
            SET status = 'sent_for_review', updated_at = NOW()
            WHERE review_id = %s AND status = 'changes_requested'
            """,
            [int(row[1])],
        )

    updated = con.execute(
        """
        SELECT comment_id, review_id, author_type, author_name, author_email,
               comment_text, section_reference, status, crm_response,
               created_at, addressed_at, addressed_by
        FROM report_review_comments WHERE comment_id = %s
        """,
        [int(comment_id)],
    ).fetchone()
    return _row_to_comment(updated)


# ---------------------------------------------------------------------------
# Portal dashboard data
# ---------------------------------------------------------------------------

def portal_dashboard_jobs(client_db_id: int, *, con=None) -> list[dict[str, Any]]:
    """Return all jobs for a client with review status for the portal dashboard."""
    if con is None:
        with get_conn() as managed:
            return portal_dashboard_jobs(client_db_id, con=managed)
    ensure_portal_schema(con)
    rows = con.execute(
        """
        SELECT j.job_id, j.job_number, j.title,
               COALESCE(
                   EXTRACT(YEAR FROM j.reporting_period_end)::int,
                   j.reporting_year
               ) AS display_year,
               j.status,
               COALESCE(r.status, 'not_sent') AS review_status,
               r.review_id, r.sent_for_review_at, r.approved_at,
               rv.version_label, rv.version_number, rv.snapshot_at
        FROM jobs j
        LEFT JOIN report_reviews r ON r.job_id = j.job_id
        LEFT JOIN LATERAL (
            SELECT
                jrv.version_label,
                jrv.version_number,
                COALESCE(jrv.finalized_at, jrv.reviewed_at, jrv.generated_at) AS snapshot_at
            FROM job_report_versions jrv
            WHERE jrv.job_id = j.job_id
              AND jrv.snapshot_json IS NOT NULL
              AND lower(COALESCE(jrv.status, '')) IN ('final', 'review', 'draft')
            ORDER BY
                CASE lower(COALESCE(jrv.status, ''))
                    WHEN 'final' THEN 1
                    WHEN 'review' THEN 2
                    WHEN 'draft' THEN 3
                    ELSE 4
                END,
                COALESCE(jrv.finalized_at, jrv.reviewed_at, jrv.generated_at) DESC NULLS LAST,
                jrv.version_number DESC NULLS LAST
            LIMIT 1
        ) rv ON TRUE
        WHERE j.client_db_id = %s
        ORDER BY display_year DESC NULLS LAST, j.job_id DESC
        """,
        [int(client_db_id)],
    ).fetchall()
    return [
        {
            "job_id": int(r[0]),
            "job_number": str(r[1] or ""),
            "title": str(r[2] or ""),
            "reporting_year": int(r[3]) if r[3] is not None else None,
            "status": str(r[4] or ""),
            "review_status": str(r[5] or "not_sent"),
            "review_id": int(r[6]) if r[6] is not None else None,
            "sent_for_review_at": str(r[7]) if r[7] else None,
            "approved_at": str(r[8]) if r[8] else None,
            "snapshot_version_label": str(r[9] or "") or None,
            "snapshot_version_number": int(r[10]) if r[10] is not None else None,
            "snapshot_at": str(r[11]) if r[11] else None,
        }
        for r in (rows or [])
    ]
