--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: client_contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client_contacts (
    contact_id integer NOT NULL,
    client_db_id integer,
    full_name character varying,
    job_title character varying,
    email character varying
);


--
-- Name: client_contacts_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client_contacts ALTER COLUMN contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_contacts_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client_notes (
    note_id integer NOT NULL,
    client_db_id integer,
    author character varying,
    note_text text,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: client_notes_note_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client_notes ALTER COLUMN note_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_notes_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_sites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client_sites (
    site_id integer NOT NULL,
    client_db_id integer,
    site_name character varying,
    location character varying,
    is_registered_office boolean DEFAULT false NOT NULL
);


--
-- Name: client_sites_site_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client_sites ALTER COLUMN site_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_sites_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    db_id integer NOT NULL,
    client_name character varying,
    industry character varying,
    description_long text,
    website character varying,
    year_end_month character varying,
    company_reg character varying,
    headquarters character varying,
    addr_line1 character varying,
    addr_line2 character varying,
    addr_city character varying,
    addr_region character varying,
    addr_postcode character varying,
    addr_country character varying,
    logo_url character varying,
    crm_owner character varying,
    status character varying DEFAULT 'Active'::character varying,
    net_zero_year integer DEFAULT 2050,
    interim_year integer DEFAULT 2035,
    interim_s1_pct integer DEFAULT 50,
    interim_s2_pct integer DEFAULT 50,
    interim_s3_pct integer DEFAULT 50,
    portfolio character varying,
    target_s1_year integer,
    target_s2_year integer,
    target_s3_year integer,
    target_s1_pct integer,
    target_s2_pct integer,
    target_s3_pct integer,
    benchmark_year integer
);


--
-- Name: clients_db_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients ALTER COLUMN db_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_db_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crp_job_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crp_job_details (
    job_id integer NOT NULL,
    reporting_period_from date,
    reporting_period_to date,
    is_benchmark boolean DEFAULT false NOT NULL,
    reporting_year integer NOT NULL,
    is_renewal boolean DEFAULT false NOT NULL,
    client_order_number character varying,
    client_contact_name character varying,
    client_contact_email character varying,
    report_signee_name character varying,
    report_signee_position character varying,
    payment_term_id integer DEFAULT 1 NOT NULL,
    free_training_place boolean DEFAULT false NOT NULL,
    num_employees integer,
    turnover_gbp numeric,
    premises_size_m2 numeric,
    vehicles_owned integer,
    vehicles_leased integer,
    premises_owned integer,
    premises_leased integer,
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: crp_scope_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crp_scope_entries (
    entry_id integer NOT NULL,
    job_id integer NOT NULL,
    scope character varying NOT NULL,
    category character varying,
    subcategory character varying,
    description character varying,
    amount numeric,
    unit character varying,
    dataset_id integer,
    factor_id integer,
    factor_value numeric,
    tco2e numeric,
    method character varying,
    notes character varying,
    is_archived boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: crp_scope_entries_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.crp_scope_entries ALTER COLUMN entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crp_scope_entries_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: datasets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.datasets (
    dataset_id integer NOT NULL,
    name character varying,
    source character varying,
    analysis_type character varying,
    country character varying,
    region character varying,
    currency character varying,
    year integer,
    version character varying,
    license character varying,
    notes text,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: datasets_dataset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.datasets ALTER COLUMN dataset_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.datasets_dataset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: factor_lookup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.factor_lookup (
    db_id integer NOT NULL,
    dataset_id integer,
    file_name character varying,
    year integer,
    original_id character varying,
    scope character varying,
    level_1 character varying,
    level_2 character varying,
    level_3 character varying,
    level_4 character varying,
    column_text character varying,
    uom character varying,
    ghg_unit character varying,
    factor numeric,
    source character varying,
    region character varying,
    currency character varying
);


--
-- Name: factor_lookup_db_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.factor_lookup ALTER COLUMN db_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factor_lookup_db_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: industries_lookup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.industries_lookup (
    industry_id integer NOT NULL,
    name character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: job_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_plan (
    job_id integer NOT NULL,
    data_collection_due date,
    first_draft_due date,
    final_report_due date,
    override_dates boolean DEFAULT false NOT NULL,
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: job_scope_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_scope_config (
    job_id integer NOT NULL,
    scope character varying NOT NULL,
    include_scope boolean DEFAULT true NOT NULL,
    dataset_id integer,
    factor_method character varying
);


--
-- Name: job_scope_rows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_scope_rows (
    row_id integer NOT NULL,
    job_id integer NOT NULL,
    scope character varying NOT NULL,
    dataset_id integer,
    factor_db_id integer,
    original_id character varying NOT NULL,
    level_1 character varying,
    level_2 character varying,
    level_3 character varying,
    level_4 character varying,
    column_text character varying,
    report_label character varying,
    notes character varying,
    enabled boolean DEFAULT true NOT NULL,
    qty numeric,
    uom character varying,
    factor numeric,
    ghg_unit character varying,
    calc_tco2e numeric,
    override_tco2e numeric,
    override_reason character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: job_scope_rows_row_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.job_scope_rows_row_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: job_scope_rows_row_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.job_scope_rows_row_id_seq OWNED BY public.job_scope_rows.row_id;


--
-- Name: job_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_types (
    job_type_id integer NOT NULL,
    name character varying,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: job_types_job_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job_types ALTER COLUMN job_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_types_job_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    job_id integer NOT NULL,
    client_db_id integer,
    job_type_id integer,
    job_type character varying,
    job_number character varying,
    title character varying,
    reporting_year integer,
    crp_id integer,
    status character varying DEFAULT 'Open'::character varying,
    start_date date,
    due_date date,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: jobs_job_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobs ALTER COLUMN job_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lookups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lookups (
    type character varying,
    value character varying
);


--
-- Name: payment_terms_lookup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_terms_lookup (
    term_id integer NOT NULL,
    name character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: portfolios_lookup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolios_lookup (
    portfolio_id integer NOT NULL,
    name character varying,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: portfolios_lookup_portfolio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.portfolios_lookup ALTER COLUMN portfolio_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolios_lookup_portfolio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles_lookup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_lookup (
    role_name character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: time_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.time_logs (
    time_id integer NOT NULL,
    job_id integer,
    user_id character varying,
    subject character varying,
    work_date date,
    minutes integer,
    notes text,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: time_logs_time_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.time_logs ALTER COLUMN time_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_logs_time_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: time_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.time_subjects (
    subject_id integer NOT NULL,
    name character varying,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: time_subjects_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.time_subjects ALTER COLUMN subject_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_subjects_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id character varying NOT NULL,
    full_name character varying,
    role character varying DEFAULT 'ReadOnly'::character varying NOT NULL,
    email character varying NOT NULL,
    status character varying DEFAULT 'Active'::character varying NOT NULL
);


--
-- Name: job_scope_rows row_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_scope_rows ALTER COLUMN row_id SET DEFAULT nextval('public.job_scope_rows_row_id_seq'::regclass);


--
-- Name: client_contacts client_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_contacts
    ADD CONSTRAINT client_contacts_pkey PRIMARY KEY (contact_id);


--
-- Name: client_notes client_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_notes
    ADD CONSTRAINT client_notes_pkey PRIMARY KEY (note_id);


--
-- Name: client_sites client_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_sites
    ADD CONSTRAINT client_sites_pkey PRIMARY KEY (site_id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (db_id);


--
-- Name: crp_job_details crp_job_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crp_job_details
    ADD CONSTRAINT crp_job_details_pkey PRIMARY KEY (job_id);


--
-- Name: crp_scope_entries crp_scope_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crp_scope_entries
    ADD CONSTRAINT crp_scope_entries_pkey PRIMARY KEY (entry_id);


--
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (dataset_id);


--
-- Name: factor_lookup factor_lookup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factor_lookup
    ADD CONSTRAINT factor_lookup_pkey PRIMARY KEY (db_id);


--
-- Name: industries_lookup industries_lookup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.industries_lookup
    ADD CONSTRAINT industries_lookup_pkey PRIMARY KEY (industry_id);


--
-- Name: job_plan job_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_plan
    ADD CONSTRAINT job_plan_pkey PRIMARY KEY (job_id);


--
-- Name: job_scope_config job_scope_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_scope_config
    ADD CONSTRAINT job_scope_config_pkey PRIMARY KEY (job_id, scope);


--
-- Name: job_scope_rows job_scope_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_scope_rows
    ADD CONSTRAINT job_scope_rows_pkey PRIMARY KEY (row_id);


--
-- Name: job_types job_types_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_types
    ADD CONSTRAINT job_types_name_key UNIQUE (name);


--
-- Name: job_types job_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_types
    ADD CONSTRAINT job_types_pkey PRIMARY KEY (job_type_id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (job_id);


--
-- Name: payment_terms_lookup payment_terms_lookup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_terms_lookup
    ADD CONSTRAINT payment_terms_lookup_pkey PRIMARY KEY (term_id);


--
-- Name: portfolios_lookup portfolios_lookup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolios_lookup
    ADD CONSTRAINT portfolios_lookup_pkey PRIMARY KEY (portfolio_id);


--
-- Name: roles_lookup roles_lookup_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_lookup
    ADD CONSTRAINT roles_lookup_pkey PRIMARY KEY (role_name);


--
-- Name: time_logs time_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_logs
    ADD CONSTRAINT time_logs_pkey PRIMARY KEY (time_id);


--
-- Name: time_subjects time_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_subjects
    ADD CONSTRAINT time_subjects_pkey PRIMARY KEY (subject_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: crp_scope_entries_job_scope_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX crp_scope_entries_job_scope_idx ON public.crp_scope_entries USING btree (job_id, scope, is_archived);


--
-- Name: job_scope_rows_job_scope_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX job_scope_rows_job_scope_enabled_idx ON public.job_scope_rows USING btree (job_id, scope, enabled);


--
-- Name: job_scope_rows_job_scope_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX job_scope_rows_job_scope_idx ON public.job_scope_rows USING btree (job_id, scope);


--
-- Name: jobs_job_number_uidx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX jobs_job_number_uidx ON public.jobs USING btree (job_number);


--
-- Name: users_email_uidx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_email_uidx ON public.users USING btree (email);


--
-- Name: crp_job_details crp_job_details_payment_term_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crp_job_details
    ADD CONSTRAINT crp_job_details_payment_term_id_fkey FOREIGN KEY (payment_term_id) REFERENCES public.payment_terms_lookup(term_id);


--
-- Name: job_scope_rows job_scope_rows_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_scope_rows
    ADD CONSTRAINT job_scope_rows_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(dataset_id);


--
-- Name: job_scope_rows job_scope_rows_factor_db_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_scope_rows
    ADD CONSTRAINT job_scope_rows_factor_db_id_fkey FOREIGN KEY (factor_db_id) REFERENCES public.factor_lookup(db_id);


--
-- Name: job_scope_rows job_scope_rows_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_scope_rows
    ADD CONSTRAINT job_scope_rows_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(job_id);


--
-- PostgreSQL database dump complete
--
