CREATE TABLE IF NOT EXISTS public.vat_rates_lookup (
  vat_rate_id integer generated by default as identity primary key,
  name text not null,
  rate_pct numeric not null,
  is_default boolean not null default false,
  is_active boolean not null default true
);

ALTER TABLE public.job_types
  ADD COLUMN IF NOT EXISTS description text;

ALTER TABLE public.job_types
  ADD COLUMN IF NOT EXISTS unit_price_ex_vat numeric;

ALTER TABLE public.job_types
  ADD COLUMN IF NOT EXISTS vat_rate_id integer;

INSERT INTO public.vat_rates_lookup (name, rate_pct, is_default, is_active)
SELECT '20% Standard Rate', 20, TRUE, TRUE
WHERE NOT EXISTS (
  SELECT 1 FROM public.vat_rates_lookup WHERE lower(name)=lower('20% Standard Rate')
);

INSERT INTO public.vat_rates_lookup (name, rate_pct, is_default, is_active)
SELECT 'No VAT', 0, FALSE, TRUE
WHERE NOT EXISTS (
  SELECT 1 FROM public.vat_rates_lookup WHERE lower(name)=lower('No VAT')
);

UPDATE public.vat_rates_lookup
SET is_default=TRUE
WHERE vat_rate_id = (
  SELECT vat_rate_id FROM public.vat_rates_lookup
  WHERE lower(name)=lower('20% Standard Rate')
  ORDER BY vat_rate_id
  LIMIT 1
);
