-- Job-level templates (Excel + CRP)

CREATE TABLE IF NOT EXISTS public.job_templates (
  job_template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key text UNIQUE NOT NULL,
  template_name text,
  excel_template_path text,
  crp_template_path text,
  is_active boolean NOT NULL DEFAULT true,
  created_by text,
  archived boolean NOT NULL DEFAULT false,
  archived_at timestamptz,
  archived_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS job_template_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'jobs_job_template_id_fkey'
  ) THEN
    ALTER TABLE public.jobs
      ADD CONSTRAINT jobs_job_template_id_fkey
      FOREIGN KEY (job_template_id)
      REFERENCES public.job_templates(job_template_id);
  END IF;
END $$;

INSERT INTO public.job_templates (template_key, template_name, excel_template_path, crp_template_path, is_active, created_by)
SELECT
  'basic_uk',
  'NZI Data Upload Template - Basic UK',
  'templates/NZI Data Upload Template - Basic UK.xlsx',
  'templates/DEMOCO Carbon Reduction Plan Dec 2025 - Second Year Onwards.docx',
  true,
  'system'
WHERE NOT EXISTS (
  SELECT 1 FROM public.job_templates WHERE template_key='basic_uk'
);

UPDATE public.jobs
SET job_template_id = (
  SELECT job_template_id FROM public.job_templates WHERE template_key='basic_uk' LIMIT 1
)
WHERE job_template_id IS NULL;
