-- Job Items - Service items menu for building jobs, quotes and invoices

-- Main job items table
CREATE TABLE IF NOT EXISTS public.job_items (
  item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_code text UNIQUE NOT NULL,
  item_name text NOT NULL,
  description text,
  category text,
  unit text DEFAULT 'day',
  estimated_hours numeric(10,2) DEFAULT 0,
  vat_rate_id integer REFERENCES vat_rates_lookup(vat_rate_id),
  cost_amount numeric(12,2) NOT NULL DEFAULT 0,
  cost_currency text DEFAULT 'GBP',
  sell_amount numeric(12,2) NOT NULL DEFAULT 0,
  sell_currency text DEFAULT 'GBP',
  vat_rate numeric(5,2) DEFAULT 20.00,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Many-to-many relationship: Job Types <-> Job Items
-- A job type can consist of multiple job items
CREATE TABLE IF NOT EXISTS public.job_type_items (
  job_type_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type_id integer NOT NULL REFERENCES job_types(job_type_id) ON DELETE CASCADE,
  item_id integer NOT NULL REFERENCES job_items(item_id) ON DELETE CASCADE,
  quantity numeric(10,2) DEFAULT 1,
  is_required boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  UNIQUE(job_type_id, item_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_job_items_active ON job_items(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_job_items_category ON job_items(category);
CREATE INDEX IF NOT EXISTS idx_job_type_items_job_type ON job_type_items(job_type_id);
CREATE INDEX IF NOT EXISTS idx_job_type_items_item ON job_type_items(item_id);

-- Insert some default job items
INSERT INTO public.job_items (item_code, item_name, description, category, unit, cost_amount, sell_amount, vat_rate, sort_order)
SELECT 
  'ASSESS', 
  'Carbon Assessment', 
  'Initial carbon footprint assessment and data gathering', 
  'Assessment', 
  'day', 
  350.00, 
  750.00, 
  20.00, 
  10
WHERE NOT EXISTS (SELECT 1 FROM public.job_items WHERE item_code = 'ASSESS');

INSERT INTO public.job_items (item_code, item_name, description, category, unit, cost_amount, sell_amount, vat_rate, sort_order)
SELECT 
  'REPORT', 
  'Carbon Report Generation', 
  'Production of formal carbon reduction report', 
  'Reporting', 
  'day', 
  250.00, 
  500.00, 
  20.00, 
  20
WHERE NOT EXISTS (SELECT 1 FROM public.job_items WHERE item_code = 'REPORT');

INSERT INTO public.job_items (item_code, item_name, description, category, unit, cost_amount, sell_amount, vat_rate, sort_order)
SELECT 
  'STRATEGY', 
  'Reduction Strategy', 
  'Development of carbon reduction strategy and action plan', 
  'Advisory', 
  'day', 
  400.00, 
  850.00, 
  20.00, 
  30
WHERE NOT EXISTS (SELECT 1 FROM public.job_items WHERE item_code = 'STRATEGY');

INSERT INTO public.job_items (item_code, item_name, description, category, unit, cost_amount, sell_amount, vat_rate, sort_order)
SELECT 
  'TRAINING', 
  'Staff Training', 
  'Training session for staff on carbon reporting', 
  'Training', 
  'day', 
  300.00, 
  600.00, 
  20.00, 
  40
WHERE NOT EXISTS (SELECT 1 FROM public.job_items WHERE item_code = 'TRAINING');

INSERT INTO public.job_items (item_code, item_name, description, category, unit, cost_amount, sell_amount, vat_rate, sort_order)
SELECT 
  'IT', 
  'DataAUD Audit', 
  'Audit and verification of carbon data', 
  'Assessment', 
  'day', 
  275.00, 
  550.00, 
  20.00, 
  50
WHERE NOT EXISTS (SELECT 1 FROM public.job_items WHERE item_code = 'AUDIT');

INSERT INTO public.job_items (item_code, item_name, description, category, unit, cost_amount, sell_amount, vat_rate, sort_order)
SELECT 
  'MONTHLY', 
  'Monthly Monitoring', 
  'Ongoing monthly carbon monitoring and reporting', 
  'Ongoing', 
  'month', 
  150.00, 
  350.00, 
  20.00, 
  60
WHERE NOT EXISTS (SELECT 1 FROM public.job_items WHERE item_code = 'MONTHLY');
