-- Currency lookup table
CREATE TABLE IF NOT EXISTS public.currency_lookup (
    currency_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code text UNIQUE NOT NULL,
    currency_name text NOT NULL,
    symbol text,
    exchange_rate numeric(12,6) DEFAULT 1.0,
    is_default boolean DEFAULT false,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Insert default currencies if table is empty
INSERT INTO public.currency_lookup (currency_code, currency_name, symbol, exchange_rate, is_default, sort_order)
SELECT 'GBP', 'British Pound', '£', 1.0, true, 10
WHERE NOT EXISTS (SELECT 1 FROM public.currency_lookup WHERE currency_code = 'GBP');

INSERT INTO public.currency_lookup (currency_code, currency_name, symbol, exchange_rate, is_default, sort_order)
SELECT 'EUR', 'Euro', '€', 1.18, false, 20
WHERE NOT EXISTS (SELECT 1 FROM public.currency_lookup WHERE currency_code = 'EUR');

INSERT INTO public.currency_lookup (currency_code, currency_name, symbol, exchange_rate, is_default, sort_order)
SELECT 'USD', 'US Dollar', '$', 1.27, false, 30
WHERE NOT EXISTS (SELECT 1 FROM public.currency_lookup WHERE currency_code = 'USD');

INSERT INTO public.currency_lookup (currency_code, currency_name, symbol, exchange_rate, is_default, sort_order)
SELECT 'AUD', 'Australian Dollar', 'A$', 1.92, false, 40
WHERE NOT EXISTS (SELECT 1 FROM public.currency_lookup WHERE currency_code = 'AUD');

INSERT INTO public.currency_lookup (currency_code, currency_name, symbol, exchange_rate, is_default, sort_order)
SELECT 'CAD', 'Canadian Dollar', 'C$', 1.71, false, 50
WHERE NOT EXISTS (SELECT 1 FROM public.currency_lookup WHERE currency_code = 'CAD');
