-- Versioned report archive for review/final PDFs

CREATE TABLE IF NOT EXISTS job_report_versions (
  report_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
  client_db_id INTEGER NOT NULL REFERENCES clients(db_id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  version_label VARCHAR,
  status VARCHAR NOT NULL DEFAULT 'review',
  report_format VARCHAR NOT NULL DEFAULT 'pdf',
  template_id INTEGER REFERENCES report_templates(template_id) ON DELETE SET NULL,
  version_id INTEGER REFERENCES report_template_versions(version_id) ON DELETE SET NULL,
  file_id INTEGER REFERENCES job_files(file_id) ON DELETE SET NULL,
  file_name TEXT,
  file_path TEXT,
  storage_provider VARCHAR DEFAULT 'local',
  external_item_id VARCHAR,
  external_web_url TEXT,
  external_path TEXT,
  data_hash VARCHAR,
  snapshot_json TEXT,
  notes TEXT,
  generated_at TIMESTAMP DEFAULT NOW(),
  generated_by VARCHAR,
  reviewed_at TIMESTAMP,
  reviewed_by VARCHAR,
  finalized_at TIMESTAMP,
  finalized_by VARCHAR,
  superseded_at TIMESTAMP,
  superseded_by VARCHAR,
  UNIQUE(job_id, version_number)
);

CREATE INDEX IF NOT EXISTS job_report_versions_job_idx
ON job_report_versions (job_id, version_number DESC);

CREATE INDEX IF NOT EXISTS job_report_versions_client_idx
ON job_report_versions (client_db_id, generated_at DESC);
