CREATE TABLE IF NOT EXISTS job_template_milestone_completions (
  completion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES milestone_template_items(item_id) ON DELETE CASCADE,
  is_complete BOOLEAN NOT NULL DEFAULT TRUE,
  completed_at TIMESTAMP,
  completed_by VARCHAR,
  updated_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS is_complete BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS completed_by VARCHAR;
ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'job_template_milestone_completions_unique'
  ) THEN
    ALTER TABLE job_template_milestone_completions
    ADD CONSTRAINT job_template_milestone_completions_unique
    UNIQUE (job_id, item_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS job_template_milestone_completions_job_idx
ON job_template_milestone_completions (job_id, item_id, is_complete);
