-- 0046_training_phase1.sql
--
-- Phase 1 training foundation.
-- Adds reusable training products, job-linked course runs, participant bookings,
-- and free-place entitlements that can be linked from CRP jobs.

CREATE TABLE IF NOT EXISTS training_products (
    training_product_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                  VARCHAR NOT NULL,
    product_code            VARCHAR,
    product_name            VARCHAR NOT NULL,
    description             TEXT,
    default_hours           NUMERIC(10,2),
    default_delivery_mode   VARCHAR,
    default_capacity        INTEGER,
    default_min_attendees   INTEGER,
    certificate_policy      TEXT,
    default_documents_json  TEXT,
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by              VARCHAR,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by              VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_training_products_org_active
    ON training_products (org_id, is_active, product_name);

CREATE TABLE IF NOT EXISTS training_course_runs (
    training_course_run_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                  VARCHAR NOT NULL,
    job_id                  INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    training_product_id     INTEGER REFERENCES training_products(training_product_id) ON DELETE SET NULL,
    run_name                VARCHAR,
    course_code             VARCHAR,
    total_hours             NUMERIC(10,2),
    delivery_mode           VARCHAR,
    capacity                INTEGER,
    min_attendees           INTEGER,
    status                  VARCHAR NOT NULL DEFAULT 'draft',
    workflow_stage_key      VARCHAR NOT NULL DEFAULT 'setup',
    start_date              DATE,
    end_date                DATE,
    venue_name              VARCHAR,
    venue_address           TEXT,
    online_meeting_url      TEXT,
    online_meeting_id       VARCHAR,
    online_passcode         VARCHAR,
    notes                   TEXT,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by              VARCHAR,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by              VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_training_course_runs_job
    ON training_course_runs (org_id, job_id, status, start_date);
CREATE INDEX IF NOT EXISTS ix_training_course_runs_product
    ON training_course_runs (training_product_id);

CREATE TABLE IF NOT EXISTS training_bookings (
    training_booking_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                  VARCHAR NOT NULL,
    training_course_run_id  INTEGER NOT NULL REFERENCES training_course_runs(training_course_run_id) ON DELETE CASCADE,
    client_db_id            INTEGER,
    contact_id              INTEGER,
    participant_type        VARCHAR NOT NULL DEFAULT 'external_individual',
    booking_source          VARCHAR NOT NULL DEFAULT 'manual',
    person_name             VARCHAR NOT NULL,
    person_email            VARCHAR,
    person_phone            VARCHAR,
    billing_status          VARCHAR NOT NULL DEFAULT 'pending',
    attendance_status       VARCHAR NOT NULL DEFAULT 'booked',
    special_requirements     TEXT,
    consent_status          VARCHAR NOT NULL DEFAULT 'unknown',
    notes                   TEXT,
    entitlement_id          INTEGER,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by              VARCHAR,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by              VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_training_bookings_run
    ON training_bookings (org_id, training_course_run_id, attendance_status, person_name);
CREATE INDEX IF NOT EXISTS ix_training_bookings_client
    ON training_bookings (client_db_id);
CREATE INDEX IF NOT EXISTS ix_training_bookings_entitlement
    ON training_bookings (entitlement_id);

CREATE TABLE IF NOT EXISTS training_entitlements (
    training_entitlement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                  VARCHAR NOT NULL,
    source_job_id           INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    source_job_number       VARCHAR,
    source_client_db_id     INTEGER,
    entitlement_type        VARCHAR NOT NULL DEFAULT 'free_place',
    status                  VARCHAR NOT NULL DEFAULT 'available',
    allocated_to_booking_id INTEGER,
    reserved_at             TIMESTAMP,
    consumed_at             TIMESTAMP,
    expires_at              TIMESTAMP,
    notes                   TEXT,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by              VARCHAR,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by              VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_training_entitlements_org_status
    ON training_entitlements (org_id, status, source_job_id);
CREATE INDEX IF NOT EXISTS ix_training_entitlements_source_job
    ON training_entitlements (source_job_id);
CREATE INDEX IF NOT EXISTS ix_training_entitlements_allocated
    ON training_entitlements (allocated_to_booking_id);
