-- 0047_training_sessions_attendance.sql
--
-- Phase 1.1 training delivery management.
-- Adds scheduled sessions and per-attendee attendance tracking for each training course run.

CREATE TABLE IF NOT EXISTS training_course_sessions (
    training_course_session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                  VARCHAR NOT NULL,
    training_course_run_id   INTEGER NOT NULL REFERENCES training_course_runs(training_course_run_id) ON DELETE CASCADE,
    session_title            VARCHAR,
    session_date             DATE,
    start_time               TIME,
    end_time                 TIME,
    session_hours            NUMERIC(10,2),
    delivery_mode            VARCHAR,
    venue_name               VARCHAR,
    venue_address            TEXT,
    online_meeting_url       TEXT,
    online_meeting_id        VARCHAR,
    online_passcode          VARCHAR,
    status                   VARCHAR NOT NULL DEFAULT 'scheduled',
    notes                    TEXT,
    created_at               TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by               VARCHAR,
    updated_at               TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by               VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_training_course_sessions_run
    ON training_course_sessions (org_id, training_course_run_id, session_date, start_time);
CREATE INDEX IF NOT EXISTS ix_training_course_sessions_status
    ON training_course_sessions (org_id, status);

CREATE TABLE IF NOT EXISTS training_session_attendance (
    training_session_attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                  VARCHAR NOT NULL,
    training_course_session_id INTEGER NOT NULL REFERENCES training_course_sessions(training_course_session_id) ON DELETE CASCADE,
    training_booking_id      INTEGER NOT NULL REFERENCES training_bookings(training_booking_id) ON DELETE CASCADE,
    attendance_status       VARCHAR NOT NULL DEFAULT 'booked',
    attendance_minutes      INTEGER,
    notes                   TEXT,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by              VARCHAR,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by              VARCHAR,
    UNIQUE (training_course_session_id, training_booking_id)
);

CREATE INDEX IF NOT EXISTS ix_training_session_attendance_session
    ON training_session_attendance (org_id, training_course_session_id, attendance_status);
CREATE INDEX IF NOT EXISTS ix_training_session_attendance_booking
    ON training_session_attendance (training_booking_id);
