ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS reminder_schedule_json TEXT NOT NULL DEFAULT '[7,1,0]';
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS reminder_subject_template TEXT;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS reminder_body_template TEXT;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS completion_subject_template TEXT;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS completion_body_template TEXT;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS post_course_documents_json TEXT;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS auto_certificate BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS certificate_template_key TEXT NOT NULL DEFAULT 'training_certificate';
ALTER TABLE training_course_runs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS training_automation_log (
  training_automation_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id VARCHAR NOT NULL,
  training_course_run_id INTEGER NOT NULL REFERENCES training_course_runs(training_course_run_id) ON DELETE CASCADE,
  training_course_session_id INTEGER,
  training_booking_id INTEGER,
  automation_key TEXT NOT NULL,
  trigger_key TEXT NOT NULL,
  action_type TEXT NOT NULL,
  recipient_name TEXT,
  recipient_email TEXT,
  subject TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  error_text TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_by TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_training_automation_log_key ON training_automation_log (automation_key);
CREATE INDEX IF NOT EXISTS ix_training_automation_log_run ON training_automation_log (org_id, training_course_run_id, created_at DESC);
