-- 0058_lca_pcf_rebuild.sql
--
-- Full replacement of the LCA/PCF feature. The previous tables
-- (lca_products, lca_inventory_items, lca_product_datasets,
-- lca_result_snapshots) were a working prototype never used for real
-- client delivery -- confirmed zero rows in production -- so this is a
-- clean rebuild, not a data migration.
--
-- Design points (see plan for full rationale):
--   - flat line items, no BOM tree (confirmed real-world workbooks
--     flatten multi-level BOMs for calculation purposes anyway)
--   - open, admin-editable module + material-category vocabularies
--     instead of 4 hardcoded stage keys
--   - a reusable, client-scoped component library (mirrors
--     custom_factors/job_custom_factors' client_db_id/is_global pattern)
--   - mass reconciliation (confirmed quantity vs captured line-item mass)
--   - scenario tables created now so Phase 3 (the what-if engine) is
--     additive-only; not wired into calc/UI until then
--   - lca_assessments replaces lca_products; a job can hold several
--     assessments (the "Model Register" pattern -- e.g. comparing a 6L
--     vs 9L variant of the same product)

DROP TABLE IF EXISTS lca_result_snapshots;
DROP TABLE IF EXISTS lca_inventory_items;
DROP TABLE IF EXISTS lca_product_datasets;
DROP TABLE IF EXISTS lca_products;

-- job_pcf_details (a separate, free-text-only "goal & scope" form, api/job_pcf_routes.py
-- + frontend/src/components/JobPcf.tsx) is superseded by lca_assessments, which already
-- captures the same fields (name/functional unit/boundary/standard/assumptions) per
-- assessment plus a real calculation engine. Confirmed empty (table had never been
-- created in production -- lazily created on first use, which never happened).
DROP TABLE IF EXISTS job_pcf_details;

-- ---------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_modules_lookup (
  module_code VARCHAR PRIMARY KEY,
  label VARCHAR NOT NULL,
  description TEXT,
  module_group VARCHAR NOT NULL, -- 'product' (A1-A3), 'construction'/'transport' (A4-A5), 'use' (B1-B7), 'end_of_life' (C1-C4), 'benefits' (D)
  sort_order INTEGER NOT NULL DEFAULT 0,
  default_in_pcf BOOLEAN NOT NULL DEFAULT FALSE,
  default_in_lca BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO lca_modules_lookup (module_code, label, description, module_group, sort_order, default_in_pcf, default_in_lca) VALUES
  ('A1', 'Raw material supply',        'Extraction and processing of raw materials',            'product',    10, TRUE,  TRUE),
  ('A2', 'Transport to manufacturer',  'Transport of raw materials to the manufacturing site',   'product',    20, TRUE,  TRUE),
  ('A3', 'Manufacturing',              'Manufacturing and assembly of the product',              'product',    30, TRUE,  TRUE),
  ('A4', 'Transport to site/user',     'Transport of the finished product to the point of use',  'transport',  40, FALSE, TRUE),
  ('A5', 'Construction/installation',  'Installation or construction impacts',                   'transport',  50, FALSE, TRUE),
  ('B1', 'Use',                        'Emissions during normal use of the product',             'use',        60, FALSE, TRUE),
  ('B2', 'Maintenance',                'Emissions from maintaining the product',                 'use',        70, FALSE, TRUE),
  ('B3', 'Repair',                     'Emissions from repairing the product',                   'use',        80, FALSE, TRUE),
  ('B4', 'Replacement',                'Emissions from replacing parts of the product',          'use',        90, FALSE, TRUE),
  ('B5', 'Refurbishment',              'Emissions from refurbishment',                           'use',       100, FALSE, TRUE),
  ('B6', 'Operational energy use',     'Energy consumed during use',                             'use',       110, FALSE, TRUE),
  ('B7', 'Operational water use',      'Water consumed during use',                              'use',       120, FALSE, TRUE),
  ('C1', 'Deconstruction/demolition',  'End-of-life deconstruction',                             'end_of_life',130, FALSE, TRUE),
  ('C2', 'Transport to waste processing', 'Transport of waste product to processing',            'end_of_life',140, FALSE, TRUE),
  ('C3', 'Waste processing',           'Processing of waste for recycling/recovery',             'end_of_life',150, FALSE, TRUE),
  ('C4', 'Disposal',                   'Final disposal (landfill/incineration)',                 'end_of_life',160, FALSE, TRUE),
  ('D',  'Benefits beyond system boundary', 'Recycling/recovery/reuse credits',                  'benefits',   170, FALSE, TRUE)
ON CONFLICT (module_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS lca_material_categories_lookup (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id TEXT,
  name VARCHAR NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO lca_material_categories_lookup (name, description) VALUES
  ('Metal', 'Steel, aluminium, and other metals'),
  ('Plastic', 'Plastic resins and components'),
  ('Rubber', 'Rubber and synthetic elastomers'),
  ('Foam', 'Polymeric foam materials'),
  ('Aramid Fiber', 'Advanced/reinforcement fibres'),
  ('Cardboard', 'Corrugated board and paper packaging'),
  ('Label', 'Labels and small paper items'),
  ('Ink', 'Printing ink and coatings'),
  ('Equipment', 'Purchased equipment items'),
  ('Water', 'Water inputs'),
  ('Other', 'Fallback category until a more specific one is available')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------
-- Reusable component library (client-scoped, mirrors custom_factors)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_components (
  component_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_db_id INTEGER, -- NULL = shared/global component, else client-scoped
  component_code VARCHAR,
  description VARCHAR NOT NULL,
  material_category_id INTEGER REFERENCES lca_material_categories_lookup(category_id),
  default_unit_mass DOUBLE PRECISION,
  default_unit VARCHAR NOT NULL DEFAULT 'kg',
  origin_country VARCHAR,
  supplier_name VARCHAR,
  supplier_contact VARCHAR,
  notes TEXT,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  archived_at TIMESTAMP,
  archived_by VARCHAR,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_components_client ON lca_components (client_db_id, archived);
CREATE INDEX IF NOT EXISTS ix_lca_components_code ON lca_components (client_db_id, component_code);

-- ---------------------------------------------------------------------
-- Assessments (replaces lca_products) -- a job can hold several
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_assessments (
  assessment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
  client_db_id INTEGER,
  assessment_type VARCHAR NOT NULL DEFAULT 'product', -- 'product' (Phase 1) | 'service' (Phase 5)
  name VARCHAR NOT NULL,
  sku VARCHAR,
  description TEXT,
  functional_unit_value DOUBLE PRECISION NOT NULL DEFAULT 1,
  functional_unit_unit VARCHAR NOT NULL DEFAULT 'unit',
  confirmed_quantity DOUBLE PRECISION,
  confirmed_quantity_unit VARCHAR NOT NULL DEFAULT 'kg',
  lifecycle_boundary VARCHAR NOT NULL DEFAULT 'cradle_to_gate', -- 'cradle_to_gate' | 'cradle_to_grave' | 'custom'
  included_modules JSONB NOT NULL DEFAULT '["A1","A2","A3"]',
  standard VARCHAR NOT NULL DEFAULT 'ISO 14067',
  reference_year INTEGER,
  geography VARCHAR,
  assumptions TEXT,
  data_sources_note TEXT,
  review_status VARCHAR NOT NULL DEFAULT 'draft', -- draft | in_review | verified | published
  total_tco2e DOUBLE PRECISION NOT NULL DEFAULT 0,
  last_calculated_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_assessments_job ON lca_assessments (job_id, assessment_id);
CREATE INDEX IF NOT EXISTS ix_lca_assessments_client ON lca_assessments (client_db_id);

CREATE TABLE IF NOT EXISTS lca_assessment_datasets (
  assessment_id INTEGER NOT NULL REFERENCES lca_assessments(assessment_id) ON DELETE CASCADE,
  dataset_id INTEGER NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  PRIMARY KEY (assessment_id, dataset_id)
);

CREATE INDEX IF NOT EXISTS ix_lca_assessment_datasets_assessment ON lca_assessment_datasets (assessment_id);

-- ---------------------------------------------------------------------
-- Line items (replaces lca_inventory_items) -- flat, no BOM tree
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_line_items (
  line_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id INTEGER NOT NULL REFERENCES lca_assessments(assessment_id) ON DELETE CASCADE,
  component_id INTEGER REFERENCES lca_components(component_id), -- nullable: library link or ad hoc line
  module_code VARCHAR NOT NULL REFERENCES lca_modules_lookup(module_code),
  line_label VARCHAR NOT NULL,
  material_category_id INTEGER REFERENCES lca_material_categories_lookup(category_id),
  quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
  unit VARCHAR NOT NULL DEFAULT 'kg',
  origin_country VARCHAR,
  transport_mode VARCHAR,
  distance_km DOUBLE PRECISION,
  energy_kwh DOUBLE PRECISION,
  end_of_life_route VARCHAR, -- landfill | recycling | incineration | compost | other
  mapped_factor_source VARCHAR, -- 'factor_lookup' | 'custom_factor' | 'manual'
  mapped_factor_id INTEGER,
  factor_value DOUBLE PRECISION,
  factor_unit VARCHAR,
  factor_source_label VARCHAR,
  factor_source_url VARCHAR,
  data_quality VARCHAR NOT NULL DEFAULT 'secondary', -- primary | secondary | proxy | estimated
  is_gap_filled BOOLEAN NOT NULL DEFAULT FALSE,
  gap_fill_method VARCHAR,
  is_placeholder BOOLEAN NOT NULL DEFAULT FALSE, -- assembly-grouping/zero-weight row, excluded from calc
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_line_items_assessment ON lca_line_items (assessment_id, module_code);
CREATE INDEX IF NOT EXISTS ix_lca_line_items_component ON lca_line_items (component_id);
CREATE INDEX IF NOT EXISTS ix_lca_line_items_factor ON lca_line_items (mapped_factor_source, mapped_factor_id);

-- ---------------------------------------------------------------------
-- Scenarios (schema only in Phase 1 -- engine/UI wired in Phase 3)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_scenarios (
  scenario_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id INTEGER NOT NULL REFERENCES lca_assessments(assessment_id) ON DELETE CASCADE,
  name VARCHAR NOT NULL,
  description TEXT,
  is_baseline BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_scenarios_assessment ON lca_scenarios (assessment_id);

CREATE TABLE IF NOT EXISTS lca_scenario_multipliers (
  multiplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_id INTEGER NOT NULL REFERENCES lca_scenarios(scenario_id) ON DELETE CASCADE,
  module_code VARCHAR NOT NULL REFERENCES lca_modules_lookup(module_code),
  material_category_id INTEGER REFERENCES lca_material_categories_lookup(category_id), -- nullable: category-wide...
  component_id INTEGER REFERENCES lca_components(component_id), -- ...or a specific component override (more specific wins)
  multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0
);

CREATE INDEX IF NOT EXISTS ix_lca_scenario_multipliers_scenario ON lca_scenario_multipliers (scenario_id);

-- ---------------------------------------------------------------------
-- Result snapshots -- kept, but with real JSONB instead of Python str() reprs
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_result_snapshots (
  snapshot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id INTEGER NOT NULL REFERENCES lca_assessments(assessment_id) ON DELETE CASCADE,
  scenario_id INTEGER REFERENCES lca_scenarios(scenario_id),
  calculated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  calculated_by VARCHAR,
  total_tco2e DOUBLE PRECISION NOT NULL DEFAULT 0,
  module_breakdown JSONB NOT NULL DEFAULT '[]',
  hotspots JSONB NOT NULL DEFAULT '[]',
  mass_reconciliation JSONB NOT NULL DEFAULT '{}',
  notes TEXT
);

CREATE INDEX IF NOT EXISTS ix_lca_snapshots_assessment ON lca_result_snapshots (assessment_id, snapshot_id DESC);
