-- 0060_lca_service_assessments.sql
--
-- Phase 5 of the LCA/PCF rebuild (see plan for full rationale): a second,
-- structurally different assessment mode, assessment_type='service'
-- (the column has existed since Phase 1 but create_lca_assessment has
-- hard-rejected anything but 'product' until now). Activity x quantity
-- instead of material x mass, classified by GHG Protocol Scope 3 category
-- instead of EN 15804 lifecycle module.
--
-- Unification: rather than a separate Scope 3 taxonomy table, the 15
-- categories are seeded as 15 more rows in the *existing* lca_modules_lookup
-- table (module_code='S1'..'S15', module_group='scope3'). lca_line_items
-- .module_code already means "the grouping bucket this line rolls up
-- into" -- for a product line that's an EN 15804 module, for a service
-- line it's a Scope 3 category, same column, always populated, no schema
-- change needed there. This means module-breakdown grouping, scenario
-- multiplier resolution, readiness module-coverage, factor search, and
-- report/frontend module-label rendering all already work for services
-- with zero further schema change -- only the reusable-library concept
-- (lca_components -> lca_activities) and the two genuinely product-specific
-- things (mass reconciliation, material-category dimension) need new code.

INSERT INTO lca_modules_lookup (module_code, label, description, module_group, sort_order, default_in_pcf, default_in_lca) VALUES
  ('S1',  'Purchased Goods & Services',        'Extraction, production, and transport of purchased goods and services', 'scope3', 200, FALSE, FALSE),
  ('S2',  'Capital Goods',                     'Extraction, production, and transport of capital goods',                'scope3', 210, FALSE, FALSE),
  ('S3',  'Fuel- and Energy-Related Activities', 'Upstream emissions of purchased fuels and energy not in Scope 1/2',   'scope3', 220, FALSE, FALSE),
  ('S4',  'Upstream Transportation & Distribution', 'Transport and distribution of purchased goods',                    'scope3', 230, FALSE, FALSE),
  ('S5',  'Waste Generated in Operations',     'Disposal and treatment of waste generated in operations',               'scope3', 240, FALSE, FALSE),
  ('S6',  'Business Travel',                   'Transport of employees for business-related activities',                'scope3', 250, FALSE, FALSE),
  ('S7',  'Employee Commuting',                'Transport of employees between home and work',                          'scope3', 260, FALSE, FALSE),
  ('S8',  'Upstream Leased Assets',            'Operation of assets leased by the reporting entity (upstream)',         'scope3', 270, FALSE, FALSE),
  ('S9',  'Downstream Transportation & Distribution', 'Transport and distribution of sold products',                    'scope3', 280, FALSE, FALSE),
  ('S10', 'Processing of Sold Products',       'Processing of intermediate products sold by downstream companies',      'scope3', 290, FALSE, FALSE),
  ('S11', 'Use of Sold Products',              'End-use of goods and services sold by the reporting entity',            'scope3', 300, FALSE, FALSE),
  ('S12', 'End-of-Life Treatment of Sold Products', 'Disposal and treatment of sold products at end of life',           'scope3', 310, FALSE, FALSE),
  ('S13', 'Downstream Leased Assets',          'Operation of assets owned and leased to others (downstream)',           'scope3', 320, FALSE, FALSE),
  ('S14', 'Franchises',                        'Operation of franchises not included in Scope 1/2',                     'scope3', 330, FALSE, FALSE),
  ('S15', 'Investments',                       'Operation of investments, including equity and debt investments',       'scope3', 340, FALSE, FALSE)
ON CONFLICT (module_code) DO NOTHING;

-- ---------------------------------------------------------------------
-- Activity library -- the service-assessment equivalent of lca_components
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS lca_activities (
  activity_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_db_id INTEGER, -- NULL = shared/global activity, else client-scoped
  activity_code VARCHAR,
  description VARCHAR NOT NULL,
  default_module_code VARCHAR REFERENCES lca_modules_lookup(module_code), -- default Scope 3 category
  default_quantity DOUBLE PRECISION,
  default_unit VARCHAR NOT NULL DEFAULT 'unit',
  notes TEXT,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  archived_at TIMESTAMP,
  archived_by VARCHAR,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_activities_client ON lca_activities (client_db_id, archived);
CREATE INDEX IF NOT EXISTS ix_lca_activities_code ON lca_activities (client_db_id, activity_code);

ALTER TABLE lca_line_items
  ADD COLUMN IF NOT EXISTS activity_id INTEGER REFERENCES lca_activities(activity_id);

ALTER TABLE lca_scenario_multipliers
  ADD COLUMN IF NOT EXISTS activity_id INTEGER REFERENCES lca_activities(activity_id);
