-- 0061_lca_transport_legs.sql
--
-- A2/A4/C2 ("Transport to manufacturer" / "Transport to site/user" /
-- "Transport to waste processing") were schema-supported since Phase 1
-- (lca_modules_lookup) but never actually calculable: lca_line_items.
-- transport_mode/distance_km were read/written by the API but never used
-- in compute_line_emissions_tco2e (services/lca_engine.py), and never
-- rendered in any frontend UI. A single flat mode+distance per line item
-- also can't represent a real multi-leg journey (factory -> port -> port
-- -> client site), each leg needing its own mode/distance/emission factor.
--
-- This adds a child table so a transport-module line item can hold an
-- ordered sequence of legs, each geocoded (services/geocoding.py) and
-- distance-estimated (services/lca_transport.py: haversine + a
-- mode-specific detour factor -- no routing API exists in this repo).
-- transport_emissions_tco2e on lca_line_items is a cached sum of the
-- line's legs so the existing per-line aggregation in summarize_assessment
-- doesn't need to join this table at read time.

CREATE TABLE IF NOT EXISTS lca_transport_legs (
  leg_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_item_id INTEGER NOT NULL REFERENCES lca_line_items(line_item_id) ON DELETE CASCADE,
  leg_order INTEGER NOT NULL DEFAULT 0,
  mode VARCHAR NOT NULL, -- 'road' | 'rail' | 'sea' | 'air' -- drives the detour factor only, NOT the emission factor
  origin_label VARCHAR NOT NULL,
  origin_latitude NUMERIC,
  origin_longitude NUMERIC,
  origin_geocode_precision VARCHAR, -- 'address' | 'city' | 'country' | 'manual' | 'failed'
  destination_label VARCHAR NOT NULL,
  destination_latitude NUMERIC,
  destination_longitude NUMERIC,
  destination_geocode_precision VARCHAR,
  straight_line_km DOUBLE PRECISION,
  detour_factor DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  distance_km DOUBLE PRECISION, -- straight_line_km * detour_factor, or a manual override
  distance_source VARCHAR NOT NULL DEFAULT 'calculated', -- 'calculated' | 'manual'
  mapped_factor_id INTEGER, -- v_factor_lookup.db_id, chosen via the existing factor-search endpoint
  factor_value DOUBLE PRECISION,
  factor_unit VARCHAR, -- e.g. 'kgCO2e/tonne.km'
  factor_source_label VARCHAR,
  emissions_tco2e DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_transport_legs_line_item ON lca_transport_legs (line_item_id, leg_order);

ALTER TABLE lca_line_items ADD COLUMN IF NOT EXISTS transport_emissions_tco2e DOUBLE PRECISION;
