-- 0062_lca_supplier_library.sql
--
-- Global (not client-scoped), geocoded supplier library for LCA A2/A4/C2
-- transport legs. Picking a supplier location for a leg's origin -- or a
-- client site (client_sites, already geocoded) for its destination -- skips
-- the live Nominatim call in create_transport_leg entirely, since both are
-- pre-geocoded once when added to their respective libraries. Modelled the
-- same way as lca_components' global rows / factor_lookup: one live-
-- referenced-by-id table, not copied per client, since a supplier's address
-- doesn't need per-client forking.
--
-- Named lca_suppliers (not "suppliers") to avoid any confusion with the
-- pre-existing, unrelated `suppliers` table (api/admin_suppliers_routes.py)
-- -- that one is NZI's own subcontractor rate-card for job costing, has no
-- geocoding, and has nothing to do with LCA manufacturing supply chains.

CREATE TABLE IF NOT EXISTS lca_suppliers (
  supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name VARCHAR NOT NULL,
  website VARCHAR,
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lca_suppliers_name_ci ON lca_suppliers (LOWER(supplier_name));

-- Mirrors client_sites' geocode column naming (latitude/longitude/
-- geocode_source/geocode_precision/geocoded_at) for consistency -- see
-- ensure_client_sites_runtime_columns() in api/admin_user_helpers.py.
CREATE TABLE IF NOT EXISTS lca_supplier_locations (
  location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL REFERENCES lca_suppliers(supplier_id) ON DELETE CASCADE,
  location_label VARCHAR NOT NULL,
  address VARCHAR NOT NULL,
  latitude NUMERIC,
  longitude NUMERIC,
  geocode_source VARCHAR,
  geocode_precision VARCHAR,
  geocoded_at TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_supplier_locations_supplier ON lca_supplier_locations (supplier_id);

-- Structured, searchable catalog of what a supplier supplies -- powers
-- "who supplies X" lookup when adding an LCA line item, per user decision
-- (2026-08) to make this a real catalog rather than a notes field.
CREATE TABLE IF NOT EXISTS lca_supplier_components (
  component_link_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL REFERENCES lca_suppliers(supplier_id) ON DELETE CASCADE,
  component_description VARCHAR NOT NULL,
  material_category_id INTEGER REFERENCES lca_material_categories_lookup(category_id),
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_lca_supplier_components_supplier ON lca_supplier_components (supplier_id);

-- Optional link from the existing reusable component library to a known
-- supplier -- additive alongside the pre-existing free-text supplier_name/
-- supplier_contact columns, which stay for backward compat / ad hoc cases.
ALTER TABLE lca_components ADD COLUMN IF NOT EXISTS supplier_id INTEGER REFERENCES lca_suppliers(supplier_id);

-- Provenance only: origin_label/latitude/longitude on the leg itself remain
-- the actual source of truth (a snapshot taken at pick time), so editing a
-- library entry later never retroactively changes an already-saved leg's
-- distance/emissions.
ALTER TABLE lca_transport_legs ADD COLUMN IF NOT EXISTS origin_supplier_location_id INTEGER REFERENCES lca_supplier_locations(location_id);
ALTER TABLE lca_transport_legs ADD COLUMN IF NOT EXISTS destination_client_site_id INTEGER REFERENCES client_sites(site_id);
