-- 0064_action_lever_framework.sql
--
-- ISO 14060-style action lever framework: 3 Spheres -> 9 Sub-Spheres -> 24
-- Levers, used to categorize every report_action_options library entry and
-- every client_report_actions row. Mirrored (schema + seed + backfill) in
-- services.report_actions.ensure_report_actions_schema() so a fresh database
-- bootstrapped at runtime ends up in the same state as one built from these
-- migration files.

CREATE TABLE IF NOT EXISTS action_levers_lookup (
  lever_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sphere_code VARCHAR,
  sphere_name VARCHAR,
  sub_sphere_code VARCHAR,
  sub_sphere_name VARCHAR,
  lever_code VARCHAR NOT NULL,
  lever_name VARCHAR NOT NULL,
  lever_description TEXT,
  is_custom BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_action_levers_lookup_code_ci
  ON action_levers_lookup (LOWER(lever_code));

CREATE INDEX IF NOT EXISTS ix_action_levers_lookup_sort
  ON action_levers_lookup (sort_order, lever_id);

-- Standard ISO 14060 levers (is_custom = FALSE). Text transcribed verbatim
-- from the reference "Sub-Spheres and Action Levers" table.
INSERT INTO action_levers_lookup
  (sphere_code, sphere_name, sub_sphere_code, sub_sphere_name, lever_code, lever_name, lever_description, is_custom, sort_order)
VALUES
  ('A', 'Products and Services', 'A1', 'Product and Service Innovation', 'A1.1', 'A1.1',
   'Develop and scale products that accelerate others'' emissions reductions (i.e., resulting in avoided emissions)', FALSE, 10),
  ('A', 'Products and Services', 'A1', 'Product and Service Innovation', 'A1.2', 'A1.2',
   'Develop and scale services that accelerate others'' emissions reductions (i.e., resulting in avoided emissions)', FALSE, 20),
  ('A', 'Products and Services', 'A2', 'Business Model Innovation', 'A2.1', 'A2.1',
   'Implement revenue models that decouple growth from material consumption', FALSE, 30),
  ('A', 'Products and Services', 'A2', 'Business Model Innovation', 'A2.2', 'A2.2',
   'Implement incentives for sustainable consumer behaviours', FALSE, 40),
  ('A', 'Products and Services', 'A3', 'Climate Solutions Research and Development', 'A3.1', 'A3.1',
   'Catalyze and invest in internal climate solutions R&D (e.g., patents for climate solutions)', FALSE, 50),
  ('A', 'Products and Services', 'A3', 'Climate Solutions Research and Development', 'A3.2', 'A3.2',
   'Conduct joint climate solutions R&D for own products and services with external partners', FALSE, 60),

  ('B', 'Portfolio of Climate System Investments', 'B1', 'Low-carbon systems and solutions', 'B1.1', 'B1.1',
   'Scale high-integrity credits/certificates for low-carbon technology and solutions beyond the emissions inventory', FALSE, 70),
  ('B', 'Portfolio of Climate System Investments', 'B1', 'Low-carbon systems and solutions', 'B1.2', 'B1.2',
   'Support the scaling of low-carbon solutions through advanced financing (e.g., accelerators, incubator funds, offtake deals)', FALSE, 80),
  ('B', 'Portfolio of Climate System Investments', 'B1', 'Low-carbon systems and solutions', 'B1.3', 'B1.3',
   'Invest in enabling infrastructure (e.g., grids, renewables) and shift money from high-emitting activities to low-emitting activities to grow new markets for solutions', FALSE, 90),
  ('B', 'Portfolio of Climate System Investments', 'B2', 'Nature conservation and restoration', 'B2.1', 'B2.1',
   'Purchase and retire high-integrity credits/certificates supporting nature-based solutions beyond the emissions inventory', FALSE, 100),
  ('B', 'Portfolio of Climate System Investments', 'B2', 'Nature conservation and restoration', 'B2.2', 'B2.2',
   'Support conservation and restoration programmes/initiatives', FALSE, 110),
  ('B', 'Portfolio of Climate System Investments', 'B2', 'Nature conservation and restoration', 'B2.3', 'B2.3',
   'Invest in enabling infrastructure, services and wider local programmes that support the longevity and impact of restoration projects', FALSE, 120),
  ('B', 'Portfolio of Climate System Investments', 'B3', 'Carbon removals', 'B3.1', 'B3.1',
   'Purchase and retire high-integrity removal credits/certificates the beyond emissions inventory', FALSE, 130),
  ('B', 'Portfolio of Climate System Investments', 'B3', 'Carbon removals', 'B3.2', 'B3.2',
   'Support removal technology development through forward looking purchases and financing (e.g., offtake agreements, demand aggregation partnerships)', FALSE, 140),
  ('B', 'Portfolio of Climate System Investments', 'B3', 'Carbon removals', 'B3.3', 'B3.3',
   'Invest in enabling infrastructure for removals', FALSE, 150),

  ('C', 'Policy and Public Engagement', 'C1', 'Government and Policy Engagement', 'C1.1', 'C1.1',
   'Advocate for policies to address external dependencies and climate risk', FALSE, 160),
  ('C', 'Policy and Public Engagement', 'C1', 'Government and Policy Engagement', 'C1.2', 'C1.2',
   'Advocate for policies to incentivize corporate climate action', FALSE, 170),
  ('C', 'Policy and Public Engagement', 'C1', 'Government and Policy Engagement', 'C1.3', 'C1.3',
   'Advocate for policies to remove barriers for net zero compatible lifestyles', FALSE, 180),
  ('C', 'Policy and Public Engagement', 'C2', 'Industry Engagement', 'C2.1', 'C2.1',
   'Advocate and engage with suppliers and partners to implement climate action and sustainable practices', FALSE, 190),
  ('C', 'Policy and Public Engagement', 'C2', 'Industry Engagement', 'C2.2', 'C2.2',
   'Advocate for alignment to the Paris Agreement for all affiliated coalitions, business and trade associations', FALSE, 200),
  ('C', 'Policy and Public Engagement', 'C2', 'Industry Engagement', 'C2.3', 'C2.3',
   'Participate in a multistakeholder coalition or initiative with the explicit objective of aligning with global net zero', FALSE, 210),
  ('C', 'Policy and Public Engagement', 'C2', 'Industry Engagement', 'C2.4', 'C2.4',
   'Open-source climate knowledge and solutions', FALSE, 220),
  ('C', 'Policy and Public Engagement', 'C3', 'Public Engagement and Empowerment', 'C3.1', 'C3.1',
   'Equip the public with science-backed efforts to generate demand for and enable sustainable lifestyles (e.g., campaigns, entertainment or advertising to clients, customers, employees, or broader public)', FALSE, 230),
  ('C', 'Policy and Public Engagement', 'C3', 'Public Engagement and Empowerment', 'C3.2', 'C3.2',
   'Participate in public climate advocacy campaigns', FALSE, 240)
ON CONFLICT (LOWER(lever_code)) DO NOTHING;

-- Reserved bucket for actions/options that predate this framework.
INSERT INTO action_levers_lookup
  (sphere_code, sphere_name, sub_sphere_code, sub_sphere_name, lever_code, lever_name, lever_description, is_custom, sort_order)
SELECT NULL, NULL, NULL, NULL, 'UNCLASSIFIED-LEGACY', 'Unclassified (Legacy)',
  'Actions and library options created before the lever framework was introduced. Reclassify as time allows.', TRUE, 9999
ON CONFLICT (LOWER(lever_code)) DO NOTHING;

ALTER TABLE report_action_options
  ADD COLUMN IF NOT EXISTS lever_id INTEGER REFERENCES action_levers_lookup(lever_id);
ALTER TABLE client_report_actions
  ADD COLUMN IF NOT EXISTS lever_id INTEGER REFERENCES action_levers_lookup(lever_id);

UPDATE report_action_options
SET lever_id = (SELECT lever_id FROM action_levers_lookup WHERE LOWER(lever_code) = 'unclassified-legacy')
WHERE lever_id IS NULL;

UPDATE client_report_actions
SET lever_id = (SELECT lever_id FROM action_levers_lookup WHERE LOWER(lever_code) = 'unclassified-legacy')
WHERE lever_id IS NULL;
