-- 0065_srs_readiness.sql
--
-- UK SRS Readiness Tool: a 4-section (Governance, Strategy, Risk Management,
-- Metrics & Targets), 24-question evidence-based maturity assessment, scored
-- 1 (Compliance) to 3 (Cultural) per question. Mirrored (schema + seed) in
-- services.srs_readiness.ensure_srs_readiness_schema() so a fresh database
-- bootstrapped at runtime ends up in the same state as one built from this
-- migration file.

CREATE TABLE IF NOT EXISTS srs_readiness_questions (
  question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_code VARCHAR NOT NULL,
  section VARCHAR NOT NULL,
  theme VARCHAR,
  question_text TEXT NOT NULL,
  evidence_examples TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_custom BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_srs_readiness_questions_code_ci
  ON srs_readiness_questions (LOWER(question_code));

CREATE INDEX IF NOT EXISTS ix_srs_readiness_questions_sort
  ON srs_readiness_questions (sort_order, question_id);

CREATE TABLE IF NOT EXISTS srs_readiness_responses (
  response_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_db_id INTEGER NOT NULL REFERENCES clients(db_id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES srs_readiness_questions(question_id) ON DELETE CASCADE,
  score SMALLINT,
  evidence_notes TEXT,
  priority VARCHAR,
  owner VARCHAR,
  target_date DATE,
  status VARCHAR NOT NULL DEFAULT 'not_started',
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR,
  CONSTRAINT ck_srs_readiness_responses_score CHECK (score IS NULL OR score BETWEEN 1 AND 3),
  CONSTRAINT ux_srs_readiness_responses_client_question UNIQUE (client_db_id, question_id)
);

CREATE INDEX IF NOT EXISTS ix_srs_readiness_responses_client
  ON srs_readiness_responses (client_db_id);

-- 24 standard questions (is_custom = FALSE), transcribed verbatim from the
-- UK SRS Readiness Tracker Dashboard Scoring Tool "Assessment" tab.
INSERT INTO srs_readiness_questions (question_code, section, theme, question_text, evidence_examples, is_custom, sort_order)
SELECT * FROM (VALUES
  ('GOV-1', 'Governance', 'Leadership oversight', 'Is there a named senior leader or leadership team with accountability for sustainability-related decisions?', 'Board papers, leadership terms of reference, named role profile, management structure.', FALSE, 10),
  ('GOV-2', 'Governance', 'Roles and responsibilities', 'Are sustainability roles and responsibilities documented and communicated across the business?', 'RACI, job descriptions, policy statements, induction material.', FALSE, 20),
  ('GOV-3', 'Governance', 'Reporting cadence', 'Is sustainability performance reviewed on a defined timetable by leadership?', 'Meeting calendar, agenda papers, minutes, KPI packs.', FALSE, 30),
  ('GOV-4', 'Governance', 'Decision-making', 'Is sustainability considered in major business decisions such as bids, supplier choices, investment, or product changes?', 'Approval papers, tender sign-off checklist, procurement template, capex form.', FALSE, 40),
  ('GOV-5', 'Governance', 'Policy framework', 'Does the business have a current policy or governance statement covering sustainability commitments and expectations?', 'Approved policy, intranet page, external statement, supplier code.', FALSE, 50),
  ('GOV-6', 'Governance', 'Accountability', 'Are sustainability objectives or responsibilities reflected in management objectives or team plans?', 'Performance objectives, departmental plans, management scorecards.', FALSE, 60),
  ('STR-1', 'Strategy', 'Customer expectations', 'Has the business identified what large customers are asking for on climate, carbon, or sustainability reporting?', 'Bid requirements log, customer questionnaires, account notes, sales feedback.', FALSE, 70),
  ('STR-2', 'Strategy', 'Business planning', 'Is sustainability reflected in the business plan, growth plan, or strategic priorities?', 'Strategy documents, annual plan, investment roadmap.', FALSE, 80),
  ('STR-3', 'Strategy', 'Commercial opportunity', 'Has the business assessed where stronger sustainability performance could help win, retain, or deepen customer relationships?', 'Customer account plan, market analysis, pipeline review, workshop notes.', FALSE, 90),
  ('STR-4', 'Strategy', 'Value chain understanding', 'Has the business considered where it sits in customers'' supply chains and what data or action it may need to provide?', 'Supply chain map, customer reporting templates, materiality discussion.', FALSE, 100),
  ('STR-5', 'Strategy', 'Resource planning', 'Has the business identified the people, systems, and budget needed to improve sustainability reporting readiness?', 'Budget line, project plan, system review, resourcing plan.', FALSE, 110),
  ('STR-6', 'Strategy', 'Forward priorities', 'Is there a documented 12-24 month plan for improving sustainability capability?', 'Roadmap, implementation plan, milestone tracker.', FALSE, 120),
  ('RISK-1', 'Risk Management', 'Risk identification', 'Has the business identified sustainability-related risks that could affect operations, customers, compliance, or reputation?', 'Risk register, workshop output, board paper.', FALSE, 130),
  ('RISK-2', 'Risk Management', 'Customer risk', 'Does the business assess the risk of losing work or being excluded from tenders due to weak sustainability data or performance?', 'Tender review, lost-opportunity log, customer feedback.', FALSE, 140),
  ('RISK-3', 'Risk Management', 'Regulatory awareness', 'Is there a process for monitoring relevant reporting developments and customer-driven requirements?', 'Horizon scanning note, legal update, advisor update, compliance calendar.', FALSE, 150),
  ('RISK-4', 'Risk Management', 'Mitigation actions', 'Are actions in place to manage key sustainability risks once identified?', 'Action plan, mitigation owners, project tracker.', FALSE, 160),
  ('RISK-5', 'Risk Management', 'Review cycle', 'Are sustainability-related risks reviewed regularly alongside other business risks?', 'Risk committee papers, quarterly risk reviews, board minutes.', FALSE, 170),
  ('RISK-6', 'Risk Management', 'Escalation', 'Is there a clear route to escalate sustainability issues or customer concerns to leadership?', 'Escalation procedure, governance map, incident log.', FALSE, 180),
  ('MET-1', 'Metrics & Targets', 'Data coverage', 'Does the business collect a defined set of sustainability or carbon data relevant to customer requirements?', 'Data map, spreadsheet, software export, reporting template.', FALSE, 190),
  ('MET-2', 'Metrics & Targets', 'Data quality', 'Are data sources, assumptions, and calculation methods documented?', 'Methodology note, calculation file, assumptions log.', FALSE, 200),
  ('MET-3', 'Metrics & Targets', 'KPIs', 'Are sustainability KPIs reported internally on a regular basis?', 'KPI dashboard, monthly report, management pack.', FALSE, 210),
  ('MET-4', 'Metrics & Targets', 'Targets', 'Does the business have formal sustainability or carbon targets with baselines and dates?', 'Target statement, baseline year note, transition plan.', FALSE, 220),
  ('MET-5', 'Metrics & Targets', 'Action tracking', 'Are actions to improve performance tracked against milestones, owners, and dates?', 'Action tracker, project plan, governance pack.', FALSE, 230),
  ('MET-6', 'Metrics & Targets', 'Customer reporting readiness', 'Can the business respond efficiently to customer requests for sustainability data, policies, and evidence?', 'Completed customer questionnaires, data room, bid library, case examples.', FALSE, 240)
) AS seed(question_code, section, theme, question_text, evidence_examples, is_custom, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM srs_readiness_questions WHERE lower(srs_readiness_questions.question_code) = lower(seed.question_code)
);
