-- 0069_srs_readiness_assessments.sql
--
-- Adds period-on-period history to the UK SRS Readiness tool.
--
-- Until now srs_readiness_responses held exactly one mutable row per
-- (client, question) -- every re-score overwrote the last, so there was no
-- way to show how a client matures over time. This migration introduces a
-- timestamped "assessment" (survey round) that freezes the scored answers,
-- while srs_readiness_responses stays as the rolling action tracker
-- (priority / owner / target_date / status / working notes) plus a
-- denormalised mirror of the latest finalised score.
--
-- Mirrored (schema only, not the backfill) in
-- services.srs_readiness.ensure_srs_readiness_schema() so a runtime-
-- bootstrapped database ends up in the same shape -- same convention as
-- sql_migrations/0065_srs_readiness.sql.

CREATE TABLE IF NOT EXISTS srs_readiness_assessments (
  assessment_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_db_id   INTEGER NOT NULL REFERENCES clients(db_id) ON DELETE CASCADE,
  label          VARCHAR,
  period_year    INTEGER NOT NULL,
  period_label   VARCHAR,
  conducted_on   DATE NOT NULL DEFAULT CURRENT_DATE,
  status         VARCHAR NOT NULL DEFAULT 'draft',
  is_baseline    BOOLEAN NOT NULL DEFAULT FALSE,
  workshop_notes TEXT,
  finalised_at   TIMESTAMP,
  finalised_by   VARCHAR,
  created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by     VARCHAR,
  updated_at     TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by     VARCHAR,
  CONSTRAINT ck_srs_readiness_assessments_status CHECK (status IN ('draft', 'finalised'))
);

-- At most one open draft per client.
CREATE UNIQUE INDEX IF NOT EXISTS ux_srs_assessments_one_draft
  ON srs_readiness_assessments (client_db_id) WHERE status = 'draft';

CREATE INDEX IF NOT EXISTS ix_srs_assessments_client
  ON srs_readiness_assessments (client_db_id, conducted_on);

CREATE TABLE IF NOT EXISTS srs_readiness_assessment_scores (
  assessment_id  INTEGER NOT NULL REFERENCES srs_readiness_assessments(assessment_id) ON DELETE CASCADE,
  question_id    INTEGER NOT NULL REFERENCES srs_readiness_questions(question_id),
  question_code  VARCHAR NOT NULL,
  section        VARCHAR NOT NULL,
  theme          VARCHAR,
  question_text  TEXT NOT NULL,
  score          SMALLINT,
  evidence_notes TEXT,
  updated_at     TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_srs_assessment_scores_score CHECK (score IS NULL OR score BETWEEN 1 AND 3),
  CONSTRAINT pk_srs_assessment_scores PRIMARY KEY (assessment_id, question_id)
);

-- ---------------------------------------------------------------------------
-- Backfill: turn each client's existing scored responses into a finalised
-- "Baseline (imported)" assessment, timestamped at their last edit. Guarded
-- so re-running is a no-op and so clients that already have an assessment
-- (runtime-bootstrapped ahead of this file) are skipped.
-- ---------------------------------------------------------------------------

INSERT INTO srs_readiness_assessments
  (client_db_id, label, period_year, conducted_on, status, is_baseline,
   finalised_at, finalised_by, created_by, updated_by)
SELECT r.client_db_id,
       'Baseline (imported)',
       EXTRACT(YEAR FROM MAX(r.updated_at))::INTEGER,
       MAX(r.updated_at)::DATE,
       'finalised',
       TRUE,
       NOW(),
       'system:migration',
       'system:migration',
       'system:migration'
FROM srs_readiness_responses r
WHERE r.score IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM srs_readiness_assessments a WHERE a.client_db_id = r.client_db_id
  )
GROUP BY r.client_db_id;

INSERT INTO srs_readiness_assessment_scores
  (assessment_id, question_id, question_code, section, theme, question_text, score, evidence_notes)
SELECT a.assessment_id, q.question_id, q.question_code, q.section, q.theme, q.question_text,
       r.score, r.evidence_notes
FROM srs_readiness_assessments a
JOIN srs_readiness_responses r
  ON r.client_db_id = a.client_db_id AND r.score IS NOT NULL
JOIN srs_readiness_questions q
  ON q.question_id = r.question_id
WHERE a.label = 'Baseline (imported)'
  AND a.finalised_by = 'system:migration'
  AND NOT EXISTS (
    SELECT 1 FROM srs_readiness_assessment_scores s
    WHERE s.assessment_id = a.assessment_id AND s.question_id = r.question_id
  );
