CREATE TABLE IF NOT EXISTS client_teams_lookup (
  client_team_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO client_teams_lookup (name, is_active)
VALUES
  ('HR', TRUE),
  ('Finance', TRUE),
  ('Sales and Marketing', TRUE),
  ('Operations', TRUE),
  ('Board', TRUE)
ON CONFLICT (name) DO NOTHING;
