-- Add the requested defaults without removing existing or custom categories.
CREATE TABLE IF NOT EXISTS action_categories_lookup (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO action_categories_lookup (name)
SELECT defaults.name
FROM (VALUES ('Governance'), ('Metrics'), ('Strategy'), ('Risk'),
             ('Upskilling'), ('Energy'), ('Engagement'), ('Accreditation')) AS defaults(name)
WHERE NOT EXISTS (
  SELECT 1 FROM action_categories_lookup existing
  WHERE lower(existing.name) = lower(defaults.name)
);
