"""Client Files API — direct client-level file storage + cascaded job files view."""
import re
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse

from api.auth import _current_user
from api.job_files_routes import (
    _ensure_job_files_table,
    _mime_type_for_filename,
    _onedrive_enabled,
    _onedrive_upload_bytes,
)
from core.database import get_conn
from services.virus_scan import VirusScanError, scan_bytes

router = APIRouter()

UPLOAD_DIR = Path("uploads/client_files")
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


def _ensure_client_files_table(con) -> None:
    """Keep client_files schema resilient across local and upgraded environments.

    CREATE TABLE IF NOT EXISTS is a no-op against an already-existing table,
    so any column added here after the table was first created in production
    must also be backfilled via ALTER TABLE ... ADD COLUMN IF NOT EXISTS
    (mirrors the same pattern already used for job_files).
    """
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS client_files (
          file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          client_db_id INTEGER NOT NULL,
          file_type VARCHAR NOT NULL DEFAULT 'general',
          file_name VARCHAR NOT NULL,
          file_path TEXT,
          file_size BIGINT,
          mime_type VARCHAR,
          description TEXT,
          uploaded_by VARCHAR,
          uploaded_at TIMESTAMP DEFAULT NOW(),
          storage_provider VARCHAR DEFAULT 'local',
          external_item_id VARCHAR,
          external_web_url TEXT,
          external_path TEXT,
          notes TEXT
        )
        """
    )
    for _stmt in [
        "ALTER TABLE client_files ADD COLUMN IF NOT EXISTS storage_provider VARCHAR DEFAULT 'local'",
        "ALTER TABLE client_files ADD COLUMN IF NOT EXISTS external_item_id VARCHAR",
        "ALTER TABLE client_files ADD COLUMN IF NOT EXISTS external_web_url TEXT",
        "ALTER TABLE client_files ADD COLUMN IF NOT EXISTS external_path TEXT",
        "ALTER TABLE client_files ADD COLUMN IF NOT EXISTS notes TEXT",
    ]:
        try:
            con.execute(_stmt)
        except Exception:
            pass


def _safe_client_filename(client_id: int, filename: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._ -]+", "_", str(filename or "unknown").strip())
    cleaned = cleaned.replace("..", "_")
    cleaned = cleaned.strip(" .") or "upload.bin"
    return f"c{int(client_id)}_{cleaned}"


def _save_client_upload(file: UploadFile, client_id: int) -> tuple[dict, str]:
    contents = file.file.read()
    if not contents:
        raise HTTPException(status_code=400, detail="Cannot upload empty file")
    try:
        scan_bytes(contents, filename=file.filename or "unknown")
    except VirusScanError as e:
        raise HTTPException(status_code=400, detail=str(e))
    storage_name = _safe_client_filename(client_id, file.filename or "unknown")
    mime_type = _mime_type_for_filename(file.filename or "unknown")
    if _onedrive_enabled():
        result = _onedrive_upload_bytes(
            filename=storage_name,
            content=contents,
            job_id=client_id,
            file_type="client_provided",
            storage_folder_key=f"clients/client-{client_id}",
        )
        return result, mime_type
    local_path = UPLOAD_DIR / storage_name
    with open(local_path, "wb") as f:
        f.write(contents)
    return {
        "storage_provider": "local",
        "file_path": str(local_path),
        "external_item_id": None,
        "external_web_url": None,
        "external_path": None,
        "file_size": len(contents),
    }, mime_type


@router.get("/clients/{client_id}/files")
def list_client_files(client_id: int, _user: dict = Depends(_current_user)):
    """Return direct client files + all files from this client's jobs (cascaded)."""
    try:
        with get_conn() as con:
            _ensure_client_files_table(con)
            _ensure_job_files_table(con)

            cr = con.execute(
                """
                SELECT file_id, client_db_id, file_type, file_name, file_size,
                       mime_type, description, uploaded_by, uploaded_at,
                       storage_provider, external_web_url, notes
                FROM client_files
                WHERE client_db_id = %s
                ORDER BY uploaded_at DESC
                """,
                [int(client_id)],
            ).fetchall()

            jr = con.execute(
                """
                SELECT jf.file_id, jf.job_id, j.job_number, j.title,
                       jf.file_type, jf.file_name, jf.file_size, jf.mime_type,
                       jf.description, jf.uploaded_by, jf.uploaded_at,
                       jf.storage_provider, jf.external_web_url, jf.notes
                FROM job_files jf
                JOIN jobs j ON j.job_id = jf.job_id
                WHERE j.client_db_id = %s
                ORDER BY jf.uploaded_at DESC
                """,
                [int(client_id)],
            ).fetchall()

            files = []
            for r in cr:
                files.append({
                    "file_id": int(r[0]),
                    "source": "client",
                    "client_db_id": int(r[1]),
                    "job_id": None,
                    "job_number": None,
                    "job_title": None,
                    "file_type": str(r[2] or "general"),
                    "file_name": str(r[3] or ""),
                    "file_size": int(r[4]) if r[4] is not None else None,
                    "mime_type": str(r[5] or ""),
                    "description": str(r[6] or ""),
                    "uploaded_by": str(r[7] or ""),
                    "uploaded_at": str(r[8]) if r[8] else None,
                    "storage_provider": str(r[9] or "local"),
                    "external_web_url": str(r[10]) if r[10] else None,
                    "notes": str(r[11]) if r[11] else None,
                })
            for r in jr:
                files.append({
                    "file_id": int(r[0]),
                    "source": "job",
                    "client_db_id": int(client_id),
                    "job_id": int(r[1]),
                    "job_number": str(r[2] or ""),
                    "job_title": str(r[3] or ""),
                    "file_type": str(r[4] or ""),
                    "file_name": str(r[5] or ""),
                    "file_size": int(r[6]) if r[6] is not None else None,
                    "mime_type": str(r[7] or ""),
                    "description": str(r[8] or ""),
                    "uploaded_by": str(r[9] or ""),
                    "uploaded_at": str(r[10]) if r[10] else None,
                    "storage_provider": str(r[11] or "local"),
                    "external_web_url": str(r[12]) if r[12] else None,
                    "notes": str(r[13]) if r[13] else None,
                })

            return {"files": files, "total": len(files)}
    except Exception:
        import logging
        logging.getLogger(__name__).exception("Failed to list client files")
        return {"files": [], "total": 0}


@router.post("/clients/{client_id}/files")
async def upload_client_file(
    client_id: int,
    file: UploadFile = File(...),
    file_type: str = Form(default="general"),
    description: str = Form(default=""),
    notes: str = Form(default=""),
    _user: dict = Depends(_current_user),
):
    """Upload a file directly to a client."""
    with get_conn() as con:
        _ensure_client_files_table(con)
        user_id = str(_user.get("user_id") or "")
        storage_info, mime_type = _save_client_upload(file, client_id)
        row = con.execute(
            """
            INSERT INTO client_files (
                client_db_id, file_type, file_name, file_path, file_size, mime_type,
                description, uploaded_by, storage_provider,
                external_item_id, external_web_url, external_path, notes
            ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            RETURNING file_id
            """,
            [
                int(client_id),
                str(file_type or "general"),
                str(file.filename or "unknown"),
                str(storage_info.get("file_path") or ""),
                storage_info.get("file_size"),
                mime_type,
                str(description or ""),
                user_id,
                str(storage_info.get("storage_provider") or "local"),
                storage_info.get("external_item_id"),
                storage_info.get("external_web_url"),
                storage_info.get("external_path"),
                str(notes or ""),
            ],
        ).fetchone()
        return {"ok": True, "file_id": int(row[0]), "file_name": file.filename}


@router.delete("/clients/{client_id}/files/{file_id}")
def delete_client_file(
    client_id: int,
    file_id: int,
    _user: dict = Depends(_current_user),
):
    with get_conn() as con:
        _ensure_client_files_table(con)
        row = con.execute(
            "SELECT file_path, storage_provider FROM client_files WHERE file_id = %s AND client_db_id = %s",
            [int(file_id), int(client_id)],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="File not found")
        file_path, storage_provider = row
        if (storage_provider or "local") == "local" and file_path:
            try:
                Path(file_path).unlink(missing_ok=True)
            except Exception:
                pass
        con.execute(
            "DELETE FROM client_files WHERE file_id = %s AND client_db_id = %s",
            [int(file_id), int(client_id)],
        )
        return {"ok": True}


@router.get("/clients/{client_id}/files/{file_id}/download")
def download_client_file(
    client_id: int,
    file_id: int,
    _user: dict = Depends(_current_user),
):
    with get_conn() as con:
        _ensure_client_files_table(con)
        row = con.execute(
            """
            SELECT file_name, file_path, mime_type, storage_provider, external_web_url
            FROM client_files
            WHERE file_id = %s AND client_db_id = %s
            """,
            [int(file_id), int(client_id)],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="File not found")
        file_name, file_path, mime_type, storage_provider, external_web_url = row
        if (storage_provider or "local") == "onedrive" and external_web_url:
            from fastapi.responses import RedirectResponse
            return RedirectResponse(url=str(external_web_url))
        if not file_path or not Path(file_path).exists():
            raise HTTPException(status_code=404, detail="File not found on disk")
        return FileResponse(
            path=str(file_path),
            filename=str(file_name or "download"),
            media_type=str(mime_type or "application/octet-stream"),
        )
