from __future__ import annotations

from datetime import date
from typing import Any
import re
import logging

from fastapi import APIRouter, Body, Depends, HTTPException, Query, Request, Response
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate

from api.auth import _current_user
from api.org_admin_helpers import _require_org_plan_active
from core.database import get_conn
from services.audit_log import fetch_entity_history, record_audit_event
from services.messaging_templates import build_email_content
from services.outbound_email import send_tracked_email

from api.quotes_routes import (
    _safe_float,
    _safe_int,
    _quote_org_id,
    _invoice_lines_for,
    _invoice_totals_from_lines,
    _serialize_invoice,
    _build_financial_pdf_story,
    _display_date,
    _pdf_footer,
)
from services.company_profile import get_company_profile

router = APIRouter(tags=["credit_notes"])
logger = logging.getLogger(__name__)


def _ensure_credit_note_tables(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS credit_notes (
          credit_note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          client_db_id INTEGER NOT NULL,
          org_id UUID,
          job_id INTEGER,
          invoice_id INTEGER,
          credit_note_number VARCHAR,
          credit_note_date DATE,
          currency_code VARCHAR,
          subtotal DOUBLE PRECISION DEFAULT 0,
          vat DOUBLE PRECISION DEFAULT 0,
          total DOUBLE PRECISION DEFAULT 0,
          status VARCHAR DEFAULT 'Draft',
          notes TEXT,
          xero_credit_note_id VARCHAR,
          xero_credit_note_number VARCHAR,
          xero_status VARCHAR,
          xero_sync_status VARCHAR DEFAULT 'pending',
          xero_synced_at TIMESTAMP,
          xero_sync_error TEXT,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute("ALTER TABLE credit_notes ADD COLUMN IF NOT EXISTS applied_amount DOUBLE PRECISION DEFAULT 0")
    con.execute("ALTER TABLE credit_notes ADD COLUMN IF NOT EXISTS applied_date DATE")
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS credit_note_lines (
          credit_note_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          credit_note_id INTEGER NOT NULL,
          org_id UUID,
          sort_order INTEGER,
          item_id INTEGER,
          description TEXT,
          unit VARCHAR,
          qty DOUBLE PRECISION,
          unit_price_ex_vat DOUBLE PRECISION,
          amount_ex_vat DOUBLE PRECISION,
          vat_rate_id INTEGER,
          vat_rate_pct DOUBLE PRECISION,
          notes TEXT
        )
        """
    )
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS credit_note_email_log (
          email_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          credit_note_id INTEGER NOT NULL,
          org_id UUID,
          sent_to VARCHAR NOT NULL,
          subject TEXT,
          body TEXT,
          sent_by VARCHAR,
          sent_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS xero_credit_note_links (
          credit_note_id INTEGER PRIMARY KEY,
          xero_credit_note_id VARCHAR,
          xero_credit_note_number VARCHAR,
          xero_status VARCHAR,
          xero_sync_status VARCHAR NOT NULL DEFAULT 'pending',
          xero_sync_error TEXT,
          last_synced_at TIMESTAMP,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute("CREATE INDEX IF NOT EXISTS credit_notes_xero_idx ON credit_notes (xero_credit_note_id)")
    con.execute("CREATE INDEX IF NOT EXISTS credit_notes_client_idx ON credit_notes (client_db_id)")
    con.execute("CREATE INDEX IF NOT EXISTS credit_notes_job_idx ON credit_notes (job_id)")
    con.execute("CREATE INDEX IF NOT EXISTS credit_notes_invoice_idx ON credit_notes (invoice_id)")
    con.execute("CREATE INDEX IF NOT EXISTS credit_note_lines_credit_note_idx ON credit_note_lines (credit_note_id)")


def _next_credit_note_number(con, org_id: str | None = None) -> str:
    org_clause = " AND org_id = %s" if org_id else ""
    params = [org_id] if org_id else []
    df = con.execute(
        f"SELECT credit_note_number FROM credit_notes WHERE credit_note_number IS NOT NULL{org_clause}",
        params,
    ).df()
    max_num = 999
    if df is not None and not df.empty:
        for _, r in df.iterrows():
            cn = str(r.get("credit_note_number") or "").strip()
            m = re.match(r"^CN(\d+)$", cn, flags=re.IGNORECASE)
            if not m:
                continue
            value = int(m.group(1))
            if value > max_num:
                max_num = value
    return f"CN{max_num + 1:06d}"


def _credit_note_lines_for(con, credit_note_id: int, org_id: str | None = None) -> list[dict[str, Any]]:
    org_clause = " AND cn.org_id = %s" if org_id else ""
    params: list[Any] = [int(credit_note_id)]
    if org_id:
        params.append(str(org_id).strip())
    df = con.execute(
        """
        SELECT cnl.credit_note_line_id, cnl.credit_note_id, cnl.sort_order, cnl.item_id, ji.item_name,
               cnl.description, cnl.unit, cnl.qty, cnl.unit_price_ex_vat, cnl.amount_ex_vat,
               cnl.vat_rate_id, cnl.vat_rate_pct, cnl.notes
        FROM credit_note_lines cnl
        JOIN credit_notes cn ON cn.credit_note_id = cnl.credit_note_id
        LEFT JOIN job_items ji ON ji.item_id = cnl.item_id
        WHERE cnl.credit_note_id = %s
        """ + org_clause + """
        ORDER BY COALESCE(cnl.sort_order, 0), cnl.credit_note_line_id
        """,
        params,
    ).df()
    lines: list[dict[str, Any]] = []
    if df is None or df.empty:
        return lines
    for _, r in df.iterrows():
        qty = _safe_float(r.get("qty"), 0.0)
        rate = _safe_float(r.get("unit_price_ex_vat"), 0.0)
        amount = _safe_float(r.get("amount_ex_vat"), qty * rate)
        lines.append(
            {
                "credit_note_line_id": _safe_int(r.get("credit_note_line_id"), 0),
                "sort_order": _safe_int(r.get("sort_order"), 0),
                "item_id": _safe_int(r.get("item_id"), None),
                "item_name": str(r.get("item_name") or ""),
                "description": str(r.get("description") or ""),
                "unit": str(r.get("unit") or ""),
                "qty": qty,
                "rate": rate,
                "amount": round(amount, 2),
                "vat_rate_id": _safe_int(r.get("vat_rate_id"), None),
                "vat_rate_pct": _safe_float(r.get("vat_rate_pct"), 0.0),
                "notes": str(r.get("notes") or ""),
            }
        )
    return lines


def _write_credit_note_lines(con, credit_note_id: int, lines: list[dict[str, Any]], org_id: str | None = None) -> None:
    if org_id:
        con.execute(
            "DELETE FROM credit_note_lines WHERE credit_note_id = %s AND org_id = %s",
            [int(credit_note_id), org_id],
        )
    else:
        con.execute("DELETE FROM credit_note_lines WHERE credit_note_id = %s", [int(credit_note_id)])
    for idx, line in enumerate(lines):
        qty = _safe_float(line.get("qty"), 0.0)
        rate = _safe_float(line.get("rate"), 0.0)
        amount = _safe_float(line.get("amount"), qty * rate)
        con.execute(
            """
            INSERT INTO credit_note_lines (
              credit_note_id, org_id, sort_order, item_id, description, unit,
              qty, unit_price_ex_vat, amount_ex_vat, vat_rate_id, vat_rate_pct, notes
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            [
                int(credit_note_id),
                str(org_id).strip() if org_id else None,
                _safe_int(line.get("sort_order"), idx + 1),
                _safe_int(line.get("item_id"), None),
                str(line.get("description") or ""),
                str(line.get("unit") or ""),
                qty,
                rate,
                amount,
                _safe_int(line.get("vat_rate_id"), None),
                _safe_float(line.get("vat_rate_pct"), 0.0),
                str(line.get("notes") or ""),
            ],
        )


def _serialize_credit_note(con, credit_note_id: int, org_id: str | None = None) -> dict[str, Any]:
    org_clause = " AND org_id = %s" if org_id else ""
    params: list[Any] = [int(credit_note_id)]
    if org_id:
        params.append(str(org_id).strip())
    row = con.execute(
        """
        SELECT credit_note_id, client_db_id, job_id, invoice_id, credit_note_number, credit_note_date,
               currency_code, subtotal, vat, total, status, notes,
               xero_credit_note_id, xero_credit_note_number, xero_status, xero_sync_status,
               xero_synced_at, xero_sync_error, created_at, updated_at, applied_amount, applied_date
        FROM credit_notes
        WHERE credit_note_id = %s
        """ + org_clause + """
        """,
        params,
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Credit note not found")
    lines = _credit_note_lines_for(con, int(credit_note_id), org_id=org_id)
    if lines:
        totals = _invoice_totals_from_lines(lines)
    else:
        totals = {
            "subtotal": round(_safe_float(row[7]), 2),
            "vat": round(_safe_float(row[8]), 2),
            "total": round(_safe_float(row[9]), 2),
        }
    job_id = _safe_int(row[2], None)
    job_number = ""
    if job_id is not None:
        j_row = con.execute("SELECT job_number FROM jobs WHERE job_id = %s", [job_id]).fetchone()
        if j_row:
            job_number = str(j_row[0] or "")
    invoice_id = _safe_int(row[3], None)
    invoice_number = ""
    if invoice_id is not None:
        inv_row = con.execute("SELECT invoice_number FROM invoices WHERE invoice_id = %s", [invoice_id]).fetchone()
        if inv_row:
            invoice_number = str(inv_row[0] or "")
    client_db_id = int(row[1])
    c_row = con.execute(
        "SELECT client_name, addr_line1, addr_line2, addr_city, addr_region, addr_postcode, addr_country FROM clients WHERE db_id = %s",
        [client_db_id],
    ).fetchone()
    client_name = str(c_row[0] or "") if c_row else ""
    bill_to = ""
    if c_row:
        address_lines = [str(c_row[i] or "").strip() for i in range(1, 7)]
        bill_to = "\n".join([line for line in [client_name, *address_lines] if line])
    return {
        "credit_note_id": int(row[0]),
        "client_db_id": client_db_id,
        "client_name": client_name,
        "job_id": job_id,
        "job_number": job_number,
        "invoice_id": invoice_id,
        "invoice_number": invoice_number,
        "credit_note_number": str(row[4] or ""),
        "credit_note_date": row[5].isoformat() if row[5] else None,
        "currency_code": str(row[6] or "GBP"),
        "subtotal": totals["subtotal"],
        "vat": totals["vat"],
        "total": totals["total"],
        "status": str(row[10] or "Draft"),
        "notes": str(row[11] or ""),
        "xero_credit_note_id": str(row[12] or "") if row[12] is not None else "",
        "xero_credit_note_number": str(row[13] or "") if row[13] is not None else "",
        "xero_status": str(row[14] or "") if row[14] is not None else "",
        "xero_sync_status": str(row[15] or "") if row[15] is not None else "pending",
        "xero_synced_at": row[16].isoformat() if row[16] else None,
        "xero_sync_error": str(row[17] or "") if row[17] is not None else "",
        "created_at": row[18].isoformat() if row[18] else None,
        "updated_at": row[19].isoformat() if row[19] else None,
        "applied_amount": round(_safe_float(row[20]), 2) if len(row) > 20 else 0.0,
        "applied_date": row[21].isoformat() if len(row) > 21 and row[21] else None,
        "bill_to": bill_to,
        "lines": lines,
        "company_profile": get_company_profile(con),
    }


def _render_credit_note_pdf_bytes(credit_note: dict[str, Any]) -> bytes:
    import io

    currency = str(credit_note.get("currency_code") or "GBP").strip().upper()
    company_profile = credit_note.get("company_profile") or {}
    lines = credit_note.get("lines") or []
    left_details = [x for x in str(credit_note.get("bill_to") or "").splitlines() if x.strip()]
    middle_details = [
        ("Date", _display_date(credit_note.get("credit_note_date"))),
        ("Credit Note Number", str(credit_note.get("credit_note_number") or "-")),
        ("Job Number", str(credit_note.get("job_number") or "-")),
    ]
    if str(credit_note.get("invoice_number") or "").strip():
        middle_details.append(("Related Invoice", str(credit_note.get("invoice_number"))))
    totals_rows = [
        ("Sub-total", f"{_safe_float(credit_note.get('subtotal'), 0.0):,.2f}"),
        ("VAT", f"{_safe_float(credit_note.get('vat'), 0.0):,.2f}"),
        (f"Total {currency}", f"{_safe_float(credit_note.get('total'), 0.0):,.2f}"),
    ]

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=10 * mm,
        rightMargin=10 * mm,
        topMargin=10 * mm,
        bottomMargin=14 * mm,
        title=str(credit_note.get("credit_note_number") or f"Credit Note {credit_note.get('credit_note_id')}"),
    )
    story = _build_financial_pdf_story(
        doc_title="CREDIT NOTE",
        left_details=left_details,
        middle_details=middle_details,
        subject_line=None,
        currency_code=str(credit_note.get("currency_code") or "GBP"),
        lines=lines,
        options_lines=None,
        totals_rows=totals_rows,
        notes=str(credit_note.get("notes") or ""),
        payment_terms_text=None,
        company_profile=company_profile,
    )
    footer = _pdf_footer(company_profile)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buf.getvalue()


@router.get("/credit-notes")
def list_all_credit_notes(_user: dict = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            df = con.execute(
                """
                SELECT cn.credit_note_id, cn.client_db_id, c.client_name, cn.job_id, j.job_number,
                       cn.invoice_id, i.invoice_number, cn.credit_note_number, cn.credit_note_date,
                       cn.currency_code, cn.subtotal, cn.vat, cn.total, cn.status,
                       cn.xero_sync_status, cn.updated_at
                FROM credit_notes cn
                LEFT JOIN clients c ON c.db_id = cn.client_db_id
                LEFT JOIN jobs j ON j.job_id = cn.job_id
                LEFT JOIN invoices i ON i.invoice_id = cn.invoice_id
                """ + ("WHERE cn.org_id = %s" if org_id else "") + """
                ORDER BY COALESCE(cn.credit_note_date, cn.created_at) DESC, cn.credit_note_id DESC
                """,
                ([org_id] if org_id else []),
            ).df()
            items: list[dict[str, Any]] = []
            if df is not None and not df.empty:
                for _, r in df.iterrows():
                    items.append(
                        {
                            "credit_note_id": _safe_int(r.get("credit_note_id"), 0),
                            "client_db_id": _safe_int(r.get("client_db_id"), 0),
                            "client_name": str(r.get("client_name") or ""),
                            "job_id": _safe_int(r.get("job_id"), None),
                            "job_number": str(r.get("job_number") or ""),
                            "invoice_id": _safe_int(r.get("invoice_id"), None),
                            "invoice_number": str(r.get("invoice_number") or ""),
                            "credit_note_number": str(r.get("credit_note_number") or ""),
                            "credit_note_date": r.get("credit_note_date").isoformat() if r.get("credit_note_date") else None,
                            "currency_code": str(r.get("currency_code") or "GBP"),
                            "subtotal": round(_safe_float(r.get("subtotal"), 0.0), 2),
                            "vat": round(_safe_float(r.get("vat"), 0.0), 2),
                            "total": round(_safe_float(r.get("total"), 0.0), 2),
                            "status": str(r.get("status") or "Draft"),
                            "xero_sync_status": str(r.get("xero_sync_status") or "pending"),
                            "updated_at": r.get("updated_at").isoformat() if r.get("updated_at") else None,
                        }
                    )
        return {"items": items}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list all credit notes: {e}")


@router.get("/clients/{client_id}/credit-notes")
def list_client_credit_notes(client_id: int, _user: dict = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            df = con.execute(
                """
                SELECT cn.credit_note_id, cn.client_db_id, cn.job_id, j.job_number, cn.invoice_id, cn.credit_note_number, cn.credit_note_date,
                       cn.currency_code, cn.subtotal, cn.vat, cn.total, cn.status, cn.notes,
                       cn.xero_credit_note_id, cn.xero_credit_note_number, cn.xero_status, cn.xero_sync_status,
                       cn.xero_synced_at, cn.xero_sync_error, cn.created_at, cn.updated_at
                FROM credit_notes cn
                LEFT JOIN jobs j ON j.job_id = cn.job_id
                WHERE cn.client_db_id = %s
                  AND cn.org_id = %s
                ORDER BY COALESCE(cn.credit_note_date, cn.created_at) DESC, cn.credit_note_id DESC
                """,
                [int(client_id), org_id],
            ).df()

            items: list[dict[str, Any]] = []
            if df is not None and not df.empty:
                for _, r in df.iterrows():
                    credit_note_id = _safe_int(r.get("credit_note_id"), 0)
                    lines = _credit_note_lines_for(con, int(credit_note_id), org_id=org_id)
                    totals = _invoice_totals_from_lines(lines) if lines else {
                        "subtotal": round(_safe_float(r.get("subtotal"), 0.0), 2),
                        "vat": round(_safe_float(r.get("vat"), 0.0), 2),
                        "total": round(_safe_float(r.get("total"), 0.0), 2),
                    }
                    items.append(
                        {
                            "credit_note_id": credit_note_id,
                            "client_db_id": _safe_int(r.get("client_db_id"), 0),
                            "job_id": _safe_int(r.get("job_id"), None),
                            "job_number": str(r.get("job_number") or ""),
                            "invoice_id": _safe_int(r.get("invoice_id"), None),
                            "credit_note_number": str(r.get("credit_note_number") or ""),
                            "credit_note_date": r.get("credit_note_date").isoformat() if r.get("credit_note_date") else None,
                            "currency_code": str(r.get("currency_code") or "GBP"),
                            "subtotal": totals["subtotal"],
                            "vat": totals["vat"],
                            "total": totals["total"],
                            "status": str(r.get("status") or "Draft"),
                            "notes": str(r.get("notes") or ""),
                            "xero_credit_note_id": str(r.get("xero_credit_note_id") or ""),
                            "xero_credit_note_number": str(r.get("xero_credit_note_number") or ""),
                            "xero_status": str(r.get("xero_status") or ""),
                            "xero_sync_status": str(r.get("xero_sync_status") or "pending"),
                            "xero_synced_at": r.get("xero_synced_at").isoformat() if r.get("xero_synced_at") else None,
                            "xero_sync_error": str(r.get("xero_sync_error") or ""),
                            "created_at": r.get("created_at").isoformat() if r.get("created_at") else None,
                            "updated_at": r.get("updated_at").isoformat() if r.get("updated_at") else None,
                            "line_count": len(lines),
                        }
                    )
        return {"items": items}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list credit notes: {e}")


@router.get("/jobs/{job_id}/credit-notes")
def list_job_credit_notes(job_id: int, _user: dict = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            df = con.execute(
                """
                SELECT credit_note_id, client_db_id, job_id, invoice_id, credit_note_number, credit_note_date,
                       currency_code, subtotal, vat, total, status, notes,
                       xero_credit_note_id, xero_credit_note_number, xero_status, xero_sync_status,
                       xero_synced_at, xero_sync_error, created_at, updated_at
                FROM credit_notes
                WHERE job_id = %s
                  AND org_id = %s
                ORDER BY COALESCE(credit_note_date, created_at) DESC, credit_note_id DESC
                """,
                [int(job_id), org_id],
            ).df()

            items: list[dict[str, Any]] = []
            if df is not None and not df.empty:
                for _, r in df.iterrows():
                    credit_note_id = _safe_int(r.get("credit_note_id"), 0)
                    lines = _credit_note_lines_for(con, int(credit_note_id), org_id=org_id)
                    totals = _invoice_totals_from_lines(lines) if lines else {
                        "subtotal": round(_safe_float(r.get("subtotal"), 0.0), 2),
                        "vat": round(_safe_float(r.get("vat"), 0.0), 2),
                        "total": round(_safe_float(r.get("total"), 0.0), 2),
                    }
                    items.append(
                        {
                            "credit_note_id": credit_note_id,
                            "client_db_id": _safe_int(r.get("client_db_id"), 0),
                            "job_id": _safe_int(r.get("job_id"), None),
                            "invoice_id": _safe_int(r.get("invoice_id"), None),
                            "credit_note_number": str(r.get("credit_note_number") or ""),
                            "credit_note_date": r.get("credit_note_date").isoformat() if r.get("credit_note_date") else None,
                            "currency_code": str(r.get("currency_code") or "GBP"),
                            "subtotal": totals["subtotal"],
                            "vat": totals["vat"],
                            "total": totals["total"],
                            "status": str(r.get("status") or "Draft"),
                            "notes": str(r.get("notes") or ""),
                            "xero_credit_note_id": str(r.get("xero_credit_note_id") or ""),
                            "xero_credit_note_number": str(r.get("xero_credit_note_number") or ""),
                            "xero_status": str(r.get("xero_status") or ""),
                            "xero_sync_status": str(r.get("xero_sync_status") or "pending"),
                            "xero_synced_at": r.get("xero_synced_at").isoformat() if r.get("xero_synced_at") else None,
                            "xero_sync_error": str(r.get("xero_sync_error") or ""),
                            "created_at": r.get("created_at").isoformat() if r.get("created_at") else None,
                            "updated_at": r.get("updated_at").isoformat() if r.get("updated_at") else None,
                            "line_count": len(lines),
                        }
                    )
        return {"items": items}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list job credit notes: {e}")


@router.post("/clients/{client_id}/credit-notes")
def create_credit_note(client_id: int, body: dict = Body(...), _user: dict = Depends(_current_user), request: Request = None):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            _require_org_plan_active(con, org_id)
            client_exists = con.execute(
                "SELECT db_id FROM clients WHERE db_id = %s AND org_id = %s",
                [int(client_id), org_id],
            ).fetchone()
            if not client_exists:
                raise HTTPException(status_code=404, detail="Client not found")
            job_id = _safe_int(body.get("job_id"), None)
            if job_id is None:
                raise HTTPException(status_code=400, detail="job_id is required to create a credit note")
            job_exists = con.execute(
                "SELECT job_id FROM jobs WHERE job_id = %s AND client_db_id = %s",
                [job_id, int(client_id)],
            ).fetchone()
            if not job_exists:
                raise HTTPException(status_code=400, detail="job_id does not belong to this client")
            invoice_id = _safe_int(body.get("invoice_id"), None)
            if invoice_id is not None:
                invoice_exists = con.execute(
                    "SELECT invoice_id FROM invoices WHERE invoice_id = %s AND client_db_id = %s",
                    [invoice_id, int(client_id)],
                ).fetchone()
                if not invoice_exists:
                    raise HTTPException(status_code=400, detail="invoice_id does not belong to this client")

            credit_note_number = str(body.get("credit_note_number") or "").strip() or _next_credit_note_number(con, org_id=org_id)
            credit_note_date = str(body.get("credit_note_date") or date.today().isoformat())

            lines = body.get("lines") or []
            if not isinstance(lines, list):
                raise HTTPException(status_code=400, detail="lines must be an array")
            computed_totals = _invoice_totals_from_lines(lines) if lines else None

            con.execute(
                """
                INSERT INTO credit_notes (
                  client_db_id, org_id, job_id, invoice_id, credit_note_number, credit_note_date,
                  currency_code, subtotal, vat, total, status, notes,
                  created_at, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), NOW())
                """,
                [
                    int(client_id),
                    org_id,
                    job_id,
                    invoice_id,
                    credit_note_number,
                    credit_note_date,
                    str(body.get("currency_code") or "GBP").upper(),
                    computed_totals["subtotal"] if computed_totals else _safe_float(body.get("subtotal"), 0.0),
                    computed_totals["vat"] if computed_totals else _safe_float(body.get("vat"), 0.0),
                    computed_totals["total"] if computed_totals else _safe_float(body.get("total"), 0.0),
                    str(body.get("status") or "Draft"),
                    str(body.get("notes") or ""),
                ],
            )
            row = con.execute(
                "SELECT MAX(credit_note_id) FROM credit_notes WHERE client_db_id = %s AND org_id = %s",
                [int(client_id), org_id],
            ).fetchone()
            if not row or row[0] is None:
                raise HTTPException(status_code=500, detail="Failed to create credit note")
            credit_note_id = int(row[0])
            if lines:
                _write_credit_note_lines(con, credit_note_id, lines, org_id=org_id)
                con.execute(
                    "UPDATE credit_notes SET subtotal = %s, vat = %s, total = %s, updated_at = NOW() WHERE credit_note_id = %s",
                    [computed_totals["subtotal"], computed_totals["vat"], computed_totals["total"], int(credit_note_id)],
                )
            result = _serialize_credit_note(con, credit_note_id, org_id=org_id)
            record_audit_event(
                con, request=request, actor=_user, action="credit_note_created",
                entity_type="credit_note", entity_id=credit_note_id, client_id=int(client_id), job_id=job_id, after=result,
            )
            return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create credit note: {e}")


@router.post("/jobs/{job_id}/credit-notes")
def create_job_credit_note(job_id: int, body: dict = Body(...), _user: dict = Depends(_current_user), request: Request = None):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            _require_org_plan_active(con, org_id)
            job_row = con.execute(
                "SELECT client_db_id FROM jobs WHERE job_id = %s AND org_id = %s",
                [int(job_id), org_id],
            ).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            client_id = _safe_int(job_row[0], None)
            if client_id is None:
                raise HTTPException(status_code=400, detail="Job has no client assigned")

            payload = dict(body or {})
            payload["job_id"] = int(job_id)
            return create_credit_note(int(client_id), payload, _user, request=request)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create job credit note: {e}")


@router.post("/invoices/{invoice_id}/credit-notes")
def create_credit_note_from_invoice(invoice_id: int, body: dict = Body(default={}), _user: dict = Depends(_current_user), request: Request = None):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            invoice = _serialize_invoice(con, int(invoice_id), org_id=org_id)

            lines = body.get("lines")
            if lines is not None and not isinstance(lines, list):
                raise HTTPException(status_code=400, detail="lines must be an array")
            if lines is None:
                # Default to a full credit of the invoice -- copy its lines as-is;
                # the user can edit quantities/amounts before saving.
                lines = [
                    {
                        "sort_order": l.get("sort_order"),
                        "item_id": l.get("item_id"),
                        "description": l.get("description"),
                        "unit": l.get("unit"),
                        "qty": l.get("qty"),
                        "rate": l.get("rate"),
                        "amount": l.get("amount"),
                        "vat_rate_id": l.get("vat_rate_id"),
                        "vat_rate_pct": l.get("vat_rate_pct"),
                        "notes": l.get("notes"),
                    }
                    for l in (invoice.get("lines") or [])
                ]

            payload = {
                "job_id": invoice.get("job_id"),
                "invoice_id": int(invoice_id),
                "credit_note_number": body.get("credit_note_number"),
                "credit_note_date": body.get("credit_note_date"),
                "currency_code": invoice.get("currency_code"),
                "status": body.get("status") or "Draft",
                "notes": body.get("notes") if body.get("notes") is not None else invoice.get("notes"),
                "lines": lines,
            }
            return create_credit_note(int(invoice["client_db_id"]), payload, _user, request=request)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create credit note from invoice: {e}")


@router.patch("/credit-notes/{credit_note_id}")
def update_credit_note(credit_note_id: int, body: dict = Body(...), _user: dict = Depends(_current_user), request: Request = None):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            exists = con.execute(
                "SELECT credit_note_id, xero_credit_note_id FROM credit_notes WHERE credit_note_id = %s AND org_id = %s",
                [int(credit_note_id), org_id],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail="Credit note not found")
            xero_credit_note_id = str(exists[1] or "").strip() if len(exists) > 1 else ""
            before = _serialize_credit_note(con, int(credit_note_id), org_id=org_id)

            updates = []
            params: list[Any] = []
            for key, col in [
                ("job_id", "job_id"),
                ("invoice_id", "invoice_id"),
                ("credit_note_number", "credit_note_number"),
                ("credit_note_date", "credit_note_date"),
                ("currency_code", "currency_code"),
                ("subtotal", "subtotal"),
                ("vat", "vat"),
                ("total", "total"),
                ("status", "status"),
                ("notes", "notes"),
            ]:
                if key not in body:
                    continue
                value = body.get(key)
                if key in ("job_id", "invoice_id"):
                    value = _safe_int(value, None)
                elif key == "currency_code":
                    value = str(value or "GBP").upper()
                elif key in ("subtotal", "vat", "total"):
                    value = _safe_float(value, 0.0)
                updates.append(f"{col} = %s")
                params.append(value)

            if "lines" in body:
                lines = body.get("lines") or []
                if not isinstance(lines, list):
                    raise HTTPException(status_code=400, detail="lines must be an array")
                _write_credit_note_lines(con, int(credit_note_id), lines, org_id=org_id)
                line_totals = _invoice_totals_from_lines(lines)
                updates.extend(["subtotal = %s", "vat = %s", "total = %s"])
                params.extend([line_totals["subtotal"], line_totals["vat"], line_totals["total"]])

            if not updates:
                raise HTTPException(status_code=400, detail="No updates provided")

            if xero_credit_note_id:
                updates.append("xero_sync_status = %s")
                params.append("needs_resync")
                updates.append("xero_sync_error = %s")
                params.append(None)
            updates.append("updated_at = NOW()")
            params.append(int(credit_note_id))
            params.append(org_id)
            con.execute(f"UPDATE credit_notes SET {', '.join(updates)} WHERE credit_note_id = %s AND org_id = %s", params)
            result = _serialize_credit_note(con, int(credit_note_id), org_id=org_id)
            record_audit_event(
                con, request=request, actor=_user, action="credit_note_updated",
                entity_type="credit_note", entity_id=int(credit_note_id),
                client_id=_safe_int(result.get("client_db_id"), None), job_id=_safe_int(result.get("job_id"), None),
                before=before, after=result,
            )
            return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update credit note: {e}")


@router.delete("/credit-notes/{credit_note_id}")
def delete_credit_note(credit_note_id: int, _user: dict = Depends(_current_user), request: Request = None):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            exists = con.execute(
                "SELECT credit_note_id FROM credit_notes WHERE credit_note_id = %s AND org_id = %s",
                [int(credit_note_id), org_id],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail="Credit note not found")
            before = _serialize_credit_note(con, int(credit_note_id), org_id=org_id)
            _write_credit_note_lines(con, int(credit_note_id), [], org_id=org_id)
            con.execute("DELETE FROM xero_credit_note_links WHERE credit_note_id = %s", [int(credit_note_id)])
            con.execute("DELETE FROM credit_notes WHERE credit_note_id = %s AND org_id = %s", [int(credit_note_id), org_id])
            record_audit_event(
                con, request=request, actor=_user, action="credit_note_deleted",
                entity_type="credit_note", entity_id=int(credit_note_id),
                client_id=_safe_int(before.get("client_db_id"), None), job_id=_safe_int(before.get("job_id"), None),
                before=before,
            )
        return {"ok": True, "credit_note_id": int(credit_note_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete credit note: {e}")


@router.get("/credit-notes/{credit_note_id}")
def get_credit_note(credit_note_id: int, _user: dict = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            return _serialize_credit_note(con, int(credit_note_id), org_id=org_id)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load credit note: {e}")


@router.get("/credit-notes/{credit_note_id}/history")
def credit_note_history(
    credit_note_id: int,
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    _user: dict = Depends(_current_user),
):
    with get_conn() as con:
        _ensure_credit_note_tables(con)
        org_id = _quote_org_id(_user)
        exists = con.execute(
            "SELECT credit_note_id FROM credit_notes WHERE credit_note_id = %s AND org_id = %s",
            [int(credit_note_id), org_id],
        ).fetchone()
        if not exists:
            raise HTTPException(status_code=404, detail="Credit note not found")
        return fetch_entity_history(con, entity_type="credit_note", entity_id=int(credit_note_id), org_id=org_id, limit=limit, offset=offset)


@router.get("/credit-notes/{credit_note_id}/pdf")
def get_credit_note_pdf(credit_note_id: int, _user: dict = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            credit_note = _serialize_credit_note(con, int(credit_note_id), org_id=org_id)
        pdf_bytes = _render_credit_note_pdf_bytes(credit_note)
        filename = f"{credit_note.get('credit_note_number') or f'credit-note-{credit_note_id}'}.pdf"
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"inline; filename={filename}",
                "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
                "Pragma": "no-cache",
                "Expires": "0",
            },
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate credit note PDF: {e}")


@router.post("/credit-notes/{credit_note_id}/email-pdf")
def email_credit_note_pdf(credit_note_id: int, body: dict = Body(...), _user: dict = Depends(_current_user), request: Request = None):
    try:
        to_email = str(body.get("to") or "").strip()
        if not to_email:
            raise HTTPException(status_code=400, detail="to is required")
        cc_emails = [e.strip() for e in str(body.get("cc") or "").split(",") if e.strip()]
        requested_subject = str(body.get("subject") or "").strip()
        requested_message = str(body.get("message") or "").strip()
        with get_conn() as con:
            _ensure_credit_note_tables(con)
            org_id = _quote_org_id(_user)
            credit_note = _serialize_credit_note(con, int(credit_note_id), org_id=org_id)
            pdf_bytes = _render_credit_note_pdf_bytes(credit_note)
            sender = str(_user.get("email") or _user.get("user_id") or "system")
            email_ctx = {
                "credit_note_number": str(credit_note.get("credit_note_number") or f"CN{int(credit_note_id):06d}"),
                "client_name": str(credit_note.get("client_name") or ""),
                "attention_name": str(credit_note.get("client_name") or ""),
                "job_number": str(credit_note.get("job_number") or ""),
                "sender_name": str(_user.get("full_name") or sender),
                "custom_message": requested_message,
            }
            rendered = build_email_content(
                con=con,
                template_key="credit_note_send",
                context=email_ctx,
                fallback_subject=f"Credit Note {credit_note.get('credit_note_number') or credit_note_id} from {str((credit_note.get('company_profile') or {}).get('company_display_name') or 'Net Zero International')}",
                fallback_body="Please find the attached credit note PDF.",
                sender_identifier=sender,
                override_subject=requested_subject or None,
                override_body=requested_message or None,
            )
            send_res = send_tracked_email(
                con,
                to_email=to_email,
                cc=cc_emails or None,
                subject=rendered["subject"],
                body_text=rendered["body_text"],
                body_html=rendered["body_html"],
                created_by=sender,
                template_key="credit_note_send",
                entity_type="credit_note",
                entity_id=int(credit_note_id),
                client_db_id=_safe_int(credit_note.get("client_db_id"), None),
                job_id=_safe_int(credit_note.get("job_id"), None),
                metadata={"kind": "credit_note_pdf"},
                attachment={
                    "bytes": pdf_bytes,
                    "filename": f"{credit_note.get('credit_note_number') or f'credit-note-{credit_note_id}'}.pdf",
                    "mime": "application/pdf",
                },
                raise_on_error=False,
            )
            con.execute(
                """
                INSERT INTO credit_note_email_log (credit_note_id, org_id, sent_to, subject, body, sent_by, sent_at)
                VALUES (%s, %s, %s, %s, %s, %s, NOW())
                """,
                [int(credit_note_id), org_id, to_email, rendered["subject"], rendered["body_html"], sender],
            )
            if str(send_res.get("status") or "") == "sent" and str(credit_note.get("status") or "").strip().lower() == "draft":
                con.execute(
                    "UPDATE credit_notes SET status = 'Sent', updated_at = NOW() WHERE credit_note_id = %s AND org_id = %s",
                    [int(credit_note_id), org_id],
                )
            if str(send_res.get("status") or "") != "sent":
                raise HTTPException(status_code=500, detail=f"Failed to send email: {send_res.get('error') or 'Unknown error'}")
            record_audit_event(
                con, request=request, actor=_user, action="credit_note_sent",
                entity_type="credit_note", entity_id=int(credit_note_id),
                client_id=_safe_int(credit_note.get("client_db_id"), None), job_id=_safe_int(credit_note.get("job_id"), None),
                metadata={"sent_to": to_email, "cc": cc_emails, "subject": rendered["subject"], "kind": "credit_note_pdf"},
            )
        return {"ok": True, "credit_note_id": int(credit_note_id), "sent_to": to_email, "email_id": int(send_res.get('email_id') or 0)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to email credit note PDF: {e}")
