"""
API routes for custom conversion factors management.

Key upgrades:
- Unlimited years via normalized table (custom_factor_year_values)
- Global + client-specific factor scoping
- Admin-governed write operations (with dev fallback when user is anonymous)
"""

from __future__ import annotations

import math
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query

from api.auth import _current_user
from core.database import get_conn
from services.permissions import user_has_permission

router = APIRouter(prefix="/custom-factors", tags=["custom-factors"])


def _safe_int(value: Any) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except Exception:
        return None


def _safe_float(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        out = float(text)
        if not math.isfinite(out):
            return None
        return out
    except Exception:
        return None


def _table_exists(con, table_name: str) -> bool:
    try:
        row = con.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = ? LIMIT 1",
            [table_name],
        ).fetchone()
        return bool(row)
    except Exception:
        return False


def _table_columns(con, table_name: str) -> set[str]:
    try:
        df = con.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = ?",
            [table_name],
        ).df()
        if df is None or df.empty:
            return set()
        return {str(v).strip().lower() for v in df["column_name"].tolist()}
    except Exception:
        return set()


def _ensure_custom_factor_schema(con) -> None:
    """Keep route resilient if migrations lag behind code deployment."""
    # Ensure the wide base table exists.
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS custom_factors (
          factor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          country VARCHAR,
          scope VARCHAR,
          description TEXT,
          uom VARCHAR,
          ghg_unit VARCHAR,
          source VARCHAR,
          factor_2018 DOUBLE PRECISION,
          factor_2019 DOUBLE PRECISION,
          factor_2020 DOUBLE PRECISION,
          factor_2021 DOUBLE PRECISION,
          factor_2022 DOUBLE PRECISION,
          factor_2023 DOUBLE PRECISION,
          factor_2024 DOUBLE PRECISION,
          factor_2025 DOUBLE PRECISION,
          factor_2026 DOUBLE PRECISION,
          factor_2027 DOUBLE PRECISION,
          factor_2028 DOUBLE PRECISION,
          factor_2029 DOUBLE PRECISION,
          factor_2030 DOUBLE PRECISION,
          created_by VARCHAR,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_by VARCHAR,
          updated_at TIMESTAMP,
          archived BOOLEAN DEFAULT FALSE,
          archived_at TIMESTAMP,
          archived_by VARCHAR
        )
        """
    )

    # New governance/scoping fields.
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS country VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS scope VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS description TEXT")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS uom VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS ghg_unit VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS source VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS custom_id VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS report_label VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS category VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS client_db_id INTEGER")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS is_global BOOLEAN DEFAULT TRUE")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS created_by VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS updated_by VARCHAR")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
    con.execute("ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS archived_by VARCHAR")

    # Ensure legacy deployments missing some year columns do not break list/select.
    for year in range(2018, 2031):
        con.execute(
            f"ALTER TABLE custom_factors ADD COLUMN IF NOT EXISTS factor_{year} DOUBLE PRECISION"
        )

    # Unlimited year storage model.
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS custom_factor_year_values (
          factor_id INTEGER NOT NULL REFERENCES custom_factors(factor_id) ON DELETE CASCADE,
          year INTEGER NOT NULL,
          factor DOUBLE PRECISION,
          PRIMARY KEY (factor_id, year)
        )
        """
    )

    # Ensure legacy rows have a stable custom ID.
    con.execute(
        """
        UPDATE custom_factors
        SET custom_id = ('CF-' || CAST(factor_id AS VARCHAR))
        WHERE custom_id IS NULL OR TRIM(custom_id) = ''
        """
    )


def _actor_email(user: dict[str, str]) -> str:
    return str((user or {}).get("email") or (user or {}).get("user_id") or (user or {}).get("user") or "").strip()


def _assert_admin(user: dict[str, str]) -> str:
    """
    Best-effort admin gate.

    - If caller is anonymous, allow (dev fallback for local environments without auth)
    - Otherwise require admin access via the standard permission model or an
      administrative role name.
    """
    actor = _actor_email(user)
    if not actor or actor.lower() == "anonymous":
        return "admin"

    role_value = str(user.get("role") or "").strip().lower()
    if user_has_permission(user, "admin.access") or role_value in {"admin", "administrator", "superadmin"}:
        return actor

    try:
        with get_conn() as con:
            row = con.execute(
                """
                SELECT role
                FROM users
                WHERE lower(coalesce(email, '')) = lower(?)
                   OR lower(coalesce(user_id, '')) = lower(?)
                LIMIT 1
                """,
                [actor, actor],
            ).fetchone()
        role = str(row[0] or "") if row else ""
        if role.strip().lower() not in {"admin", "administrator", "superadmin"}:
            raise HTTPException(status_code=403, detail="Admin role required")
        return actor
    except HTTPException:
        raise
    except Exception:
        # If role lookup fails unexpectedly, deny rather than silently bypass.
        raise HTTPException(status_code=403, detail="Unable to verify admin role")


def _parse_factors_by_year(body: dict[str, Any]) -> dict[int, float]:
    out: dict[int, float] = {}

    raw = body.get("factors_by_year")
    if isinstance(raw, dict):
        for year_key, factor_val in raw.items():
            year = _safe_int(year_key)
            factor = _safe_float(factor_val)
            if year is None or factor is None:
                continue
            out[int(year)] = float(factor)
    elif isinstance(raw, list):
        for entry in raw:
            if not isinstance(entry, dict):
                continue
            year = _safe_int(entry.get("year"))
            factor = _safe_float(entry.get("factor"))
            if year is None or factor is None:
                continue
            out[int(year)] = float(factor)

    # Backward compatibility: accept legacy factor_YYYY keys.
    for key, value in (body or {}).items():
        if not str(key).startswith("factor_"):
            continue
        year = _safe_int(str(key).replace("factor_", "", 1))
        factor = _safe_float(value)
        if year is None or factor is None:
            continue
        out[int(year)] = float(factor)

    return dict(sorted(out.items(), key=lambda kv: kv[0]))


def _replace_year_values(con, factor_id: int, factors_by_year: dict[int, float]) -> None:
    con.execute("DELETE FROM custom_factor_year_values WHERE factor_id = ?", [int(factor_id)])
    for year, factor in sorted(factors_by_year.items(), key=lambda kv: kv[0]):
        con.execute(
            """
            INSERT INTO custom_factor_year_values (factor_id, year, factor)
            VALUES (?, ?, ?)
            """,
            [int(factor_id), int(year), float(factor)],
        )


def _load_year_values_map(con, factor_ids: list[int]) -> dict[int, dict[int, float]]:
    out: dict[int, dict[int, float]] = {int(fid): {} for fid in factor_ids}
    if not factor_ids:
        return out
    if not _table_exists(con, "custom_factor_year_values"):
        return out

    placeholders = ",".join(["?"] * len(factor_ids))
    df = con.execute(
        f"""
        SELECT factor_id, year, factor
        FROM custom_factor_year_values
        WHERE factor_id IN ({placeholders})
        ORDER BY factor_id, year
        """,
        factor_ids,
    ).df()

    if df is None or df.empty:
        return out

    for _, row in df.iterrows():
        fid = _safe_int(row.get("factor_id"))
        year = _safe_int(row.get("year"))
        factor = _safe_float(row.get("factor"))
        if fid is None or year is None or factor is None:
            continue
        out.setdefault(int(fid), {})[int(year)] = float(factor)

    return out


def _legacy_year_values_from_row(row: dict[str, Any]) -> dict[int, float]:
    out: dict[int, float] = {}
    for y in range(2018, 2031):
        key = f"factor_{y}"
        if key not in row:
            continue
        val = _safe_float(row.get(key))
        if val is None:
            continue
        out[y] = float(val)
    return out


@router.get("")
def list_custom_factors(
    include_archived: bool = Query(False),
    client_db_id: int | None = Query(None),
    scope: str | None = Query(None),
    _user: dict[str, str] = Depends(_current_user),
):
    """List custom factors (admin-managed)."""
    _assert_admin(_user)

    try:
        with get_conn() as con:
            _ensure_custom_factor_schema(con)

            cols = _table_columns(con, "custom_factors")
            has_client = "client_db_id" in cols
            has_global = "is_global" in cols

            select_cols = [
                "factor_id",
                "country",
                "scope",
                "description",
                "uom",
                "ghg_unit",
                "source",
                "created_by",
                "created_at",
                "updated_by",
                "updated_at",
                "archived",
                "archived_at",
                "archived_by",
                "custom_id",
                "report_label",
                "category",
                "is_global",
                "client_db_id",
                "is_active",
                "factor_2018",
                "factor_2019",
                "factor_2020",
                "factor_2021",
                "factor_2022",
                "factor_2023",
                "factor_2024",
                "factor_2025",
                "factor_2026",
                "factor_2027",
                "factor_2028",
                "factor_2029",
                "factor_2030",
            ]

            where_clauses: list[str] = []
            params: list[Any] = []

            if not include_archived:
                where_clauses.append("(archived = FALSE OR archived IS NULL)")

            if scope:
                where_clauses.append("scope = ?")
                params.append(str(scope).strip())

            if client_db_id is not None and has_client:
                if has_global:
                    where_clauses.append("(client_db_id = ? OR COALESCE(is_global, TRUE) = TRUE)")
                else:
                    where_clauses.append("(client_db_id = ? OR client_db_id IS NULL)")
                params.append(int(client_db_id))

            where_sql = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""

            df = con.execute(
                f"""
                SELECT {', '.join(select_cols)}
                FROM custom_factors
                {where_sql}
                ORDER BY scope, description, factor_id
                """,
                params,
            ).df()

            items: list[dict[str, Any]] = []
            if df is None or df.empty:
                return {"items": items}

            factor_ids = [int(v) for v in df["factor_id"].tolist() if _safe_int(v) is not None]
            year_values = _load_year_values_map(con, factor_ids)

            # Optional client names for display convenience.
            client_name_map: dict[int, str] = {}
            client_ids = sorted(
                {
                    int(v)
                    for v in df["client_db_id"].tolist()
                    if _safe_int(v) is not None
                }
            )
            if client_ids:
                ph = ",".join(["?"] * len(client_ids))
                cdf = con.execute(
                    f"SELECT db_id, client_name FROM clients WHERE db_id IN ({ph})",
                    client_ids,
                ).df()
                if cdf is not None and not cdf.empty:
                    for _, row in cdf.iterrows():
                        cid = _safe_int(row.get("db_id"))
                        if cid is None:
                            continue
                        client_name_map[int(cid)] = str(row.get("client_name") or "")

            for _, r in df.iterrows():
                fid = _safe_int(r.get("factor_id"))
                if fid is None:
                    continue

                row_dict = {k: r.get(k) for k in r.index}
                legacy_values = _legacy_year_values_from_row(row_dict)
                merged_years = dict(legacy_values)
                merged_years.update(year_values.get(int(fid), {}))

                client_id = _safe_int(r.get("client_db_id"))
                custom_id = str(r.get("custom_id") or "").strip() or f"CF-{fid}"

                items.append(
                    {
                        "factor_id": int(fid),
                        "custom_id": custom_id,
                        "country": str(r.get("country") or ""),
                        "scope": str(r.get("scope") or ""),
                        "description": str(r.get("description") or ""),
                        "report_label": str(r.get("report_label") or "").strip() or None,
                        "category": str(r.get("category") or "").strip() or None,
                        "uom": str(r.get("uom") or ""),
                        "ghg_unit": str(r.get("ghg_unit") or ""),
                        "source": str(r.get("source") or ""),
                        "is_global": bool(r.get("is_global")) if r.get("is_global") is not None else True,
                        "client_db_id": int(client_id) if client_id is not None else None,
                        "client_name": client_name_map.get(int(client_id)) if client_id is not None else None,
                        "is_active": bool(r.get("is_active")) if r.get("is_active") is not None else True,
                        "factors_by_year": {str(y): v for y, v in sorted(merged_years.items())},
                        "created_by": str(r.get("created_by")) if r.get("created_by") else None,
                        "created_at": str(r.get("created_at")) if r.get("created_at") else None,
                        "updated_by": str(r.get("updated_by")) if r.get("updated_by") else None,
                        "updated_at": str(r.get("updated_at")) if r.get("updated_at") else None,
                        "archived": bool(r.get("archived")) if r.get("archived") is not None else False,
                        "archived_at": str(r.get("archived_at")) if r.get("archived_at") else None,
                        "archived_by": str(r.get("archived_by")) if r.get("archived_by") else None,
                    }
                )

            return {"items": items}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list custom factors: {e}")


@router.post("")
def create_custom_factor(body: dict = Body(...), _user: dict[str, str] = Depends(_current_user)):
    """Create a new custom factor."""
    actor = _assert_admin(_user)

    factors_by_year = _parse_factors_by_year(body)
    is_global = bool(body.get("is_global", True))
    client_db_id = _safe_int(body.get("client_db_id"))
    if not is_global and client_db_id is None:
        raise HTTPException(status_code=400, detail="client_db_id is required when is_global is false")

    custom_id = str(body.get("custom_id") or "").strip() or None

    legacy_vals = {y: factors_by_year.get(y) for y in range(2018, 2031)}

    try:
        with get_conn() as con:
            _ensure_custom_factor_schema(con)

            row = con.execute(
                """
                INSERT INTO custom_factors
                (country, scope, description, report_label, category, uom, ghg_unit, source,
                 custom_id, is_global, client_db_id, is_active,
                 factor_2018, factor_2019, factor_2020, factor_2021, factor_2022,
                 factor_2023, factor_2024, factor_2025, factor_2026, factor_2027,
                 factor_2028, factor_2029, factor_2030,
                 created_by)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                        ?)
                RETURNING factor_id
                """,
                [
                    body.get("country"),
                    body.get("scope"),
                    body.get("description"),
                    body.get("report_label"),
                    body.get("category"),
                    body.get("uom"),
                    body.get("ghg_unit"),
                    body.get("source"),
                    custom_id,
                    bool(is_global),
                    client_db_id,
                    bool(body.get("is_active", True)),
                    legacy_vals.get(2018),
                    legacy_vals.get(2019),
                    legacy_vals.get(2020),
                    legacy_vals.get(2021),
                    legacy_vals.get(2022),
                    legacy_vals.get(2023),
                    legacy_vals.get(2024),
                    legacy_vals.get(2025),
                    legacy_vals.get(2026),
                    legacy_vals.get(2027),
                    legacy_vals.get(2028),
                    legacy_vals.get(2029),
                    legacy_vals.get(2030),
                    actor,
                ],
            ).fetchone()

            factor_id = _safe_int(row[0] if row else None)
            if factor_id is None:
                raise HTTPException(status_code=500, detail="Failed to create custom factor")

            if not custom_id:
                con.execute(
                    "UPDATE custom_factors SET custom_id = ('CF-' || CAST(factor_id AS VARCHAR)) WHERE factor_id = ?",
                    [int(factor_id)],
                )

            _replace_year_values(con, int(factor_id), factors_by_year)

            return {"ok": True, "factor_id": int(factor_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create custom factor: {e}")


@router.put("/{factor_id}")
def update_custom_factor(
    factor_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    """Update an existing custom factor."""
    actor = _assert_admin(_user)

    factors_by_year = _parse_factors_by_year(body)
    is_global = bool(body.get("is_global", True))
    client_db_id = _safe_int(body.get("client_db_id"))
    if not is_global and client_db_id is None:
        raise HTTPException(status_code=400, detail="client_db_id is required when is_global is false")

    custom_id = str(body.get("custom_id") or "").strip() or None
    legacy_vals = {y: factors_by_year.get(y) for y in range(2018, 2031)}

    try:
        with get_conn() as con:
            _ensure_custom_factor_schema(con)

            exists = con.execute(
                "SELECT factor_id FROM custom_factors WHERE factor_id = ?",
                [int(factor_id)],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail=f"Custom factor {factor_id} not found")

            con.execute(
                """
                UPDATE custom_factors
                SET country = ?,
                    scope = ?,
                    description = ?,
                    report_label = ?,
                    category = ?,
                    uom = ?,
                    ghg_unit = ?,
                    source = ?,
                    custom_id = ?,
                    is_global = ?,
                    client_db_id = ?,
                    is_active = ?,
                    factor_2018 = ?,
                    factor_2019 = ?,
                    factor_2020 = ?,
                    factor_2021 = ?,
                    factor_2022 = ?,
                    factor_2023 = ?,
                    factor_2024 = ?,
                    factor_2025 = ?,
                    factor_2026 = ?,
                    factor_2027 = ?,
                    factor_2028 = ?,
                    factor_2029 = ?,
                    factor_2030 = ?,
                    updated_by = ?,
                    updated_at = CURRENT_TIMESTAMP
                WHERE factor_id = ?
                """,
                [
                    body.get("country"),
                    body.get("scope"),
                    body.get("description"),
                    body.get("report_label"),
                    body.get("category"),
                    body.get("uom"),
                    body.get("ghg_unit"),
                    body.get("source"),
                    custom_id,
                    bool(is_global),
                    client_db_id,
                    bool(body.get("is_active", True)),
                    legacy_vals.get(2018),
                    legacy_vals.get(2019),
                    legacy_vals.get(2020),
                    legacy_vals.get(2021),
                    legacy_vals.get(2022),
                    legacy_vals.get(2023),
                    legacy_vals.get(2024),
                    legacy_vals.get(2025),
                    legacy_vals.get(2026),
                    legacy_vals.get(2027),
                    legacy_vals.get(2028),
                    legacy_vals.get(2029),
                    legacy_vals.get(2030),
                    actor,
                    int(factor_id),
                ],
            )

            if not custom_id:
                con.execute(
                    "UPDATE custom_factors SET custom_id = ('CF-' || CAST(factor_id AS VARCHAR)) WHERE factor_id = ?",
                    [int(factor_id)],
                )

            _replace_year_values(con, int(factor_id), factors_by_year)

            return {"ok": True, "message": "Custom factor updated successfully"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update custom factor: {e}")


@router.patch("/{factor_id}/archive")
def archive_custom_factor(
    factor_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    """Archive or unarchive a custom factor."""
    actor = _assert_admin(_user)

    archived = bool(body.get("archived", True))
    try:
        with get_conn() as con:
            _ensure_custom_factor_schema(con)

            exists = con.execute(
                "SELECT factor_id FROM custom_factors WHERE factor_id = ?",
                [int(factor_id)],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail=f"Custom factor {factor_id} not found")

            if archived:
                con.execute(
                    """
                    UPDATE custom_factors
                    SET archived = TRUE,
                        is_active = FALSE,
                        archived_at = CURRENT_TIMESTAMP,
                        archived_by = ?
                    WHERE factor_id = ?
                    """,
                    [actor, int(factor_id)],
                )
                message = "Custom factor archived successfully"
            else:
                con.execute(
                    """
                    UPDATE custom_factors
                    SET archived = FALSE,
                        is_active = TRUE,
                        archived_at = NULL,
                        archived_by = NULL
                    WHERE factor_id = ?
                    """,
                    [int(factor_id)],
                )
                message = "Custom factor unarchived successfully"

            return {"ok": True, "message": message}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to archive custom factor: {e}")


@router.delete("/{factor_id}")
def delete_custom_factor(
    factor_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    """Permanently delete a custom factor. Admin only."""
    _assert_admin(_user)

    try:
        with get_conn() as con:
            _ensure_custom_factor_schema(con)

            exists = con.execute(
                "SELECT factor_id FROM custom_factors WHERE factor_id = ?",
                [int(factor_id)],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail=f"Custom factor {factor_id} not found")

            # Child rows are ON DELETE CASCADE, but keep this explicit for resilience.
            if _table_exists(con, "custom_factor_year_values"):
                con.execute("DELETE FROM custom_factor_year_values WHERE factor_id = ?", [int(factor_id)])
            con.execute("DELETE FROM custom_factors WHERE factor_id = ?", [int(factor_id)])

            return {"ok": True, "message": "Custom factor permanently deleted"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete custom factor: {e}")
