import json
import os
import re
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query

from api.auth import _current_user
from core.database import get_conn

router = APIRouter(prefix="/databank", tags=["databank"])

TEAM_ROLES = {"superadmin", "admin", "consultant", "readonly", "crm", "qa", "support"}
DEFAULT_SUBJECTS = [
    "Legislation & Regulations",
    "COP",
    "News",
    "Industry",
    "Glossary",
    "Datasets",
]


def _actor_identifier(user: dict) -> str:
    return str(user.get("email") or user.get("user_id") or "").strip()


def _require_team_user(user: dict) -> str:
    actor = _actor_identifier(user)
    if not actor:
        raise HTTPException(status_code=401, detail="Missing authenticated user")

    role = str(user.get("role") or "").strip().lower()
    if role not in TEAM_ROLES:
        raise HTTPException(status_code=403, detail="Team member role required")
    return actor


def _ensure_databank_tables(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS databank_subjects_lookup (
          subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR NOT NULL UNIQUE,
          is_active BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS databank_cards (
          card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          subject_id INTEGER REFERENCES databank_subjects_lookup(subject_id),
          category VARCHAR NOT NULL,
          country VARCHAR,
          reporting_year INTEGER,
          title TEXT NOT NULL,
          content TEXT NOT NULL,
          source_type VARCHAR,
          source_url TEXT,
          reference_text TEXT,
          tags TEXT,
          created_by VARCHAR NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP,
          is_active BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )

    # Defensive add for existing deployments.
    con.execute("ALTER TABLE databank_cards ADD COLUMN IF NOT EXISTS tags TEXT")
    con.execute("ALTER TABLE databank_cards ADD COLUMN IF NOT EXISTS source_type VARCHAR")
    con.execute("ALTER TABLE databank_cards ADD COLUMN IF NOT EXISTS source_url TEXT")
    con.execute("ALTER TABLE databank_cards ADD COLUMN IF NOT EXISTS reference_text TEXT")
    con.execute("ALTER TABLE databank_cards ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP")
    con.execute("ALTER TABLE databank_cards ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE")

    for subject in DEFAULT_SUBJECTS:
        con.execute(
            """
            INSERT INTO databank_subjects_lookup (name, is_active)
            SELECT %s, TRUE
            WHERE NOT EXISTS (
              SELECT 1 FROM databank_subjects_lookup WHERE lower(name) = lower(%s)
            )
            """,
            [subject, subject],
        )


def _parse_json_array(text: str) -> list[dict[str, Any]]:
    raw = (text or "").strip()
    if not raw:
        return []
    try:
        obj = json.loads(raw)
        if isinstance(obj, list):
            return [x for x in obj if isinstance(x, dict)]
    except Exception:
        pass
    m = re.search(r"```(?:json)?\s*(\[.*\])\s*```", raw, flags=re.DOTALL)
    if m:
        try:
            obj = json.loads(m.group(1))
            if isinstance(obj, list):
                return [x for x in obj if isinstance(x, dict)]
        except Exception:
            return []
    return []


def _suggestions_fallback(subject: str, country: str, category: str, year: int | None, query: str) -> list[dict[str, Any]]:
    subject_value = (subject or "General").strip()
    category_value = (category or subject_value or "General").strip()
    country_value = (country or "Global").strip()
    query_value = (query or "").strip()
    industry_hint = "Include industry-specific compliance triggers where relevant."
    cards: list[dict[str, Any]] = []

    subject_key = subject_value.lower()
    if "legislation" in subject_key or "regulation" in subject_key:
        templates = [
            ("Current Mandatory Reporting Rules", "Summarize current mandatory reporting obligations, thresholds, and reporting cadence."),
            ("Regulator Guidance Update", "Capture latest regulator publications, implementation notes, and transition periods."),
            ("Enforcement and Penalties Snapshot", "List enforcement trends, penalties, and common non-compliance findings."),
            ("Cross-Border Reporting Interactions", "Identify interactions with IFRS/ISSB/CSRD/SEC-style requirements where applicable."),
            ("Immediate Compliance Checklist (90 days)", "Define practical actions, owners, and evidence needed for audit-ready reporting."),
        ]
    elif "cop" in subject_key:
        templates = [
            ("COP Commitments Relevant to Business", "Extract business-relevant commitments, sector pledges, and implementation implications."),
            ("Country NDC Progress Summary", "Summarize NDC direction and near-term policy signals tied to emissions and disclosures."),
            ("Sector Implications from COP Decisions", "Map key COP outcomes to sector-specific risk and opportunity areas."),
            ("Funding and Incentive Signals", "Identify climate finance, incentives, and market mechanisms that affect decarbonization plans."),
            ("Stakeholder Messaging Points", "Create board/client-ready messaging from latest COP outcomes."),
        ]
    elif "news" in subject_key:
        templates = [
            ("Top Regulatory News Digest", "Capture top regulatory stories and summarize business impact."),
            ("Competitor and Peer Disclosure Signals", "Summarize notable peer announcements and disclosure trends."),
            ("Market Risk Watchlist", "Track emerging risks likely to affect emissions reporting assumptions."),
            ("Opportunity Watchlist", "Track partnerships, grants, and technology updates with practical near-term value."),
            ("Monthly Executive Brief", "Prepare concise monthly briefing notes for leadership."),
        ]
    elif "industry" in subject_key:
        templates = [
            ("Sector Benchmark Metrics", "List most-used sector KPIs and reference values."),
            ("Best-Practice Case Studies", "Summarize practical case studies and proven interventions."),
            ("Material Emissions Hotspots", "Highlight most material emissions sources by sub-sector."),
            ("Supplier Engagement Playbook", "Define supplier data, clauses, and cadence for better scope 3 quality."),
            ("Decarbonization Cost Ranges", "Capture indicative cost ranges and payback horizons for key actions."),
        ]
    elif "glossary" in subject_key:
        templates = [
            ("Core Reporting Terminology", "Define key reporting terms used in client outputs."),
            ("Assurance and Verification Terms", "Define verification, assurance scope, and evidence terms."),
            ("Methodology Terms", "Clarify terms for boundaries, baselines, and factor usage."),
            ("Data Quality Terms", "Define data quality ratings and reconciliation terminology."),
            ("Regulatory Terms", "Define legal terms that appear in compliance narratives."),
        ]
    else:
        templates = [
            ("Priority Update Summary", "Summarize priority updates relevant to this subject."),
            ("Practical Actions and Owners", "Define actions, ownership, and delivery timeline."),
            ("Risk and Opportunity Notes", "Capture key risk/opportunity implications."),
            ("Evidence and Sources Tracker", "List source types and evidence required for quality."),
            ("Leadership Briefing Draft", "Provide concise executive-ready narrative."),
        ]

    for idx, (title_seed, content_seed) in enumerate(templates, start=1):
        title = f"{subject_value}: {title_seed} ({country_value})"
        content_lines = [
            content_seed,
            f"Context: {country_value}" + (f", {year}" if year else ""),
            f"Focus: {query_value or 'Current requirements, practical implications, and next actions.'}",
            industry_hint,
            "Include: source links, key dates, scope, affected entities, and action owners.",
        ]
        cards.append(
            {
                "title": title,
                "content": " ".join(content_lines),
                "category": category_value,
                "country": country_value,
                "reporting_year": year,
                "source_url": "",
                "reference_text": "Fallback suggestion generated locally (OpenAI unavailable or returned unusable output).",
            }
        )

    return cards[:10]


def _looks_like_echo(text: str, query: str) -> bool:
    base = (text or "").strip().lower()
    q = (query or "").strip().lower()
    if not base:
        return True
    if not q:
        return False
    if q in base and len(base) <= max(180, int(len(q) * 1.8)):
        return True
    return base.startswith("draft insight")


def _openai_suggestions(subject: str, country: str, category: str, year: int | None, query: str, industry: str) -> list[dict[str, Any]]:
    try:
        from openai import OpenAI
    except ImportError:
        return _suggestions_fallback(subject, country, category, year, query)

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return _suggestions_fallback(subject, country, category, year, query)

    model = os.environ.get("OPENAI_MODEL", "gpt-4.1")
    client = OpenAI(api_key=api_key)

    prompt = (
        "Return ONLY valid JSON array with up to 10 objects using keys: "
        "title, content, category, country, reporting_year, source_url, reference_text. "
        "Each item should be useful for a sustainability data bank card.\n"
        f"Subject: {subject or 'General'}\n"
        f"Country: {country or 'Global'}\n"
        f"Category: {category or 'General'}\n"
        f"Year: {year if year else 'N/A'}\n"
        f"Industry: {industry or 'General'}\n"
        f"Research focus: {query or 'Key climate legislation, COP developments, and practical reductions guidance'}\n"
        "Prioritize credible references and include short reference_text notes."
    )

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1800,
            temperature=0.2,
        )
        content = (response.choices[0].message.content or "").strip() if response.choices else ""
        parsed = _parse_json_array(content)
        if not parsed:
            return _suggestions_fallback(subject, country, category, year, query)
        normalized: list[dict[str, Any]] = []
        for row in parsed[:10]:
            title = str(row.get("title") or "").strip()
            content_text = str(row.get("content") or "").strip()
            if _looks_like_echo(title, query):
                continue
            if _looks_like_echo(content_text, query):
                continue
            normalized.append(
                {
                    "title": title,
                    "content": content_text,
                    "category": str(row.get("category") or category or "General").strip(),
                    "country": str(row.get("country") or country or "Global").strip(),
                    "reporting_year": int(row.get("reporting_year")) if str(row.get("reporting_year") or "").strip().isdigit() else year,
                    "source_url": str(row.get("source_url") or "").strip(),
                    "reference_text": str(row.get("reference_text") or "").strip(),
                }
            )
        if not normalized:
            return _suggestions_fallback(subject, country, category, year, query)
        return normalized
    except Exception:
        return _suggestions_fallback(subject, country, category, year, query)


@router.get("/subjects")
def list_databank_subjects(_user: dict = Depends(_current_user)):
    _require_team_user(_user)
    try:
        with get_conn() as con:
            _ensure_databank_tables(con)
            df = con.execute(
                """
                SELECT subject_id, name, is_active
                FROM databank_subjects_lookup
                ORDER BY lower(name)
                """
            ).df()
        items = []
        if df is not None and not df.empty:
            for _, r in df.iterrows():
                items.append(
                    {
                        "subject_id": int(r.get("subject_id")),
                        "name": str(r.get("name") or ""),
                        "is_active": bool(r.get("is_active")),
                    }
                )
        return {"items": items}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list databank subjects: {e}")


@router.post("/subjects")
def create_databank_subject(body: dict = Body(...), _user: dict = Depends(_current_user)):
    _require_team_user(_user)
    name = str(body.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=400, detail="name is required")
    try:
        with get_conn() as con:
            _ensure_databank_tables(con)
            con.execute(
                """
                INSERT INTO databank_subjects_lookup (name, is_active)
                SELECT %s, TRUE
                WHERE NOT EXISTS (
                  SELECT 1 FROM databank_subjects_lookup WHERE lower(name) = lower(%s)
                )
                """,
                [name, name],
            )
        return {"ok": True, "message": "Subject saved"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create subject: {e}")


@router.get("/cards")
def list_databank_cards(
    category: str = Query(default=""),
    country: str = Query(default=""),
    reporting_year: int | None = Query(default=None),
    subject_id: int | None = Query(default=None),
    query: str = Query(default=""),
    include_inactive: bool = Query(default=False),
    limit: int = Query(default=200, ge=1, le=1000),
    _user: dict = Depends(_current_user),
):
    _require_team_user(_user)
    try:
        with get_conn() as con:
            _ensure_databank_tables(con)
            where = []
            params: list[Any] = []
            if category.strip():
                where.append("lower(c.category) = lower(%s)")
                params.append(category.strip())
            if country.strip():
                where.append("lower(COALESCE(c.country, '')) = lower(%s)")
                params.append(country.strip())
            if reporting_year is not None:
                where.append("c.reporting_year = %s")
                params.append(int(reporting_year))
            if subject_id is not None:
                where.append("c.subject_id = %s")
                params.append(int(subject_id))
            if query.strip():
                q = f"%{query.strip()}%"
                where.append("(c.title ILIKE %s OR c.content ILIKE %s OR COALESCE(c.reference_text, '') ILIKE %s)")
                params.extend([q, q, q])
            if not include_inactive:
                where.append("c.is_active = TRUE")

            where_sql = f"WHERE {' AND '.join(where)}" if where else ""
            df = con.execute(
                f"""
                SELECT
                  c.card_id, c.subject_id, s.name AS subject_name,
                  c.category, c.country, c.reporting_year, c.title, c.content,
                  c.source_type, c.source_url, c.reference_text, c.tags,
                  c.created_by, c.created_at, c.updated_at, c.is_active
                FROM databank_cards c
                LEFT JOIN databank_subjects_lookup s ON s.subject_id = c.subject_id
                {where_sql}
                ORDER BY c.created_at DESC
                LIMIT %s
                """,
                [*params, int(limit)],
            ).df()

        items = []
        categories = set()
        countries = set()
        years = set()
        if df is not None and not df.empty:
            for _, r in df.iterrows():
                cval = str(r.get("category") or "").strip()
                kval = str(r.get("country") or "").strip()
                yval = r.get("reporting_year")
                if cval:
                    categories.add(cval)
                if kval:
                    countries.add(kval)
                if yval is not None and yval == yval:
                    years.add(int(yval))
                items.append(
                    {
                        "card_id": int(r.get("card_id")),
                        "subject_id": int(r.get("subject_id")) if r.get("subject_id") is not None else None,
                        "subject_name": str(r.get("subject_name") or ""),
                        "category": cval,
                        "country": kval,
                        "reporting_year": int(yval) if yval is not None and yval == yval else None,
                        "title": str(r.get("title") or ""),
                        "content": str(r.get("content") or ""),
                        "source_type": str(r.get("source_type") or ""),
                        "source_url": str(r.get("source_url") or ""),
                        "reference_text": str(r.get("reference_text") or ""),
                        "tags": str(r.get("tags") or ""),
                        "created_by": str(r.get("created_by") or ""),
                        "created_at": r.get("created_at").isoformat() if r.get("created_at") else None,
                        "updated_at": r.get("updated_at").isoformat() if r.get("updated_at") else None,
                        "is_active": bool(r.get("is_active")),
                    }
                )

        return {
            "items": items,
            "facets": {
                "categories": sorted(list(categories), key=lambda x: x.lower()),
                "countries": sorted(list(countries), key=lambda x: x.lower()),
                "years": sorted(list(years), reverse=True),
            },
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list databank cards: {e}")


@router.post("/cards")
def create_databank_card(body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = _require_team_user(_user)
    subject_id = body.get("subject_id")
    category = str(body.get("category") or "").strip()
    country = str(body.get("country") or "").strip()
    title = str(body.get("title") or "").strip()
    content = str(body.get("content") or "").strip()
    source_type = str(body.get("source_type") or "").strip()
    source_url = str(body.get("source_url") or "").strip()
    reference_text = str(body.get("reference_text") or "").strip()
    tags = str(body.get("tags") or "").strip()
    reporting_year = body.get("reporting_year")

    if not category:
        raise HTTPException(status_code=400, detail="category is required")
    if not title:
        raise HTTPException(status_code=400, detail="title is required")
    if not content:
        raise HTTPException(status_code=400, detail="content is required")
    if subject_id is None:
        raise HTTPException(status_code=400, detail="subject_id is required")

    try:
        year_val = int(reporting_year) if reporting_year not in (None, "", "null") else None
    except Exception:
        raise HTTPException(status_code=400, detail="reporting_year must be a valid year")

    try:
        with get_conn() as con:
            _ensure_databank_tables(con)
            con.execute(
                """
                INSERT INTO databank_cards (
                  subject_id, category, country, reporting_year,
                  title, content, source_type, source_url, reference_text, tags,
                  created_by, created_at, updated_at, is_active
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), NOW(), TRUE)
                """,
                [
                    int(subject_id),
                    category,
                    country,
                    year_val,
                    title,
                    content,
                    source_type,
                    source_url,
                    reference_text,
                    tags,
                    actor,
                ],
            )
        return {"ok": True, "message": "Data card created"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create data card: {e}")


@router.patch("/cards/{card_id}")
def update_databank_card(card_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    _require_team_user(_user)
    try:
        with get_conn() as con:
            _ensure_databank_tables(con)
            updates = []
            params: list[Any] = []
            if "subject_id" in body:
                updates.append("subject_id = %s")
                params.append(int(body.get("subject_id")))
            if "category" in body:
                category = str(body.get("category") or "").strip()
                if not category:
                    raise HTTPException(status_code=400, detail="category cannot be empty")
                updates.append("category = %s")
                params.append(category)
            if "country" in body:
                updates.append("country = %s")
                params.append(str(body.get("country") or "").strip())
            if "reporting_year" in body:
                rv = body.get("reporting_year")
                updates.append("reporting_year = %s")
                params.append(int(rv) if rv not in (None, "", "null") else None)
            if "title" in body:
                title = str(body.get("title") or "").strip()
                if not title:
                    raise HTTPException(status_code=400, detail="title cannot be empty")
                updates.append("title = %s")
                params.append(title)
            if "content" in body:
                content = str(body.get("content") or "").strip()
                if not content:
                    raise HTTPException(status_code=400, detail="content cannot be empty")
                updates.append("content = %s")
                params.append(content)
            if "source_type" in body:
                updates.append("source_type = %s")
                params.append(str(body.get("source_type") or "").strip())
            if "source_url" in body:
                updates.append("source_url = %s")
                params.append(str(body.get("source_url") or "").strip())
            if "reference_text" in body:
                updates.append("reference_text = %s")
                params.append(str(body.get("reference_text") or "").strip())
            if "tags" in body:
                updates.append("tags = %s")
                params.append(str(body.get("tags") or "").strip())
            if "is_active" in body:
                updates.append("is_active = %s")
                params.append(bool(body.get("is_active")))

            if not updates:
                return {"ok": True, "message": "No fields to update"}

            updates.append("updated_at = NOW()")
            params.append(int(card_id))
            con.execute(
                f"UPDATE databank_cards SET {', '.join(updates)} WHERE card_id = %s",
                params,
            )
        return {"ok": True, "message": "Data card updated"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update data card: {e}")


@router.post("/suggestions")
def databank_suggestions(body: dict = Body(...), _user: dict = Depends(_current_user)):
    _require_team_user(_user)
    subject = str(body.get("subject") or "").strip()
    country = str(body.get("country") or "").strip()
    category = str(body.get("category") or "").strip()
    query = str(body.get("query") or "").strip()
    industry = str(body.get("industry") or "").strip()
    year_raw = body.get("reporting_year")
    try:
        year_val = int(year_raw) if year_raw not in (None, "", "null") else None
    except Exception:
        raise HTTPException(status_code=400, detail="reporting_year must be a valid year")

    if not subject and not query:
        raise HTTPException(status_code=400, detail="Provide subject and/or query")

    try:
        items = _openai_suggestions(subject, country, category, year_val, query, industry)
        return {"items": items[:10]}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate suggestions: {e}")
