from fastapi import APIRouter, Body, Depends, HTTPException, Query
import json
import os
import re

from api.auth import _current_user
from core.database import get_conn

router = APIRouter(prefix="/feedback", tags=["feedback"])

TEAM_ROLES = {"admin", "consultant", "readonly", "crm", "qa", "support"}
FEEDBACK_TYPES = {"wishlist", "bug", "business_dev"}


def _actor_identifier(user: dict) -> str:
    return str(user.get("email") or user.get("user_id") or "").strip()


def _require_team_user(user: dict) -> str:
    actor = _actor_identifier(user)
    if not actor:
        raise HTTPException(status_code=401, detail="Missing authenticated user")

    role = str(user.get("role") or "").strip().lower()
    if role not in TEAM_ROLES:
        raise HTTPException(status_code=403, detail="Team member role required")
    return actor


def _ensure_feedback_table(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS feedback_items (
          feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          feedback_type VARCHAR NOT NULL,
          title TEXT NOT NULL,
          details TEXT,
          process_name VARCHAR,
          page_path VARCHAR,
          is_completed BOOLEAN NOT NULL DEFAULT FALSE,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR NOT NULL,
          updated_at TIMESTAMP,
          completed_at TIMESTAMP,
          completed_by VARCHAR
        )
        """
    )

    con.execute(
        """
        ALTER TABLE feedback_items
        ADD COLUMN IF NOT EXISTS process_name VARCHAR
        """
    )
    con.execute(
        """
        ALTER TABLE feedback_items
        ADD COLUMN IF NOT EXISTS page_path VARCHAR
        """
    )


def _parse_json_array(text: str) -> list[dict]:
    raw = (text or "").strip()
    if not raw:
        return []
    try:
        obj = json.loads(raw)
        if isinstance(obj, list):
            return [x for x in obj if isinstance(x, dict)]
    except Exception:
        pass
    m = re.search(r"```(?:json)?\s*(\[.*\])\s*```", raw, flags=re.DOTALL)
    if m:
        try:
            obj = json.loads(m.group(1))
            if isinstance(obj, list):
                return [x for x in obj if isinstance(x, dict)]
        except Exception:
            return []
    return []


def _bizdev_fallback(criteria: dict) -> list[dict]:
    target = str(criteria.get("target_market") or "target market").strip()
    geography = str(criteria.get("geography") or "selected geography").strip()
    service = str(criteria.get("service_line") or "carbon reporting services").strip()
    segment = str(criteria.get("customer_segment") or "client segment").strip()
    objective = str(criteria.get("objective") or "growth and conversion").strip()
    templates = [
        "Partner-led lead generation campaign",
        "Verticalized offer packaging and pricing",
        "Referral and channel incentive program",
        "Thought-leadership webinar to pipeline motion",
        "Compliance-triggered outreach sequence",
        "Account expansion playbook for existing clients",
        "Country-specific proposition and messaging refresh",
        "Pilot engagement offer for high-fit prospects",
        "Sector benchmarking report as lead magnet",
        "Customer success case study campaign",
    ]
    ideas = []
    for idx, title in enumerate(templates, start=1):
        ideas.append(
            {
                "title": f"{title}: {service}",
                "details": (
                    f"Idea {idx} for {segment} in {target} ({geography}). "
                    f"Primary objective: {objective}. Include owner, timeline, budget, KPI, and expected conversion impact."
                ),
            }
        )
    return ideas[:10]


def _bizdev_ai_suggestions(criteria: dict) -> list[dict]:
    try:
        from openai import OpenAI
    except Exception:
        return _bizdev_fallback(criteria)

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return _bizdev_fallback(criteria)

    model = os.environ.get("OPENAI_MODEL", "gpt-4.1")
    client = OpenAI(api_key=api_key)
    prompt = (
        "Return ONLY valid JSON array with up to 10 objects using keys: title, details.\n"
        "Generate practical business development ideas for a sustainability consultancy.\n"
        f"Target market: {criteria.get('target_market') or 'General'}\n"
        f"Customer segment: {criteria.get('customer_segment') or 'General'}\n"
        f"Geography: {criteria.get('geography') or 'Global'}\n"
        f"Service line: {criteria.get('service_line') or 'Carbon accounting/reporting'}\n"
        f"Objective: {criteria.get('objective') or 'Grow revenue'}\n"
        f"Constraints: {criteria.get('constraints') or 'None'}\n"
        f"Time horizon: {criteria.get('time_horizon') or '12 months'}\n"
        "Each idea must include concrete action and commercial rationale."
    )
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1200,
            temperature=0.3,
        )
        content = (response.choices[0].message.content or "").strip() if response.choices else ""
        parsed = _parse_json_array(content)
        if not parsed:
            return _bizdev_fallback(criteria)
        out = []
        for row in parsed[:10]:
            title = str(row.get("title") or "").strip()
            details = str(row.get("details") or "").strip()
            if not title:
                continue
            out.append({"title": title, "details": details})
        return out or _bizdev_fallback(criteria)
    except Exception:
        return _bizdev_fallback(criteria)


@router.get("/items")
def list_feedback_items(
    feedback_type: str = Query(default="all"),
    include_completed: bool = Query(default=True),
    _user: dict = Depends(_current_user),
):
    actor = _require_team_user(_user)
    _ = actor

    ft = (feedback_type or "all").strip().lower()
    if ft != "all" and ft not in FEEDBACK_TYPES:
        raise HTTPException(status_code=400, detail="Invalid feedback_type")

    try:
        with get_conn() as con:
            _ensure_feedback_table(con)
            where = []
            params = []

            if ft != "all":
                where.append("feedback_type = %s")
                params.append(ft)

            if not include_completed:
                where.append("is_completed = FALSE")

            where_clause = f"WHERE {' AND '.join(where)}" if where else ""
            df = con.execute(
                f"""
                SELECT feedback_id, feedback_type, title, details, process_name, page_path,
                       is_completed, created_at, created_by, updated_at, completed_at, completed_by
                FROM feedback_items
                {where_clause}
                ORDER BY is_completed ASC, created_at DESC
                """,
                params,
            ).df()

        items = []
        if df is not None and not df.empty:
            for _, row in df.iterrows():
                items.append(
                    {
                        "feedback_id": int(row.get("feedback_id")),
                        "feedback_type": str(row.get("feedback_type") or ""),
                        "title": str(row.get("title") or ""),
                        "details": str(row.get("details") or ""),
                        "process_name": str(row.get("process_name") or ""),
                        "page_path": str(row.get("page_path") or ""),
                        "is_completed": bool(row.get("is_completed")),
                        "created_at": row.get("created_at").isoformat() if row.get("created_at") else None,
                        "created_by": str(row.get("created_by") or ""),
                        "updated_at": row.get("updated_at").isoformat() if row.get("updated_at") else None,
                        "completed_at": row.get("completed_at").isoformat() if row.get("completed_at") else None,
                        "completed_by": str(row.get("completed_by") or ""),
                    }
                )

        return {"items": items}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list feedback items: {e}")


@router.post("/items")
def create_feedback_item(
    body: dict = Body(...),
    _user: dict = Depends(_current_user),
):
    actor = _require_team_user(_user)

    feedback_type = str(body.get("feedback_type") or "").strip().lower()
    title = str(body.get("title") or "").strip()
    details = str(body.get("details") or "").strip()
    process_name = str(body.get("process_name") or "").strip()
    page_path = str(body.get("page_path") or "").strip()

    if feedback_type not in FEEDBACK_TYPES:
        raise HTTPException(status_code=400, detail="feedback_type must be wishlist, bug, or business_dev")
    if not title:
        raise HTTPException(status_code=400, detail="title is required")

    try:
        with get_conn() as con:
            _ensure_feedback_table(con)
            con.execute(
                """
                INSERT INTO feedback_items (
                    feedback_type, title, details, process_name, page_path,
                    is_completed, created_by, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, FALSE, %s, NOW())
                """,
                [feedback_type, title, details, process_name, page_path, actor],
            )

        return {"ok": True, "message": "Feedback item created"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create feedback item: {e}")


@router.patch("/items/{feedback_id}")
def update_feedback_item(
    feedback_id: int,
    body: dict = Body(...),
    _user: dict = Depends(_current_user),
):
    actor = _require_team_user(_user)

    try:
        with get_conn() as con:
            _ensure_feedback_table(con)
            updates = []
            params = []

            if "title" in body:
                title = str(body.get("title") or "").strip()
                if not title:
                    raise HTTPException(status_code=400, detail="title cannot be empty")
                updates.append("title = %s")
                params.append(title)

            if "details" in body:
                updates.append("details = %s")
                params.append(str(body.get("details") or "").strip())

            if "process_name" in body:
                updates.append("process_name = %s")
                params.append(str(body.get("process_name") or "").strip())

            if "page_path" in body:
                updates.append("page_path = %s")
                params.append(str(body.get("page_path") or "").strip())

            if "is_completed" in body:
                is_completed = bool(body.get("is_completed"))
                updates.append("is_completed = %s")
                params.append(is_completed)
                if is_completed:
                    updates.append("completed_at = NOW()")
                    updates.append("completed_by = %s")
                    params.append(actor)
                else:
                    updates.append("completed_at = NULL")
                    updates.append("completed_by = NULL")

            if not updates:
                return {"ok": True, "message": "No fields to update"}

            updates.append("updated_at = NOW()")
            params.append(int(feedback_id))
            con.execute(
                f"UPDATE feedback_items SET {', '.join(updates)} WHERE feedback_id = %s",
                params,
            )

        return {"ok": True, "message": "Feedback item updated"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update feedback item: {e}")


@router.post("/business-dev/suggestions")
def business_dev_suggestions(body: dict = Body(...), _user: dict = Depends(_current_user)):
    _require_team_user(_user)
    try:
        ideas = _bizdev_ai_suggestions(body or {})
        return {"items": ideas}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate suggestions: {e}")
