"""Intelligence routes - client health, action queue, and call prep."""
from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
import logging
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query

from api.auth import _current_user
from api.crm_timeline_routes import _ensure_tables as _ensure_crm_timeline_tables
from core.database import get_conn
from services.client_benchmark import get_client_benchmark_metrics
from services.emissions_reporting import load_combined_emissions_summary_rows
from services.tenancy import require_org

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/intelligence", tags=["intelligence"])


def _table_exists(con, table_name: str) -> bool:
    try:
        row = con.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = CURRENT_SCHEMA()
              AND table_name = ?
            LIMIT 1
            """,
            [table_name],
        ).fetchone()
        return bool(row)
    except Exception:
        try:
            con.execute(f"SELECT 1 FROM {table_name} LIMIT 1").fetchone()
            return True
        except Exception:
            return False


def _column_exists(con, table_name: str, column_name: str) -> bool:
    try:
        row = con.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = CURRENT_SCHEMA()
              AND table_name = ?
              AND column_name = ?
            LIMIT 1
            """,
            [table_name, column_name],
        ).fetchone()
        return bool(row)
    except Exception:
        try:
            con.execute(f"SELECT {column_name} FROM {table_name} LIMIT 1").fetchone()
            return True
        except Exception:
            return False


def _ensure_schema(con) -> None:
    try:
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS client_touchpoints (
              touchpoint_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              org_id UUID NOT NULL,
              client_db_id INTEGER NOT NULL,
              crm_owner VARCHAR NOT NULL,
              touchpoint_type VARCHAR NOT NULL DEFAULT 'call',
              summary TEXT,
              outcome VARCHAR,
              next_action TEXT,
              next_action_due DATE,
              occurred_at TIMESTAMP NOT NULL DEFAULT NOW(),
              created_at TIMESTAMP DEFAULT NOW(),
              created_by VARCHAR
            )
            """
        )
    except Exception:
        pass
    try:
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS client_health_snapshots (
              snapshot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              org_id UUID NOT NULL,
              client_db_id INTEGER NOT NULL,
              health_score INTEGER NOT NULL DEFAULT 0,
              score_emissions INTEGER,
              score_milestones INTEGER,
              score_engagement INTEGER,
              score_payments INTEGER,
              risk_flags TEXT,
              computed_at TIMESTAMP DEFAULT NOW(),
              UNIQUE (org_id, client_db_id)
            )
            """
        )
    except Exception:
        pass
    for ddl in (
        "CREATE INDEX IF NOT EXISTS ix_client_touchpoints_client ON client_touchpoints (client_db_id, occurred_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_client_touchpoints_org_crm ON client_touchpoints (org_id, crm_owner, occurred_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_client_health_snapshots_org_client ON client_health_snapshots (org_id, client_db_id)",
    ):
        try:
            con.execute(ddl)
        except Exception:
            pass


def _normalize_text(value: Any, fallback: str = "") -> str:
    txt = str(value or "").strip()
    return txt or fallback


def _safe_date(value: Any):
    if value is None:
        return None
    if isinstance(value, date):
        return value
    if hasattr(value, "date"):
        try:
            return value.date()
        except Exception:
            return None
    txt = str(value).strip()
    if not txt:
        return None
    try:
        return date.fromisoformat(txt[:10])
    except Exception:
        return None


def _safe_datetime(value: Any):
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    txt = str(value).strip()
    if not txt:
        return None
    try:
        return datetime.fromisoformat(txt.replace("Z", "+00:00"))
    except Exception:
        try:
            return datetime.fromisoformat(txt[:19])
        except Exception:
            return None


def _default_crm_owner(user: dict[str, Any]) -> str:
    return _normalize_text(user.get("full_name") or user.get("email") or user.get("user_id"), "Unassigned")


def _cadence_window(cadence: str | None) -> tuple[int, int]:
    cadence_key = _normalize_text(cadence, "monthly").lower()
    if cadence_key == "quarterly":
        return 100, 150
    return 35, 60


def _touchpoint_type_value(value: Any) -> str:
    allowed = {"call", "email", "meeting", "report_sent", "data_request", "other"}
    txt = _normalize_text(value, "call").lower()
    return txt if txt in allowed else "other"


def _outcome_value(value: Any) -> str:
    allowed = {"positive", "neutral", "concern_raised", "escalation_needed"}
    txt = _normalize_text(value, "neutral").lower()
    return txt if txt in allowed else "neutral"


def _milestone_status(due_date: Any, completed_at: Any) -> str:
    if completed_at:
        return "green"
    due = _safe_date(due_date)
    if due is None:
        return "none"
    days_until_due = (due - date.today()).days
    if days_until_due < 0:
        return "red"
    if days_until_due <= 7:
        return "amber"
    return "green"


def _overall_milestone_status(statuses: list[str]) -> str | None:
    filtered = [str(status or "").strip().lower() for status in statuses if str(status or "").strip()]
    if not filtered:
        return None
    if "red" in filtered:
        return "red"
    if "amber" in filtered:
        return "amber"
    if "green" in filtered:
        return "green"
    return None


def _milestone_score(status: str | None) -> int:
    normalized = _normalize_text(status, "").lower()
    if normalized == "green":
        return 25
    if normalized == "amber":
        return 15
    if normalized == "red":
        return 5
    return 10


def _engagement_score(last_touchpoint: date | None, cadence: str | None) -> tuple[int, list[str], int | None, date | None]:
    low, mid = _cadence_window(cadence)
    if last_touchpoint is None:
        return 0, ["OVERDUE_CALL"], None, None
    days_since = (date.today() - last_touchpoint).days
    if days_since < low:
        return 25, [], days_since, last_touchpoint + timedelta(days=low)
    if days_since <= mid:
        return 15, ["OVERDUE_CALL"], days_since, last_touchpoint + timedelta(days=low)
    return 0, ["OVERDUE_CALL"], days_since, last_touchpoint + timedelta(days=low)


def _emissions_score(
    *,
    benchmark_year: int | None,
    benchmark_total: float | None,
    net_zero_year: int | None,
    latest_year: int | None,
    latest_total: float | None,
) -> tuple[int, list[str], float | None]:
    if benchmark_year is None or benchmark_total is None or latest_year is None or latest_total is None:
        return 5, [], None
    if net_zero_year is None or net_zero_year <= benchmark_year:
        return 5, [], None
    years_to_go = max(1, net_zero_year - benchmark_year)
    progress_years = max(0, min(latest_year - benchmark_year, years_to_go))
    expected = float(benchmark_total) * max(0.0, 1.0 - (progress_years / float(years_to_go)))
    if expected <= 0:
        return 30, [], None
    variance_pct = ((float(latest_total) - expected) / expected) * 100.0
    if variance_pct <= 5:
        return 30, [], variance_pct
    if variance_pct <= 15:
        return 20, [], variance_pct
    if variance_pct <= 30:
        return 10, ["EMISSIONS_OFF_TRACK"], variance_pct
    return 5, ["EMISSIONS_OFF_TRACK"], variance_pct


def _payment_score(overdue_invoices: int) -> tuple[int, list[str]]:
    if overdue_invoices <= 0:
        return 20, []
    if overdue_invoices == 1:
        return 10, ["INVOICE_OVERDUE"]
    return 0, ["INVOICE_OVERDUE"]


def _priority_for_flag(flag: str) -> int:
    return {
        "RENEWAL_30": 1,
        "MILESTONE_RED": 1,
        "INVOICE_OVERDUE": 2,
        "RENEWAL_90": 2,
        "OVERDUE_CALL": 3,
        "EMISSIONS_OFF_TRACK": 4,
        "NO_ACTIVE_JOB": 5,
    }.get(flag, 5)


def _format_due_date(value: date | None) -> str | None:
    return value.isoformat() if value else None


def _load_scoped_clients(con, org_id: str, crm_owner: str | None) -> list[dict[str, Any]]:
    filters = ["c.org_id = ?"]
    params: list[object] = [org_id]
    if crm_owner:
        filters.append("COALESCE(NULLIF(TRIM(c.crm_owner), ''), 'Unassigned') = ?")
        params.append(crm_owner)
    query = f"""
        SELECT
            c.db_id,
            c.client_name,
            COALESCE(NULLIF(TRIM(c.crm_owner), ''), 'Unassigned') AS crm_owner,
            c.net_zero_year,
            c.benchmark_year,
            c.benchmark_total_tco2e,
            c.engagement_start_date,
            c.engagement_end_date,
            c.touchpoint_cadence
        FROM clients c
        WHERE {' AND '.join(filters)}
        ORDER BY c.client_name ASC, c.db_id ASC
    """
    rows = con.execute(query, params).fetchall()
    clients: list[dict[str, Any]] = []
    for row in rows or []:
        clients.append(
            {
                "client_db_id": int(row[0]),
                "client_name": _normalize_text(row[1], "Untitled client"),
                "crm_owner": _normalize_text(row[2], "Unassigned"),
                "net_zero_year": int(row[3]) if row[3] is not None else None,
                "benchmark_year": int(row[4]) if row[4] is not None else None,
                "benchmark_total_tco2e": float(row[5]) if row[5] is not None else None,
                "engagement_start_date": _safe_date(row[6]),
                "engagement_end_date": _safe_date(row[7]),
                "touchpoint_cadence": _normalize_text(row[8], "monthly"),
            }
        )
    return clients


def _load_touchpoints(con, org_id: str, client_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not client_ids or not _table_exists(con, "client_touchpoints"):
        return {}
    placeholders = ",".join(["?"] * len(client_ids))
    rows = con.execute(
        f"""
        SELECT
            touchpoint_id, client_db_id, crm_owner, touchpoint_type,
            summary, outcome, next_action, next_action_due,
            occurred_at, created_at, created_by
        FROM client_touchpoints
        WHERE org_id = ? AND client_db_id IN ({placeholders})
        ORDER BY occurred_at DESC, touchpoint_id DESC
        """,
        [org_id, *client_ids],
    ).fetchall()
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in rows or []:
        grouped[int(row[1])].append(
            {
                "touchpoint_id": int(row[0]),
                "client_db_id": int(row[1]),
                "crm_owner": _normalize_text(row[2], "Unassigned"),
                "touchpoint_type": _normalize_text(row[3], "call"),
                "summary": _normalize_text(row[4], ""),
                "outcome": _normalize_text(row[5], "neutral"),
                "next_action": _normalize_text(row[6], ""),
                "next_action_due": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
                "occurred_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
                "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
                "created_by": _normalize_text(row[10], ""),
            }
        )
    return grouped


def _load_health_snapshots(con, org_id: str, client_ids: list[int]) -> dict[int, dict[str, Any]]:
    if not client_ids or not _table_exists(con, "client_health_snapshots"):
        return {}
    placeholders = ",".join(["?"] * len(client_ids))
    rows = con.execute(
        f"""
        SELECT
            client_db_id,
            health_score,
            score_emissions,
            score_milestones,
            score_engagement,
            score_payments,
            risk_flags
        FROM client_health_snapshots
        WHERE org_id = ? AND client_db_id IN ({placeholders})
        ORDER BY computed_at DESC, snapshot_id DESC
        """,
        [org_id, *client_ids],
    ).fetchall()
    snapshots: dict[int, dict[str, Any]] = {}
    for row in rows or []:
        client_db_id = int(row[0])
        if client_db_id in snapshots:
            continue
        snapshots[client_db_id] = {
            "health_score": int(row[1] or 0),
            "score_emissions": int(row[2]) if row[2] is not None else None,
            "score_milestones": int(row[3]) if row[3] is not None else None,
            "score_engagement": int(row[4]) if row[4] is not None else None,
            "score_payments": int(row[5]) if row[5] is not None else None,
            "risk_flags": _normalize_text(row[6], ""),
        }
    return snapshots


def _load_invoice_stats(con, org_id: str, client_ids: list[int]) -> dict[int, dict[str, int]]:
    if not client_ids or not _table_exists(con, "invoices"):
        return {}
    placeholders = ",".join(["?"] * len(client_ids))
    rows = con.execute(
        f"""
        SELECT
            client_db_id,
            COALESCE(SUM(CASE WHEN LOWER(COALESCE(status, '')) = 'overdue' AND COALESCE(due_date, CURRENT_DATE) < CURRENT_DATE THEN 1 ELSE 0 END), 0) AS overdue_count,
            COALESCE(SUM(CASE WHEN LOWER(COALESCE(status, '')) NOT IN ('paid', 'void', 'refunded') THEN 1 ELSE 0 END), 0) AS open_count
        FROM invoices
        WHERE org_id = ? AND client_db_id IN ({placeholders})
        GROUP BY client_db_id
        """,
        [org_id, *client_ids],
    ).fetchall()
    stats: dict[int, dict[str, int]] = {}
    for row in rows or []:
        stats[int(row[0])] = {
            "overdue_invoices": int(row[1] or 0),
            "open_invoices": int(row[2] or 0),
        }
    return stats


def _load_jobs(con, org_id: str, client_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not client_ids:
        return {}
    has_job_plan = _table_exists(con, "job_plan")
    placeholders = ",".join(["?"] * len(client_ids))
    milestone_select = """
        jp.data_collection_due,
        jp.data_collection_completed_at,
        jp.first_draft_due,
        jp.first_draft_completed_at,
        jp.final_report_due,
        jp.final_report_completed_at
    """ if has_job_plan else """
        NULL AS data_collection_due,
        NULL AS data_collection_completed_at,
        NULL AS first_draft_due,
        NULL AS first_draft_completed_at,
        NULL AS final_report_due,
        NULL AS final_report_completed_at
    """
    rows = con.execute(
        f"""
        SELECT
            j.job_id,
            j.client_db_id,
            j.job_number,
            j.title,
            COALESCE(NULLIF(TRIM(j.status), ''), 'Unknown') AS status,
            j.reporting_year,
            j.start_date,
            j.due_date,
            j.created_at,
            {milestone_select}
        FROM jobs j
        LEFT JOIN clients c ON c.db_id = j.client_db_id
        {"LEFT JOIN job_plan jp ON jp.job_id = j.job_id" if has_job_plan else ""}
        WHERE COALESCE(j.org_id, c.org_id) = ? AND j.client_db_id IN ({placeholders})
        ORDER BY j.client_db_id ASC, j.reporting_year DESC NULLS LAST, j.job_id DESC
        """,
        [org_id, *client_ids],
    ).fetchall()
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in rows or []:
        client_id = int(row[1])
        grouped[client_id].append(
            {
                "job_id": int(row[0]),
                "client_db_id": client_id,
                "job_number": _normalize_text(row[2], ""),
                "title": _normalize_text(row[3], ""),
                "status": _normalize_text(row[4], "Unknown"),
                "reporting_year": int(row[5]) if row[5] is not None else None,
                "start_date": _safe_date(row[6]).isoformat() if _safe_date(row[6]) else None,
                "due_date": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
                "created_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
                "data_collection_due": _safe_date(row[9]),
                "data_collection_completed_at": _safe_datetime(row[10]),
                "first_draft_due": _safe_date(row[11]),
                "first_draft_completed_at": _safe_datetime(row[12]),
                "final_report_due": _safe_date(row[13]),
                "final_report_completed_at": _safe_datetime(row[14]),
            }
        )
    return grouped


def _aggregate_emissions(con, job_ids: list[int]) -> dict[int, float]:
    if not job_ids:
        return {}
    try:
        rows_df = load_combined_emissions_summary_rows(con, job_ids)
    except Exception:
        logger.exception("intelligence.emissions_summary_failed")
        return {}
    if rows_df is None or rows_df.empty:
        return {}
    totals: dict[int, float] = defaultdict(float)
    for _, row in rows_df.iterrows():
        job_id = row.get("job_id")
        if job_id is None:
            continue
        try:
            totals[int(job_id)] += float(row.get("emissions") or 0.0)
        except Exception:
            continue
    return {key: round(val, 2) for key, val in totals.items()}


def _pick_active_job(jobs: list[dict[str, Any]]) -> dict[str, Any] | None:
    active = [job for job in jobs if _normalize_text(job.get("status"), "").lower() not in {"completed", "archived", "cancelled"}]
    if not active:
        return None
    return active[0]


def _pick_latest_completed_job(jobs: list[dict[str, Any]]) -> dict[str, Any] | None:
    completed = [job for job in jobs if _normalize_text(job.get("status"), "").lower() in {"completed", "archived"}]
    if not completed:
        return None
    return completed[0]


def _touchpoint_due_date(last_touchpoint_date: date | None, cadence: str | None) -> date | None:
    if last_touchpoint_date is None:
        return None
    low, _mid = _cadence_window(cadence)
    return last_touchpoint_date + timedelta(days=low)


def _compute_client_record(
    *,
    client: dict[str, Any],
    jobs: list[dict[str, Any]],
    touchpoints: list[dict[str, Any]],
    invoice_stats: dict[str, int],
    emissions_by_job: dict[int, float],
) -> dict[str, Any]:
    last_touchpoint = _safe_date(touchpoints[0]["occurred_at"]) if touchpoints else None
    cadence = client.get("touchpoint_cadence")
    engagement_score, engagement_flags, days_since_contact, next_touchpoint_due = _engagement_score(last_touchpoint, cadence)

    active_job = _pick_active_job(jobs)
    active_status = _overall_milestone_status(
        [_milestone_status(job.get("data_collection_due"), job.get("data_collection_completed_at")) for job in (jobs[:1] if active_job is None else [active_job])]
    )
    milestone_score = _milestone_score(active_status)
    milestone_flags = ["MILESTONE_RED"] if active_status == "red" else []

    latest_completed_job = _pick_latest_completed_job(jobs)
    latest_year = latest_completed_job.get("reporting_year") if latest_completed_job else None
    latest_total = emissions_by_job.get(int(latest_completed_job["job_id"])) if latest_completed_job else None
    emissions_score, emissions_flags, variance_pct = _emissions_score(
        benchmark_year=client.get("benchmark_year"),
        benchmark_total=client.get("benchmark_total_tco2e"),
        net_zero_year=client.get("net_zero_year"),
        latest_year=latest_year,
        latest_total=latest_total,
    )

    overdue_invoices = int(invoice_stats.get("overdue_invoices") or 0)
    open_invoices = int(invoice_stats.get("open_invoices") or 0)
    payment_score, payment_flags = _payment_score(overdue_invoices)

    flags: list[str] = []
    flags.extend(engagement_flags)
    flags.extend(emissions_flags)
    flags.extend(milestone_flags)
    flags.extend(payment_flags)
    if client.get("engagement_end_date") is not None:
        days_remaining = (_safe_date(client["engagement_end_date"]) - date.today()).days if _safe_date(client["engagement_end_date"]) else None
        if days_remaining is not None and days_remaining <= 30:
            flags.append("RENEWAL_30")
        elif days_remaining is not None and days_remaining <= 90:
            flags.append("RENEWAL_90")
    if not any(_normalize_text(job.get("status"), "").lower() not in {"completed", "archived", "cancelled"} for job in jobs):
        flags.append("NO_ACTIVE_JOB")

    score = min(100, max(0, emissions_score + milestone_score + engagement_score + payment_score))

    risk_flags = ",".join(sorted({flag for flag in flags if flag}))
    return {
        "client_db_id": int(client["client_db_id"]),
        "client_name": client["client_name"],
        "crm_owner": client["crm_owner"],
        "health_score": int(score),
        "score_emissions": int(emissions_score),
        "score_milestones": int(milestone_score),
        "score_engagement": int(engagement_score),
        "score_payments": int(payment_score),
        "risk_flags": risk_flags,
        "last_touchpoint_date": last_touchpoint.isoformat() if last_touchpoint else None,
        "days_since_contact": days_since_contact,
        "touchpoint_due_date": _format_due_date(next_touchpoint_due),
        "active_job": active_job,
        "latest_completed_job": latest_completed_job,
        "latest_year": int(latest_year) if latest_year is not None else None,
        "latest_total_tco2e": float(latest_total) if latest_total is not None else None,
        "emissions_variance_pct": round(float(variance_pct), 1) if variance_pct is not None else None,
        "open_invoices": open_invoices,
        "overdue_invoices": overdue_invoices,
        "engagement_end_date": _safe_date(client.get("engagement_end_date")).isoformat() if _safe_date(client.get("engagement_end_date")) else None,
    }


def _build_dashboard_record(
    *,
    client: dict[str, Any],
    snapshot: dict[str, Any] | None,
    touchpoints: list[dict[str, Any]],
    invoice_stats: dict[str, int],
) -> dict[str, Any]:
    last_touchpoint = _safe_date(touchpoints[0]["occurred_at"]) if touchpoints else None
    cadence = client.get("touchpoint_cadence")
    engagement_score, engagement_flags, days_since_contact, next_touchpoint_due = _engagement_score(last_touchpoint, cadence)
    snapshot = snapshot or {}
    score = int(snapshot.get("health_score") or 0)
    risk_flags = str(snapshot.get("risk_flags") or "").strip()
    if not risk_flags:
        flags = list(engagement_flags)
        if client.get("engagement_end_date") is not None:
            days_remaining = (_safe_date(client["engagement_end_date"]) - date.today()).days if _safe_date(client["engagement_end_date"]) else None
            if days_remaining is not None and days_remaining <= 30:
                flags.append("RENEWAL_30")
            elif days_remaining is not None and days_remaining <= 90:
                flags.append("RENEWAL_90")
        risk_flags = ",".join(sorted({flag for flag in flags if flag}))
    return {
        "client_db_id": int(client["client_db_id"]),
        "client_name": client["client_name"],
        "crm_owner": client["crm_owner"],
        "health_score": score,
        "risk_flags": risk_flags,
        "last_touchpoint_date": last_touchpoint.isoformat() if last_touchpoint else None,
        "days_since_contact": days_since_contact,
        "touchpoint_due_date": _format_due_date(next_touchpoint_due),
        "engagement_end_date": _safe_date(client.get("engagement_end_date")).isoformat() if _safe_date(client.get("engagement_end_date")) else None,
        "open_invoices": int(invoice_stats.get("open_invoices") or 0),
        "overdue_invoices": int(invoice_stats.get("overdue_invoices") or 0),
    }


def _refresh_snapshots(con, org_id: str, records: list[dict[str, Any]]) -> None:
    if not records:
        return
    values: list[object] = []
    placeholders: list[str] = []
    for record in records:
        placeholders.append("(?, ?, ?, ?, ?, ?, ?, ?, NOW())")
        values.extend(
            [
                org_id,
                record["client_db_id"],
                record["health_score"],
                record["score_emissions"],
                record["score_milestones"],
                record["score_engagement"],
                record["score_payments"],
                record["risk_flags"],
            ]
        )
    con.execute(
        f"""
        INSERT INTO client_health_snapshots (
          org_id, client_db_id, health_score, score_emissions,
          score_milestones, score_engagement, score_payments, risk_flags,
          computed_at
        )
        VALUES {", ".join(placeholders)}
        ON CONFLICT (org_id, client_db_id) DO UPDATE SET
          health_score = EXCLUDED.health_score,
          score_emissions = EXCLUDED.score_emissions,
          score_milestones = EXCLUDED.score_milestones,
          score_engagement = EXCLUDED.score_engagement,
          score_payments = EXCLUDED.score_payments,
          risk_flags = EXCLUDED.risk_flags,
          computed_at = NOW()
        """,
        values,
    )


def _build_talking_points(record: dict[str, Any], client: dict[str, Any]) -> list[str]:
    points: list[str] = []
    flags = {flag.strip() for flag in str(record.get("risk_flags") or "").split(",") if flag.strip()}
    days_since = record.get("days_since_contact")
    if "OVERDUE_CALL" in flags and days_since is not None:
        points.append(f"Check in - last contact was {days_since} days ago")
    if "EMISSIONS_OFF_TRACK" in flags and record.get("emissions_variance_pct") is not None:
        points.append(f"Emissions {round(float(record['emissions_variance_pct']), 1)}% above target trajectory - discuss reduction actions")
    if "MILESTONE_RED" in flags:
        points.append("Job milestone overdue - confirm data submission timeline")
    if "RENEWAL_90" in flags and record.get("engagement_end_date"):
        points.append(f"Contract renewal due {record['engagement_end_date']} - begin renewal conversation")
    if "INVOICE_OVERDUE" in flags:
        points.append("Outstanding invoice - confirm payment status")
    points.append(f"Review progress against net zero target ({client.get('net_zero_year') or 'n/a'})")
    return points


def _build_talking_points_enhanced(
    record: dict[str, Any],
    client: dict[str, Any],
    recent_touchpoints: list[dict[str, Any]],
    active_job_full: dict[str, Any] | None,
    open_tasks: list[dict[str, Any]],
) -> list[str]:
    points: list[str] = []
    flags = {flag.strip() for flag in str(record.get("risk_flags") or "").split(",") if flag.strip()}

    # 1. Agreed next action from last touchpoint
    last_tp = recent_touchpoints[0] if recent_touchpoints else None
    if last_tp and last_tp.get("next_action"):
        action = last_tp["next_action"]
        due = last_tp.get("next_action_due")
        if due:
            points.append(f"Agreed next action: {action} (due {due})")
        else:
            points.append(f"Agreed next action: {action}")

    # 2. Imminent renewal
    if "RENEWAL_30" in flags and record.get("engagement_end_date"):
        points.append(f"Engagement ends {record['engagement_end_date']} — confirm renewal or exit plan")
    elif "RENEWAL_90" in flags and record.get("engagement_end_date"):
        points.append(f"Contract renewal due {record['engagement_end_date']} — begin renewal conversation")

    # 3. Overdue milestones (specific)
    if active_job_full:
        for m in active_job_full.get("milestones", []):
            if m.get("status") == "red" and not m.get("completed"):
                points.append(f"{m['name']} milestone overdue (was due {m['due']}) — confirm delivery timeline")
            elif m.get("status") == "amber" and not m.get("completed"):
                points.append(f"{m['name']} deadline approaching — due {m['due']}")

    # 4. Overdue invoice
    if "INVOICE_OVERDUE" in flags:
        overdue = record.get("overdue_invoices", 0)
        points.append(f"{overdue} invoice{'s' if overdue != 1 else ''} overdue — confirm payment status")

    # 5. Emissions off track
    if "EMISSIONS_OFF_TRACK" in flags and record.get("emissions_variance_pct") is not None:
        pct = round(float(record["emissions_variance_pct"]), 1)
        points.append(f"Emissions {pct}% above target trajectory — discuss reduction actions")

    # 6. Overdue call (if no next action covered it above)
    if "OVERDUE_CALL" in flags and not (last_tp and last_tp.get("next_action")):
        days = record.get("days_since_contact")
        if days is not None:
            points.append(f"Check in — last contact was {days} days ago")
        else:
            points.append("No contact logged yet — this is the first touch")

    # 7. High-priority open tasks
    urgent = [t for t in open_tasks if t.get("priority") in ("urgent", "high")]
    if urgent:
        names = ", ".join(t["title"] for t in urgent[:3] if t.get("title"))
        if names:
            points.append(f"High-priority tasks open: {names}")

    # 8. Net zero progress (always)
    net_zero = client.get("net_zero_year")
    if net_zero:
        points.append(f"Review progress against net zero target ({net_zero})")

    return points


def _serialize_job(job: dict[str, Any] | None) -> dict[str, Any] | None:
    if not job:
        return None
    due_date = _safe_date(job.get("due_date"))
    next_milestone_name = None
    next_milestone_due = None
    for name, due_key, completed_key in (
        ("Data Collection", "data_collection_due", "data_collection_completed_at"),
        ("First Draft", "first_draft_due", "first_draft_completed_at"),
        ("Final Report", "final_report_due", "final_report_completed_at"),
    ):
        due = job.get(due_key)
        completed = job.get(completed_key)
        if due and not completed:
            next_milestone_name = name
            next_milestone_due = _safe_date(due)
            break
    days_to_milestone = (next_milestone_due - date.today()).days if next_milestone_due else None
    milestone_status = _overall_milestone_status(
        [_milestone_status(job.get("data_collection_due"), job.get("data_collection_completed_at")),
         _milestone_status(job.get("first_draft_due"), job.get("first_draft_completed_at")),
         _milestone_status(job.get("final_report_due"), job.get("final_report_completed_at"))]
    )
    return {
        "job_id": int(job["job_id"]),
        "job_number": job.get("job_number"),
        "title": job.get("title"),
        "status": job.get("status"),
        "milestone_status": milestone_status,
        "next_milestone": next_milestone_name,
        "days_to_milestone": days_to_milestone,
        "due_date": due_date.isoformat() if due_date else None,
    }


def _serialize_job_full(job: dict[str, Any] | None) -> dict[str, Any] | None:
    if not job:
        return None
    milestones = []
    for name, due_key, completed_key in (
        ("Data Collection", "data_collection_due", "data_collection_completed_at"),
        ("First Draft", "first_draft_due", "first_draft_completed_at"),
        ("Final Report", "final_report_due", "final_report_completed_at"),
    ):
        due = job.get(due_key)
        completed = job.get(completed_key)
        status = _milestone_status(due, completed)
        milestones.append({
            "name": name,
            "due": _safe_date(due).isoformat() if _safe_date(due) else None,
            "completed": bool(completed),
            "completed_at": _safe_datetime(completed).isoformat() if _safe_datetime(completed) else None,
            "status": status,
        })
    overall_status = _overall_milestone_status([m["status"] for m in milestones])
    next_milestone_name = None
    next_milestone_due_str = None
    days_to_milestone = None
    for m in milestones:
        if not m["completed"] and m["due"]:
            next_milestone_name = m["name"]
            next_milestone_due_str = m["due"]
            due_date = _safe_date(m["due"])
            if due_date:
                days_to_milestone = (due_date - date.today()).days
            break
    due_date = _safe_date(job.get("due_date"))
    return {
        "job_id": int(job["job_id"]),
        "job_number": job.get("job_number"),
        "title": job.get("title"),
        "status": job.get("status"),
        "reporting_year": job.get("reporting_year"),
        "milestone_status": overall_status,
        "milestones": milestones,
        "next_milestone": next_milestone_name,
        "next_milestone_due": next_milestone_due_str,
        "days_to_milestone": days_to_milestone,
        "due_date": due_date.isoformat() if due_date else None,
    }


def _load_recent_notes(con, client_db_id: int, limit: int = 5) -> list[dict[str, Any]]:
    """Load recent notes for a client from client_notes, crm_events, and job_communications."""
    notes: list[dict[str, Any]] = []

    # 1. client_notes table
    try:
        rows = con.execute(
            """
            SELECT
                cn.note_id,
                cn.subject,
                cn.note_text,
                cn.author,
                cn.job_id,
                j.job_number,
                j.title AS job_title,
                COALESCE(cn.updated_at, cn.created_at) AS note_at
            FROM client_notes cn
            LEFT JOIN jobs j ON j.job_id = cn.job_id
            WHERE cn.client_db_id = ?
              AND COALESCE(cn.archived, FALSE) = FALSE
              AND cn.note_text IS NOT NULL AND cn.note_text != ''
            ORDER BY COALESCE(cn.updated_at, cn.created_at) DESC NULLS LAST
            LIMIT ?
            """,
            [int(client_db_id), limit],
        ).fetchall()
        for row in rows or []:
            notes.append({
                "source": "client_note",
                "source_label": "Client Note",
                "note_id": int(row[0]),
                "subject": _normalize_text(row[1], "") or None,
                "note_text": _normalize_text(row[2], ""),
                "author": _normalize_text(row[3], ""),
                "job_id": int(row[4]) if row[4] is not None else None,
                "job_number": _normalize_text(row[5], "") or None,
                "job_title": _normalize_text(row[6], "") or None,
                "note_at": _safe_datetime(row[7]).isoformat() if _safe_datetime(row[7]) else None,
            })
    except Exception:
        pass

    # 2. crm_events (event_type = 'note')
    try:
        rows = con.execute(
            """
            SELECT
                e.event_id,
                e.subject,
                e.body_text,
                e.created_by,
                e.job_id,
                j.job_number,
                j.title AS job_title,
                COALESCE(e.event_at, e.updated_at, e.created_at) AS note_at
            FROM crm_events e
            LEFT JOIN jobs j ON j.job_id = e.job_id
            WHERE e.client_db_id = ?
              AND lower(COALESCE(e.event_type, '')) = 'note'
              AND COALESCE(e.archived, FALSE) = FALSE
              AND e.body_text IS NOT NULL AND e.body_text != ''
            ORDER BY COALESCE(e.event_at, e.updated_at, e.created_at) DESC NULLS LAST
            LIMIT ?
            """,
            [int(client_db_id), limit],
        ).fetchall()
        for row in rows or []:
            notes.append({
                "source": "crm_event",
                "source_label": "CRM Note",
                "note_id": int(row[0]),
                "subject": _normalize_text(row[1], "") or None,
                "note_text": _normalize_text(row[2], ""),
                "author": _normalize_text(row[3], ""),
                "job_id": int(row[4]) if row[4] is not None else None,
                "job_number": _normalize_text(row[5], "") or None,
                "job_title": _normalize_text(row[6], "") or None,
                "note_at": _safe_datetime(row[7]).isoformat() if _safe_datetime(row[7]) else None,
            })
    except Exception:
        pass

    # 3. job_communications (channel = 'note') for this client's jobs
    try:
        rows = con.execute(
            """
            SELECT
                jc.communication_id,
                jc.subject,
                jc.message_text,
                jc.created_by,
                jc.job_id,
                j.job_number,
                j.title AS job_title,
                COALESCE(jc.event_at, jc.updated_at, jc.created_at) AS note_at
            FROM job_communications jc
            JOIN jobs j ON j.job_id = jc.job_id
            WHERE j.client_db_id = ?
              AND lower(COALESCE(jc.channel, '')) = 'note'
              AND COALESCE(jc.archived, FALSE) = FALSE
              AND jc.message_text IS NOT NULL AND jc.message_text != ''
            ORDER BY COALESCE(jc.event_at, jc.updated_at, jc.created_at) DESC NULLS LAST
            LIMIT ?
            """,
            [int(client_db_id), limit],
        ).fetchall()
        for row in rows or []:
            notes.append({
                "source": "job_note",
                "source_label": "Job Note",
                "note_id": int(row[0]),
                "subject": _normalize_text(row[1], "") or None,
                "note_text": _normalize_text(row[2], ""),
                "author": _normalize_text(row[3], ""),
                "job_id": int(row[4]) if row[4] is not None else None,
                "job_number": _normalize_text(row[5], "") or None,
                "job_title": _normalize_text(row[6], "") or None,
                "note_at": _safe_datetime(row[7]).isoformat() if _safe_datetime(row[7]) else None,
            })
    except Exception:
        pass

    # Sort all combined notes by date descending, return top N
    notes.sort(key=lambda n: str(n.get("note_at") or ""), reverse=True)
    return notes[:limit]


def _load_crm_tasks(con, client_db_id: int) -> list[dict[str, Any]]:
    if not _table_exists(con, "crm_tasks"):
        return []
    try:
        rows = con.execute(
            """
            SELECT task_id, client_db_id, job_id, title, details, assignee_user_id,
                   priority, due_at, status, created_at
            FROM crm_tasks
            WHERE client_db_id = ?
              AND status NOT IN ('completed', 'cancelled', 'archived')
            ORDER BY
                CASE priority
                    WHEN 'urgent' THEN 1
                    WHEN 'high' THEN 2
                    WHEN 'normal' THEN 3
                    ELSE 4
                END,
                due_at ASC NULLS LAST,
                task_id ASC
            LIMIT 20
            """,
            [int(client_db_id)],
        ).fetchall()
    except Exception:
        return []
    tasks: list[dict[str, Any]] = []
    for row in rows or []:
        tasks.append(
            {
                "task_id": int(row[0]),
                "client_db_id": int(row[1]),
                "job_id": int(row[2]) if row[2] is not None else None,
                "title": _normalize_text(row[3], ""),
                "details": _normalize_text(row[4], ""),
                "assignee_user_id": _normalize_text(row[5], ""),
                "priority": _normalize_text(row[6], "normal"),
                "due_at": _safe_datetime(row[7]).isoformat() if _safe_datetime(row[7]) else None,
                "status": _normalize_text(row[8], "open"),
                "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
            }
        )
    return tasks


def _build_call_prep(record: dict[str, Any], client: dict[str, Any], touchpoints: list[dict[str, Any]]) -> dict[str, Any]:
    active_job = _serialize_job(record.get("active_job"))
    last_touchpoint = touchpoints[0] if touchpoints else None
    talking_points = _build_talking_points(record, client)
    return {
        "client_name": client["client_name"],
        "crm_owner": client["crm_owner"],
        "last_touchpoint": last_touchpoint,
        "days_since_contact": record.get("days_since_contact"),
        "health_score": record["health_score"],
        "risk_flags": [flag for flag in str(record.get("risk_flags") or "").split(",") if flag],
        "active_job": active_job,
        "emissions_summary": {
            "latest_year": record.get("latest_year"),
            "latest_tco2e": record.get("latest_total_tco2e"),
            "yoy_change_pct": None,
            "vs_trajectory_pct": record.get("emissions_variance_pct"),
        } if record.get("latest_year") is not None else None,
        "open_invoices": record.get("open_invoices", 0),
        "overdue_invoices": record.get("overdue_invoices", 0),
        "talking_points": talking_points,
        "engagement_end_date": record.get("engagement_end_date"),
    }


def _build_call_prep_full(
    record: dict[str, Any],
    client: dict[str, Any],
    recent_touchpoints: list[dict[str, Any]],
    jobs: list[dict[str, Any]],
    open_tasks: list[dict[str, Any]],
    recent_notes: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    active_job_raw = record.get("active_job")
    active_job_full = _serialize_job_full(active_job_raw)
    all_jobs_brief = [
        {
            "job_id": int(j["job_id"]),
            "title": j.get("title"),
            "status": j.get("status"),
            "reporting_year": j.get("reporting_year"),
        }
        for j in jobs[:10]
    ]
    talking_points = _build_talking_points_enhanced(record, client, recent_touchpoints, active_job_full, open_tasks)
    return {
        "client_name": client["client_name"],
        "crm_owner": client["crm_owner"],
        "health_score": record["health_score"],
        "risk_flags": [flag for flag in str(record.get("risk_flags") or "").split(",") if flag],
        "engagement": {
            "start_date": _safe_date(client.get("engagement_start_date")).isoformat() if _safe_date(client.get("engagement_start_date")) else None,
            "end_date": record.get("engagement_end_date"),
            "net_zero_year": client.get("net_zero_year"),
            "benchmark_year": client.get("benchmark_year"),
            "touchpoint_cadence": client.get("touchpoint_cadence"),
        },
        "recent_touchpoints": recent_touchpoints,
        "days_since_contact": record.get("days_since_contact"),
        "active_job": active_job_full,
        "all_jobs": all_jobs_brief,
        "open_tasks": open_tasks,
        "emissions_summary": {
            "latest_year": record.get("latest_year"),
            "latest_tco2e": record.get("latest_total_tco2e"),
            "yoy_change_pct": None,
            "vs_trajectory_pct": record.get("emissions_variance_pct"),
        } if record.get("latest_year") is not None else None,
        "invoices": {
            "open": record.get("open_invoices", 0),
            "overdue": record.get("overdue_invoices", 0),
        },
        "recent_notes": recent_notes or [],
        "talking_points": talking_points,
    }


def _build_fallback_call_prep(client_name: str, crm_owner: str, detail: str) -> dict[str, Any]:
    return {
        "client_name": client_name,
        "crm_owner": crm_owner,
        "last_touchpoint": None,
        "days_since_contact": None,
        "health_score": 0,
        "risk_flags": ["OVERDUE_CALL"],
        "active_job": None,
        "emissions_summary": None,
        "open_invoices": 0,
        "overdue_invoices": 0,
        "talking_points": [detail],
        "engagement_end_date": None,
        "detail": detail,
    }


@router.get("/dashboard")
def get_dashboard(
    crm_owner: str | None = Query(default=None, description="Optional CRM filter"),
    all_crms: bool = Query(default=False, description="Show all CRMs for superusers"),
    _user: dict[str, str] = Depends(_current_user),
):
    org_id = require_org(_user)
    default_owner = _default_crm_owner(_user)
    if all_crms and bool(_user.get("is_super_admin")):
        owner_filter = None
    else:
        owner_filter = _normalize_text(crm_owner or default_owner, default_owner)

    with get_conn() as con:
        try:
            _ensure_schema(con)
            clients = _load_scoped_clients(con, org_id, owner_filter)
            client_ids = [int(client["client_db_id"]) for client in clients]
            if not clients:
                return {
                    "action_queue": [],
                    "portfolio_summary": {
                        "total_clients": 0,
                        "healthy": 0,
                        "needs_attention": 0,
                        "at_risk": 0,
                        "avg_health_score": 0,
                    },
                    "upcoming_touchpoints": [],
                    "renewal_pipeline": [],
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                    "crm_owner": owner_filter or "__all__",
                }

            touchpoints = _load_touchpoints(con, org_id, client_ids)
            invoice_stats = _load_invoice_stats(con, org_id, client_ids)
            snapshots = _load_health_snapshots(con, org_id, client_ids)

            records: list[dict[str, Any]] = []
            for client in clients:
                record = _build_dashboard_record(
                    client=client,
                    snapshot=snapshots.get(client["client_db_id"]),
                    touchpoints=touchpoints.get(client["client_db_id"], []),
                    invoice_stats=invoice_stats.get(client["client_db_id"], {}),
                )
                records.append(record)

            action_queue: list[dict[str, Any]] = []
            upcoming_touchpoints: list[dict[str, Any]] = []
            renewal_pipeline: list[dict[str, Any]] = []
            score_total = 0
            healthy_count = 0
            needs_attention = 0
            at_risk = 0

            for client, record in zip(clients, records):
                score = int(record["health_score"])
                score_total += score
                if score >= 70:
                    healthy_count += 1
                elif score >= 40:
                    needs_attention += 1
                else:
                    at_risk += 1

                _flag_details: dict[str, str] = {
                    "RENEWAL_30": "Engagement ending soon — prioritise renewal conversation.",
                    "RENEWAL_90": "Engagement ending within 90 days — begin renewal planning.",
                    "MILESTONE_RED": "Job milestone is overdue — check delivery status.",
                    "INVOICE_OVERDUE": "Outstanding invoice requires follow-up.",
                    "OVERDUE_CALL": "No recent contact logged — schedule a call.",
                    "EMISSIONS_OFF_TRACK": "Emissions reporting behind schedule.",
                    "NO_ACTIVE_JOB": "No active job in portfolio — consider re-engagement.",
                }
                flags = [flag for flag in str(record.get("risk_flags") or "").split(",") if flag]
                for flag in flags:
                    action_queue.append(
                        {
                            "action_type": flag,
                            "priority": _priority_for_flag(flag),
                            "client_db_id": client["client_db_id"],
                            "client_name": client["client_name"],
                            "crm_owner": client["crm_owner"],
                            "headline": {
                                "RENEWAL_30": "Renewal due within 30 days",
                                "MILESTONE_RED": "Milestone overdue",
                                "INVOICE_OVERDUE": "Invoice overdue",
                                "RENEWAL_90": "Renewal due within 90 days",
                                "OVERDUE_CALL": "Call overdue",
                                "EMISSIONS_OFF_TRACK": "Emissions off track",
                                "NO_ACTIVE_JOB": "No active job",
                            }.get(flag, flag),
                            "detail": _flag_details.get(flag, ""),
                            "due_date": record.get("engagement_end_date") if flag in {"RENEWAL_30", "RENEWAL_90"} else record.get("touchpoint_due_date"),
                        }
                    )

                touchpoint_due = _safe_date(record.get("touchpoint_due_date"))
                if touchpoint_due:
                    days_until_due = (touchpoint_due - date.today()).days
                    if days_until_due <= 14:
                        upcoming_touchpoints.append(
                            {
                                "client_db_id": client["client_db_id"],
                                "client_name": client["client_name"],
                                "crm_owner": client["crm_owner"],
                                "last_touchpoint_date": record.get("last_touchpoint_date"),
                                "next_touchpoint_due": touchpoint_due.isoformat(),
                                "days_overdue": abs(days_until_due) if days_until_due < 0 else 0,
                                "days_remaining": days_until_due,
                            }
                        )

                if record.get("engagement_end_date"):
                    end_date = _safe_date(record.get("engagement_end_date"))
                    if end_date:
                        days_remaining = (end_date - date.today()).days
                        if days_remaining <= 90:
                            renewal_pipeline.append(
                                {
                                    "client_db_id": client["client_db_id"],
                                    "client_name": client["client_name"],
                                    "crm_owner": client["crm_owner"],
                                    "engagement_end_date": end_date.isoformat(),
                                    "days_remaining": days_remaining,
                                    "health_score": score,
                                }
                            )

            action_queue.sort(key=lambda item: (int(item["priority"]), _safe_date(item.get("due_date")) or date.max, str(item["client_name"])))
            upcoming_touchpoints.sort(key=lambda item: (item.get("days_remaining", 9999), str(item["client_name"])))
            renewal_pipeline.sort(key=lambda item: (int(item["days_remaining"]), str(item["client_name"])))

            return {
                "action_queue": action_queue,
                "portfolio_summary": {
                    "total_clients": len(records),
                    "healthy": healthy_count,
                    "needs_attention": needs_attention,
                    "at_risk": at_risk,
                    "avg_health_score": round(score_total / len(records), 1) if records else 0,
                },
                "upcoming_touchpoints": upcoming_touchpoints,
                "renewal_pipeline": renewal_pipeline,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "crm_owner": owner_filter or "__all__",
            }
        except Exception as exc:
            logger.exception("intelligence.dashboard_failed")
            return {
                "action_queue": [],
                "portfolio_summary": {
                    "total_clients": 0,
                    "healthy": 0,
                    "needs_attention": 0,
                    "at_risk": 0,
                    "avg_health_score": 0,
                },
                "upcoming_touchpoints": [],
                "renewal_pipeline": [],
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "crm_owner": owner_filter or "__all__",
                "detail": "Dashboard data is temporarily unavailable.",
            }


@router.get("/client/{client_db_id}/call-prep")
def get_call_prep(
    client_db_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    org_id = require_org(_user)
    with get_conn() as con:
        try:
            _ensure_schema(con)
            client_row = con.execute(
                """
                SELECT
                    db_id,
                    client_name,
                    COALESCE(NULLIF(TRIM(crm_owner), ''), 'Unassigned') AS crm_owner,
                    net_zero_year,
                    benchmark_year,
                    benchmark_total_tco2e,
                    engagement_start_date,
                    engagement_end_date,
                    touchpoint_cadence
                FROM clients
                WHERE db_id = ? AND org_id = ?
                LIMIT 1
                """,
                [int(client_db_id), org_id],
            ).fetchone()
            if not client_row:
                raise HTTPException(status_code=404, detail="Client not found")

            client = {
                "client_db_id": int(client_row[0]),
                "client_name": _normalize_text(client_row[1], "Untitled client"),
                "crm_owner": _normalize_text(client_row[2], "Unassigned"),
                "net_zero_year": int(client_row[3]) if client_row[3] is not None else None,
                "benchmark_year": int(client_row[4]) if client_row[4] is not None else None,
                "benchmark_total_tco2e": float(client_row[5]) if client_row[5] is not None else None,
                "engagement_start_date": _safe_date(client_row[6]),
                "engagement_end_date": _safe_date(client_row[7]),
                "touchpoint_cadence": _normalize_text(client_row[8], "monthly"),
            }

            # Load all supporting data for a live, comprehensive call prep
            all_touchpoints = _load_touchpoints(con, org_id, [int(client_db_id)]).get(int(client_db_id), [])
            invoice_stats = _load_invoice_stats(con, org_id, [int(client_db_id)]).get(int(client_db_id), {})
            jobs = _load_jobs(con, org_id, [int(client_db_id)]).get(int(client_db_id), [])
            job_ids = [int(j["job_id"]) for j in jobs]
            emissions_by_job = _aggregate_emissions(con, job_ids) if job_ids else {}
            open_tasks = _load_crm_tasks(con, int(client_db_id))
            recent_notes = _load_recent_notes(con, int(client_db_id), limit=5)

            # Live compute (not snapshot-based) so active_job and emissions are current
            record = _compute_client_record(
                client=client,
                jobs=jobs,
                touchpoints=all_touchpoints,
                invoice_stats=invoice_stats,
                emissions_by_job=emissions_by_job,
            )

            # Pass last 5 touchpoints for the recent contacts section
            recent_touchpoints = all_touchpoints[:5]
            return _build_call_prep_full(record, client, recent_touchpoints, jobs, open_tasks, recent_notes)
        except HTTPException:
            raise
        except Exception:
            logger.exception("intelligence.call_prep_failed", extra={"client_db_id": int(client_db_id)})
            return _build_fallback_call_prep("Call Prep", "Unassigned", "Call prep data is temporarily unavailable.")


@router.get("/touchpoints/{client_db_id}")
def list_touchpoints(client_db_id: int, _user: dict[str, str] = Depends(_current_user)):
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_schema(con)
        rows = con.execute(
            """
            SELECT
                touchpoint_id, client_db_id, crm_owner, touchpoint_type,
                summary, outcome, next_action, next_action_due,
                occurred_at, created_at, created_by
            FROM client_touchpoints
            WHERE org_id = ? AND client_db_id = ?
            ORDER BY occurred_at DESC, touchpoint_id DESC
            LIMIT 20
            """,
            [org_id, int(client_db_id)],
        ).fetchall()
        items: list[dict[str, Any]] = []
        for row in rows or []:
            items.append(
                {
                    "touchpoint_id": int(row[0]),
                    "client_db_id": int(row[1]),
                    "crm_owner": _normalize_text(row[2], "Unassigned"),
                    "touchpoint_type": _normalize_text(row[3], "call"),
                    "summary": _normalize_text(row[4], ""),
                    "outcome": _normalize_text(row[5], "neutral"),
                    "next_action": _normalize_text(row[6], ""),
                    "next_action_due": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
                    "occurred_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
                    "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
                    "created_by": _normalize_text(row[10], ""),
                }
            )
        return {"items": items}


@router.post("/touchpoints")
def create_touchpoint(body: dict[str, Any], _user: dict[str, str] = Depends(_current_user)):
    org_id = require_org(_user)
    client_db_id = body.get("client_db_id")
    if client_db_id is None:
        raise HTTPException(status_code=400, detail="client_db_id is required")

    touchpoint_type = _touchpoint_type_value(body.get("touchpoint_type"))
    outcome = _outcome_value(body.get("outcome"))
    summary = _normalize_text(body.get("summary"))
    if not summary:
        raise HTTPException(status_code=400, detail="summary is required")
    next_action = _normalize_text(body.get("next_action"), "")
    next_action_due = _safe_date(body.get("next_action_due"))
    occurred_at = _safe_datetime(body.get("occurred_at")) or datetime.now(timezone.utc)
    crm_owner = _default_crm_owner(_user)
    created_by = _normalize_text(_user.get("email") or _user.get("user_id"), "")
    timeline_subject = f"Touchpoint: {touchpoint_type.replace('_', ' ').title()}"
    body_lines = [summary]
    body_lines.append(f"Outcome: {outcome.replace('_', ' ').title()}")
    if next_action:
        body_lines.append(f"Next action: {next_action}")
    if next_action_due:
        body_lines.append(f"Due: {next_action_due.isoformat()}")
    timeline_body = "\n".join(line for line in body_lines if line)

    with get_conn(autocommit=False) as con:
        _ensure_schema(con)
        row = con.execute(
            """
            INSERT INTO client_touchpoints (
              org_id, client_db_id, crm_owner, touchpoint_type, summary, outcome,
              next_action, next_action_due, occurred_at, created_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING
              touchpoint_id, client_db_id, crm_owner, touchpoint_type,
              summary, outcome, next_action, next_action_due,
              occurred_at, created_at, created_by
            """,
            [
                org_id,
                int(client_db_id),
                crm_owner,
                touchpoint_type,
                summary,
                outcome,
                next_action or None,
                next_action_due,
                occurred_at,
                created_by or None,
            ],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=500, detail="Failed to save touchpoint")
        touchpoint_id = int(row[0])
        _ensure_crm_timeline_tables(con)
        con.execute(
            """
            INSERT INTO crm_events (
              client_db_id, job_id, event_type, channel, direction, subject,
              body_text, body_html, status, owner_user_id, due_at, source, source_ref,
              payload_json, is_private, created_by, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
            RETURNING event_id
            """,
            [
                int(client_db_id),
                None,
                "note",
                touchpoint_type,
                "internal",
                timeline_subject,
                timeline_body,
                None,
                "logged",
                created_by or None,
                next_action_due,
                "intelligence",
                f"touchpoint:{touchpoint_id}",
                {
                    "touchpoint_id": touchpoint_id,
                    "touchpoint_type": touchpoint_type,
                    "outcome": outcome,
                    "next_action": next_action or None,
                    "next_action_due": next_action_due.isoformat() if next_action_due else None,
                    "occurred_at": occurred_at.isoformat() if occurred_at else None,
                },
                False,
                created_by or None,
            ],
        ).fetchone()
        return {
            "touchpoint_id": touchpoint_id,
            "client_db_id": int(row[1]),
            "crm_owner": _normalize_text(row[2], "Unassigned"),
            "touchpoint_type": _normalize_text(row[3], "call"),
            "summary": _normalize_text(row[4], ""),
            "outcome": _normalize_text(row[5], "neutral"),
            "next_action": _normalize_text(row[6], ""),
            "next_action_due": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
            "occurred_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
            "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
            "created_by": _normalize_text(row[10], ""),
        }
