"""Intelligence routes - client health, action queue, and call prep."""
from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
import logging
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query

from api.auth import _current_user
from core.database import get_conn
from services.client_benchmark import get_client_benchmark_metrics
from services.emissions_reporting import load_combined_emissions_summary_rows
from services.tenancy import require_org

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/intelligence", tags=["intelligence"])


def _table_exists(con, table_name: str) -> bool:
    try:
        row = con.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = CURRENT_SCHEMA()
              AND table_name = ?
            LIMIT 1
            """,
            [table_name],
        ).fetchone()
        return bool(row)
    except Exception:
        try:
            con.execute(f"SELECT 1 FROM {table_name} LIMIT 1").fetchone()
            return True
        except Exception:
            return False


def _column_exists(con, table_name: str, column_name: str) -> bool:
    try:
        row = con.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = CURRENT_SCHEMA()
              AND table_name = ?
              AND column_name = ?
            LIMIT 1
            """,
            [table_name, column_name],
        ).fetchone()
        return bool(row)
    except Exception:
        try:
            con.execute(f"SELECT {column_name} FROM {table_name} LIMIT 1").fetchone()
            return True
        except Exception:
            return False


def _ensure_schema(con) -> None:
    try:
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS client_touchpoints (
              touchpoint_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              org_id UUID NOT NULL,
              client_db_id INTEGER NOT NULL,
              crm_owner VARCHAR NOT NULL,
              touchpoint_type VARCHAR NOT NULL DEFAULT 'call',
              summary TEXT,
              outcome VARCHAR,
              next_action TEXT,
              next_action_due DATE,
              occurred_at TIMESTAMP NOT NULL DEFAULT NOW(),
              created_at TIMESTAMP DEFAULT NOW(),
              created_by VARCHAR
            )
            """
        )
    except Exception:
        pass
    try:
        con.execute(
            """
            CREATE TABLE IF NOT EXISTS client_health_snapshots (
              snapshot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              org_id UUID NOT NULL,
              client_db_id INTEGER NOT NULL,
              health_score INTEGER NOT NULL DEFAULT 0,
              score_emissions INTEGER,
              score_milestones INTEGER,
              score_engagement INTEGER,
              score_payments INTEGER,
              risk_flags TEXT,
              computed_at TIMESTAMP DEFAULT NOW(),
              UNIQUE (org_id, client_db_id)
            )
            """
        )
    except Exception:
        pass
    for ddl in (
        "CREATE INDEX IF NOT EXISTS ix_client_touchpoints_client ON client_touchpoints (client_db_id, occurred_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_client_touchpoints_org_crm ON client_touchpoints (org_id, crm_owner, occurred_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_client_health_snapshots_org_client ON client_health_snapshots (org_id, client_db_id)",
    ):
        try:
            con.execute(ddl)
        except Exception:
            pass


def _normalize_text(value: Any, fallback: str = "") -> str:
    txt = str(value or "").strip()
    return txt or fallback


def _safe_date(value: Any):
    if value is None:
        return None
    if isinstance(value, date):
        return value
    if hasattr(value, "date"):
        try:
            return value.date()
        except Exception:
            return None
    txt = str(value).strip()
    if not txt:
        return None
    try:
        return date.fromisoformat(txt[:10])
    except Exception:
        return None


def _safe_datetime(value: Any):
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    txt = str(value).strip()
    if not txt:
        return None
    try:
        return datetime.fromisoformat(txt.replace("Z", "+00:00"))
    except Exception:
        try:
            return datetime.fromisoformat(txt[:19])
        except Exception:
            return None


def _default_crm_owner(user: dict[str, Any]) -> str:
    return _normalize_text(user.get("full_name") or user.get("email") or user.get("user_id"), "Unassigned")


def _cadence_window(cadence: str | None) -> tuple[int, int]:
    cadence_key = _normalize_text(cadence, "monthly").lower()
    if cadence_key == "quarterly":
        return 100, 150
    return 35, 60


def _touchpoint_type_value(value: Any) -> str:
    allowed = {"call", "email", "meeting", "report_sent", "data_request", "other"}
    txt = _normalize_text(value, "call").lower()
    return txt if txt in allowed else "other"


def _outcome_value(value: Any) -> str:
    allowed = {"positive", "neutral", "concern_raised", "escalation_needed"}
    txt = _normalize_text(value, "neutral").lower()
    return txt if txt in allowed else "neutral"


def _milestone_status(due_date: Any, completed_at: Any) -> str:
    if completed_at:
        return "green"
    due = _safe_date(due_date)
    if due is None:
        return "none"
    days_until_due = (due - date.today()).days
    if days_until_due < 0:
        return "red"
    if days_until_due <= 7:
        return "amber"
    return "green"


def _overall_milestone_status(statuses: list[str]) -> str | None:
    filtered = [str(status or "").strip().lower() for status in statuses if str(status or "").strip()]
    if not filtered:
        return None
    if "red" in filtered:
        return "red"
    if "amber" in filtered:
        return "amber"
    if "green" in filtered:
        return "green"
    return None


def _milestone_score(status: str | None) -> int:
    normalized = _normalize_text(status, "").lower()
    if normalized == "green":
        return 25
    if normalized == "amber":
        return 15
    if normalized == "red":
        return 5
    return 10


def _engagement_score(last_touchpoint: date | None, cadence: str | None) -> tuple[int, list[str], int | None, date | None]:
    low, mid = _cadence_window(cadence)
    if last_touchpoint is None:
        return 0, ["OVERDUE_CALL"], None, None
    days_since = (date.today() - last_touchpoint).days
    if days_since < low:
        return 25, [], days_since, last_touchpoint + timedelta(days=low)
    if days_since <= mid:
        return 15, ["OVERDUE_CALL"], days_since, last_touchpoint + timedelta(days=low)
    return 0, ["OVERDUE_CALL"], days_since, last_touchpoint + timedelta(days=low)


def _emissions_score(
    *,
    benchmark_year: int | None,
    benchmark_total: float | None,
    net_zero_year: int | None,
    latest_year: int | None,
    latest_total: float | None,
) -> tuple[int, list[str], float | None]:
    if benchmark_year is None or benchmark_total is None or latest_year is None or latest_total is None:
        return 5, [], None
    if net_zero_year is None or net_zero_year <= benchmark_year:
        return 5, [], None
    years_to_go = max(1, net_zero_year - benchmark_year)
    progress_years = max(0, min(latest_year - benchmark_year, years_to_go))
    expected = float(benchmark_total) * max(0.0, 1.0 - (progress_years / float(years_to_go)))
    if expected <= 0:
        return 30, [], None
    variance_pct = ((float(latest_total) - expected) / expected) * 100.0
    if variance_pct <= 5:
        return 30, [], variance_pct
    if variance_pct <= 15:
        return 20, [], variance_pct
    if variance_pct <= 30:
        return 10, ["EMISSIONS_OFF_TRACK"], variance_pct
    return 5, ["EMISSIONS_OFF_TRACK"], variance_pct


def _payment_score(overdue_invoices: int) -> tuple[int, list[str]]:
    if overdue_invoices <= 0:
        return 20, []
    if overdue_invoices == 1:
        return 10, ["INVOICE_OVERDUE"]
    return 0, ["INVOICE_OVERDUE"]


def _priority_for_flag(flag: str) -> int:
    return {
        "RENEWAL_30": 1,
        "MILESTONE_RED": 1,
        "INVOICE_OVERDUE": 2,
        "RENEWAL_90": 2,
        "OVERDUE_CALL": 3,
        "EMISSIONS_OFF_TRACK": 4,
        "NO_ACTIVE_JOB": 5,
    }.get(flag, 5)


def _format_due_date(value: date | None) -> str | None:
    return value.isoformat() if value else None


def _load_scoped_clients(con, org_id: str, crm_owner: str | None) -> list[dict[str, Any]]:
    filters = ["c.org_id = ?"]
    params: list[object] = [org_id]
    if crm_owner:
        filters.append("COALESCE(NULLIF(TRIM(c.crm_owner), ''), 'Unassigned') = ?")
        params.append(crm_owner)
    query = f"""
        SELECT
            c.db_id,
            c.client_name,
            COALESCE(NULLIF(TRIM(c.crm_owner), ''), 'Unassigned') AS crm_owner,
            c.net_zero_year,
            c.benchmark_year,
            c.benchmark_total_tco2e,
            c.engagement_start_date,
            c.engagement_end_date,
            c.touchpoint_cadence
        FROM clients c
        WHERE {' AND '.join(filters)}
        ORDER BY c.client_name ASC, c.db_id ASC
    """
    rows = con.execute(query, params).fetchall()
    clients: list[dict[str, Any]] = []
    for row in rows or []:
        clients.append(
            {
                "client_db_id": int(row[0]),
                "client_name": _normalize_text(row[1], "Untitled client"),
                "crm_owner": _normalize_text(row[2], "Unassigned"),
                "net_zero_year": int(row[3]) if row[3] is not None else None,
                "benchmark_year": int(row[4]) if row[4] is not None else None,
                "benchmark_total_tco2e": float(row[5]) if row[5] is not None else None,
                "engagement_start_date": _safe_date(row[6]),
                "engagement_end_date": _safe_date(row[7]),
                "touchpoint_cadence": _normalize_text(row[8], "monthly"),
            }
        )
    return clients


def _load_touchpoints(con, org_id: str, client_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not client_ids or not _table_exists(con, "client_touchpoints"):
        return {}
    placeholders = ",".join(["?"] * len(client_ids))
    rows = con.execute(
        f"""
        SELECT
            touchpoint_id, client_db_id, crm_owner, touchpoint_type,
            summary, outcome, next_action, next_action_due,
            occurred_at, created_at, created_by
        FROM client_touchpoints
        WHERE org_id = ? AND client_db_id IN ({placeholders})
        ORDER BY occurred_at DESC, touchpoint_id DESC
        """,
        [org_id, *client_ids],
    ).fetchall()
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in rows or []:
        grouped[int(row[1])].append(
            {
                "touchpoint_id": int(row[0]),
                "client_db_id": int(row[1]),
                "crm_owner": _normalize_text(row[2], "Unassigned"),
                "touchpoint_type": _normalize_text(row[3], "call"),
                "summary": _normalize_text(row[4], ""),
                "outcome": _normalize_text(row[5], "neutral"),
                "next_action": _normalize_text(row[6], ""),
                "next_action_due": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
                "occurred_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
                "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
                "created_by": _normalize_text(row[10], ""),
            }
        )
    return grouped


def _load_invoice_stats(con, org_id: str, client_ids: list[int]) -> dict[int, dict[str, int]]:
    if not client_ids or not _table_exists(con, "invoices"):
        return {}
    placeholders = ",".join(["?"] * len(client_ids))
    rows = con.execute(
        f"""
        SELECT
            client_db_id,
            COALESCE(SUM(CASE WHEN LOWER(COALESCE(status, '')) = 'overdue' AND COALESCE(due_date, CURRENT_DATE) < CURRENT_DATE THEN 1 ELSE 0 END), 0) AS overdue_count,
            COALESCE(SUM(CASE WHEN LOWER(COALESCE(status, '')) NOT IN ('paid', 'void', 'refunded') THEN 1 ELSE 0 END), 0) AS open_count
        FROM invoices
        WHERE org_id = ? AND client_db_id IN ({placeholders})
        GROUP BY client_db_id
        """,
        [org_id, *client_ids],
    ).fetchall()
    stats: dict[int, dict[str, int]] = {}
    for row in rows or []:
        stats[int(row[0])] = {
            "overdue_invoices": int(row[1] or 0),
            "open_invoices": int(row[2] or 0),
        }
    return stats


def _load_jobs(con, org_id: str, client_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not client_ids:
        return {}
    has_job_plan = _table_exists(con, "job_plan")
    placeholders = ",".join(["?"] * len(client_ids))
    milestone_select = """
        jp.data_collection_due,
        jp.data_collection_completed_at,
        jp.first_draft_due,
        jp.first_draft_completed_at,
        jp.final_report_due,
        jp.final_report_completed_at
    """ if has_job_plan else """
        NULL AS data_collection_due,
        NULL AS data_collection_completed_at,
        NULL AS first_draft_due,
        NULL AS first_draft_completed_at,
        NULL AS final_report_due,
        NULL AS final_report_completed_at
    """
    rows = con.execute(
        f"""
        SELECT
            j.job_id,
            j.client_db_id,
            j.job_number,
            j.title,
            COALESCE(NULLIF(TRIM(j.status), ''), 'Unknown') AS status,
            j.reporting_year,
            j.start_date,
            j.due_date,
            j.created_at,
            {milestone_select}
        FROM jobs j
        LEFT JOIN clients c ON c.db_id = j.client_db_id
        {"LEFT JOIN job_plan jp ON jp.job_id = j.job_id" if has_job_plan else ""}
        WHERE COALESCE(j.org_id, c.org_id) = ? AND j.client_db_id IN ({placeholders})
        ORDER BY j.client_db_id ASC, j.reporting_year DESC NULLS LAST, j.job_id DESC
        """,
        [org_id, *client_ids],
    ).fetchall()
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in rows or []:
        client_id = int(row[1])
        grouped[client_id].append(
            {
                "job_id": int(row[0]),
                "client_db_id": client_id,
                "job_number": _normalize_text(row[2], ""),
                "title": _normalize_text(row[3], ""),
                "status": _normalize_text(row[4], "Unknown"),
                "reporting_year": int(row[5]) if row[5] is not None else None,
                "start_date": _safe_date(row[6]).isoformat() if _safe_date(row[6]) else None,
                "due_date": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
                "created_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
                "data_collection_due": _safe_date(row[9]),
                "data_collection_completed_at": _safe_datetime(row[10]),
                "first_draft_due": _safe_date(row[11]),
                "first_draft_completed_at": _safe_datetime(row[12]),
                "final_report_due": _safe_date(row[13]),
                "final_report_completed_at": _safe_datetime(row[14]),
            }
        )
    return grouped


def _aggregate_emissions(con, job_ids: list[int]) -> dict[int, float]:
    if not job_ids:
        return {}
    try:
        rows_df = load_combined_emissions_summary_rows(con, job_ids)
    except Exception:
        logger.exception("intelligence.emissions_summary_failed")
        return {}
    if rows_df is None or rows_df.empty:
        return {}
    totals: dict[int, float] = defaultdict(float)
    for _, row in rows_df.iterrows():
        job_id = row.get("job_id")
        if job_id is None:
            continue
        try:
            totals[int(job_id)] += float(row.get("emissions") or 0.0)
        except Exception:
            continue
    return {key: round(val, 2) for key, val in totals.items()}


def _pick_active_job(jobs: list[dict[str, Any]]) -> dict[str, Any] | None:
    active = [job for job in jobs if _normalize_text(job.get("status"), "").lower() not in {"completed", "archived", "cancelled"}]
    if not active:
        return None
    return active[0]


def _pick_latest_completed_job(jobs: list[dict[str, Any]]) -> dict[str, Any] | None:
    completed = [job for job in jobs if _normalize_text(job.get("status"), "").lower() in {"completed", "archived"}]
    if not completed:
        return None
    return completed[0]


def _touchpoint_due_date(last_touchpoint_date: date | None, cadence: str | None) -> date | None:
    if last_touchpoint_date is None:
        return None
    low, _mid = _cadence_window(cadence)
    return last_touchpoint_date + timedelta(days=low)


def _compute_client_record(
    *,
    client: dict[str, Any],
    jobs: list[dict[str, Any]],
    touchpoints: list[dict[str, Any]],
    invoice_stats: dict[str, int],
    emissions_by_job: dict[int, float],
) -> dict[str, Any]:
    last_touchpoint = _safe_date(touchpoints[0]["occurred_at"]) if touchpoints else None
    cadence = client.get("touchpoint_cadence")
    engagement_score, engagement_flags, days_since_contact, next_touchpoint_due = _engagement_score(last_touchpoint, cadence)

    active_job = _pick_active_job(jobs)
    active_status = _overall_milestone_status(
        [_milestone_status(job.get("data_collection_due"), job.get("data_collection_completed_at")) for job in (jobs[:1] if active_job is None else [active_job])]
    )
    milestone_score = _milestone_score(active_status)
    milestone_flags = ["MILESTONE_RED"] if active_status == "red" else []

    latest_completed_job = _pick_latest_completed_job(jobs)
    latest_year = latest_completed_job.get("reporting_year") if latest_completed_job else None
    latest_total = emissions_by_job.get(int(latest_completed_job["job_id"])) if latest_completed_job else None
    emissions_score, emissions_flags, variance_pct = _emissions_score(
        benchmark_year=client.get("benchmark_year"),
        benchmark_total=client.get("benchmark_total_tco2e"),
        net_zero_year=client.get("net_zero_year"),
        latest_year=latest_year,
        latest_total=latest_total,
    )

    overdue_invoices = int(invoice_stats.get("overdue_invoices") or 0)
    open_invoices = int(invoice_stats.get("open_invoices") or 0)
    payment_score, payment_flags = _payment_score(overdue_invoices)

    flags: list[str] = []
    flags.extend(engagement_flags)
    flags.extend(emissions_flags)
    flags.extend(milestone_flags)
    flags.extend(payment_flags)
    if client.get("engagement_end_date") is not None:
        days_remaining = (_safe_date(client["engagement_end_date"]) - date.today()).days if _safe_date(client["engagement_end_date"]) else None
        if days_remaining is not None and days_remaining <= 30:
            flags.append("RENEWAL_30")
        elif days_remaining is not None and days_remaining <= 90:
            flags.append("RENEWAL_90")
    if not any(_normalize_text(job.get("status"), "").lower() not in {"completed", "archived", "cancelled"} for job in jobs):
        flags.append("NO_ACTIVE_JOB")

    score = min(100, max(0, emissions_score + milestone_score + engagement_score + payment_score))

    risk_flags = ",".join(sorted({flag for flag in flags if flag}))
    return {
        "client_db_id": int(client["client_db_id"]),
        "client_name": client["client_name"],
        "crm_owner": client["crm_owner"],
        "health_score": int(score),
        "score_emissions": int(emissions_score),
        "score_milestones": int(milestone_score),
        "score_engagement": int(engagement_score),
        "score_payments": int(payment_score),
        "risk_flags": risk_flags,
        "last_touchpoint_date": last_touchpoint.isoformat() if last_touchpoint else None,
        "days_since_contact": days_since_contact,
        "touchpoint_due_date": _format_due_date(next_touchpoint_due),
        "active_job": active_job,
        "latest_completed_job": latest_completed_job,
        "latest_year": int(latest_year) if latest_year is not None else None,
        "latest_total_tco2e": float(latest_total) if latest_total is not None else None,
        "emissions_variance_pct": round(float(variance_pct), 1) if variance_pct is not None else None,
        "open_invoices": open_invoices,
        "overdue_invoices": overdue_invoices,
        "engagement_end_date": _safe_date(client.get("engagement_end_date")).isoformat() if _safe_date(client.get("engagement_end_date")) else None,
    }


def _refresh_snapshots(con, org_id: str, records: list[dict[str, Any]]) -> None:
    if not records:
        return
    values: list[object] = []
    placeholders: list[str] = []
    for record in records:
        placeholders.append("(?, ?, ?, ?, ?, ?, ?, ?, NOW())")
        values.extend(
            [
                org_id,
                record["client_db_id"],
                record["health_score"],
                record["score_emissions"],
                record["score_milestones"],
                record["score_engagement"],
                record["score_payments"],
                record["risk_flags"],
            ]
        )
    con.execute(
        f"""
        INSERT INTO client_health_snapshots (
          org_id, client_db_id, health_score, score_emissions,
          score_milestones, score_engagement, score_payments, risk_flags,
          computed_at
        )
        VALUES {", ".join(placeholders)}
        ON CONFLICT (org_id, client_db_id) DO UPDATE SET
          health_score = EXCLUDED.health_score,
          score_emissions = EXCLUDED.score_emissions,
          score_milestones = EXCLUDED.score_milestones,
          score_engagement = EXCLUDED.score_engagement,
          score_payments = EXCLUDED.score_payments,
          risk_flags = EXCLUDED.risk_flags,
          computed_at = NOW()
        """,
        values,
    )


def _build_talking_points(record: dict[str, Any], client: dict[str, Any]) -> list[str]:
    points: list[str] = []
    flags = {flag.strip() for flag in str(record.get("risk_flags") or "").split(",") if flag.strip()}
    days_since = record.get("days_since_contact")
    if "OVERDUE_CALL" in flags and days_since is not None:
        points.append(f"Check in - last contact was {days_since} days ago")
    if "EMISSIONS_OFF_TRACK" in flags and record.get("emissions_variance_pct") is not None:
        points.append(f"Emissions {round(float(record['emissions_variance_pct']), 1)}% above target trajectory - discuss reduction actions")
    if "MILESTONE_RED" in flags:
        points.append("Job milestone overdue - confirm data submission timeline")
    if "RENEWAL_90" in flags and record.get("engagement_end_date"):
        points.append(f"Contract renewal due {record['engagement_end_date']} - begin renewal conversation")
    if "INVOICE_OVERDUE" in flags:
        points.append("Outstanding invoice - confirm payment status")
    points.append(f"Review progress against net zero target ({client.get('net_zero_year') or 'n/a'})")
    return points


def _serialize_job(job: dict[str, Any] | None) -> dict[str, Any] | None:
    if not job:
        return None
    due_date = _safe_date(job.get("due_date"))
    next_milestone_name = None
    next_milestone_due = None
    for name, due_key, completed_key in (
        ("Data Collection", "data_collection_due", "data_collection_completed_at"),
        ("First Draft", "first_draft_due", "first_draft_completed_at"),
        ("Final Report", "final_report_due", "final_report_completed_at"),
    ):
        due = job.get(due_key)
        completed = job.get(completed_key)
        if due and not completed:
            next_milestone_name = name
            next_milestone_due = _safe_date(due)
            break
    days_to_milestone = (next_milestone_due - date.today()).days if next_milestone_due else None
    milestone_status = _overall_milestone_status(
        [_milestone_status(job.get("data_collection_due"), job.get("data_collection_completed_at")),
         _milestone_status(job.get("first_draft_due"), job.get("first_draft_completed_at")),
         _milestone_status(job.get("final_report_due"), job.get("final_report_completed_at"))]
    )
    return {
        "job_id": int(job["job_id"]),
        "job_number": job.get("job_number"),
        "title": job.get("title"),
        "status": job.get("status"),
        "milestone_status": milestone_status,
        "next_milestone": next_milestone_name,
        "days_to_milestone": days_to_milestone,
        "due_date": due_date.isoformat() if due_date else None,
    }


def _build_call_prep(record: dict[str, Any], client: dict[str, Any], touchpoints: list[dict[str, Any]]) -> dict[str, Any]:
    active_job = _serialize_job(record.get("active_job"))
    last_touchpoint = touchpoints[0] if touchpoints else None
    talking_points = _build_talking_points(record, client)
    return {
        "client_name": client["client_name"],
        "crm_owner": client["crm_owner"],
        "last_touchpoint": last_touchpoint,
        "days_since_contact": record.get("days_since_contact"),
        "health_score": record["health_score"],
        "risk_flags": [flag for flag in str(record.get("risk_flags") or "").split(",") if flag],
        "active_job": active_job,
        "emissions_summary": {
            "latest_year": record.get("latest_year"),
            "latest_tco2e": record.get("latest_total_tco2e"),
            "yoy_change_pct": None,
            "vs_trajectory_pct": record.get("emissions_variance_pct"),
        } if record.get("latest_year") is not None else None,
        "open_invoices": record.get("open_invoices", 0),
        "overdue_invoices": record.get("overdue_invoices", 0),
        "talking_points": talking_points,
        "engagement_end_date": record.get("engagement_end_date"),
    }


@router.get("/dashboard")
def get_dashboard(
    crm_owner: str | None = Query(default=None, description="Optional CRM filter"),
    all_crms: bool = Query(default=False, description="Show all CRMs for superusers"),
    _user: dict[str, str] = Depends(_current_user),
):
    org_id = require_org(_user)
    default_owner = _default_crm_owner(_user)
    if all_crms and bool(_user.get("is_super_admin")):
        owner_filter = None
    else:
        owner_filter = _normalize_text(crm_owner or default_owner, default_owner)

    with get_conn() as con:
        _ensure_schema(con)
        clients = _load_scoped_clients(con, org_id, owner_filter)
        client_ids = [int(client["client_db_id"]) for client in clients]
        if not clients:
            return {
                "action_queue": [],
                "portfolio_summary": {
                    "total_clients": 0,
                    "healthy": 0,
                    "needs_attention": 0,
                    "at_risk": 0,
                    "avg_health_score": 0,
                },
                "upcoming_touchpoints": [],
                "renewal_pipeline": [],
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "crm_owner": owner_filter or "__all__",
            }

        touchpoints = _load_touchpoints(con, org_id, client_ids)
        invoice_stats = _load_invoice_stats(con, org_id, client_ids)
        jobs_by_client = _load_jobs(con, org_id, client_ids)

        records: list[dict[str, Any]] = []
        for client in clients:
            client_jobs = jobs_by_client.get(client["client_db_id"], [])
            record = _compute_client_record(
                client=client,
                jobs=client_jobs,
                touchpoints=touchpoints.get(client["client_db_id"], []),
                invoice_stats=invoice_stats.get(client["client_db_id"], {}),
                emissions_by_job={},
            )
            record["active_job"] = _pick_active_job(client_jobs)
            record["touchpoints"] = touchpoints.get(client["client_db_id"], [])
            records.append(record)

        action_queue: list[dict[str, Any]] = []
        upcoming_touchpoints: list[dict[str, Any]] = []
        renewal_pipeline: list[dict[str, Any]] = []
        score_total = 0
        healthy_count = 0
        needs_attention = 0
        at_risk = 0

        for client, record in zip(clients, records):
            score = int(record["health_score"])
            score_total += score
            if score >= 70:
                healthy_count += 1
            elif score >= 40:
                needs_attention += 1
            else:
                at_risk += 1

            flags = [flag for flag in str(record.get("risk_flags") or "").split(",") if flag]
            for flag in flags:
                action_queue.append(
                    {
                        "action_type": flag,
                        "priority": _priority_for_flag(flag),
                        "client_db_id": client["client_db_id"],
                        "client_name": client["client_name"],
                        "crm_owner": client["crm_owner"],
                        "headline": {
                            "RENEWAL_30": "Renewal due within 30 days",
                            "MILESTONE_RED": "Milestone overdue",
                            "INVOICE_OVERDUE": "Invoice overdue",
                            "RENEWAL_90": "Renewal due within 90 days",
                            "OVERDUE_CALL": "Call overdue",
                            "EMISSIONS_OFF_TRACK": "Emissions off track",
                            "NO_ACTIVE_JOB": "No active job",
                        }.get(flag, flag),
                        "detail": f"Health score {score}.",
                        "due_date": record.get("engagement_end_date") if flag in {"RENEWAL_30", "RENEWAL_90"} else record.get("touchpoint_due_date"),
                    }
                )

            touchpoint_due = _safe_date(record.get("touchpoint_due_date"))
            if touchpoint_due:
                days_until_due = (touchpoint_due - date.today()).days
                if days_until_due <= 14:
                    upcoming_touchpoints.append(
                        {
                            "client_db_id": client["client_db_id"],
                            "client_name": client["client_name"],
                            "crm_owner": client["crm_owner"],
                            "last_touchpoint_date": record.get("last_touchpoint_date"),
                            "next_touchpoint_due": touchpoint_due.isoformat(),
                            "days_overdue": abs(days_until_due) if days_until_due < 0 else 0,
                            "days_remaining": days_until_due,
                        }
                    )

            if record.get("engagement_end_date"):
                end_date = _safe_date(record.get("engagement_end_date"))
                if end_date:
                    days_remaining = (end_date - date.today()).days
                    if days_remaining <= 90:
                        renewal_pipeline.append(
                            {
                                "client_db_id": client["client_db_id"],
                                "client_name": client["client_name"],
                                "crm_owner": client["crm_owner"],
                                "engagement_end_date": end_date.isoformat(),
                                "days_remaining": days_remaining,
                                "health_score": score,
                            }
                        )

        action_queue.sort(key=lambda item: (int(item["priority"]), _safe_date(item.get("due_date")) or date.max, str(item["client_name"])))
        upcoming_touchpoints.sort(key=lambda item: (item.get("days_remaining", 9999), str(item["client_name"])))
        renewal_pipeline.sort(key=lambda item: (int(item["days_remaining"]), str(item["client_name"])))

        return {
            "action_queue": action_queue,
            "portfolio_summary": {
                "total_clients": len(records),
                "healthy": healthy_count,
                "needs_attention": needs_attention,
                "at_risk": at_risk,
                "avg_health_score": round(score_total / len(records), 1) if records else 0,
            },
            "upcoming_touchpoints": upcoming_touchpoints,
            "renewal_pipeline": renewal_pipeline,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "crm_owner": owner_filter or "__all__",
        }


@router.get("/client/{client_db_id}/call-prep")
def get_call_prep(
    client_db_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_schema(con)
        client_row = con.execute(
            """
            SELECT
                db_id,
                client_name,
                COALESCE(NULLIF(TRIM(crm_owner), ''), 'Unassigned') AS crm_owner,
                net_zero_year,
                benchmark_year,
                benchmark_total_tco2e,
                engagement_start_date,
                engagement_end_date,
                touchpoint_cadence
            FROM clients
            WHERE db_id = ? AND org_id = ?
            LIMIT 1
            """,
            [int(client_db_id), org_id],
        ).fetchone()
        if not client_row:
            raise HTTPException(status_code=404, detail="Client not found")

        client = {
            "client_db_id": int(client_row[0]),
            "client_name": _normalize_text(client_row[1], "Untitled client"),
            "crm_owner": _normalize_text(client_row[2], "Unassigned"),
            "net_zero_year": int(client_row[3]) if client_row[3] is not None else None,
            "benchmark_year": int(client_row[4]) if client_row[4] is not None else None,
            "benchmark_total_tco2e": float(client_row[5]) if client_row[5] is not None else None,
            "engagement_start_date": _safe_date(client_row[6]),
            "engagement_end_date": _safe_date(client_row[7]),
            "touchpoint_cadence": _normalize_text(client_row[8], "monthly"),
        }
        jobs_by_client = _load_jobs(con, org_id, [int(client_db_id)])
        jobs = jobs_by_client.get(int(client_db_id), [])
        touchpoints = _load_touchpoints(con, org_id, [int(client_db_id)]).get(int(client_db_id), [])
        invoice_stats = _load_invoice_stats(con, org_id, [int(client_db_id)]).get(int(client_db_id), {})
        emissions_by_job = _aggregate_emissions(con, [job["job_id"] for job in jobs])
        record = _compute_client_record(
            client=client,
            jobs=jobs,
            touchpoints=touchpoints,
            invoice_stats=invoice_stats,
            emissions_by_job=emissions_by_job,
        )
        record["active_job"] = _pick_active_job(jobs)
        return _build_call_prep(record, client, touchpoints[:1])


@router.get("/touchpoints/{client_db_id}")
def list_touchpoints(client_db_id: int, _user: dict[str, str] = Depends(_current_user)):
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_schema(con)
        rows = con.execute(
            """
            SELECT
                touchpoint_id, client_db_id, crm_owner, touchpoint_type,
                summary, outcome, next_action, next_action_due,
                occurred_at, created_at, created_by
            FROM client_touchpoints
            WHERE org_id = ? AND client_db_id = ?
            ORDER BY occurred_at DESC, touchpoint_id DESC
            LIMIT 20
            """,
            [org_id, int(client_db_id)],
        ).fetchall()
        items: list[dict[str, Any]] = []
        for row in rows or []:
            items.append(
                {
                    "touchpoint_id": int(row[0]),
                    "client_db_id": int(row[1]),
                    "crm_owner": _normalize_text(row[2], "Unassigned"),
                    "touchpoint_type": _normalize_text(row[3], "call"),
                    "summary": _normalize_text(row[4], ""),
                    "outcome": _normalize_text(row[5], "neutral"),
                    "next_action": _normalize_text(row[6], ""),
                    "next_action_due": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
                    "occurred_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
                    "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
                    "created_by": _normalize_text(row[10], ""),
                }
            )
        return {"items": items}


@router.post("/touchpoints")
def create_touchpoint(body: dict[str, Any], _user: dict[str, str] = Depends(_current_user)):
    org_id = require_org(_user)
    client_db_id = body.get("client_db_id")
    if client_db_id is None:
        raise HTTPException(status_code=400, detail="client_db_id is required")

    touchpoint_type = _touchpoint_type_value(body.get("touchpoint_type"))
    outcome = _outcome_value(body.get("outcome"))
    summary = _normalize_text(body.get("summary"))
    if not summary:
        raise HTTPException(status_code=400, detail="summary is required")
    next_action = _normalize_text(body.get("next_action"), "")
    next_action_due = _safe_date(body.get("next_action_due"))
    occurred_at = _safe_datetime(body.get("occurred_at")) or datetime.now(timezone.utc)
    crm_owner = _default_crm_owner(_user)
    created_by = _normalize_text(_user.get("email") or _user.get("user_id"), "")

    with get_conn() as con:
        _ensure_schema(con)
        row = con.execute(
            """
            INSERT INTO client_touchpoints (
              org_id, client_db_id, crm_owner, touchpoint_type, summary, outcome,
              next_action, next_action_due, occurred_at, created_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING
              touchpoint_id, client_db_id, crm_owner, touchpoint_type,
              summary, outcome, next_action, next_action_due,
              occurred_at, created_at, created_by
            """,
            [
                org_id,
                int(client_db_id),
                crm_owner,
                touchpoint_type,
                summary,
                outcome,
                next_action or None,
                next_action_due,
                occurred_at,
                created_by or None,
            ],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=500, detail="Failed to save touchpoint")
        return {
            "touchpoint_id": int(row[0]),
            "client_db_id": int(row[1]),
            "crm_owner": _normalize_text(row[2], "Unassigned"),
            "touchpoint_type": _normalize_text(row[3], "call"),
            "summary": _normalize_text(row[4], ""),
            "outcome": _normalize_text(row[5], "neutral"),
            "next_action": _normalize_text(row[6], ""),
            "next_action_due": _safe_date(row[7]).isoformat() if _safe_date(row[7]) else None,
            "occurred_at": _safe_datetime(row[8]).isoformat() if _safe_datetime(row[8]) else None,
            "created_at": _safe_datetime(row[9]).isoformat() if _safe_datetime(row[9]) else None,
            "created_by": _normalize_text(row[10], ""),
        }
