"""
Job Files API Routes
Handles file uploads and management for jobs (client documents and generated reports).
"""

import io
import json
import os
import re
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Body, Depends, File, Form, HTTPException, Query, UploadFile
from fastapi.responses import FileResponse, StreamingResponse

from api.auth import _current_user
from api.onedrive_routes import (
    _drive_base_path,
    _graph_download,
    _graph_request,
    _graph_token,
    _joined_remote_path,
)
from core.database import get_conn

router = APIRouter()

# Local fallback storage.
UPLOAD_DIR = Path("uploads/job_files")
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


def _ensure_job_files_table(con) -> None:
    """Keep job_files schema resilient across local and upgraded environments."""
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_files (
          file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          row_id INTEGER,
          file_type VARCHAR NOT NULL,
          file_name VARCHAR NOT NULL,
          file_path TEXT,
          file_size BIGINT,
          mime_type VARCHAR,
          description TEXT,
          uploaded_by VARCHAR,
          uploaded_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS storage_provider VARCHAR DEFAULT 'local'")
    con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS external_item_id VARCHAR")
    con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS external_web_url TEXT")
    con.execute("ALTER TABLE job_files ADD COLUMN IF NOT EXISTS external_path TEXT")


def _mime_type_for_filename(filename: str) -> str:
    ext = Path(filename or "unknown").suffix.lower()
    mime_types = {
        ".pdf": "application/pdf",
        ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ".xls": "application/vnd.ms-excel",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".doc": "application/msword",
        ".csv": "text/csv",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".zip": "application/zip",
    }
    return mime_types.get(ext, "application/octet-stream")


def _safe_storage_filename(job_id: int, filename: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._ -]+", "_", str(filename or "unknown").strip())
    cleaned = cleaned.replace("..", "_")
    cleaned = cleaned.strip(" .") or "upload.bin"
    return f"{int(job_id)}_{cleaned}"


def _onedrive_enabled() -> bool:
    try:
        _drive_base_path()
    except Exception:
        return False
    return all(
        [
            str(os.getenv("MS_TENANT_ID") or "").strip(),
            str(os.getenv("MS_CLIENT_ID") or "").strip(),
            str(os.getenv("MS_CLIENT_SECRET") or "").strip(),
        ]
    )


def _graph_raw_request(method: str, url: str, body: bytes | None = None, headers: dict[str, str] | None = None) -> bytes:
    req = urllib.request.Request(url, data=body, method=method.upper())
    for key, value in (headers or {}).items():
        req.add_header(key, value)
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            return resp.read()
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="ignore")
        raise HTTPException(status_code=502, detail=f"Graph upload error {e.code}: {detail}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Graph upload failed: {e}")


def _onedrive_ensure_folder(token: str, folder_path: str) -> None:
    drive_base = _drive_base_path()
    segments = [seg for seg in str(folder_path or "").strip("/").split("/") if seg]
    current = ""
    for segment in segments:
        current = f"{current}/{segment}" if current else f"/{segment}"
        encoded = urllib.parse.quote(current, safe="/")
        try:
            _graph_request("GET", f"{drive_base}/root:{encoded}:", token)
            continue
        except HTTPException as e:
            if "Graph API error 404" not in str(e.detail):
                raise
        parent = current.rsplit("/", 1)[0]
        parent_target = (
            f"{drive_base}/root:{urllib.parse.quote(parent, safe='/')}:/children" if parent else f"{drive_base}/root/children"
        )
        payload = json.dumps(
            {
                "name": segment,
                "folder": {},
                "@microsoft.graph.conflictBehavior": "replace",
            }
        ).encode("utf-8")
        _graph_request("POST", parent_target, token, body=payload, content_type="application/json")


def _onedrive_job_folder(job_id: int, file_type: str) -> str:
    suffix = "generated-reports" if file_type == "generated_report" else "client-provided"
    return _joined_remote_path(f"job-files/job-{int(job_id)}/{suffix}")


def _onedrive_upload_bytes(*, filename: str, content: bytes, job_id: int, file_type: str) -> dict[str, str | int | None]:
    token = _graph_token()
    drive_base = _drive_base_path()
    remote_folder = _onedrive_job_folder(job_id, file_type)
    _onedrive_ensure_folder(token, remote_folder)

    full_path = f"{remote_folder}/{filename}" if remote_folder else f"/{filename}"
    encoded = urllib.parse.quote(full_path, safe="/")

    if len(content) <= 4 * 1024 * 1024:
        meta = _graph_request(
            "PUT",
            f"{drive_base}/root:{encoded}:/content",
            token,
            body=content,
            content_type="application/octet-stream",
        )
    else:
        session = _graph_request(
            "POST",
            f"{drive_base}/root:{encoded}:/createUploadSession",
            token,
            body=json.dumps(
                {
                    "item": {
                        "@microsoft.graph.conflictBehavior": "replace",
                        "name": filename,
                    }
                }
            ).encode("utf-8"),
            content_type="application/json",
        )
        upload_url = str(session.get("uploadUrl") or "").strip()
        if not upload_url:
            raise HTTPException(status_code=500, detail="Failed to create OneDrive upload session")

        chunk_size = 5 * 1024 * 1024
        start = 0
        meta: dict[str, object] = {}
        while start < len(content):
            end = min(start + chunk_size, len(content)) - 1
            chunk = content[start : end + 1]
            raw = _graph_raw_request(
                "PUT",
                upload_url,
                body=chunk,
                headers={
                    "Content-Length": str(len(chunk)),
                    "Content-Range": f"bytes {start}-{end}/{len(content)}",
                    "Content-Type": "application/octet-stream",
                },
            )
            if raw:
                meta = json.loads(raw.decode("utf-8"))
            start = end + 1

    return {
        "storage_provider": "onedrive",
        "file_path": str(full_path),
        "external_item_id": str(meta.get("id") or ""),
        "external_web_url": str(meta.get("webUrl") or ""),
        "external_path": str(full_path),
        "file_size": len(content),
    }


def _save_uploaded_file(file: UploadFile, job_id: int, file_type: str) -> tuple[dict[str, str | int | None], str]:
    contents = file.file.read()
    if not contents:
        raise HTTPException(status_code=400, detail="Cannot upload empty file")

    storage_name = _safe_storage_filename(job_id, file.filename or "unknown")
    mime_type = _mime_type_for_filename(file.filename or "unknown")

    if _onedrive_enabled():
        return _onedrive_upload_bytes(
            filename=storage_name,
            content=contents,
            job_id=job_id,
            file_type=file_type,
        ), mime_type

    file_path = UPLOAD_DIR / storage_name
    with open(file_path, "wb") as f:
        f.write(contents)

    return {
        "storage_provider": "local",
        "file_path": str(file_path),
        "external_item_id": None,
        "external_web_url": None,
        "external_path": None,
        "file_size": len(contents),
    }, mime_type


@router.get("/jobs/{job_id}/files")
def list_job_files(
    job_id: int,
    file_type: Optional[str] = Query(None, description="Filter by file_type: 'client_provided' or 'generated_report'"),
    row_id: Optional[int] = Query(None, description="Filter by linked row_id"),
    _user: dict[str, str] = Depends(_current_user),
):
    """List all files for a job."""
    try:
        with get_conn() as con:
            _ensure_job_files_table(con)
            job_exists = con.execute("SELECT 1 FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_exists:
                raise HTTPException(status_code=404, detail="Job not found")

            query = """
                SELECT file_id, job_id, row_id, file_type, file_name, file_path,
                       file_size, mime_type, description, uploaded_by, uploaded_at,
                       storage_provider, external_item_id, external_web_url, external_path
                FROM job_files
                WHERE job_id = %s
            """
            params = [int(job_id)]
            if file_type:
                query += " AND file_type = %s"
                params.append(file_type)
            if row_id is not None:
                query += " AND row_id = %s"
                params.append(row_id)
            query += " ORDER BY uploaded_at DESC"
            df = con.execute(query, params).df()

        files = []
        if df is not None and not df.empty:
            for _, row in df.iterrows():
                files.append(
                    {
                        "file_id": int(row["file_id"]),
                        "job_id": int(row["job_id"]),
                        "row_id": int(row["row_id"]) if row["row_id"] is not None else None,
                        "file_type": row["file_type"],
                        "file_name": row["file_name"],
                        "file_path": row["file_path"],
                        "file_size": int(row["file_size"]) if row["file_size"] is not None else None,
                        "mime_type": row["mime_type"],
                        "description": row["description"],
                        "uploaded_by": row["uploaded_by"],
                        "uploaded_at": str(row["uploaded_at"]) if row["uploaded_at"] else None,
                        "storage_provider": row["storage_provider"],
                        "external_item_id": row["external_item_id"],
                        "external_web_url": row["external_web_url"],
                        "external_path": row["external_path"],
                    }
                )

        return {"job_id": int(job_id), "files": files}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list files: {e}")


@router.post("/jobs/{job_id}/files")
async def upload_job_file(
    job_id: int,
    file: UploadFile = File(...),
    file_type: str = Form("client_provided"),
    row_id: Optional[int] = Form(None),
    description: str = Form(""),
    _user: dict[str, str] = Depends(_current_user),
):
    """Upload a file for a job."""
    try:
        if file_type not in ["client_provided", "generated_report"]:
            raise HTTPException(status_code=400, detail="file_type must be 'client_provided' or 'generated_report'")

        with get_conn() as con:
            _ensure_job_files_table(con)
            job_exists = con.execute("SELECT 1 FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_exists:
                raise HTTPException(status_code=404, detail="Job not found")

            if row_id is not None:
                row_exists = con.execute(
                    "SELECT 1 FROM job_scope_rows WHERE row_id = %s AND job_id = %s",
                    [int(row_id), int(job_id)],
                ).fetchone()
                if not row_exists:
                    raise HTTPException(status_code=400, detail="row_id does not belong to this job")

        file_meta, mime_type = _save_uploaded_file(file, int(job_id), file_type)

        with get_conn() as con:
            _ensure_job_files_table(con)
            result = con.execute(
                """
                INSERT INTO job_files (
                    job_id, row_id, file_type, file_name, file_path, file_size, mime_type,
                    description, uploaded_by, storage_provider, external_item_id, external_web_url, external_path
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING file_id
                """,
                [
                    int(job_id),
                    row_id,
                    file_type,
                    file.filename or "unknown",
                    file_meta.get("file_path"),
                    file_meta.get("file_size"),
                    mime_type,
                    description,
                    _user.get("email", "unknown"),
                    file_meta.get("storage_provider"),
                    file_meta.get("external_item_id"),
                    file_meta.get("external_web_url"),
                    file_meta.get("external_path"),
                ],
            ).fetchone()
            file_id = int(result[0])

        return {
            "ok": True,
            "file_id": file_id,
            "file_name": file.filename,
            "file_type": file_type,
            "row_id": row_id,
            "storage_provider": file_meta.get("storage_provider"),
            "external_web_url": file_meta.get("external_web_url"),
            "message": "File uploaded successfully",
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to upload file: {e}")


@router.patch("/jobs/{job_id}/files/{file_id}")
def update_job_file(
    job_id: int,
    file_id: int,
    row_id: Optional[int] = Body(None),
    description: Optional[str] = Body(None),
    _user: dict[str, str] = Depends(_current_user),
):
    """Update file metadata (link to row_id, update description)."""
    try:
        with get_conn() as con:
            _ensure_job_files_table(con)
            file_exists = con.execute(
                "SELECT 1 FROM job_files WHERE file_id = %s AND job_id = %s",
                [int(file_id), int(job_id)],
            ).fetchone()
            if not file_exists:
                raise HTTPException(status_code=404, detail="File not found")

            if row_id is not None:
                row_exists = con.execute(
                    "SELECT 1 FROM job_scope_rows WHERE row_id = %s AND job_id = %s",
                    [int(row_id), int(job_id)],
                ).fetchone()
                if not row_exists:
                    raise HTTPException(status_code=400, detail="row_id does not belong to this job")

            updates = []
            params = []
            if row_id is not None:
                updates.append("row_id = %s")
                params.append(int(row_id))
            if description is not None:
                updates.append("description = %s")
                params.append(description)
            if not updates:
                return {"ok": True, "message": "No changes to update"}

            params.extend([int(file_id), int(job_id)])
            query = f"UPDATE job_files SET {', '.join(updates)} WHERE file_id = %s AND job_id = %s"
            con.execute(query, params)

        return {"ok": True, "message": "File updated successfully"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update file: {e}")


@router.delete("/jobs/{job_id}/files/{file_id}")
def delete_job_file(
    job_id: int,
    file_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    """Delete a file."""
    try:
        with get_conn() as con:
            _ensure_job_files_table(con)
            file_row = con.execute(
                """
                SELECT file_path, storage_provider, external_item_id
                FROM job_files
                WHERE file_id = %s AND job_id = %s
                """,
                [int(file_id), int(job_id)],
            ).fetchone()
            if not file_row:
                raise HTTPException(status_code=404, detail="File not found")

            file_path = file_row[0]
            storage_provider = str(file_row[1] or "local")
            external_item_id = str(file_row[2] or "").strip()

            con.execute("DELETE FROM job_files WHERE file_id = %s AND job_id = %s", [int(file_id), int(job_id)])

        if storage_provider == "onedrive" and external_item_id:
            token = _graph_token()
            drive_base = _drive_base_path()
            _graph_request("DELETE", f"{drive_base}/items/{urllib.parse.quote(external_item_id)}", token)
        elif file_path and os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception:
                pass

        return {"ok": True, "message": "File deleted successfully"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete file: {e}")


@router.get("/jobs/{job_id}/files/{file_id}/download")
def download_job_file(
    job_id: int,
    file_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    """Download a file."""
    try:
        with get_conn() as con:
            _ensure_job_files_table(con)
            file_row = con.execute(
                """
                SELECT file_name, file_path, storage_provider, external_item_id
                FROM job_files
                WHERE file_id = %s AND job_id = %s
                """,
                [int(file_id), int(job_id)],
            ).fetchone()
            if not file_row:
                raise HTTPException(status_code=404, detail="File not found")

            file_name = file_row[0]
            file_path = file_row[1]
            storage_provider = str(file_row[2] or "local")
            external_item_id = str(file_row[3] or "").strip()

        if storage_provider == "onedrive":
            if not external_item_id:
                raise HTTPException(status_code=404, detail="External file ID missing")
            token = _graph_token()
            drive_base = _drive_base_path()
            content, content_type = _graph_download(
                f"{drive_base}/items/{urllib.parse.quote(external_item_id)}/content",
                token,
            )
            return StreamingResponse(
                io.BytesIO(content),
                media_type=content_type or "application/octet-stream",
                headers={"Content-Disposition": f'attachment; filename="{file_name}"'},
            )

        if not file_path or not os.path.exists(file_path):
            raise HTTPException(status_code=404, detail="File not found on disk")
        return FileResponse(path=file_path, filename=file_name, media_type="application/octet-stream")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to download file: {e}")
