from __future__ import annotations

from datetime import datetime
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Request

from api.auth import _current_user
from api.permissions import assert_job_access, assert_permission
from core.database import get_conn
from services.audit_log import fetch_row_dict, record_audit_event

router = APIRouter(tags=["job-milestones"])


def _safe_int(value: Any) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except Exception:
        return None


def _ensure_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_template_milestone_completions (
          completion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          item_id INTEGER NOT NULL REFERENCES milestone_template_items(item_id) ON DELETE CASCADE,
          is_complete BOOLEAN NOT NULL DEFAULT TRUE,
          completed_at TIMESTAMP,
          completed_by VARCHAR,
          updated_at TIMESTAMP DEFAULT NOW(),
          created_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        "ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS is_complete BOOLEAN NOT NULL DEFAULT TRUE"
    )
    con.execute(
        "ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP"
    )
    con.execute(
        "ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS completed_by VARCHAR"
    )
    con.execute(
        "ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP"
    )
    con.execute(
        "ALTER TABLE job_template_milestone_completions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()"
    )
    con.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'job_template_milestone_completions_unique'
            ) THEN
                ALTER TABLE job_template_milestone_completions
                ADD CONSTRAINT job_template_milestone_completions_unique
                UNIQUE (job_id, item_id);
            END IF;
        END $$;
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_template_milestone_completions_job_idx
        ON job_template_milestone_completions (job_id, item_id, is_complete)
        """
    )


def _actor_identifier(user: dict[str, Any] | None) -> str:
    if not isinstance(user, dict):
        return "system"
    return str(
        user.get("email")
        or user.get("user_id")
        or user.get("full_name")
        or user.get("user")
        or "system"
    ).strip()


def _job_context(con, job_id: int) -> dict[str, Any]:
    row = con.execute(
        """
        SELECT job_id, job_number, milestone_template_id
        FROM jobs
        WHERE job_id = ?
        """,
        [int(job_id)],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    return {
        "job_id": _safe_int(row[0]),
        "job_number": str(row[1] or "").strip() or None,
        "milestone_template_id": _safe_int(row[2]),
    }


def _snapshot(con, job_id: int, item_id: int) -> dict[str, Any] | None:
    return fetch_row_dict(
        con,
        """
        SELECT *
        FROM job_template_milestone_completions
        WHERE job_id = ? AND item_id = ?
        """,
        [int(job_id), int(item_id)],
    )


@router.get("/jobs/{job_id}/milestone-template-completions")
def list_milestone_template_completions(
    job_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        assert_permission(_user, "jobs.view")
    except HTTPException as exc:
        if exc.status_code == 403:
            return {"job_id": int(job_id), "items": []}
        raise
    try:
        with get_conn() as con:
            _ensure_schema(con)
            ctx = _job_context(con, int(job_id))
            df = con.execute(
                """
                SELECT
                  c.completion_id,
                  c.job_id,
                  c.item_id,
                  c.is_complete,
                  c.completed_at,
                  c.completed_by,
                  c.updated_at,
                  c.created_at,
                  i.template_id,
                  i.milestone_name,
                  i.days_offset,
                  i.sort_order
                FROM job_template_milestone_completions c
                JOIN milestone_template_items i ON i.item_id = c.item_id
                WHERE c.job_id = ?
                ORDER BY i.sort_order, i.item_id
                """,
                [int(job_id)],
            ).df()

            items: list[dict[str, Any]] = []
            if df is not None and not df.empty:
                df = df.where(df.notna(), None)
                for _, row in df.iterrows():
                    item_id = _safe_int(row.get("item_id"))
                    if item_id is None:
                        continue
                    items.append(
                        {
                            "completion_id": _safe_int(row.get("completion_id")),
                            "job_id": ctx["job_id"],
                            "item_id": item_id,
                            "template_id": _safe_int(row.get("template_id")),
                            "milestone_name": str(row.get("milestone_name") or ""),
                            "days_offset": _safe_int(row.get("days_offset")),
                            "sort_order": _safe_int(row.get("sort_order")),
                            "is_complete": bool(row.get("is_complete")) if row.get("is_complete") is not None else False,
                            "completed_at": str(row.get("completed_at")) if row.get("completed_at") else None,
                            "completed_by": str(row.get("completed_by")) if row.get("completed_by") else None,
                            "updated_at": str(row.get("updated_at")) if row.get("updated_at") else None,
                            "created_at": str(row.get("created_at")) if row.get("created_at") else None,
                        }
                    )

            return {"job_id": ctx["job_id"], "items": items}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list milestone completions: {e}")


@router.post("/jobs/{job_id}/milestone-template-items/{item_id}/complete")
def complete_job_template_milestone(
    request: Request,
    job_id: int,
    item_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    actor = _actor_identifier(_user)
    completed = bool(body.get("completed", True))

    try:
        with get_conn(autocommit=False) as con:
            _ensure_schema(con)
            ctx = _job_context(con, int(job_id))
            if not ctx.get("milestone_template_id"):
                raise HTTPException(status_code=400, detail="Job milestone template is not set")

            template_item = con.execute(
                """
                SELECT item_id, template_id, milestone_name, days_offset, sort_order
                FROM milestone_template_items
                WHERE item_id = ?
                """,
                [int(item_id)],
            ).fetchone()
            if not template_item:
                raise HTTPException(status_code=404, detail="Template milestone item not found")

            if _safe_int(template_item[1]) != ctx["milestone_template_id"]:
                raise HTTPException(status_code=400, detail="Template milestone item does not belong to this job template")

            before = _snapshot(con, int(job_id), int(item_id))
            now = datetime.now()

            con.execute(
                """
                INSERT INTO job_template_milestone_completions
                (job_id, item_id, is_complete, completed_at, completed_by, updated_at)
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT (job_id, item_id)
                DO UPDATE SET
                  is_complete = EXCLUDED.is_complete,
                  completed_at = EXCLUDED.completed_at,
                  completed_by = EXCLUDED.completed_by,
                  updated_at = EXCLUDED.updated_at
                """,
                [
                    int(job_id),
                    int(item_id),
                    completed,
                    now if completed else None,
                    actor if completed else None,
                    now,
                ],
            )

            after = _snapshot(con, int(job_id), int(item_id))
            record_audit_event(
                con,
                request=request,
                actor=_user,
                action="complete" if completed else "incomplete",
                entity_type="job_template_milestone_completion",
                entity_id=f"{int(job_id)}:{int(item_id)}",
                job_id=int(job_id),
                before=before,
                after=after,
                metadata={
                    "item_id": int(item_id),
                    "template_id": _safe_int(template_item[1]),
                    "milestone_name": str(template_item[2] or ""),
                },
            )

            return {"ok": True, "completed": completed, "item_id": int(item_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update milestone completion: {e}")
