from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query

from api.auth import _current_user
from api.job_scope_data_routes import _lookup_factor_from_reference, _safe_float, _safe_int
from core.database import get_conn

router = APIRouter()


def _ensure_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emission_groups (
          group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          scope VARCHAR NOT NULL,
          category VARCHAR,
          group_type VARCHAR NOT NULL DEFAULT 'asset',
          group_name VARCHAR NOT NULL,
          site_id INTEGER REFERENCES client_sites(site_id),
          rollup_method VARCHAR NOT NULL DEFAULT 'sum',
          notes TEXT,
          enabled BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS job_emission_groups_job_type_name_uidx
        ON job_emission_groups (job_id, group_type, group_name)
        WHERE COALESCE(enabled, TRUE) = TRUE
        """
    )
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emission_sources (
          source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          group_id INTEGER REFERENCES job_emission_groups(group_id) ON DELETE SET NULL,
          scope VARCHAR NOT NULL,
          category VARCHAR,
          source_type VARCHAR NOT NULL DEFAULT 'asset',
          source_subtype VARCHAR,
          site_id INTEGER REFERENCES client_sites(site_id),
          source_name VARCHAR NOT NULL,
          asset_identifier VARCHAR,
          employee_name VARCHAR,
          dataset_id INTEGER REFERENCES datasets(dataset_id),
          factor_db_id INTEGER REFERENCES factor_lookup(db_id),
          original_id VARCHAR,
          qty NUMERIC,
          uom VARCHAR,
          factor NUMERIC,
          ghg_unit VARCHAR,
          apply_pct NUMERIC DEFAULT 100,
          data_source VARCHAR DEFAULT 'Source Register',
          data_confidence VARCHAR DEFAULT 'M',
          notes TEXT,
          detail_json JSONB DEFAULT '{}'::jsonb,
          calc_tco2e NUMERIC,
          enabled BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_sources_job_type_enabled_idx
        ON job_emission_sources (job_id, source_type, enabled)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_sources_group_idx
        ON job_emission_sources (group_id, enabled)
        """
    )


def _calc_tco2e(qty: Any, factor: Any, apply_pct: Any, ghg_unit: Any) -> float:
    qty_val = float(qty or 0)
    factor_val = float(factor or 0)
    pct_val = float(apply_pct or 100)
    value = qty_val * factor_val * (pct_val / 100.0)
    if "kg" in str(ghg_unit or "kgCO2e").lower():
        value /= 1000.0
    return float(value)


def _job_exists(con, job_id: int) -> bool:
    return bool(con.execute("SELECT 1 FROM jobs WHERE job_id=%s", [int(job_id)]).fetchone())


def _resolve_factor(con, scope: str, original_id: str | None, factor_db_id: int | None) -> dict[str, Any]:
    out: dict[str, Any] = {
        "dataset_id": None,
        "factor_db_id": factor_db_id,
        "original_id": original_id,
        "factor": None,
        "ghg_unit": None,
        "category": None,
        "uom": None,
    }
    if factor_db_id is not None:
        row = con.execute(
            """
            SELECT db_id, dataset_id, original_id, factor, ghg_unit, category, uom
            FROM factor_lookup
            WHERE db_id=%s
            LIMIT 1
            """,
            [int(factor_db_id)],
        ).fetchone()
        if row:
            out["factor_db_id"] = _safe_int(row[0])
            out["dataset_id"] = _safe_int(row[1])
            out["original_id"] = str(row[2]).strip() if row[2] is not None else out["original_id"]
            out["factor"] = _safe_float(row[3])
            out["ghg_unit"] = str(row[4]).strip() if row[4] is not None else None
            out["category"] = str(row[5]).strip() if row[5] is not None else None
            out["uom"] = str(row[6]).strip() if row[6] is not None else None
            return out
    lookup = _lookup_factor_from_reference(con, None, scope, original_id)
    if lookup:
        out["factor_db_id"] = lookup.get("db_id")
        out["factor"] = lookup.get("factor")
        out["ghg_unit"] = lookup.get("ghg_unit")
        row = con.execute(
            """
            SELECT dataset_id, original_id, category, uom
            FROM factor_lookup
            WHERE db_id=%s
            LIMIT 1
            """,
            [int(lookup["db_id"])],
        ).fetchone()
        if row:
            out["dataset_id"] = _safe_int(row[0])
            out["original_id"] = str(row[1]).strip() if row[1] is not None else out["original_id"]
            out["category"] = str(row[2]).strip() if row[2] is not None else None
            out["uom"] = str(row[3]).strip() if row[3] is not None else None
    return out


def _list_register(con, job_id: int, source_type: str | None, include_disabled: bool) -> dict[str, Any]:
    group_where = ["job_id=%s"]
    group_params: list[Any] = [int(job_id)]
    source_where = ["js.job_id=%s"]
    source_params: list[Any] = [int(job_id)]
    if source_type:
        group_where.append("group_type=%s")
        group_params.append(str(source_type))
        source_where.append("js.source_type=%s")
        source_params.append(str(source_type))
    if not include_disabled:
        group_where.append("COALESCE(enabled, TRUE) = TRUE")
        source_where.append("COALESCE(js.enabled, TRUE) = TRUE")

    groups_df = con.execute(
        f"""
        SELECT group_id, job_id, scope, category, group_type, group_name, site_id, rollup_method, notes, enabled, created_at, updated_at
        FROM job_emission_groups
        WHERE {" AND ".join(group_where)}
        ORDER BY group_name
        """,
        group_params,
    ).df()

    sources_df = con.execute(
        f"""
        SELECT
          js.source_id, js.job_id, js.group_id, g.group_name, js.scope, js.category,
          js.source_type, js.source_subtype, js.site_id, cs.site_name,
          js.source_name, js.asset_identifier, js.employee_name,
          js.dataset_id, js.factor_db_id, js.original_id, js.qty, js.uom, js.factor, js.ghg_unit,
          js.apply_pct, js.data_source, js.data_confidence, js.notes, js.detail_json, js.calc_tco2e,
          js.enabled, js.created_at, js.updated_at
        FROM job_emission_sources js
        LEFT JOIN job_emission_groups g ON g.group_id = js.group_id
        LEFT JOIN client_sites cs ON cs.site_id = js.site_id
        WHERE {" AND ".join(source_where)}
        ORDER BY COALESCE(g.group_name, ''), COALESCE(js.source_name, ''), js.source_id
        """,
        source_params,
    ).df()

    groups: list[dict[str, Any]] = []
    group_map: dict[int, list[dict[str, Any]]] = {}
    source_rows = [] if sources_df is None or sources_df.empty else sources_df.to_dict("records")
    for row in source_rows:
        gid = row.get("group_id")
        if gid is None:
            continue
        try:
            group_map.setdefault(int(gid), []).append(row)
        except Exception:
            pass

    if groups_df is not None and not groups_df.empty:
        for _, row in groups_df.iterrows():
            gid = _safe_int(row.get("group_id"))
            members = group_map.get(int(gid or 0), []) if gid is not None else []
            groups.append(
                {
                    "group_id": gid,
                    "job_id": _safe_int(row.get("job_id")),
                    "scope": row.get("scope"),
                    "category": row.get("category"),
                    "group_type": row.get("group_type"),
                    "group_name": row.get("group_name"),
                    "site_id": _safe_int(row.get("site_id")),
                    "rollup_method": row.get("rollup_method"),
                    "notes": row.get("notes"),
                    "enabled": bool(row.get("enabled")) if row.get("enabled") is not None else True,
                    "created_at": row.get("created_at"),
                    "updated_at": row.get("updated_at"),
                    "source_count": len(members),
                    "source_total_qty": round(sum(float(m.get("qty") or 0) for m in members), 4),
                    "source_total_tco2e": round(sum(float(m.get("calc_tco2e") or 0) for m in members), 4),
                }
            )

    sources: list[dict[str, Any]] = []
    total_tco2e = 0.0
    if source_rows:
        for row in source_rows:
            calc_tco2e = _safe_float(row.get("calc_tco2e"))
            if calc_tco2e is None:
                calc_tco2e = _calc_tco2e(row.get("qty"), row.get("factor"), row.get("apply_pct"), row.get("ghg_unit"))
            total_tco2e += float(calc_tco2e or 0)
            sources.append(
                {
                    "source_id": _safe_int(row.get("source_id")),
                    "job_id": _safe_int(row.get("job_id")),
                    "group_id": _safe_int(row.get("group_id")),
                    "group_name": row.get("group_name"),
                    "scope": row.get("scope"),
                    "category": row.get("category"),
                    "source_type": row.get("source_type"),
                    "source_subtype": row.get("source_subtype"),
                    "site_id": _safe_int(row.get("site_id")),
                    "site_name": row.get("site_name"),
                    "source_name": row.get("source_name"),
                    "asset_identifier": row.get("asset_identifier"),
                    "employee_name": row.get("employee_name"),
                    "dataset_id": _safe_int(row.get("dataset_id")),
                    "factor_db_id": _safe_int(row.get("factor_db_id")),
                    "original_id": row.get("original_id"),
                    "qty": _safe_float(row.get("qty")),
                    "uom": row.get("uom"),
                    "factor": _safe_float(row.get("factor")),
                    "ghg_unit": row.get("ghg_unit"),
                    "apply_pct": _safe_float(row.get("apply_pct"), 100) or 100,
                    "data_source": row.get("data_source"),
                    "data_confidence": row.get("data_confidence"),
                    "notes": row.get("notes"),
                    "detail_json": row.get("detail_json") or {},
                    "calc_tco2e": round(float(calc_tco2e or 0), 4),
                    "enabled": bool(row.get("enabled")) if row.get("enabled") is not None else True,
                    "created_at": row.get("created_at"),
                    "updated_at": row.get("updated_at"),
                }
            )

    return {
        "job_id": int(job_id),
        "source_type": source_type,
        "summary": {
            "group_count": len(groups),
            "source_count": len(sources),
            "enabled_source_count": sum(1 for row in sources if row["enabled"]),
            "disabled_source_count": sum(1 for row in sources if not row["enabled"]),
            "ungrouped_source_count": sum(1 for row in sources if row["group_id"] is None),
            "total_tco2e": round(total_tco2e, 4),
        },
        "groups": groups,
        "sources": sources,
    }


@router.get("/jobs/{job_id}/emission-registers")
def get_emission_registers(
    job_id: int,
    source_type: str | None = None,
    include_disabled: bool = Query(False),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            return _list_register(con, int(job_id), source_type, include_disabled)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load emission register: {e}")


@router.post("/jobs/{job_id}/emission-registers/groups")
def create_emission_group(
    job_id: int,
    payload: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            scope = str(payload.get("scope") or "").strip()
            group_name = str(payload.get("group_name") or "").strip()
            if not scope or not group_name:
                raise HTTPException(status_code=400, detail="scope and group_name are required")
            group_type = str(payload.get("group_type") or "asset").strip() or "asset"
            row = con.execute(
                """
                INSERT INTO job_emission_groups (
                    job_id, scope, category, group_type, group_name, site_id, rollup_method, notes
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING group_id
                """,
                [
                    int(job_id),
                    scope,
                    payload.get("category"),
                    group_type,
                    group_name,
                    _safe_int(payload.get("site_id")),
                    str(payload.get("rollup_method") or "sum"),
                    payload.get("notes"),
                ],
            ).fetchone()
            return {"ok": True, "group_id": int(row[0]) if row else None, "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create emission group: {e}")


@router.delete("/jobs/{job_id}/emission-registers/groups/{group_id}")
def delete_emission_group(
    job_id: int,
    group_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            con.execute(
                "UPDATE job_emission_groups SET enabled=FALSE, updated_at=NOW() WHERE group_id=%s AND job_id=%s",
                [int(group_id), int(job_id)],
            )
            return {"ok": True, "group_id": int(group_id), "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete emission group: {e}")


@router.post("/jobs/{job_id}/emission-registers/sources")
def create_emission_source(
    job_id: int,
    payload: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            scope = str(payload.get("scope") or "").strip()
            source_name = str(payload.get("source_name") or "").strip()
            if not scope or not source_name:
                raise HTTPException(status_code=400, detail="scope and source_name are required")
            source_type = str(payload.get("source_type") or "asset").strip() or "asset"
            group_id = _safe_int(payload.get("group_id"))
            if group_id is not None:
                group_exists = con.execute(
                    "SELECT 1 FROM job_emission_groups WHERE group_id=%s AND job_id=%s",
                    [int(group_id), int(job_id)],
                ).fetchone()
                if not group_exists:
                    raise HTTPException(status_code=400, detail="Selected group does not belong to this job")

            factor_db_id = _safe_int(payload.get("factor_db_id"))
            original_id = str(payload.get("original_id") or "").strip() or None
            resolved = _resolve_factor(con, scope, original_id, factor_db_id)
            qty = _safe_float(payload.get("qty"))
            factor = _safe_float(payload.get("factor"), resolved.get("factor"))
            apply_pct = _safe_float(payload.get("apply_pct"), 100) or 100
            ghg_unit = payload.get("ghg_unit") or resolved.get("ghg_unit")
            calc_tco2e = _calc_tco2e(qty, factor, apply_pct, ghg_unit)

            row = con.execute(
                """
                INSERT INTO job_emission_sources (
                    job_id, group_id, scope, category, source_type, source_subtype, site_id,
                    source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                    qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                    detail_json, calc_tco2e
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
                RETURNING source_id
                """,
                [
                    int(job_id),
                    group_id,
                    scope,
                    payload.get("category") or resolved.get("category"),
                    source_type,
                    payload.get("source_subtype"),
                    _safe_int(payload.get("site_id")),
                    source_name,
                    payload.get("asset_identifier"),
                    payload.get("employee_name"),
                    _safe_int(resolved.get("dataset_id")),
                    _safe_int(resolved.get("factor_db_id")),
                    resolved.get("original_id"),
                    qty,
                    payload.get("uom") or resolved.get("uom"),
                    factor,
                    ghg_unit,
                    apply_pct,
                    payload.get("data_source") or "Source Register",
                    payload.get("data_confidence") or "M",
                    payload.get("notes"),
                    payload.get("detail_json") or payload.get("details") or {},
                    calc_tco2e,
                ],
            ).fetchone()
            return {"ok": True, "source_id": int(row[0]) if row else None, "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create emission source: {e}")


@router.delete("/jobs/{job_id}/emission-registers/sources/{source_id}")
def delete_emission_source(
    job_id: int,
    source_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            con.execute(
                "UPDATE job_emission_sources SET enabled=FALSE, updated_at=NOW() WHERE source_id=%s AND job_id=%s",
                [int(source_id), int(job_id)],
            )
            return {"ok": True, "source_id": int(source_id), "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete emission source: {e}")
