from __future__ import annotations

import io
import base64
import re
from datetime import datetime, timezone
from uuid import uuid4
from typing import Any
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.platypus import Paragraph

from api.auth import _current_user
from api.permissions import assert_job_access
from core.database import get_conn
from services.audit_log import fetch_row_dict
from services.company_profile import company_footer_text, get_company_profile
from services.emissions_reporting import exact_job_total_emissions

router = APIRouter()


def _ensure_job_emissions_certificate_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emissions_certificates (
          certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          org_id VARCHAR NOT NULL,
          client_db_id INTEGER NOT NULL,
          client_name VARCHAR NOT NULL,
          job_number VARCHAR,
          reporting_year INTEGER NOT NULL,
          emissions NUMERIC NOT NULL DEFAULT 0,
          certificate_number VARCHAR NOT NULL,
          issued_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """
    )
    con.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS job_emissions_certificates_job_year_org_idx "
        "ON job_emissions_certificates (job_id, reporting_year, org_id)"
    )
    con.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS job_emissions_certificates_number_idx "
        "ON job_emissions_certificates (certificate_number)"
    )
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS org_id VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS client_db_id INTEGER")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS client_name VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS job_number VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS reporting_year INTEGER")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS emissions NUMERIC DEFAULT 0")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS certificate_number VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()")


def _certificate_filename(job_number: str | None, certificate_number: str) -> str:
    job_stub = re.sub(r"[^A-Za-z0-9._-]+", "-", str(job_number or "job").strip()) or "job"
    cert_stub = re.sub(r"[^A-Za-z0-9._-]+", "-", str(certificate_number or "certificate").strip()) or "certificate"
    return f"{job_stub}-{cert_stub}-carbon-emissions-certificate.pdf"


def _coerce_reporting_year(row: dict[str, Any]) -> int:
    for key in ("reporting_year",):
        value = row.get(key)
        if value is None:
            continue
        try:
            year = int(float(value))
            if year > 1900:
                return year
        except Exception:
            pass
    reporting_period_end = row.get("reporting_period_end")
    if reporting_period_end:
        try:
            year = datetime.fromisoformat(str(reporting_period_end)).year
            if year > 1900:
                return year
        except Exception:
            pass
    return datetime.now(timezone.utc).year


def _parse_local_logo_path(logo_url: str | None) -> Path | None:
    value = str(logo_url or "").strip()
    if not value or value.startswith("http://") or value.startswith("https://") or value.startswith("data:"):
        return None
    if value.startswith("/"):
        candidate = Path(__file__).resolve().parents[1] / "frontend" / "public" / value.lstrip("/")
        return candidate if candidate.exists() else None
    candidate = Path(value)
    if candidate.exists():
        return candidate
    return None


def _get_nzi_logo_reader(con) -> ImageReader | None:
    try:
        rows = con.execute(
            "SELECT setting_key, setting_value FROM system_settings WHERE setting_key IN (?, ?, ?)",
            ["nzi_logo_file", "nzi_logo_b64", "nzi_logo_mime"],
        ).fetchall()
        values = {str(r[0] or ""): r[1] for r in rows}
        filename = str(values.get("nzi_logo_file") or "").strip()
        if filename:
            candidate = Path(__file__).resolve().parents[1] / "frontend" / "public" / "uploads" / "system" / filename
            if candidate.exists():
                return ImageReader(str(candidate))
        logo_b64 = str(values.get("nzi_logo_b64") or "").strip()
        if logo_b64:
            raw = base64.b64decode(logo_b64, validate=False)
            if raw:
                return ImageReader(io.BytesIO(raw))
    except Exception:
        pass

    fallback = Path(__file__).resolve().parents[1] / "frontend" / "public" / "uploads" / "system" / "nzi-logo.png"
    if fallback.exists():
        try:
            return ImageReader(str(fallback))
        except Exception:
            return None

    alt = Path(__file__).resolve().parents[1] / "assets" / "netzero-logo-big-tree-64x64-1.png"
    if alt.exists():
        try:
            return ImageReader(str(alt))
        except Exception:
            return None
    return None


def _get_image_reader_from_logo_url(logo_url: str | None) -> ImageReader | None:
    value = str(logo_url or "").strip()
    if not value:
        return None
    try:
        if value.startswith("data:"):
            header, _, payload = value.partition(",")
            if ";base64" in header:
                raw = base64.b64decode(payload, validate=False)
                return ImageReader(io.BytesIO(raw))
        if value.startswith("http://") or value.startswith("https://"):
            with urlopen(value, timeout=5) as response:
                raw = response.read()
            return ImageReader(io.BytesIO(raw))
    except Exception:
        pass

    local_path = _parse_local_logo_path(value)
    if local_path and local_path.exists():
        try:
            return ImageReader(str(local_path))
        except Exception:
            return None

    if value.startswith("/uploads/"):
        candidate = Path(__file__).resolve().parents[1] / "frontend" / "public" / value.lstrip("/")
        if candidate.exists():
            try:
                return ImageReader(str(candidate))
            except Exception:
                return None
    return None


def _certificate_display_date(value: Any) -> str:
    if not value:
        return ""
    if isinstance(value, datetime):
        return f"{value.day} {value.strftime('%B %Y')}"
    if hasattr(value, "date") and hasattr(value, "strftime"):
        try:
            return f"{value.day} {value.strftime('%B %Y')}"
        except Exception:
            pass
    text = str(value or "").strip()
    if not text:
        return ""
    try:
        parsed = datetime.fromisoformat(text[:19])
        return f"{parsed.day} {parsed.strftime('%B %Y')}"
    except Exception:
        try:
            parsed = datetime.fromisoformat(text[:10])
            return f"{parsed.day} {parsed.strftime('%B %Y')}"
        except Exception:
            return text


def _certificate_period_label(start_value: Any, end_value: Any, reporting_year: Any) -> str:
    start_label = _certificate_display_date(start_value)
    end_label = _certificate_display_date(end_value)
    if start_label and end_label:
        return f"{start_label} to {end_label}"
    if reporting_year is not None:
        year = int(reporting_year)
        return f"1 January {year} to 31 December {year}"
    if end_label:
        year = end_label.split()[-1]
        return f"1 January {year} to {end_label}"
    return "Reporting period unavailable"


def _serialize_certificate_row(row: dict[str, Any], extra: dict[str, Any] | None = None) -> dict[str, Any]:
    emissions_value = row.get("emissions")
    issued_at = row.get("issued_at")
    updated_at = row.get("updated_at")
    payload = {
        "certificate_id": int(row["certificate_id"]) if row.get("certificate_id") is not None else None,
        "job_id": int(row["job_id"]) if row.get("job_id") is not None else None,
        "org_id": str(row.get("org_id") or "").strip() or None,
        "client_db_id": int(row["client_db_id"]) if row.get("client_db_id") is not None else None,
        "client_name": str(row.get("client_name") or "").strip() or "Client",
        "job_number": str(row.get("job_number") or "").strip() or None,
        "reporting_year": int(row["reporting_year"]) if row.get("reporting_year") is not None else None,
        "reporting_period_start": row.get("reporting_period_start").isoformat() if hasattr(row.get("reporting_period_start"), "isoformat") else (str(row.get("reporting_period_start")) if row.get("reporting_period_start") else None),
        "reporting_period_end": row.get("reporting_period_end").isoformat() if hasattr(row.get("reporting_period_end"), "isoformat") else (str(row.get("reporting_period_end")) if row.get("reporting_period_end") else None),
        "emissions": float(emissions_value or 0.0),
        "certificate_number": str(row.get("certificate_number") or "").strip() or None,
        "issued_at": issued_at.isoformat() if hasattr(issued_at, "isoformat") else (str(issued_at) if issued_at else None),
        "updated_at": updated_at.isoformat() if hasattr(updated_at, "isoformat") else (str(updated_at) if updated_at else None),
        "verified_by": "Net Zero International",
        "download_url": f"/jobs/{int(row['job_id'])}/emissions-certificate/pdf" if row.get("job_id") is not None else None,
    }
    if extra:
        payload.update(extra)
    return payload


def _load_job_certificate_context(con, job_id: int, current_user: dict[str, Any]) -> dict[str, Any]:
    assert_job_access(current_user, int(job_id))
    _ensure_job_emissions_certificate_schema(con)

    job_row = fetch_row_dict(
        con,
        """
        SELECT
          j.job_id,
          j.job_number,
          j.reporting_period_start,
          COALESCE(
            j.reporting_year,
            EXTRACT(YEAR FROM j.reporting_period_end)
          ) AS reporting_year,
          j.reporting_period_end,
          j.client_db_id,
          j.org_id,
          c.client_name,
          COALESCE(c.logo_url, c.logo_file) AS client_logo_url
        FROM jobs j
        LEFT JOIN clients c ON c.db_id = j.client_db_id
        WHERE j.job_id = ?
        """,
        [int(job_id)],
    )
    if not job_row:
        raise HTTPException(status_code=404, detail="Job not found")

    org_id = str(job_row.get("org_id") or current_user.get("org_id") or "").strip()
    if not org_id:
        raise HTTPException(status_code=403, detail="Organisation context required")

    try:
        company_profile = get_company_profile(con)
    except Exception:
        company_profile = {
            "company_display_name": "Net Zero International",
            "company_legal_name": "Net Zero International Limited",
            "website_url": "https://netzero.international",
            "company_registration_number": "",
            "vat_number": "",
            "certificate_signatory_name": "David Hawes",
            "certificate_signatory_title": "Chief Executive Officer",
        }
    reporting_year = _coerce_reporting_year(job_row)
    existing = fetch_row_dict(
        con,
        """
        SELECT
          certificate_id, job_id, org_id, client_db_id, client_name, job_number,
          reporting_year, emissions, certificate_number, issued_at, updated_at
        FROM job_emissions_certificates
        WHERE job_id = ? AND reporting_year = ? AND org_id = ?
        LIMIT 1
        """,
        [int(job_id), int(reporting_year), org_id],
    )
    if existing:
        extra = {
            "client_logo_url": str(job_row.get("client_logo_url") or "").strip() or None,
            "reporting_period_start": job_row.get("reporting_period_start").isoformat() if hasattr(job_row.get("reporting_period_start"), "isoformat") else (str(job_row.get("reporting_period_start")) if job_row.get("reporting_period_start") else None),
            "reporting_period_end": job_row.get("reporting_period_end").isoformat() if hasattr(job_row.get("reporting_period_end"), "isoformat") else (str(job_row.get("reporting_period_end")) if job_row.get("reporting_period_end") else None),
            "signatory_name": str(company_profile.get("certificate_signatory_name") or "David Hawes").strip() or "David Hawes",
            "signatory_title": str(company_profile.get("certificate_signatory_title") or "Chief Executive Officer").strip() or "Chief Executive Officer",
        }
        return _serialize_certificate_row(existing, extra)

    emissions = exact_job_total_emissions(con, int(job_id))
    temp_number = f"PENDING-{uuid4().hex}"
    inserted = con.execute(
        """
        INSERT INTO job_emissions_certificates (
          job_id, org_id, client_db_id, client_name, job_number, reporting_year,
          emissions, certificate_number, issued_at, updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
        RETURNING certificate_id
        """,
        [
            int(job_id),
            org_id,
            int(job_row["client_db_id"]) if job_row.get("client_db_id") is not None else 0,
            str(job_row.get("client_name") or "Client").strip() or "Client",
            str(job_row.get("job_number") or f"Job-{job_id}").strip() or f"Job-{job_id}",
            int(reporting_year),
            float(emissions or 0.0),
            temp_number,
        ],
    ).fetchone()
    if not inserted:
        raise HTTPException(status_code=500, detail="Failed to issue certificate")

    certificate_id = int(inserted[0])
    certificate_number = f"NZI-EC-{int(reporting_year)}-{certificate_id:06d}"
    con.execute(
        """
        UPDATE job_emissions_certificates
        SET certificate_number = ?, emissions = ?, updated_at = NOW()
        WHERE certificate_id = ?
        """,
        [certificate_number, float(emissions or 0.0), certificate_id],
    )
    issued = fetch_row_dict(
        con,
        """
        SELECT
          certificate_id, job_id, org_id, client_db_id, client_name, job_number,
          reporting_year, emissions, certificate_number, issued_at, updated_at
        FROM job_emissions_certificates
        WHERE certificate_id = ?
        LIMIT 1
        """,
        [certificate_id],
    )
    if not issued:
        raise HTTPException(status_code=500, detail="Failed to load certificate")
    extra = {
        "client_logo_url": str(job_row.get("client_logo_url") or "").strip() or None,
        "reporting_period_start": job_row.get("reporting_period_start").isoformat() if hasattr(job_row.get("reporting_period_start"), "isoformat") else (str(job_row.get("reporting_period_start")) if job_row.get("reporting_period_start") else None),
        "reporting_period_end": job_row.get("reporting_period_end").isoformat() if hasattr(job_row.get("reporting_period_end"), "isoformat") else (str(job_row.get("reporting_period_end")) if job_row.get("reporting_period_end") else None),
        "signatory_name": str(company_profile.get("certificate_signatory_name") or "David Hawes").strip() or "David Hawes",
        "signatory_title": str(company_profile.get("certificate_signatory_title") or "Chief Executive Officer").strip() or "Chief Executive Officer",
    }
    return _serialize_certificate_row(issued, extra)


def _render_certificate_pdf_bytes(certificate: dict[str, Any], company_profile: dict[str, Any], con=None) -> bytes:
    buffer = io.BytesIO()
    page_w, page_h = landscape(A4)
    c = canvas.Canvas(
        buffer,
        pagesize=landscape(A4),
        title=f"Annual Carbon Emissions Certificate {certificate.get('certificate_number') or ''}",
        author="Net Zero International",
    )

    company_name = str(
        company_profile.get("company_display_name")
        or company_profile.get("company_legal_name")
        or "Net Zero International"
    ).strip()
    company_legal_name = str(company_profile.get("company_legal_name") or company_name).strip() or company_name
    client_name = str(certificate.get("client_name") or "Client").strip() or "Client"
    job_number = str(certificate.get("job_number") or f"Job {certificate.get('job_id')}").strip()
    certificate_number = str(certificate.get("certificate_number") or "NZI-EC-000000").strip()
    reporting_year = certificate.get("reporting_year")
    emissions = float(certificate.get("emissions") or 0.0)
    issued_text = _certificate_display_date(certificate.get("issued_at")) or "On issue"
    reporting_period = _certificate_period_label(
        certificate.get("reporting_period_start"),
        certificate.get("reporting_period_end"),
        reporting_year,
    )
    signatory_name = str(certificate.get("signatory_name") or company_profile.get("certificate_signatory_name") or "David Hawes").strip() or "David Hawes"
    signatory_title = str(certificate.get("signatory_title") or company_profile.get("certificate_signatory_title") or "Chief Executive Officer").strip() or "Chief Executive Officer"
    footer_text = company_footer_text(company_profile) or company_legal_name

    nzi_logo_reader = _get_nzi_logo_reader(con) if con is not None else None
    client_logo_reader = _get_image_reader_from_logo_url(certificate.get("client_logo_url"))

    def draw_centered_paragraph(text: str, style: ParagraphStyle, top_y: float, width: float) -> float:
        paragraph = Paragraph(text, style)
        wrapped_w, wrapped_h = paragraph.wrap(width, page_h)
        paragraph.drawOn(c, (page_w - wrapped_w) / 2.0, top_y - wrapped_h)
        return wrapped_h

    def draw_wrapped_left(text: str, style: ParagraphStyle, x: float, top_y: float, width: float) -> float:
        paragraph = Paragraph(text, style)
        wrapped_w, wrapped_h = paragraph.wrap(width, page_h)
        paragraph.drawOn(c, x, top_y - wrapped_h)
        return wrapped_h

    def draw_image_fitted(reader: ImageReader, x: float, y: float, max_w: float, max_h: float) -> bool:
        try:
            img_w, img_h = reader.getSize()
            if not img_w or not img_h:
                return False
            scale = min(max_w / float(img_w), max_h / float(img_h))
            draw_w = float(img_w) * scale
            draw_h = float(img_h) * scale
            c.drawImage(reader, x + (max_w - draw_w) / 2.0, y + (max_h - draw_h) / 2.0, width=draw_w, height=draw_h, mask="auto")
            return True
        except Exception:
            return False

    # Background and border.
    c.setFillColor(colors.white)
    c.rect(0, 0, page_w, page_h, fill=1, stroke=0)
    inner_x = 9 * mm
    inner_y = 8 * mm
    inner_w = page_w - inner_x * 2
    inner_h = page_h - inner_y * 2
    c.setStrokeColor(colors.HexColor("#d1d5db"))
    c.setLineWidth(0.8)
    c.rect(inner_x, inner_y, inner_w, inner_h, fill=0, stroke=1)

    # Logos.
    top_logo_y = page_h - inner_y - 20 * mm
    if nzi_logo_reader:
        draw_image_fitted(nzi_logo_reader, inner_x + 7 * mm, top_logo_y, 40 * mm, 18 * mm)
    else:
        c.setFillColor(colors.HexColor("#6b7280"))
        c.setFont("Helvetica-Bold", 18)
        c.drawString(inner_x + 10 * mm, top_logo_y + 6 * mm, "Net Zero International")

    client_logo_box_x = page_w - inner_x - 42 * mm
    client_logo_box_y = top_logo_y + 1 * mm
    if client_logo_reader:
        draw_image_fitted(client_logo_reader, client_logo_box_x, client_logo_box_y, 36 * mm, 16 * mm)
    else:
        c.setFillColor(colors.HexColor("#6b7280"))
        c.setFont("Helvetica-Bold", 11)
        c.drawRightString(page_w - inner_x - 8 * mm, top_logo_y + 10 * mm, "[CLIENT LOGO]")

    # Main title block.
    orange = colors.HexColor("#f97316")
    dark = colors.HexColor("#2f343a")
    light = colors.HexColor("#6b7280")

    title_top = page_h - 55 * mm
    c.setFillColor(orange)
    c.setFont("Helvetica-Bold", 26)
    c.drawCentredString(page_w / 2.0, title_top, "Annual Carbon Emissions Certificate")

    c.setFillColor(dark)
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(page_w / 2.0, title_top - 19 * mm, client_name)

    intro_text = (
        "Net Zero International has reviewed the greenhouse gas emissions data for the reporting period stated in this document "
        "and confirms the total reported emissions shown below."
    )
    intro_style = ParagraphStyle(
        "CertificateIntro",
        parent=getSampleStyleSheet()["Normal"],
        alignment=1,
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#42464d"),
    )
    draw_centered_paragraph(intro_text, intro_style, title_top - 35 * mm, 190 * mm)

    # Emissions figure.
    figure_y = title_top - 58 * mm
    c.setFillColor(dark)
    c.setFont("Helvetica-Bold", 50)
    c.drawCentredString(page_w / 2.0, figure_y, f"{emissions:,.2f}")
    tco2e_style = ParagraphStyle(
        "CertificateTCO2e",
        parent=getSampleStyleSheet()["Normal"],
        alignment=1,
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=18,
        textColor=light,
    )
    draw_centered_paragraph("tCO<sub>2</sub>e", tco2e_style, figure_y - 10 * mm, 30 * mm)

    # Lower information columns.
    lower_top = 38 * mm
    left_x = inner_x + 10 * mm
    mid_x = page_w / 2.0 - 8 * mm
    right_x = page_w - inner_x - 65 * mm

    c.setFillColor(dark)
    c.setFont("Helvetica-Bold", 13.5)
    c.drawString(left_x, lower_top + 18 * mm, "Verified by Net Zero International")
    c.setStrokeColor(colors.HexColor("#bfc5cc"))
    c.setLineWidth(0.9)
    c.line(left_x, lower_top + 14 * mm, left_x + 48 * mm, lower_top + 14 * mm)
    c.setFillColor(light)
    c.setFont("Helvetica-Bold", 9.2)
    c.drawString(left_x, lower_top + 9 * mm, "Authorised Signatory")
    c.setFillColor(dark)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left_x, lower_top + 4.5 * mm, signatory_name)
    c.setFont("Helvetica", 9.8)
    c.drawString(left_x, lower_top, signatory_title)
    c.setFillColor(light)
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(left_x, lower_top - 9 * mm, "ISSUE DATE")
    c.setFillColor(dark)
    c.setFont("Helvetica", 10.8)
    c.drawString(left_x, lower_top - 14 * mm, issued_text)

    column_style = ParagraphStyle(
        "CertificateColumnValue",
        parent=getSampleStyleSheet()["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#2f343a"),
    )
    column_label_style = ParagraphStyle(
        "CertificateColumnLabel",
        parent=getSampleStyleSheet()["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=11,
        textColor=colors.HexColor("#6b7280"),
    )

    c.setFillColor(light)
    draw_wrapped_left("REPORTING PERIOD", column_label_style, mid_x, lower_top + 9 * mm, 72 * mm)
    draw_wrapped_left(reporting_period, column_style, mid_x, lower_top + 3.5 * mm, 72 * mm)

    draw_wrapped_left("STATEMENT NUMBER", column_label_style, right_x, lower_top + 9 * mm, 55 * mm)
    draw_wrapped_left(certificate_number, column_style, right_x, lower_top + 3.5 * mm, 55 * mm)

    # Disclaimer banner.
    banner_x = inner_x + 10 * mm
    banner_y = 12 * mm
    banner_w = inner_w - 20 * mm
    banner_h = 16 * mm
    c.setFillColor(colors.HexColor("#eef2f7"))
    c.roundRect(banner_x, banner_y, banner_w, banner_h, 2 * mm, fill=1, stroke=0)
    disclaimer_text = (
        "This document records the reported greenhouse gas emissions for the period identified above, as reviewed by Net Zero "
        "International. It does not, by itself, represent carbon neutrality, offsetting, emissions reduction performance, or "
        "independent third-party accreditation unless expressly stated."
    )
    disclaimer_style = ParagraphStyle(
        "CertificateDisclaimerBody",
        parent=getSampleStyleSheet()["Normal"],
        alignment=1,
        fontName="Helvetica",
        fontSize=8.6,
        leading=10.6,
        textColor=colors.HexColor("#6b7280"),
    )
    draw_centered_paragraph(disclaimer_text, disclaimer_style, banner_y + banner_h - 2.6 * mm, banner_w - 6 * mm)

    # Footer.
    c.setFillColor(light)
    c.setFont("Helvetica", 8.4)
    c.drawCentredString(page_w / 2.0, 5.8 * mm, footer_text[:180])

    c.showPage()
    c.save()
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


@router.get("/jobs/{job_id}/emissions-certificate")
def get_job_emissions_certificate(job_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        certificate = _load_job_certificate_context(con, int(job_id), _user)
    return certificate


@router.get("/jobs/{job_id}/emissions-certificate/pdf")
def get_job_emissions_certificate_pdf(job_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        certificate = _load_job_certificate_context(con, int(job_id), _user)
        company_profile = get_company_profile(con)
        pdf_bytes = _render_certificate_pdf_bytes(certificate, company_profile, con)

    filename = _certificate_filename(certificate.get("job_number"), certificate.get("certificate_number") or "certificate")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
