from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Body, Depends, File, HTTPException, Query, Response, UploadFile

from api.auth import _current_user
from api.job_scope_data_routes import _lookup_factor_from_reference, _safe_float, _safe_int
from core.database import get_conn
from openpyxl import load_workbook
from services.emission_register_template import build_emission_register_workbook
from services.audit_log import record_audit_event

router = APIRouter()


def _ensure_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emission_groups (
          group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          scope VARCHAR NOT NULL,
          category VARCHAR,
          group_type VARCHAR NOT NULL DEFAULT 'asset',
          group_name VARCHAR NOT NULL,
          site_id INTEGER REFERENCES client_sites(site_id),
          rollup_method VARCHAR NOT NULL DEFAULT 'sum',
          notes TEXT,
          enabled BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS job_emission_groups_job_type_name_uidx
        ON job_emission_groups (job_id, group_type, group_name)
        WHERE COALESCE(enabled, TRUE) = TRUE
        """
    )
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emission_sources (
          source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          group_id INTEGER REFERENCES job_emission_groups(group_id) ON DELETE SET NULL,
          scope VARCHAR NOT NULL,
          category VARCHAR,
          source_type VARCHAR NOT NULL DEFAULT 'asset',
          source_subtype VARCHAR,
          site_id INTEGER REFERENCES client_sites(site_id),
          source_name VARCHAR NOT NULL,
          asset_identifier VARCHAR,
          employee_name VARCHAR,
          dataset_id INTEGER REFERENCES datasets(dataset_id),
          factor_db_id INTEGER REFERENCES factor_lookup(db_id),
          original_id VARCHAR,
          qty NUMERIC,
          uom VARCHAR,
          factor NUMERIC,
          ghg_unit VARCHAR,
          apply_pct NUMERIC DEFAULT 100,
          data_source VARCHAR DEFAULT 'Source Register',
          data_confidence VARCHAR DEFAULT 'M',
          notes TEXT,
          detail_json JSONB DEFAULT '{}'::jsonb,
          calc_tco2e NUMERIC,
          enabled BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_sources_job_type_enabled_idx
        ON job_emission_sources (job_id, source_type, enabled)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_sources_group_idx
        ON job_emission_sources (group_id, enabled)
        """
    )


def _calc_tco2e(qty: Any, factor: Any, apply_pct: Any, ghg_unit: Any) -> float:
    qty_val = float(qty or 0)
    factor_val = float(factor or 0)
    pct_val = float(apply_pct or 100)
    value = qty_val * factor_val * (pct_val / 100.0)
    if "kg" in str(ghg_unit or "kgCO2e").lower():
        value /= 1000.0
    return float(value)


def _job_exists(con, job_id: int) -> bool:
    return bool(con.execute("SELECT 1 FROM jobs WHERE job_id=%s", [int(job_id)]).fetchone())


def _resolve_site_id(con, site_name: str | None) -> int | None:
    name = str(site_name or "").strip()
    if not name:
        return None
    row = con.execute(
        """
        SELECT site_id
        FROM client_sites
        WHERE lower(site_name) = lower(%s)
        ORDER BY site_id
        LIMIT 1
        """,
        [name],
    ).fetchone()
    return _safe_int(row[0]) if row else None


def _resolve_previous_register_job_id(con, job_id: int) -> dict[str, Any] | None:
    current_job = con.execute(
        """
        SELECT client_db_id, reporting_period_start, reporting_period_end, reporting_year
        FROM jobs
        WHERE job_id=%s
        """,
        [int(job_id)],
    ).fetchone()
    if not current_job:
        return None

    client_db_id = _safe_int(current_job[0])
    if client_db_id is None:
        return None

    current_start = current_job[1]
    current_end = current_job[2]
    current_year = _safe_int(current_job[3])

    prior = con.execute(
        """
        SELECT job_id, job_number, title, reporting_period_start, reporting_period_end, reporting_year
        FROM jobs
        WHERE client_db_id=%s
          AND job_id <> %s
          AND (
            (%s IS NOT NULL AND reporting_period_end IS NOT NULL AND reporting_period_end < %s)
            OR (%s IS NOT NULL AND reporting_period_start IS NOT NULL AND reporting_period_start < %s)
            OR (%s IS NOT NULL AND reporting_year IS NOT NULL AND reporting_year < %s)
          )
        ORDER BY COALESCE(reporting_period_end, DATE '1900-01-01') DESC, COALESCE(reporting_year, 0) DESC, job_id DESC
        LIMIT 1
        """,
        [client_db_id, int(job_id), current_start, current_start, current_start, current_end, current_year, current_year],
    ).fetchone()
    if not prior:
        return None
    return {
        "job_id": _safe_int(prior[0]),
        "job_number": prior[1],
        "title": prior[2],
        "reporting_period_start": prior[3],
        "reporting_period_end": prior[4],
        "reporting_year": _safe_int(prior[5]),
    }


_GROUP_HEADER_ALIASES = {
    "group name": "group_name",
    "group": "group_name",
    "scope": "scope",
    "category": "category",
    "group type": "group_type",
    "type": "group_type",
    "site": "site_name",
    "site name": "site_name",
    "site id": "site_id",
    "rollup": "rollup_method",
    "rollup method": "rollup_method",
    "notes": "notes",
}

_SOURCE_HEADER_ALIASES = {
    "group name": "group_name",
    "group": "group_name",
    "source name": "source_name",
    "asset name": "source_name",
    "asset": "source_name",
    "source": "source_name",
    "source type": "source_type",
    "type": "source_type",
    "source subtype": "source_subtype",
    "asset subtype": "source_subtype",
    "site": "site_name",
    "site name": "site_name",
    "site id": "site_id",
    "asset identifier": "asset_identifier",
    "employee name": "employee_name",
    "scope": "scope",
    "category": "category",
    "original id": "original_id",
    "factor db id": "factor_db_id",
    "factor": "factor",
    "qty": "qty",
    "quantity": "qty",
    "uom": "uom",
    "unit": "uom",
    "apply": "apply_pct",
    "apply pct": "apply_pct",
    "apply percent": "apply_pct",
    "data source": "data_source",
    "data confidence": "data_confidence",
    "notes": "notes",
}


def _sheet_rows(ws, alias_map: dict[str, str]) -> list[dict[str, Any]]:
    headers: list[str | None] = []
    for cell in next(ws.iter_rows(min_row=1, max_row=1, values_only=True), []):
        headers.append(alias_map.get(_norm_text(cell), _norm_text(cell) or None))

    rows: list[dict[str, Any]] = []
    for raw_row in ws.iter_rows(min_row=2, values_only=True):
        record: dict[str, Any] = {}
        has_value = False
        for idx, value in enumerate(raw_row):
            if idx >= len(headers):
                break
            key = headers[idx]
            if not key:
                continue
            record[key] = value
            if value is not None and str(value).strip() != "":
                has_value = True
        if has_value:
            rows.append(record)
    return rows


def _ensure_register_group(
    con,
    *,
    job_id: int,
    group_name: str,
    scope: str,
    group_type: str,
    category: str | None = None,
    site_id: int | None = None,
    rollup_method: str = "sum",
    notes: str | None = None,
) -> tuple[int | None, bool]:
    normalized_name = str(group_name or "").strip()
    if not normalized_name:
        return None, False

    existing = con.execute(
        """
        SELECT group_id
        FROM job_emission_groups
        WHERE job_id=%s
          AND lower(group_name) = lower(%s)
          AND lower(group_type) = lower(%s)
          AND COALESCE(enabled, TRUE) = TRUE
        ORDER BY group_id
        LIMIT 1
        """,
        [int(job_id), normalized_name, str(group_type or "asset").strip() or "asset"],
    ).fetchone()
    if existing:
        return _safe_int(existing[0]), False

    row = con.execute(
        """
        INSERT INTO job_emission_groups (
            job_id, scope, category, group_type, group_name, site_id, rollup_method, notes
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING group_id
        """,
        [
            int(job_id),
            scope,
            category,
            str(group_type or "asset").strip() or "asset",
            normalized_name,
            site_id,
            str(rollup_method or "sum").strip() or "sum",
            notes,
        ],
    ).fetchone()
    return (_safe_int(row[0]) if row else None, True)


def _register_source_exists(
    con,
    *,
    job_id: int,
    source_type: str,
    group_id: int | None,
    source_name: str,
    site_id: int | None,
    scope: str,
    category: str | None,
    source_subtype: str | None,
    original_id: str | None,
    asset_identifier: str | None,
    employee_name: str | None,
) -> bool:
    return bool(
        con.execute(
            """
            SELECT 1
            FROM job_emission_sources
            WHERE job_id=%s
              AND lower(COALESCE(source_type, '')) = lower(%s)
              AND COALESCE(group_id, -1) = COALESCE(%s, -1)
              AND lower(COALESCE(source_name, '')) = lower(%s)
              AND COALESCE(site_id, -1) = COALESCE(%s, -1)
              AND lower(COALESCE(scope, '')) = lower(%s)
              AND lower(COALESCE(category, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(source_subtype, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(original_id, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(asset_identifier, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(employee_name, '')) = lower(COALESCE(%s, ''))
            LIMIT 1
            """,
            [
                int(job_id),
                source_type,
                group_id,
                source_name,
                site_id,
                scope,
                category,
                source_subtype,
                original_id,
                asset_identifier,
                employee_name,
            ],
        ).fetchone()
    )


def _resolve_factor(con, scope: str, original_id: str | None, factor_db_id: int | None) -> dict[str, Any]:
    out: dict[str, Any] = {
        "dataset_id": None,
        "factor_db_id": factor_db_id,
        "original_id": original_id,
        "factor": None,
        "ghg_unit": None,
        "category": None,
        "uom": None,
    }
    if factor_db_id is not None:
        row = con.execute(
            """
            SELECT db_id, dataset_id, original_id, factor, ghg_unit, category, uom
            FROM factor_lookup
            WHERE db_id=%s
            LIMIT 1
            """,
            [int(factor_db_id)],
        ).fetchone()
        if row:
            out["factor_db_id"] = _safe_int(row[0])
            out["dataset_id"] = _safe_int(row[1])
            out["original_id"] = str(row[2]).strip() if row[2] is not None else out["original_id"]
            out["factor"] = _safe_float(row[3])
            out["ghg_unit"] = str(row[4]).strip() if row[4] is not None else None
            out["category"] = str(row[5]).strip() if row[5] is not None else None
            out["uom"] = str(row[6]).strip() if row[6] is not None else None
            return out
    lookup = _lookup_factor_from_reference(con, None, scope, original_id)
    if lookup:
        out["factor_db_id"] = lookup.get("db_id")
        out["factor"] = lookup.get("factor")
        out["ghg_unit"] = lookup.get("ghg_unit")
        row = con.execute(
            """
            SELECT dataset_id, original_id, category, uom
            FROM factor_lookup
            WHERE db_id=%s
            LIMIT 1
            """,
            [int(lookup["db_id"])],
        ).fetchone()
        if row:
            out["dataset_id"] = _safe_int(row[0])
            out["original_id"] = str(row[1]).strip() if row[1] is not None else out["original_id"]
            out["category"] = str(row[2]).strip() if row[2] is not None else None
            out["uom"] = str(row[3]).strip() if row[3] is not None else None
    return out


def _list_register(con, job_id: int, source_type: str | None, include_disabled: bool) -> dict[str, Any]:
    group_where = ["job_id=%s"]
    group_params: list[Any] = [int(job_id)]
    source_where = ["js.job_id=%s"]
    source_params: list[Any] = [int(job_id)]
    if source_type:
        group_where.append("group_type=%s")
        group_params.append(str(source_type))
        source_where.append("js.source_type=%s")
        source_params.append(str(source_type))
    if not include_disabled:
        group_where.append("COALESCE(enabled, TRUE) = TRUE")
        source_where.append("COALESCE(js.enabled, TRUE) = TRUE")

    groups_df = con.execute(
        f"""
        SELECT group_id, job_id, scope, category, group_type, group_name, site_id, rollup_method, notes, enabled, created_at, updated_at
        FROM job_emission_groups
        WHERE {" AND ".join(group_where)}
        ORDER BY group_name
        """,
        group_params,
    ).df()

    sources_df = con.execute(
        f"""
        SELECT
          js.source_id, js.job_id, js.group_id, g.group_name, js.scope, js.category,
          js.source_type, js.source_subtype, js.site_id, cs.site_name,
          js.source_name, js.asset_identifier, js.employee_name,
          js.dataset_id, js.factor_db_id, js.original_id, js.qty, js.uom, js.factor, js.ghg_unit,
          js.apply_pct, js.data_source, js.data_confidence, js.notes, js.detail_json, js.calc_tco2e,
          js.enabled, js.created_at, js.updated_at
        FROM job_emission_sources js
        LEFT JOIN job_emission_groups g ON g.group_id = js.group_id
        LEFT JOIN client_sites cs ON cs.site_id = js.site_id
        WHERE {" AND ".join(source_where)}
        ORDER BY COALESCE(g.group_name, ''), COALESCE(js.source_name, ''), js.source_id
        """,
        source_params,
    ).df()

    groups: list[dict[str, Any]] = []
    group_map: dict[int, list[dict[str, Any]]] = {}
    source_rows = [] if sources_df is None or sources_df.empty else sources_df.to_dict("records")
    for row in source_rows:
        gid = row.get("group_id")
        if gid is None:
            continue
        try:
            group_map.setdefault(int(gid), []).append(row)
        except Exception:
            pass

    if groups_df is not None and not groups_df.empty:
        for _, row in groups_df.iterrows():
            gid = _safe_int(row.get("group_id"))
            members = group_map.get(int(gid or 0), []) if gid is not None else []
            groups.append(
                {
                    "group_id": gid,
                    "job_id": _safe_int(row.get("job_id")),
                    "scope": row.get("scope"),
                    "category": row.get("category"),
                    "group_type": row.get("group_type"),
                    "group_name": row.get("group_name"),
                    "site_id": _safe_int(row.get("site_id")),
                    "rollup_method": row.get("rollup_method"),
                    "notes": row.get("notes"),
                    "enabled": bool(row.get("enabled")) if row.get("enabled") is not None else True,
                    "created_at": row.get("created_at"),
                    "updated_at": row.get("updated_at"),
                    "source_count": len(members),
                    "source_total_qty": round(sum(float(m.get("qty") or 0) for m in members), 4),
                    "source_total_tco2e": round(sum(float(m.get("calc_tco2e") or 0) for m in members), 4),
                }
            )

    sources: list[dict[str, Any]] = []
    total_tco2e = 0.0
    if source_rows:
        for row in source_rows:
            calc_tco2e = _safe_float(row.get("calc_tco2e"))
            if calc_tco2e is None:
                calc_tco2e = _calc_tco2e(row.get("qty"), row.get("factor"), row.get("apply_pct"), row.get("ghg_unit"))
            total_tco2e += float(calc_tco2e or 0)
            sources.append(
                {
                    "source_id": _safe_int(row.get("source_id")),
                    "job_id": _safe_int(row.get("job_id")),
                    "group_id": _safe_int(row.get("group_id")),
                    "group_name": row.get("group_name"),
                    "scope": row.get("scope"),
                    "category": row.get("category"),
                    "source_type": row.get("source_type"),
                    "source_subtype": row.get("source_subtype"),
                    "site_id": _safe_int(row.get("site_id")),
                    "site_name": row.get("site_name"),
                    "source_name": row.get("source_name"),
                    "asset_identifier": row.get("asset_identifier"),
                    "employee_name": row.get("employee_name"),
                    "dataset_id": _safe_int(row.get("dataset_id")),
                    "factor_db_id": _safe_int(row.get("factor_db_id")),
                    "original_id": row.get("original_id"),
                    "qty": _safe_float(row.get("qty")),
                    "uom": row.get("uom"),
                    "factor": _safe_float(row.get("factor")),
                    "ghg_unit": row.get("ghg_unit"),
                    "apply_pct": _safe_float(row.get("apply_pct"), 100) or 100,
                    "data_source": row.get("data_source"),
                    "data_confidence": row.get("data_confidence"),
                    "notes": row.get("notes"),
                    "detail_json": row.get("detail_json") or {},
                    "calc_tco2e": round(float(calc_tco2e or 0), 4),
                    "enabled": bool(row.get("enabled")) if row.get("enabled") is not None else True,
                    "created_at": row.get("created_at"),
                    "updated_at": row.get("updated_at"),
                }
            )

    return {
        "job_id": int(job_id),
        "source_type": source_type,
        "summary": {
            "group_count": len(groups),
            "source_count": len(sources),
            "enabled_source_count": sum(1 for row in sources if row["enabled"]),
            "disabled_source_count": sum(1 for row in sources if not row["enabled"]),
            "ungrouped_source_count": sum(1 for row in sources if row["group_id"] is None),
            "total_tco2e": round(total_tco2e, 4),
        },
        "groups": groups,
        "sources": sources,
    }


@router.get("/jobs/{job_id}/emission-registers/template")
def download_emission_register_template(
    job_id: int,
    source_type: str = Query("asset"),
    kind: str = Query("template"),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            payload, file_name = build_emission_register_workbook(
                con,
                job_id=int(job_id),
                source_type=str(source_type or "asset").strip() or "asset",
                kind=str(kind or "template").strip() or "template",
            )
        return Response(
            content=payload,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{file_name}"'},
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to build emission register workbook: {e}")


@router.get("/jobs/{job_id}/emission-registers")
def get_emission_registers(
    job_id: int,
    source_type: str | None = None,
    include_disabled: bool = Query(False),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            return _list_register(con, int(job_id), source_type, include_disabled)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load emission register: {e}")


@router.post("/jobs/{job_id}/emission-registers/groups")
def create_emission_group(
    job_id: int,
    payload: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            scope = str(payload.get("scope") or "").strip()
            group_name = str(payload.get("group_name") or "").strip()
            if not scope or not group_name:
                raise HTTPException(status_code=400, detail="scope and group_name are required")
            group_type = str(payload.get("group_type") or "asset").strip() or "asset"
            row = con.execute(
                """
                INSERT INTO job_emission_groups (
                    job_id, scope, category, group_type, group_name, site_id, rollup_method, notes
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING group_id
                """,
                [
                    int(job_id),
                    scope,
                    payload.get("category"),
                    group_type,
                    group_name,
                    _safe_int(payload.get("site_id")),
                    str(payload.get("rollup_method") or "sum"),
                    payload.get("notes"),
                ],
            ).fetchone()
            return {"ok": True, "group_id": int(row[0]) if row else None, "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create emission group: {e}")


@router.delete("/jobs/{job_id}/emission-registers/groups/{group_id}")
def delete_emission_group(
    job_id: int,
    group_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            con.execute(
                "UPDATE job_emission_groups SET enabled=FALSE, updated_at=NOW() WHERE group_id=%s AND job_id=%s",
                [int(group_id), int(job_id)],
            )
            return {"ok": True, "group_id": int(group_id), "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete emission group: {e}")


@router.post("/jobs/{job_id}/emission-registers/sources")
def create_emission_source(
    job_id: int,
    payload: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            scope = str(payload.get("scope") or "").strip()
            source_name = str(payload.get("source_name") or "").strip()
            if not scope or not source_name:
                raise HTTPException(status_code=400, detail="scope and source_name are required")
            source_type = str(payload.get("source_type") or "asset").strip() or "asset"
            group_id = _safe_int(payload.get("group_id"))
            if group_id is not None:
                group_exists = con.execute(
                    "SELECT 1 FROM job_emission_groups WHERE group_id=%s AND job_id=%s",
                    [int(group_id), int(job_id)],
                ).fetchone()
                if not group_exists:
                    raise HTTPException(status_code=400, detail="Selected group does not belong to this job")

            factor_db_id = _safe_int(payload.get("factor_db_id"))
            original_id = str(payload.get("original_id") or "").strip() or None
            resolved = _resolve_factor(con, scope, original_id, factor_db_id)
            qty = _safe_float(payload.get("qty"))
            factor = _safe_float(payload.get("factor"), resolved.get("factor"))
            apply_pct = _safe_float(payload.get("apply_pct"), 100) or 100
            ghg_unit = payload.get("ghg_unit") or resolved.get("ghg_unit")
            calc_tco2e = _calc_tco2e(qty, factor, apply_pct, ghg_unit)

            row = con.execute(
                """
                INSERT INTO job_emission_sources (
                    job_id, group_id, scope, category, source_type, source_subtype, site_id,
                    source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                    qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                    detail_json, calc_tco2e
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
                RETURNING source_id
                """,
                [
                    int(job_id),
                    group_id,
                    scope,
                    payload.get("category") or resolved.get("category"),
                    source_type,
                    payload.get("source_subtype"),
                    _safe_int(payload.get("site_id")),
                    source_name,
                    payload.get("asset_identifier"),
                    payload.get("employee_name"),
                    _safe_int(resolved.get("dataset_id")),
                    _safe_int(resolved.get("factor_db_id")),
                    resolved.get("original_id"),
                    qty,
                    payload.get("uom") or resolved.get("uom"),
                    factor,
                    ghg_unit,
                    apply_pct,
                    payload.get("data_source") or "Source Register",
                    payload.get("data_confidence") or "M",
                    payload.get("notes"),
                    payload.get("detail_json") or payload.get("details") or {},
                    calc_tco2e,
                ],
            ).fetchone()
            return {"ok": True, "source_id": int(row[0]) if row else None, "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create emission source: {e}")


@router.delete("/jobs/{job_id}/emission-registers/sources/{source_id}")
def delete_emission_source(
    job_id: int,
    source_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            con.execute(
                "UPDATE job_emission_sources SET enabled=FALSE, updated_at=NOW() WHERE source_id=%s AND job_id=%s",
                [int(source_id), int(job_id)],
            )
            return {"ok": True, "source_id": int(source_id), "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete emission source: {e}")


@router.post("/jobs/{job_id}/emission-registers/import-workbook")
async def import_emission_register_workbook(
    job_id: int,
    file: UploadFile = File(...),
    source_type: str = Query("asset"),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        content = await file.read()
        if not content:
            raise HTTPException(status_code=400, detail="Empty workbook upload")

        workbook = load_workbook(io.BytesIO(content), data_only=True)
        if "Groups" not in workbook.sheetnames or "Sources" not in workbook.sheetnames:
            raise HTTPException(status_code=400, detail="Workbook must contain Groups and Sources sheets")

        groups_sheet = workbook["Groups"]
        sources_sheet = workbook["Sources"]
        group_rows = _sheet_rows(groups_sheet, _GROUP_HEADER_ALIASES)
        source_rows = _sheet_rows(sources_sheet, _SOURCE_HEADER_ALIASES)
        source_type_value = str(source_type or "asset").strip() or "asset"
        default_scope = "Scope 3" if source_type_value == "business_travel" else "Scope 1"
        actor = str(_user.get("email", "unknown"))

        with get_conn(autocommit=False) as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")

            group_map: dict[str, int] = {}
            inserted_groups = 0
            reused_groups = 0

            for row in group_rows:
                group_name = str(row.get("group_name") or "").strip()
                if not group_name:
                    continue
                scope = str(row.get("scope") or default_scope).strip() or default_scope
                group_type = str(row.get("group_type") or source_type_value).strip() or source_type_value
                category = str(row.get("category") or "").strip() or None
                site_id = _safe_int(row.get("site_id")) or _resolve_site_id(con, row.get("site_name"))
                rollup_method = str(row.get("rollup_method") or "sum").strip() or "sum"
                notes = str(row.get("notes") or "").strip() or None
                group_id, created = _ensure_register_group(
                    con,
                    job_id=int(job_id),
                    group_name=group_name,
                    scope=scope,
                    group_type=group_type,
                    category=category,
                    site_id=site_id,
                    rollup_method=rollup_method,
                    notes=notes,
                )
                if group_id is not None:
                    group_map[group_name.lower()] = int(group_id)
                if created:
                    inserted_groups += 1
                else:
                    reused_groups += 1

            inserted_sources = 0
            skipped_sources = 0
            auto_groups_created = 0

            for idx, row in enumerate(source_rows, start=2):
                source_name = str(row.get("source_name") or "").strip()
                if not source_name:
                    continue
                group_name = str(row.get("group_name") or "").strip()
                scope = str(row.get("scope") or default_scope).strip() or default_scope
                category = str(row.get("category") or "").strip() or None
                group_type = str(row.get("source_type") or source_type_value).strip() or source_type_value
                source_subtype = str(row.get("source_subtype") or "").strip() or None
                site_id = _safe_int(row.get("site_id")) or _resolve_site_id(con, row.get("site_name"))
                asset_identifier = str(row.get("asset_identifier") or "").strip() or None
                employee_name = str(row.get("employee_name") or "").strip() or None
                original_id = str(row.get("original_id") or "").strip() or None
                factor_db_id = _safe_int(row.get("factor_db_id"))
                resolved = _resolve_factor(con, scope, original_id, factor_db_id)
                qty = _safe_float(row.get("qty"), 0) or 0
                factor = _safe_float(row.get("factor"), resolved.get("factor"))
                apply_pct = _safe_float(row.get("apply_pct"), 100) or 100
                ghg_unit = row.get("ghg_unit") or resolved.get("ghg_unit")
                uom = str(row.get("uom") or resolved.get("uom") or "").strip() or None
                data_source = str(row.get("data_source") or "Asset Register Import").strip() or "Asset Register Import"
                data_confidence = str(row.get("data_confidence") or "M").strip() or "M"
                notes = str(row.get("notes") or "").strip() or None

                group_id = None
                if group_name:
                    group_id = group_map.get(group_name.lower())
                    if group_id is None:
                        group_id, created = _ensure_register_group(
                            con,
                            job_id=int(job_id),
                            group_name=group_name,
                            scope=scope,
                            group_type=group_type,
                            category=category,
                            site_id=site_id,
                            rollup_method="sum",
                            notes=None,
                        )
                        if group_id is not None:
                            group_map[group_name.lower()] = int(group_id)
                        if created:
                            auto_groups_created += 1

                if _register_source_exists(
                    con,
                    job_id=int(job_id),
                    source_type=group_type,
                    group_id=group_id,
                    source_name=source_name,
                    site_id=site_id,
                    scope=scope,
                    category=category,
                    source_subtype=source_subtype,
                    original_id=original_id,
                    asset_identifier=asset_identifier,
                    employee_name=employee_name,
                ):
                    skipped_sources += 1
                    continue

                calc_tco2e = _calc_tco2e(qty, factor, apply_pct, ghg_unit)
                detail_json = {
                    "import_source": "workbook",
                    "workbook_name": file.filename,
                    "source_row": idx,
                    "group_name": group_name or None,
                }
                row = con.execute(
                    """
                    INSERT INTO job_emission_sources (
                        job_id, group_id, scope, category, source_type, source_subtype, site_id,
                        source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                        qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                        detail_json, calc_tco2e
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                    )
                    RETURNING source_id
                    """,
                    [
                        int(job_id),
                        group_id,
                        scope,
                        category or resolved.get("category"),
                        group_type,
                        source_subtype,
                        site_id,
                        source_name,
                        asset_identifier,
                        employee_name,
                        _safe_int(resolved.get("dataset_id")),
                        _safe_int(resolved.get("factor_db_id")),
                        resolved.get("original_id") or original_id,
                        qty,
                        uom or resolved.get("uom"),
                        factor,
                        ghg_unit,
                        apply_pct,
                        data_source,
                        data_confidence,
                        notes,
                        detail_json,
                        calc_tco2e,
                    ],
                ).fetchone()
                if row:
                    inserted_sources += 1

            record_audit_event(
                con,
                request=None,
                actor={"email": actor},
                action="create",
                entity_type="job_emission_register_import",
                entity_id=None,
                job_id=int(job_id),
                after={
                    "source_type": source_type_value,
                    "inserted_groups": inserted_groups,
                    "reused_groups": reused_groups,
                    "auto_groups_created": auto_groups_created,
                    "inserted_sources": inserted_sources,
                    "skipped_sources": skipped_sources,
                    "filename": file.filename,
                },
            )

            summary = _list_register(con, int(job_id), source_type_value, False).get("summary", {})

        return {
            "ok": True,
            "job_id": int(job_id),
            "source_type": source_type_value,
            "inserted_groups": inserted_groups,
            "reused_groups": reused_groups,
            "auto_groups_created": auto_groups_created,
            "inserted_sources": inserted_sources,
            "skipped_sources": skipped_sources,
            "summary": summary,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to import emission register workbook: {e}")


@router.post("/jobs/{job_id}/emission-registers/rollforward")
def rollforward_emission_register(
    job_id: int,
    source_type: str = Query("asset"),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        source_type_value = str(source_type or "asset").strip() or "asset"
        default_scope = "Scope 3" if source_type_value == "business_travel" else "Scope 1"
        actor = str(_user.get("email", "unknown"))

        with get_conn(autocommit=False) as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")

            previous_job = _resolve_previous_register_job_id(con, int(job_id))
            if not previous_job or previous_job.get("job_id") is None:
                raise HTTPException(status_code=400, detail="No previous job found for roll-forward")

            previous_job_id = int(previous_job["job_id"])

            group_rows = con.execute(
                """
                SELECT group_id, scope, category, group_type, group_name, site_id, rollup_method, notes
                FROM job_emission_groups
                WHERE job_id=%s
                  AND lower(COALESCE(group_type, '')) = lower(%s)
                  AND COALESCE(enabled, TRUE) = TRUE
                ORDER BY group_name, group_id
                """,
                [previous_job_id, source_type_value],
            ).fetchall()

            source_rows = con.execute(
                """
                SELECT
                  source_id, group_id, scope, category, source_type, source_subtype, site_id,
                  source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                  qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes, detail_json
                FROM job_emission_sources
                WHERE job_id=%s
                  AND lower(COALESCE(source_type, '')) = lower(%s)
                  AND COALESCE(enabled, TRUE) = TRUE
                ORDER BY COALESCE(group_id, 0), source_name, source_id
                """,
                [previous_job_id, source_type_value],
            ).fetchall()

            previous_group_map: dict[int, dict[str, Any]] = {}
            new_group_map: dict[int, int] = {}
            inserted_groups = 0
            reused_groups = 0
            inserted_sources = 0
            skipped_sources = 0

            for row in group_rows or []:
                old_group_id = _safe_int(row[0])
                group_name = str(row[4] or "").strip()
                scope = str(row[1] or default_scope).strip() or default_scope
                category = str(row[2] or "").strip() or None
                group_name = group_name or f"{source_type_value} group {old_group_id}"
                site_id = _safe_int(row[5])
                rollup_method = str(row[6] or "sum").strip() or "sum"
                notes = str(row[7] or "").strip() or None
                group_id, created = _ensure_register_group(
                    con,
                    job_id=int(job_id),
                    group_name=group_name,
                    scope=scope,
                    group_type=source_type_value,
                    category=category,
                    site_id=site_id,
                    rollup_method=rollup_method,
                    notes=notes,
                )
                if old_group_id is not None:
                    previous_group_map[int(old_group_id)] = {
                        "group_name": group_name,
                        "scope": scope,
                        "category": category,
                        "site_id": site_id,
                        "rollup_method": rollup_method,
                    }
                if group_id is not None:
                    new_group_map[int(old_group_id)] = int(group_id)
                if created:
                    inserted_groups += 1
                else:
                    reused_groups += 1

            for row in source_rows or []:
                old_group_id = _safe_int(row[1])
                group_id = new_group_map.get(int(old_group_id)) if old_group_id is not None else None
                group_meta = previous_group_map.get(int(old_group_id)) if old_group_id is not None else None
                scope = str(row[2] or default_scope).strip() or default_scope
                category = str(row[3] or "").strip() or None
                source_subtype = str(row[5] or "").strip() or None
                site_id = _safe_int(row[6])
                source_name = str(row[7] or "").strip()
                asset_identifier = str(row[8] or "").strip() or None
                employee_name = str(row[9] or "").strip() or None
                dataset_id = _safe_int(row[10])
                factor_db_id = _safe_int(row[11])
                original_id = str(row[12] or "").strip() or None
                qty = 0.0
                uom = str(row[14] or "").strip() or None
                factor = _safe_float(row[15])
                ghg_unit = str(row[16] or "").strip() or None
                apply_pct = _safe_float(row[17], 100) or 100
                data_source = "Previous Year Import"
                data_confidence = str(row[19] or "M").strip() or "M"
                notes = str(row[20] or "").strip() or None
                detail_json = row[21] if isinstance(row[21], dict) else {}
                if not source_name:
                    continue

                if _register_source_exists(
                    con,
                    job_id=int(job_id),
                    source_type=source_type_value,
                    group_id=group_id,
                    source_name=source_name,
                    site_id=site_id,
                    scope=scope,
                    category=category,
                    source_subtype=source_subtype,
                    original_id=original_id,
                    asset_identifier=asset_identifier,
                    employee_name=employee_name,
                ):
                    skipped_sources += 1
                    continue

                calc_tco2e = 0.0
                merged_detail_json = {
                    **(detail_json if isinstance(detail_json, dict) else {}),
                    "rollforward_from_job_id": previous_job_id,
                    "rollforward_from_source_id": _safe_int(row[0]),
                    "rollforward_source_type": source_type_value,
                    "rollforward_imported_at": datetime.now().isoformat(),
                }
                inserted = con.execute(
                    """
                    INSERT INTO job_emission_sources (
                        job_id, group_id, scope, category, source_type, source_subtype, site_id,
                        source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                        qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                        detail_json, calc_tco2e
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                    )
                    RETURNING source_id
                    """,
                    [
                        int(job_id),
                        group_id,
                        scope,
                        category or (group_meta or {}).get("category"),
                        source_type_value,
                        source_subtype,
                        site_id,
                        source_name,
                        asset_identifier,
                        employee_name,
                        dataset_id,
                        factor_db_id,
                        original_id,
                        qty,
                        uom,
                        factor,
                        ghg_unit,
                        apply_pct,
                        data_source,
                        data_confidence,
                        notes,
                        merged_detail_json,
                        calc_tco2e,
                    ],
                ).fetchone()
                if inserted:
                    inserted_sources += 1

            record_audit_event(
                con,
                request=None,
                actor={"email": actor},
                action="create",
                entity_type="job_emission_register_rollforward",
                entity_id=None,
                job_id=int(job_id),
                before={
                    "source_job_id": previous_job_id,
                    "source_job_number": previous_job.get("job_number"),
                },
                after={
                    "source_type": source_type_value,
                    "inserted_groups": inserted_groups,
                    "reused_groups": reused_groups,
                    "inserted_sources": inserted_sources,
                    "skipped_sources": skipped_sources,
                },
            )

            summary = _list_register(con, int(job_id), source_type_value, False).get("summary", {})

        return {
            "ok": True,
            "job_id": int(job_id),
            "source_type": source_type_value,
            "previous_job": previous_job,
            "inserted_groups": inserted_groups,
            "reused_groups": reused_groups,
            "inserted_sources": inserted_sources,
            "skipped_sources": skipped_sources,
            "summary": summary,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to roll forward emission register: {e}")
