from __future__ import annotations

import math
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query, Request

from api.auth import _current_user
from api.permissions import assert_job_access, assert_permission
from core.database import get_conn
from services.audit_log import fetch_row_dict, record_audit_event

router = APIRouter(tags=["job-custom-factors"])


def _safe_int(value: Any) -> int | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except Exception:
        return None


def _safe_float(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        out = float(text)
        if not math.isfinite(out):
            return None
        return out
    except Exception:
        return None


def _table_exists(con, table_name: str) -> bool:
    try:
        row = con.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = ? LIMIT 1",
            [table_name],
        ).fetchone()
        return bool(row)
    except Exception:
        return False


def _ensure_job_custom_factor_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_custom_factors (
          factor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          country VARCHAR,
          scope VARCHAR,
          description TEXT,
          uom VARCHAR,
          ghg_unit VARCHAR,
          source VARCHAR,
          custom_id VARCHAR,
          report_label VARCHAR,
          category VARCHAR,
          factor DOUBLE PRECISION,
          factor_year INTEGER,
          created_by VARCHAR,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_by VARCHAR,
          updated_at TIMESTAMP,
          archived BOOLEAN DEFAULT FALSE,
          archived_at TIMESTAMP,
          archived_by VARCHAR,
          is_active BOOLEAN DEFAULT TRUE
        )
        """
    )

    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS job_id INTEGER")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS country VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS scope VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS description TEXT")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS uom VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS ghg_unit VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS source VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS custom_id VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS report_label VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS category VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS factor DOUBLE PRECISION")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS factor_year INTEGER")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS created_by VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS updated_by VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS archived_by VARCHAR")
    con.execute("ALTER TABLE job_custom_factors ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE")

    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_custom_factors_job_idx
        ON job_custom_factors (job_id, archived, is_active, scope)
        """
    )


def _actor_identifier(user: dict[str, Any] | None) -> str:
    if not isinstance(user, dict):
        return "system"
    return str(
        user.get("email")
        or user.get("user_id")
        or user.get("full_name")
        or user.get("user")
        or "system"
    ).strip()


def _job_context(con, job_id: int) -> dict[str, Any]:
    row = con.execute(
        """
        SELECT job_id, job_number, title, reporting_year
        FROM jobs
        WHERE job_id = ?
        """,
        [int(job_id)],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    return {
        "job_id": _safe_int(row[0]),
        "job_number": str(row[1] or "").strip() or None,
        "job_title": str(row[2] or "").strip() or None,
        "reporting_year": _safe_int(row[3]),
    }


def _snapshot(con, job_id: int, factor_id: int) -> dict[str, Any] | None:
    return fetch_row_dict(
        con,
        "SELECT * FROM job_custom_factors WHERE factor_id = ? AND job_id = ?",
        [int(factor_id), int(job_id)],
    )


def _parse_factor_value(body: dict[str, Any]) -> float | None:
    for key in ("factor", "factor_value", "value"):
        if key in body:
            parsed = _safe_float(body.get(key))
            if parsed is not None:
                return parsed
    return None


@router.get("/jobs/{job_id}/custom-factors")
def list_job_custom_factors(
    job_id: int,
    include_archived: bool = Query(False),
    scope: str | None = Query(None),
    search: str = Query(""),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.view")
    assert_job_access(_user, int(job_id))

    try:
        with get_conn() as con:
            _ensure_job_custom_factor_schema(con)
            ctx = _job_context(con, int(job_id))

            where_clauses = ["job_id = ?"]
            params: list[Any] = [int(job_id)]

            if not include_archived:
                where_clauses.append("(archived = FALSE OR archived IS NULL)")

            if scope and str(scope).strip():
                where_clauses.append("scope = ?")
                params.append(str(scope).strip())

            search_text = str(search or "").strip().lower()
            if search_text:
                tokens = [t.strip() for t in search_text.split() if t.strip()]
                for token in tokens:
                    pattern = f"%{token}%"
                    where_clauses.append(
                        "("
                        + " OR ".join(
                            [
                                "LOWER(COALESCE(custom_id, '')) LIKE ?",
                                "LOWER(COALESCE(description, '')) LIKE ?",
                                "LOWER(COALESCE(report_label, '')) LIKE ?",
                                "LOWER(COALESCE(category, '')) LIKE ?",
                                "LOWER(COALESCE(scope, '')) LIKE ?",
                                "LOWER(COALESCE(source, '')) LIKE ?",
                                "LOWER(COALESCE(uom, '')) LIKE ?",
                                "LOWER(COALESCE(ghg_unit, '')) LIKE ?",
                            ]
                        )
                        + ")"
                    )
                    params.extend([pattern] * 8)

            df = con.execute(
                f"""
                SELECT
                  factor_id, job_id, country, scope, description, uom, ghg_unit, source,
                  custom_id, report_label, category, factor, factor_year,
                  created_by, created_at, updated_by, updated_at,
                  archived, archived_at, archived_by, is_active
                FROM job_custom_factors
                WHERE {' AND '.join(where_clauses)}
                ORDER BY scope, category, report_label, description, factor_id
                """,
                params,
            ).df()

            items: list[dict[str, Any]] = []
            if df is not None and not df.empty:
                df = df.where(df.notna(), None)
                for _, row in df.iterrows():
                    factor_id = _safe_int(row.get("factor_id"))
                    if factor_id is None:
                        continue
                    custom_id = str(row.get("custom_id") or "").strip() or f"JCF-{ctx['job_id']}-{factor_id}"
                    items.append(
                        {
                            "factor_id": int(factor_id),
                            "job_id": ctx["job_id"],
                            "job_number": ctx["job_number"],
                            "job_title": ctx["job_title"],
                            "reporting_year": ctx["reporting_year"],
                            "custom_id": custom_id,
                            "country": str(row.get("country") or ""),
                            "scope": str(row.get("scope") or ""),
                            "description": str(row.get("description") or ""),
                            "report_label": str(row.get("report_label") or "").strip() or None,
                            "category": str(row.get("category") or "").strip() or None,
                            "uom": str(row.get("uom") or ""),
                            "ghg_unit": str(row.get("ghg_unit") or ""),
                            "source": str(row.get("source") or ""),
                            "factor": _safe_float(row.get("factor")),
                            "factor_year": _safe_int(row.get("factor_year")),
                            "is_active": bool(row.get("is_active")) if row.get("is_active") is not None else True,
                            "archived": bool(row.get("archived")) if row.get("archived") is not None else False,
                            "created_by": str(row.get("created_by")) if row.get("created_by") else None,
                            "created_at": str(row.get("created_at")) if row.get("created_at") else None,
                            "updated_by": str(row.get("updated_by")) if row.get("updated_by") else None,
                            "updated_at": str(row.get("updated_at")) if row.get("updated_at") else None,
                            "archived_at": str(row.get("archived_at")) if row.get("archived_at") else None,
                            "archived_by": str(row.get("archived_by")) if row.get("archived_by") else None,
                        }
                    )

            return {
                "job_id": ctx["job_id"],
                "job_number": ctx["job_number"],
                "job_title": ctx["job_title"],
                "reporting_year": ctx["reporting_year"],
                "items": items,
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list job custom factors: {e}")


@router.post("/jobs/{job_id}/custom-factors")
def create_job_custom_factor(
    request: Request,
    job_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    actor = _actor_identifier(_user)

    description = str(body.get("description") or "").strip()
    scope = str(body.get("scope") or "").strip()
    if not description:
        raise HTTPException(status_code=400, detail="Description is required")
    if not scope:
        raise HTTPException(status_code=400, detail="Scope is required")

    factor = _parse_factor_value(body)
    if factor is None:
        raise HTTPException(status_code=400, detail="Factor value is required")

    try:
        with get_conn(autocommit=False) as con:
            _ensure_job_custom_factor_schema(con)
            ctx = _job_context(con, int(job_id))
            factor_year = _safe_int(body.get("factor_year")) or ctx["reporting_year"]
            custom_id = str(body.get("custom_id") or "").strip() or None

            row = con.execute(
                """
                INSERT INTO job_custom_factors
                (job_id, country, scope, description, uom, ghg_unit, source, custom_id,
                 report_label, category, factor, factor_year, is_active, created_by)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING factor_id
                """,
                [
                    int(job_id),
                    body.get("country"),
                    scope,
                    description,
                    body.get("uom"),
                    body.get("ghg_unit"),
                    body.get("source"),
                    custom_id,
                    body.get("report_label"),
                    body.get("category"),
                    factor,
                    factor_year,
                    bool(body.get("is_active", True)),
                    actor,
                ],
            ).fetchone()

            factor_id = _safe_int(row[0] if row else None)
            if factor_id is None:
                raise HTTPException(status_code=500, detail="Failed to create job custom factor")

            if not custom_id:
                custom_id = f"JCF-{int(job_id)}-{int(factor_id)}"
                con.execute(
                    "UPDATE job_custom_factors SET custom_id = ? WHERE factor_id = ? AND job_id = ?",
                    [custom_id, int(factor_id), int(job_id)],
                )

            after = _snapshot(con, int(job_id), int(factor_id))
            record_audit_event(
                con,
                request=request,
                actor=_user,
                action="create",
                entity_type="job_custom_factor",
                entity_id=int(factor_id),
                job_id=int(job_id),
                after=after,
                metadata={"scope": scope, "custom_id": custom_id, "factor_year": factor_year},
            )

            return {"ok": True, "factor_id": int(factor_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create job custom factor: {e}")


@router.put("/jobs/{job_id}/custom-factors/{factor_id}")
def update_job_custom_factor(
    request: Request,
    job_id: int,
    factor_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    actor = _actor_identifier(_user)

    description = str(body.get("description") or "").strip()
    scope = str(body.get("scope") or "").strip()
    if not description:
        raise HTTPException(status_code=400, detail="Description is required")
    if not scope:
        raise HTTPException(status_code=400, detail="Scope is required")

    factor = _parse_factor_value(body)
    if factor is None:
        raise HTTPException(status_code=400, detail="Factor value is required")

    try:
        with get_conn(autocommit=False) as con:
            _ensure_job_custom_factor_schema(con)
            before = _snapshot(con, int(job_id), int(factor_id))
            if not before:
                raise HTTPException(status_code=404, detail="Job custom factor not found")

            factor_year = _safe_int(body.get("factor_year")) or _safe_int(before.get("factor_year")) or None
            custom_id = str(body.get("custom_id") or "").strip() or None

            con.execute(
                """
                UPDATE job_custom_factors
                SET country = ?,
                    scope = ?,
                    description = ?,
                    uom = ?,
                    ghg_unit = ?,
                    source = ?,
                    custom_id = ?,
                    report_label = ?,
                    category = ?,
                    factor = ?,
                    factor_year = ?,
                    is_active = ?,
                    updated_by = ?,
                    updated_at = CURRENT_TIMESTAMP
                WHERE job_id = ? AND factor_id = ?
                """,
                [
                    body.get("country"),
                    scope,
                    description,
                    body.get("uom"),
                    body.get("ghg_unit"),
                    body.get("source"),
                    custom_id,
                    body.get("report_label"),
                    body.get("category"),
                    factor,
                    factor_year,
                    bool(body.get("is_active", True)),
                    actor,
                    int(job_id),
                    int(factor_id),
                ],
            )

            if not custom_id:
                custom_id = f"JCF-{int(job_id)}-{int(factor_id)}"
                con.execute(
                    "UPDATE job_custom_factors SET custom_id = ? WHERE factor_id = ? AND job_id = ?",
                    [custom_id, int(factor_id), int(job_id)],
                )

            after = _snapshot(con, int(job_id), int(factor_id))
            record_audit_event(
                con,
                request=request,
                actor=_user,
                action="update",
                entity_type="job_custom_factor",
                entity_id=int(factor_id),
                job_id=int(job_id),
                before=before,
                after=after,
                metadata={"scope": scope, "custom_id": custom_id, "factor_year": factor_year},
            )

            return {"ok": True, "factor_id": int(factor_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update job custom factor: {e}")


@router.patch("/jobs/{job_id}/custom-factors/{factor_id}/archive")
def archive_job_custom_factor(
    request: Request,
    job_id: int,
    factor_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    actor = _actor_identifier(_user)

    archived = bool(body.get("archived", True))

    try:
        with get_conn(autocommit=False) as con:
            _ensure_job_custom_factor_schema(con)
            before = _snapshot(con, int(job_id), int(factor_id))
            if not before:
                raise HTTPException(status_code=404, detail="Job custom factor not found")

            if archived:
                con.execute(
                    """
                    UPDATE job_custom_factors
                    SET archived = TRUE,
                        is_active = FALSE,
                        archived_at = CURRENT_TIMESTAMP,
                        archived_by = ?,
                        updated_by = ?,
                        updated_at = CURRENT_TIMESTAMP
                    WHERE job_id = ? AND factor_id = ?
                    """,
                    [actor, actor, int(job_id), int(factor_id)],
                )
            else:
                con.execute(
                    """
                    UPDATE job_custom_factors
                    SET archived = FALSE,
                        is_active = TRUE,
                        archived_at = NULL,
                        archived_by = NULL,
                        updated_by = ?,
                        updated_at = CURRENT_TIMESTAMP
                    WHERE job_id = ? AND factor_id = ?
                    """,
                    [actor, int(job_id), int(factor_id)],
                )

            after = _snapshot(con, int(job_id), int(factor_id))
            record_audit_event(
                con,
                request=request,
                actor=_user,
                action="archive" if archived else "restore",
                entity_type="job_custom_factor",
                entity_id=int(factor_id),
                job_id=int(job_id),
                before=before,
                after=after,
            )

            return {"ok": True, "archived": archived, "factor_id": int(factor_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update job custom factor archive state: {e}")

