from __future__ import annotations

import io
import re
from datetime import datetime, timezone
from uuid import uuid4
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from api.auth import _current_user
from api.permissions import assert_job_access
from core.database import get_conn
from services.audit_log import fetch_row_dict
from services.company_profile import company_footer_text, get_company_profile
from services.emissions_reporting import exact_job_total_emissions

router = APIRouter()


def _ensure_job_emissions_certificate_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emissions_certificates (
          certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          org_id VARCHAR NOT NULL,
          client_db_id INTEGER NOT NULL,
          client_name VARCHAR NOT NULL,
          job_number VARCHAR,
          reporting_year INTEGER NOT NULL,
          emissions NUMERIC NOT NULL DEFAULT 0,
          certificate_number VARCHAR NOT NULL,
          issued_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """
    )
    con.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS job_emissions_certificates_job_year_org_idx "
        "ON job_emissions_certificates (job_id, reporting_year, org_id)"
    )
    con.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS job_emissions_certificates_number_idx "
        "ON job_emissions_certificates (certificate_number)"
    )
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS org_id VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS client_db_id INTEGER")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS client_name VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS job_number VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS reporting_year INTEGER")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS emissions NUMERIC DEFAULT 0")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS certificate_number VARCHAR")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP DEFAULT NOW()")
    con.execute("ALTER TABLE job_emissions_certificates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()")


def _certificate_filename(job_number: str | None, certificate_number: str) -> str:
    job_stub = re.sub(r"[^A-Za-z0-9._-]+", "-", str(job_number or "job").strip()) or "job"
    cert_stub = re.sub(r"[^A-Za-z0-9._-]+", "-", str(certificate_number or "certificate").strip()) or "certificate"
    return f"{job_stub}-{cert_stub}-carbon-emissions-certificate.pdf"


def _coerce_reporting_year(row: dict[str, Any]) -> int:
    for key in ("reporting_year",):
        value = row.get(key)
        if value is None:
            continue
        try:
            year = int(float(value))
            if year > 1900:
                return year
        except Exception:
            pass
    reporting_period_end = row.get("reporting_period_end")
    if reporting_period_end:
        try:
            year = datetime.fromisoformat(str(reporting_period_end)).year
            if year > 1900:
                return year
        except Exception:
            pass
    return datetime.now(timezone.utc).year


def _serialize_certificate_row(row: dict[str, Any]) -> dict[str, Any]:
    emissions_value = row.get("emissions")
    issued_at = row.get("issued_at")
    updated_at = row.get("updated_at")
    return {
        "certificate_id": int(row["certificate_id"]) if row.get("certificate_id") is not None else None,
        "job_id": int(row["job_id"]) if row.get("job_id") is not None else None,
        "org_id": str(row.get("org_id") or "").strip() or None,
        "client_db_id": int(row["client_db_id"]) if row.get("client_db_id") is not None else None,
        "client_name": str(row.get("client_name") or "").strip() or "Client",
        "job_number": str(row.get("job_number") or "").strip() or None,
        "reporting_year": int(row["reporting_year"]) if row.get("reporting_year") is not None else None,
        "emissions": float(emissions_value or 0.0),
        "certificate_number": str(row.get("certificate_number") or "").strip() or None,
        "issued_at": issued_at.isoformat() if hasattr(issued_at, "isoformat") else (str(issued_at) if issued_at else None),
        "updated_at": updated_at.isoformat() if hasattr(updated_at, "isoformat") else (str(updated_at) if updated_at else None),
        "verified_by": "Net Zero International",
        "download_url": f"/jobs/{int(row['job_id'])}/emissions-certificate/pdf" if row.get("job_id") is not None else None,
    }


def _load_job_certificate_context(con, job_id: int, current_user: dict[str, Any]) -> dict[str, Any]:
    assert_job_access(current_user, int(job_id))
    _ensure_job_emissions_certificate_schema(con)

    job_row = fetch_row_dict(
        con,
        """
        SELECT
          j.job_id,
          j.job_number,
          COALESCE(
            j.reporting_year,
            EXTRACT(YEAR FROM j.reporting_period_end)
          ) AS reporting_year,
          j.reporting_period_end,
          j.client_db_id,
          j.org_id,
          c.client_name
        FROM jobs j
        LEFT JOIN clients c ON c.db_id = j.client_db_id
        WHERE j.job_id = ?
        """,
        [int(job_id)],
    )
    if not job_row:
        raise HTTPException(status_code=404, detail="Job not found")

    org_id = str(job_row.get("org_id") or current_user.get("org_id") or "").strip()
    if not org_id:
        raise HTTPException(status_code=403, detail="Organisation context required")

    reporting_year = _coerce_reporting_year(job_row)
    existing = fetch_row_dict(
        con,
        """
        SELECT
          certificate_id, job_id, org_id, client_db_id, client_name, job_number,
          reporting_year, emissions, certificate_number, issued_at, updated_at
        FROM job_emissions_certificates
        WHERE job_id = ? AND reporting_year = ? AND org_id = ?
        LIMIT 1
        """,
        [int(job_id), int(reporting_year), org_id],
    )
    if existing:
        return _serialize_certificate_row(existing)

    emissions = exact_job_total_emissions(con, int(job_id))
    temp_number = f"PENDING-{uuid4().hex}"
    inserted = con.execute(
        """
        INSERT INTO job_emissions_certificates (
          job_id, org_id, client_db_id, client_name, job_number, reporting_year,
          emissions, certificate_number, issued_at, updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
        RETURNING certificate_id
        """,
        [
            int(job_id),
            org_id,
            int(job_row["client_db_id"]) if job_row.get("client_db_id") is not None else 0,
            str(job_row.get("client_name") or "Client").strip() or "Client",
            str(job_row.get("job_number") or f"Job-{job_id}").strip() or f"Job-{job_id}",
            int(reporting_year),
            float(emissions or 0.0),
            temp_number,
        ],
    ).fetchone()
    if not inserted:
        raise HTTPException(status_code=500, detail="Failed to issue certificate")

    certificate_id = int(inserted[0])
    certificate_number = f"NZI-EC-{int(reporting_year)}-{certificate_id:06d}"
    con.execute(
        """
        UPDATE job_emissions_certificates
        SET certificate_number = ?, emissions = ?, updated_at = NOW()
        WHERE certificate_id = ?
        """,
        [certificate_number, float(emissions or 0.0), certificate_id],
    )
    issued = fetch_row_dict(
        con,
        """
        SELECT
          certificate_id, job_id, org_id, client_db_id, client_name, job_number,
          reporting_year, emissions, certificate_number, issued_at, updated_at
        FROM job_emissions_certificates
        WHERE certificate_id = ?
        LIMIT 1
        """,
        [certificate_id],
    )
    if not issued:
        raise HTTPException(status_code=500, detail="Failed to load certificate")
    return _serialize_certificate_row(issued)


def _render_certificate_pdf_bytes(certificate: dict[str, Any], company_profile: dict[str, Any]) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=20 * mm,
        bottomMargin=18 * mm,
        title=f"Carbon Emissions Certificate {certificate.get('certificate_number') or ''}",
        author="Net Zero International",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CertificateTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#1f2937"),
        spaceAfter=6 * mm,
    )
    subtitle_style = ParagraphStyle(
        "CertificateSubtitle",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#4b5563"),
        spaceAfter=4 * mm,
    )
    body_style = ParagraphStyle(
        "CertificateBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#111827"),
    )
    label_style = ParagraphStyle(
        "CertificateLabel",
        parent=styles["Normal"],
        fontSize=10,
        leading=12,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#374151"),
    )

    company_name = str(
        company_profile.get("company_display_name")
        or company_profile.get("company_legal_name")
        or "Net Zero International"
    )
    client_name = str(certificate.get("client_name") or "Client")
    job_number = str(certificate.get("job_number") or f"Job {certificate.get('job_id')}")
    certificate_number = str(certificate.get("certificate_number") or "NZI-EC-000000")
    reporting_year = certificate.get("reporting_year")
    emissions = float(certificate.get("emissions") or 0.0)
    issued_at = certificate.get("issued_at")
    issued_text = issued_at[:10] if isinstance(issued_at, str) and len(issued_at) >= 10 else str(issued_at or "")

    story: list[Any] = [
        Paragraph("Carbon Emissions Certificate", title_style),
        Paragraph(f"Certificate No. {certificate_number}", subtitle_style),
        Paragraph(
            f"This certificate confirms the verified carbon emissions associated with {client_name}.",
            body_style,
        ),
        Spacer(1, 4 * mm),
    ]

    detail_rows = [
        [Paragraph("Client", label_style), Paragraph(client_name, body_style)],
        [Paragraph("Job", label_style), Paragraph(job_number, body_style)],
        [Paragraph("Reporting Year", label_style), Paragraph(str(reporting_year or ""), body_style)],
        [Paragraph("Emissions", label_style), Paragraph(f"{emissions:,.2f} tCO2e", body_style)],
        [Paragraph("Issued", label_style), Paragraph(issued_text or "On issue", body_style)],
    ]
    detail_table = Table(detail_rows, colWidths=[42 * mm, 120 * mm], hAlign="LEFT")
    detail_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f9fafb")),
                ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#d1d5db")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    story.extend(
        [
            detail_table,
            Spacer(1, 8 * mm),
            Paragraph(
                "This certificate has been verified by Net Zero International and may be downloaded for client records.",
                body_style,
            ),
            Spacer(1, 10 * mm),
            Paragraph("Verified by Net Zero International", ParagraphStyle(
                "CertificateSignoff",
                parent=styles["Heading3"],
                fontName="Helvetica-Bold",
                fontSize=13,
                leading=16,
                textColor=colors.HexColor("#111827"),
            )),
            Spacer(1, 2 * mm),
            Paragraph(
                f"Authorised signatory for {company_name}",
                ParagraphStyle(
                    "CertificateSignature",
                    parent=styles["Normal"],
                    fontSize=10.5,
                    leading=13,
                    textColor=colors.HexColor("#4b5563"),
                ),
            ),
            Spacer(1, 5 * mm),
            Paragraph("______________________________", body_style),
            Paragraph(company_name, ParagraphStyle(
                "CertificateCompany",
                parent=styles["Normal"],
                fontSize=10.5,
                leading=13,
                textColor=colors.HexColor("#111827"),
            )),
        ]
    )

    footer_text = company_footer_text(company_profile) or company_name

    def _footer(canvas_obj, _doc) -> None:
        canvas_obj.saveState()
        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.setFillColor(colors.HexColor("#6b7280"))
        canvas_obj.drawCentredString(A4[0] / 2.0, 8 * mm, footer_text[:180])
        canvas_obj.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


@router.get("/jobs/{job_id}/emissions-certificate")
def get_job_emissions_certificate(job_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        certificate = _load_job_certificate_context(con, int(job_id), _user)
    return certificate


@router.get("/jobs/{job_id}/emissions-certificate/pdf")
def get_job_emissions_certificate_pdf(job_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        certificate = _load_job_certificate_context(con, int(job_id), _user)
        company_profile = get_company_profile(con)
        pdf_bytes = _render_certificate_pdf_bytes(certificate, company_profile)

    filename = _certificate_filename(certificate.get("job_number"), certificate.get("certificate_number") or "certificate")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
