from __future__ import annotations

import json
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query

from api.auth import _current_user
from api.permissions import assert_job_access, assert_permission
from core.database import get_conn
from services.tenancy import require_org

router = APIRouter(tags=["job-training"])


def _actor(user: dict[str, str]) -> str:
    return str(user.get("email") or user.get("user_id") or "system").strip() or "system"


def _clean_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _clean_int(value: Any) -> int | None:
    if value in (None, ""):
        return None
    try:
        return int(value)
    except Exception:
        return None


def _clean_float(value: Any) -> float | None:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except Exception:
        return None


def _clean_bool(value: Any, default: bool = True) -> bool:
    if value in (None, ""):
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def _ensure_tables(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_training_details (
          job_id INTEGER PRIMARY KEY REFERENCES jobs(job_id) ON DELETE CASCADE,
          training_date DATE,
          delivery_format TEXT,
          topic TEXT,
          audience TEXT,
          attendee_count INTEGER,
          session_duration_hours NUMERIC(10,2),
          materials_link TEXT,
          location TEXT,
          notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by TEXT,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by TEXT
        )
        """
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS training_products (
          training_product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id VARCHAR NOT NULL,
          product_code VARCHAR,
          product_name VARCHAR NOT NULL,
          description TEXT,
          default_hours NUMERIC(10,2),
          default_delivery_mode VARCHAR,
          default_capacity INTEGER,
          default_min_attendees INTEGER,
          certificate_policy TEXT,
          default_documents_json TEXT,
          is_active BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_products_org_active ON training_products (org_id, is_active, product_name)"
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS training_course_runs (
          training_course_run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id VARCHAR NOT NULL,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          training_product_id INTEGER REFERENCES training_products(training_product_id) ON DELETE SET NULL,
          run_name VARCHAR,
          course_code VARCHAR,
          total_hours NUMERIC(10,2),
          delivery_mode VARCHAR,
          capacity INTEGER,
          min_attendees INTEGER,
          status VARCHAR NOT NULL DEFAULT 'draft',
          workflow_stage_key VARCHAR NOT NULL DEFAULT 'setup',
          start_date DATE,
          end_date DATE,
          venue_name VARCHAR,
          venue_address TEXT,
          online_meeting_url TEXT,
          online_meeting_id VARCHAR,
          online_passcode VARCHAR,
          notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_course_runs_job ON training_course_runs (org_id, job_id, status, start_date)"
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_course_runs_product ON training_course_runs (training_product_id)"
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS training_bookings (
          training_booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id VARCHAR NOT NULL,
          training_course_run_id INTEGER NOT NULL REFERENCES training_course_runs(training_course_run_id) ON DELETE CASCADE,
          client_db_id INTEGER,
          contact_id INTEGER,
          participant_type VARCHAR NOT NULL DEFAULT 'external_individual',
          booking_source VARCHAR NOT NULL DEFAULT 'manual',
          person_name VARCHAR NOT NULL,
          person_email VARCHAR,
          person_phone VARCHAR,
          billing_status VARCHAR NOT NULL DEFAULT 'pending',
          attendance_status VARCHAR NOT NULL DEFAULT 'booked',
          special_requirements TEXT,
          consent_status VARCHAR NOT NULL DEFAULT 'unknown',
          notes TEXT,
          entitlement_id INTEGER,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_bookings_run ON training_bookings (org_id, training_course_run_id, attendance_status, person_name)"
    )
    con.execute("CREATE INDEX IF NOT EXISTS ix_training_bookings_client ON training_bookings (client_db_id)")
    con.execute("CREATE INDEX IF NOT EXISTS ix_training_bookings_entitlement ON training_bookings (entitlement_id)")

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS training_entitlements (
          training_entitlement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id VARCHAR NOT NULL,
          source_job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          source_job_number VARCHAR,
          source_client_db_id INTEGER,
          entitlement_type VARCHAR NOT NULL DEFAULT 'free_place',
          status VARCHAR NOT NULL DEFAULT 'available',
          allocated_to_booking_id INTEGER,
          reserved_at TIMESTAMP,
          consumed_at TIMESTAMP,
          expires_at TIMESTAMP,
          notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_entitlements_org_status ON training_entitlements (org_id, status, source_job_id)"
    )
    con.execute("CREATE INDEX IF NOT EXISTS ix_training_entitlements_source_job ON training_entitlements (source_job_id)")
    con.execute("CREATE INDEX IF NOT EXISTS ix_training_entitlements_allocated ON training_entitlements (allocated_to_booking_id)")

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS training_course_sessions (
          training_course_session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id VARCHAR NOT NULL,
          training_course_run_id INTEGER NOT NULL REFERENCES training_course_runs(training_course_run_id) ON DELETE CASCADE,
          session_title VARCHAR,
          session_date DATE,
          start_time TIME,
          end_time TIME,
          session_hours NUMERIC(10,2),
          delivery_mode VARCHAR,
          venue_name VARCHAR,
          venue_address TEXT,
          online_meeting_url TEXT,
          online_meeting_id VARCHAR,
          online_passcode VARCHAR,
          status VARCHAR NOT NULL DEFAULT 'scheduled',
          notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_course_sessions_run ON training_course_sessions (org_id, training_course_run_id, session_date, start_time)"
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_course_sessions_status ON training_course_sessions (org_id, status)"
    )

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS training_session_attendance (
          training_session_attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          org_id VARCHAR NOT NULL,
          training_course_session_id INTEGER NOT NULL REFERENCES training_course_sessions(training_course_session_id) ON DELETE CASCADE,
          training_booking_id INTEGER NOT NULL REFERENCES training_bookings(training_booking_id) ON DELETE CASCADE,
          attendance_status VARCHAR NOT NULL DEFAULT 'booked',
          attendance_minutes INTEGER,
          notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR,
          UNIQUE (training_course_session_id, training_booking_id)
        )
        """
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_session_attendance_session ON training_session_attendance (org_id, training_course_session_id, attendance_status)"
    )
    con.execute(
        "CREATE INDEX IF NOT EXISTS ix_training_session_attendance_booking ON training_session_attendance (training_booking_id)"
    )


def _detail_payload(row) -> dict[str, Any]:
    if not row:
        return {
            "job_id": None,
            "training_date": None,
            "delivery_format": None,
            "topic": None,
            "audience": None,
            "attendee_count": None,
            "session_duration_hours": None,
            "materials_link": None,
            "location": None,
            "notes": None,
        }
    return {
        "job_id": int(row[0]) if row[0] is not None else None,
        "training_date": str(row[1]) if row[1] else None,
        "delivery_format": row[2],
        "topic": row[3],
        "audience": row[4],
        "attendee_count": int(row[5]) if row[5] is not None else None,
        "session_duration_hours": float(row[6]) if row[6] is not None else None,
        "materials_link": row[7],
        "location": row[8],
        "notes": row[9],
    }


def _product_payload(row) -> dict[str, Any]:
    return {
        "training_product_id": int(row[0]),
        "org_id": row[1],
        "product_code": row[2],
        "product_name": row[3],
        "description": row[4],
        "default_hours": float(row[5]) if row[5] is not None else None,
        "default_delivery_mode": row[6],
        "default_capacity": int(row[7]) if row[7] is not None else None,
        "default_min_attendees": int(row[8]) if row[8] is not None else None,
        "certificate_policy": row[9],
        "default_documents_json": row[10],
        "is_active": bool(row[11]),
        "created_at": str(row[12]) if row[12] else None,
        "created_by": row[13],
        "updated_at": str(row[14]) if row[14] else None,
        "updated_by": row[15],
    }


def _run_payload(row, bookings: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    payload = {
        "training_course_run_id": int(row[0]),
        "org_id": row[1],
        "job_id": int(row[2]),
        "training_product_id": int(row[3]) if row[3] is not None else None,
        "product_name": row[4],
        "run_name": row[5],
        "course_code": row[6],
        "total_hours": float(row[7]) if row[7] is not None else None,
        "delivery_mode": row[8],
        "capacity": int(row[9]) if row[9] is not None else None,
        "min_attendees": int(row[10]) if row[10] is not None else None,
        "status": row[11],
        "workflow_stage_key": row[12],
        "start_date": str(row[13]) if row[13] else None,
        "end_date": str(row[14]) if row[14] else None,
        "venue_name": row[15],
        "venue_address": row[16],
        "online_meeting_url": row[17],
        "online_meeting_id": row[18],
        "online_passcode": row[19],
        "notes": row[20],
        "booking_count": int(row[21]) if row[21] is not None else 0,
        "confirmed_count": int(row[22]) if row[22] is not None else 0,
        "created_at": str(row[23]) if row[23] else None,
        "created_by": row[24],
        "updated_at": str(row[25]) if row[25] else None,
        "updated_by": row[26],
        "bookings": bookings or [],
    }
    payload["available_seats"] = (
        max(payload["capacity"] - payload["booking_count"], 0)
        if payload["capacity"] is not None and payload["booking_count"] is not None
        else None
    )
    return payload


def _booking_payload(row) -> dict[str, Any]:
    return {
        "training_booking_id": int(row[0]),
        "org_id": row[1],
        "training_course_run_id": int(row[2]),
        "client_db_id": int(row[3]) if row[3] is not None else None,
        "contact_id": int(row[4]) if row[4] is not None else None,
        "participant_type": row[5],
        "booking_source": row[6],
        "person_name": row[7],
        "person_email": row[8],
        "person_phone": row[9],
        "billing_status": row[10],
        "attendance_status": row[11],
        "special_requirements": row[12],
        "consent_status": row[13],
        "notes": row[14],
        "entitlement_id": int(row[15]) if row[15] is not None else None,
        "client_name": row[16],
        "source_job_number": row[17],
        "entitlement_status": row[18],
        "allocated_booking_name": row[19],
        "created_at": str(row[20]) if row[20] else None,
        "created_by": row[21],
        "updated_at": str(row[22]) if row[22] else None,
        "updated_by": row[23],
    }


def _entitlement_payload(row) -> dict[str, Any]:
    return {
        "training_entitlement_id": int(row[0]),
        "org_id": row[1],
        "source_job_id": int(row[2]) if row[2] is not None else None,
        "source_job_number": row[3],
        "source_client_db_id": int(row[4]) if row[4] is not None else None,
        "entitlement_type": row[5],
        "status": row[6],
        "allocated_to_booking_id": int(row[7]) if row[7] is not None else None,
        "reserved_at": str(row[8]) if row[8] else None,
        "consumed_at": str(row[9]) if row[9] else None,
        "expires_at": str(row[10]) if row[10] else None,
        "notes": row[11],
        "source_job_client_name": row[12],
        "allocated_booking_name": row[13],
        "created_at": str(row[14]) if row[14] else None,
        "created_by": row[15],
        "updated_at": str(row[16]) if row[16] else None,
        "updated_by": row[17],
    }


def _attendance_payload(row) -> dict[str, Any]:
    return {
        "training_session_attendance_id": int(row[0]),
        "org_id": row[1],
        "training_course_session_id": int(row[2]),
        "training_booking_id": int(row[3]),
        "attendance_status": row[4],
        "attendance_minutes": int(row[5]) if row[5] is not None else None,
        "notes": row[6],
        "person_name": row[7],
        "person_email": row[8],
        "client_name": row[9],
        "booking_source": row[10],
        "participant_type": row[11],
        "booking_attendance_status": row[12],
        "entitlement_id": int(row[13]) if row[13] is not None else None,
        "created_at": str(row[14]) if row[14] else None,
        "created_by": row[15],
        "updated_at": str(row[16]) if row[16] else None,
        "updated_by": row[17],
    }


def _session_payload(row, attendance: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    return {
        "training_course_session_id": int(row[0]),
        "org_id": row[1],
        "training_course_run_id": int(row[2]),
        "session_title": row[3],
        "session_date": str(row[4]) if row[4] else None,
        "start_time": str(row[5]) if row[5] else None,
        "end_time": str(row[6]) if row[6] else None,
        "session_hours": float(row[7]) if row[7] is not None else None,
        "delivery_mode": row[8],
        "venue_name": row[9],
        "venue_address": row[10],
        "online_meeting_url": row[11],
        "online_meeting_id": row[12],
        "online_passcode": row[13],
        "status": row[14],
        "notes": row[15],
        "attendance_count": int(row[16]) if row[16] is not None else 0,
        "attended_count": int(row[17]) if row[17] is not None else 0,
        "created_at": str(row[18]) if row[18] else None,
        "created_by": row[19],
        "updated_at": str(row[20]) if row[20] else None,
        "updated_by": row[21],
        "attendance": attendance or [],
    }


def _get_training_details(con, job_id: int) -> dict[str, Any]:
    row = con.execute(
        """
        SELECT job_id, training_date, delivery_format, topic, audience, attendee_count,
               session_duration_hours, materials_link, location, notes
        FROM job_training_details
        WHERE job_id = ?
        """,
        [int(job_id)],
    ).fetchone()
    return _detail_payload(row)


def _resolve_training_product(con, org_id: str, product_id: int | None) -> dict[str, Any] | None:
    if product_id is None:
        return None
    row = con.execute(
        """
        SELECT training_product_id, org_id, product_code, product_name, description, default_hours,
               default_delivery_mode, default_capacity, default_min_attendees, certificate_policy,
               default_documents_json, is_active, created_at, created_by, updated_at, updated_by
        FROM training_products
        WHERE training_product_id = ? AND org_id = ?
        """,
        [int(product_id), org_id],
    ).fetchone()
    return _product_payload(row) if row else None


def _list_training_products(con, org_id: str, include_inactive: bool = False) -> list[dict[str, Any]]:
    sql = """
        SELECT training_product_id, org_id, product_code, product_name, description, default_hours,
               default_delivery_mode, default_capacity, default_min_attendees, certificate_policy,
               default_documents_json, is_active, created_at, created_by, updated_at, updated_by
        FROM training_products
        WHERE org_id = ?
    """
    params: list[Any] = [org_id]
    if not include_inactive:
        sql += " AND is_active = TRUE"
    sql += " ORDER BY product_name ASC, training_product_id DESC"
    rows = con.execute(sql, params).fetchall()
    return [_product_payload(row) for row in rows]


def _get_course_run_rows(con, org_id: str, job_id: int) -> list[dict[str, Any]]:
    run_rows = con.execute(
        """
        SELECT r.training_course_run_id, r.org_id, r.job_id, r.training_product_id, p.product_name,
               r.run_name, r.course_code, r.total_hours, r.delivery_mode, r.capacity, r.min_attendees,
               r.status, r.workflow_stage_key, r.start_date, r.end_date, r.venue_name, r.venue_address,
               r.online_meeting_url, r.online_meeting_id, r.online_passcode, r.notes,
               COALESCE(counts.booking_count, 0), COALESCE(counts.confirmed_count, 0),
               r.created_at, r.created_by, r.updated_at, r.updated_by
        FROM training_course_runs r
        LEFT JOIN training_products p ON p.training_product_id = r.training_product_id
        LEFT JOIN (
          SELECT training_course_run_id,
                 COUNT(*) AS booking_count,
                 COUNT(*) FILTER (WHERE attendance_status IN ('booked', 'confirmed', 'attended')) AS confirmed_count
          FROM training_bookings
          WHERE org_id = ?
          GROUP BY training_course_run_id
        ) counts ON counts.training_course_run_id = r.training_course_run_id
        WHERE r.org_id = ? AND r.job_id = ?
        ORDER BY COALESCE(r.start_date, CURRENT_DATE), r.training_course_run_id DESC
        """,
        [org_id, org_id, int(job_id)],
    ).fetchall()
    if not run_rows:
        return []

    run_ids = [int(row[0]) for row in run_rows]
    placeholders = ",".join(["?"] * len(run_ids))
    booking_rows = con.execute(
        f"""
        SELECT b.training_booking_id, b.org_id, b.training_course_run_id, b.client_db_id, b.contact_id,
               b.participant_type, b.booking_source, b.person_name, b.person_email, b.person_phone,
               b.billing_status, b.attendance_status, b.special_requirements, b.consent_status,
               b.notes, b.entitlement_id, c.client_name, e.source_job_number,
               e.status, COALESCE(b2.person_name, ''),
               b.created_at, b.created_by, b.updated_at, b.updated_by
        FROM training_bookings b
        LEFT JOIN clients c ON c.db_id = b.client_db_id
        LEFT JOIN training_entitlements e ON e.training_entitlement_id = b.entitlement_id
        LEFT JOIN training_bookings b2 ON b2.training_booking_id = e.allocated_to_booking_id
        WHERE b.org_id = ? AND b.training_course_run_id IN ({placeholders})
        ORDER BY b.training_course_run_id, b.person_name, b.training_booking_id
        """,
        [org_id, *run_ids],
    ).fetchall()
    bookings_by_run: dict[int, list[dict[str, Any]]] = {run_id: [] for run_id in run_ids}
    for row in booking_rows:
        bookings_by_run.setdefault(int(row[2]), []).append(_booking_payload(row))

    payload: list[dict[str, Any]] = []
    for row in run_rows:
        run_payload = _run_payload(row, bookings_by_run.get(int(row[0]), []))
        payload.append(run_payload)
    return payload


def _get_available_entitlements(con, org_id: str) -> list[dict[str, Any]]:
    rows = con.execute(
        """
        SELECT e.training_entitlement_id, e.org_id, e.source_job_id, COALESCE(e.source_job_number, j.job_number),
               e.source_client_db_id, e.entitlement_type, e.status, e.allocated_to_booking_id,
               e.reserved_at, e.consumed_at, e.expires_at, e.notes,
               c.client_name, COALESCE(b.person_name, ''),
               e.created_at, e.created_by, e.updated_at, e.updated_by
        FROM training_entitlements e
        LEFT JOIN jobs j ON j.job_id = e.source_job_id
        LEFT JOIN clients c ON c.db_id = e.source_client_db_id
        LEFT JOIN training_bookings b ON b.training_booking_id = e.allocated_to_booking_id
        WHERE e.org_id = ? AND e.status IN ('available', 'reserved')
        ORDER BY CASE e.status WHEN 'available' THEN 0 WHEN 'reserved' THEN 1 ELSE 2 END,
                 e.training_entitlement_id DESC
        """,
        [org_id],
    ).fetchall()
    return [_entitlement_payload(row) for row in rows]


def _get_training_session_attendance(con, org_id: str, session_id: int) -> list[dict[str, Any]]:
    rows = con.execute(
        """
        SELECT a.training_session_attendance_id, a.org_id, a.training_course_session_id, a.training_booking_id,
               a.attendance_status, a.attendance_minutes, a.notes, b.person_name, b.person_email,
               c.client_name, b.booking_source, b.participant_type, b.attendance_status,
               b.entitlement_id, a.created_at, a.created_by, a.updated_at, a.updated_by
        FROM training_session_attendance a
        JOIN training_bookings b ON b.training_booking_id = a.training_booking_id
        LEFT JOIN clients c ON c.db_id = b.client_db_id
        WHERE a.org_id = ? AND a.training_course_session_id = ?
        ORDER BY b.person_name, a.training_session_attendance_id
        """,
        [org_id, int(session_id)],
    ).fetchall()
    return [_attendance_payload(row) for row in rows]


def _get_training_course_sessions(con, org_id: str, job_id: int) -> list[dict[str, Any]]:
    rows = con.execute(
        """
        SELECT s.training_course_session_id, s.org_id, s.training_course_run_id, s.session_title, s.session_date,
               s.start_time, s.end_time, s.session_hours, s.delivery_mode, s.venue_name, s.venue_address,
               s.online_meeting_url, s.online_meeting_id, s.online_passcode, s.status, s.notes,
               COALESCE(counts.attendance_count, 0), COALESCE(counts.attended_count, 0),
               s.created_at, s.created_by, s.updated_at, s.updated_by
        FROM training_course_sessions s
        LEFT JOIN (
          SELECT training_course_session_id,
                 COUNT(*) AS attendance_count,
                 COUNT(*) FILTER (WHERE attendance_status = 'attended') AS attended_count
          FROM training_session_attendance
          WHERE org_id = ?
          GROUP BY training_course_session_id
        ) counts ON counts.training_course_session_id = s.training_course_session_id
        WHERE s.org_id = ? AND s.training_course_run_id IN (
          SELECT training_course_run_id
          FROM training_course_runs
          WHERE org_id = ? AND job_id = ?
        )
        ORDER BY COALESCE(s.session_date, CURRENT_DATE), s.start_time NULLS LAST, s.training_course_session_id
        """,
        [org_id, org_id, org_id, int(job_id)],
    ).fetchall()
    sessions: list[dict[str, Any]] = []
    for row in rows:
        attendance = _get_training_session_attendance(con, org_id, int(row[0]))
        sessions.append(_session_payload(row, attendance))
    return sessions


def _get_training_overview(con, org_id: str, job_id: int) -> dict[str, Any]:
    details = _get_training_details(con, job_id)
    products = _list_training_products(con, org_id, include_inactive=True)
    course_runs = _get_course_run_rows(con, org_id, job_id)
    entitlements = _get_available_entitlements(con, org_id)
    sessions = _get_training_course_sessions(con, org_id, job_id)
    return {
        "job_id": int(job_id),
        "details": details,
        "products": products,
        "course_runs": course_runs,
        "available_entitlements": entitlements,
        "sessions": sessions,
    }


def _upsert_training_details(con, job_id: int, body: dict[str, Any], actor: str) -> dict[str, Any]:
    exists = con.execute("SELECT 1 FROM job_training_details WHERE job_id = ?", [int(job_id)]).fetchone()

    training_date = body.get("training_date") or None
    delivery_format = _clean_text(body.get("delivery_format"))
    topic = _clean_text(body.get("topic"))
    audience = _clean_text(body.get("audience"))
    materials_link = _clean_text(body.get("materials_link"))
    location = _clean_text(body.get("location"))
    notes = _clean_text(body.get("notes"))
    attendee_count = _clean_int(body.get("attendee_count"))
    session_duration_hours = _clean_float(body.get("session_duration_hours"))

    if exists:
        con.execute(
            """
            UPDATE job_training_details
            SET training_date = ?, delivery_format = ?, topic = ?, audience = ?, attendee_count = ?,
                session_duration_hours = ?, materials_link = ?, location = ?, notes = ?,
                updated_at = NOW(), updated_by = ?
            WHERE job_id = ?
            """,
            [
                training_date,
                delivery_format,
                topic,
                audience,
                attendee_count,
                session_duration_hours,
                materials_link,
                location,
                notes,
                actor,
                int(job_id),
            ],
        )
    else:
        con.execute(
            """
            INSERT INTO job_training_details (
              job_id, training_date, delivery_format, topic, audience, attendee_count,
              session_duration_hours, materials_link, location, notes, created_by, updated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                int(job_id),
                training_date,
                delivery_format,
                topic,
                audience,
                attendee_count,
                session_duration_hours,
                materials_link,
                location,
                notes,
                actor,
                actor,
            ],
        )
    return _get_training_details(con, job_id)


def _build_product_values(body: dict[str, Any]) -> dict[str, Any]:
    default_documents_json = body.get("default_documents_json")
    if default_documents_json is not None and not isinstance(default_documents_json, str):
        default_documents_json = json.dumps(default_documents_json)
    return {
        "product_code": _clean_text(body.get("product_code")),
        "product_name": _clean_text(body.get("product_name")),
        "description": _clean_text(body.get("description")),
        "default_hours": _clean_float(body.get("default_hours")),
        "default_delivery_mode": _clean_text(body.get("default_delivery_mode")),
        "default_capacity": _clean_int(body.get("default_capacity")),
        "default_min_attendees": _clean_int(body.get("default_min_attendees")),
        "certificate_policy": _clean_text(body.get("certificate_policy")),
        "default_documents_json": _clean_text(default_documents_json),
        "is_active": _clean_bool(body.get("is_active"), True),
    }


def _build_run_values(body: dict[str, Any], product_row: dict[str, Any] | None = None) -> dict[str, Any]:
    return {
        "training_product_id": _clean_int(body.get("training_product_id")),
        "run_name": _clean_text(body.get("run_name")),
        "course_code": _clean_text(body.get("course_code")),
        "total_hours": _clean_float(body.get("total_hours"))
        if body.get("total_hours") not in (None, "")
        else (product_row.get("default_hours") if product_row else None),
        "delivery_mode": _clean_text(body.get("delivery_mode"))
        if body.get("delivery_mode") not in (None, "")
        else (product_row.get("default_delivery_mode") if product_row else None),
        "capacity": _clean_int(body.get("capacity"))
        if body.get("capacity") not in (None, "")
        else (product_row.get("default_capacity") if product_row else None),
        "min_attendees": _clean_int(body.get("min_attendees"))
        if body.get("min_attendees") not in (None, "")
        else (product_row.get("default_min_attendees") if product_row else None),
        "status": _clean_text(body.get("status")) or "draft",
        "workflow_stage_key": _clean_text(body.get("workflow_stage_key")) or "setup",
        "start_date": body.get("start_date") or None,
        "end_date": body.get("end_date") or None,
        "venue_name": _clean_text(body.get("venue_name")),
        "venue_address": _clean_text(body.get("venue_address")),
        "online_meeting_url": _clean_text(body.get("online_meeting_url")),
        "online_meeting_id": _clean_text(body.get("online_meeting_id")),
        "online_passcode": _clean_text(body.get("online_passcode")),
        "notes": _clean_text(body.get("notes")),
    }


def _build_booking_values(body: dict[str, Any]) -> dict[str, Any]:
    return {
        "client_db_id": _clean_int(body.get("client_db_id")),
        "contact_id": _clean_int(body.get("contact_id")),
        "participant_type": _clean_text(body.get("participant_type")) or "external_individual",
        "booking_source": _clean_text(body.get("booking_source")) or "manual",
        "person_name": _clean_text(body.get("person_name")),
        "person_email": _clean_text(body.get("person_email")),
        "person_phone": _clean_text(body.get("person_phone")),
        "billing_status": _clean_text(body.get("billing_status")) or "pending",
        "attendance_status": _clean_text(body.get("attendance_status")) or "booked",
        "special_requirements": _clean_text(body.get("special_requirements")),
        "consent_status": _clean_text(body.get("consent_status")) or "unknown",
        "notes": _clean_text(body.get("notes")),
        "entitlement_id": _clean_int(body.get("entitlement_id")),
    }


def _build_entitlement_values(body: dict[str, Any], con, org_id: str) -> dict[str, Any]:
    source_job_id = _clean_int(body.get("source_job_id"))
    source_job_number = _clean_text(body.get("source_job_number"))
    source_client_db_id = _clean_int(body.get("source_client_db_id"))

    if source_job_id is None and source_job_number:
        job_row = con.execute(
            """
            SELECT job_id, job_number, client_db_id
            FROM jobs
            WHERE org_id = ? AND job_number = ?
            """,
            [org_id, source_job_number],
        ).fetchone()
        if job_row:
            source_job_id = int(job_row[0])
            source_job_number = str(job_row[1] or source_job_number)
            source_client_db_id = int(job_row[2]) if job_row[2] is not None else source_client_db_id

    if source_job_id is not None:
        job_row = con.execute(
            """
            SELECT job_id, job_number, client_db_id
            FROM jobs
            WHERE org_id = ? AND job_id = ?
            """,
            [org_id, int(source_job_id)],
        ).fetchone()
        if not job_row:
            raise HTTPException(status_code=404, detail="Source job not found")
        source_job_number = str(job_row[1] or source_job_number)
        source_client_db_id = int(job_row[2]) if job_row[2] is not None else source_client_db_id
    else:
        raise HTTPException(status_code=400, detail="source_job_id or source_job_number is required")

    return {
        "source_job_id": int(source_job_id),
        "source_job_number": source_job_number,
        "source_client_db_id": source_client_db_id,
        "entitlement_type": _clean_text(body.get("entitlement_type")) or "free_place",
        "status": _clean_text(body.get("status")) or "available",
        "expires_at": body.get("expires_at") or None,
        "notes": _clean_text(body.get("notes")),
    }


def _assert_run_access(user: dict[str, str], con, course_run_id: int, org_id: str) -> tuple[Any, int]:
    row = con.execute(
        "SELECT training_course_run_id, job_id FROM training_course_runs WHERE training_course_run_id = ? AND org_id = ?",
        [int(course_run_id), org_id],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Training course run not found")
    job_id = int(row[1])
    assert_job_access(user, job_id)
    return row, job_id


def _assert_booking_access(user: dict[str, str], con, booking_id: int, org_id: str) -> tuple[Any, int]:
    row = con.execute(
        """
        SELECT b.training_booking_id, r.job_id
        FROM training_bookings b
        JOIN training_course_runs r ON r.training_course_run_id = b.training_course_run_id
        WHERE b.training_booking_id = ? AND b.org_id = ?
        """,
        [int(booking_id), org_id],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Training booking not found")
    job_id = int(row[1])
    assert_job_access(user, job_id)
    return row, job_id


def _assert_entitlement_access(user: dict[str, str], con, entitlement_id: int, org_id: str) -> tuple[Any, int]:
    row = con.execute(
        "SELECT training_entitlement_id, source_job_id FROM training_entitlements WHERE training_entitlement_id = ? AND org_id = ?",
        [int(entitlement_id), org_id],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Training entitlement not found")
    assert_job_access(user, int(row[1]))
    return row, int(row[1])


def _sync_booking_entitlement(con, booking_id: int, entitlement_id: int | None, actor: str, org_id: str) -> None:
    booking_row = con.execute(
        "SELECT entitlement_id FROM training_bookings WHERE training_booking_id = ? AND org_id = ?",
        [int(booking_id), org_id],
    ).fetchone()
    if not booking_row:
        raise HTTPException(status_code=404, detail="Training booking not found")
    current_entitlement_id = int(booking_row[0]) if booking_row[0] is not None else None

    if current_entitlement_id is not None and current_entitlement_id != entitlement_id:
        con.execute(
            """
            UPDATE training_entitlements
            SET allocated_to_booking_id = NULL, status = 'available', consumed_at = NULL,
                updated_at = NOW(), updated_by = ?
            WHERE training_entitlement_id = ? AND org_id = ?
            """,
            [actor, current_entitlement_id, org_id],
        )

    if entitlement_id is None:
        con.execute(
            "UPDATE training_bookings SET entitlement_id = NULL, updated_at = NOW(), updated_by = ? WHERE training_booking_id = ? AND org_id = ?",
            [actor, int(booking_id), org_id],
        )
        return

    entitlement_row = con.execute(
        "SELECT allocated_to_booking_id FROM training_entitlements WHERE training_entitlement_id = ? AND org_id = ?",
        [int(entitlement_id), org_id],
    ).fetchone()
    if not entitlement_row:
        raise HTTPException(status_code=404, detail="Training entitlement not found")

    existing_booking_id = int(entitlement_row[0]) if entitlement_row[0] is not None else None
    if existing_booking_id is not None and existing_booking_id != int(booking_id):
        con.execute(
            "UPDATE training_bookings SET entitlement_id = NULL, updated_at = NOW(), updated_by = ? WHERE training_booking_id = ? AND org_id = ?",
            [actor, existing_booking_id, org_id],
        )

    con.execute(
        """
        UPDATE training_entitlements
        SET allocated_to_booking_id = ?, status = 'consumed', consumed_at = NOW(),
            updated_at = NOW(), updated_by = ?
        WHERE training_entitlement_id = ? AND org_id = ?
        """,
        [int(booking_id), actor, int(entitlement_id), org_id],
    )
    con.execute(
        "UPDATE training_bookings SET entitlement_id = ?, updated_at = NOW(), updated_by = ? WHERE training_booking_id = ? AND org_id = ?",
        [int(entitlement_id), actor, int(booking_id), org_id],
    )


def _build_session_values(body: dict[str, Any]) -> dict[str, Any]:
    return {
        "session_title": _clean_text(body.get("session_title")),
        "session_date": body.get("session_date") or None,
        "start_time": body.get("start_time") or None,
        "end_time": body.get("end_time") or None,
        "session_hours": _clean_float(body.get("session_hours")),
        "delivery_mode": _clean_text(body.get("delivery_mode")),
        "venue_name": _clean_text(body.get("venue_name")),
        "venue_address": _clean_text(body.get("venue_address")),
        "online_meeting_url": _clean_text(body.get("online_meeting_url")),
        "online_meeting_id": _clean_text(body.get("online_meeting_id")),
        "online_passcode": _clean_text(body.get("online_passcode")),
        "status": _clean_text(body.get("status")) or "scheduled",
        "notes": _clean_text(body.get("notes")),
    }


def _build_session_attendance_items(body: dict[str, Any]) -> list[dict[str, Any]]:
    raw_items = body.get("items") or []
    if not isinstance(raw_items, list):
        return []
    items: list[dict[str, Any]] = []
    for item in raw_items:
        if not isinstance(item, dict):
            continue
        booking_id = _clean_int(item.get("training_booking_id"))
        if booking_id is None:
            continue
        items.append(
            {
                "training_booking_id": booking_id,
                "attendance_status": _clean_text(item.get("attendance_status")) or "booked",
                "attendance_minutes": _clean_int(item.get("attendance_minutes")),
                "notes": _clean_text(item.get("notes")),
            }
        )
    return items


def _assert_session_access(user: dict[str, str], con, session_id: int, org_id: str) -> tuple[Any, int]:
    row = con.execute(
        """
        SELECT s.training_course_session_id, r.job_id
        FROM training_course_sessions s
        JOIN training_course_runs r ON r.training_course_run_id = s.training_course_run_id
        WHERE s.training_course_session_id = ? AND s.org_id = ?
        """,
        [int(session_id), org_id],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Training session not found")
    job_id = int(row[1])
    assert_job_access(user, job_id)
    return row, job_id


def _get_sessions_for_run(con, org_id: str, training_course_run_id: int) -> list[dict[str, Any]]:
    rows = con.execute(
        """
        SELECT s.training_course_session_id, s.org_id, s.training_course_run_id, s.session_title, s.session_date,
               s.start_time, s.end_time, s.session_hours, s.delivery_mode, s.venue_name, s.venue_address,
               s.online_meeting_url, s.online_meeting_id, s.online_passcode, s.status, s.notes,
               COALESCE(counts.attendance_count, 0), COALESCE(counts.attended_count, 0),
               s.created_at, s.created_by, s.updated_at, s.updated_by
        FROM training_course_sessions s
        LEFT JOIN (
          SELECT training_course_session_id,
                 COUNT(*) AS attendance_count,
                 COUNT(*) FILTER (WHERE attendance_status = 'attended') AS attended_count
          FROM training_session_attendance
          WHERE org_id = ?
          GROUP BY training_course_session_id
        ) counts ON counts.training_course_session_id = s.training_course_session_id
        WHERE s.org_id = ? AND s.training_course_run_id = ?
        ORDER BY COALESCE(s.session_date, CURRENT_DATE), s.start_time NULLS LAST, s.training_course_session_id
        """,
        [org_id, org_id, int(training_course_run_id)],
    ).fetchall()
    sessions: list[dict[str, Any]] = []
    for row in rows:
        attendance_rows = con.execute(
            """
            SELECT a.training_session_attendance_id, a.org_id, a.training_course_session_id, a.training_booking_id,
                   a.attendance_status, a.attendance_minutes, a.notes, b.person_name, b.person_email, c.client_name,
                   b.booking_source, b.participant_type, b.attendance_status, b.entitlement_id,
                   a.created_at, a.created_by, a.updated_at, a.updated_by
            FROM training_session_attendance a
            JOIN training_bookings b ON b.training_booking_id = a.training_booking_id
            LEFT JOIN clients c ON c.db_id = b.client_db_id
            WHERE a.org_id = ? AND a.training_course_session_id = ?
            ORDER BY b.person_name, a.training_session_attendance_id
            """,
            [org_id, int(row[0])],
        ).fetchall()
        sessions.append(_session_payload(row, [_attendance_payload(att) for att in attendance_rows]))
    return sessions


@router.get("/jobs/{job_id}/training-details")
def get_training_details(job_id: int, _user: dict[str, str] = Depends(_current_user)):
    assert_permission(_user, "jobs.view")
    assert_job_access(_user, int(job_id))
    with get_conn() as con:
        _ensure_tables(con)
        return _get_training_details(con, int(job_id))


@router.put("/jobs/{job_id}/training-details")
def save_training_details(
    job_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        return _upsert_training_details(con, int(job_id), body, actor)


@router.get("/jobs/{job_id}/training-overview")
def get_training_overview(job_id: int, _user: dict[str, str] = Depends(_current_user)):
    assert_permission(_user, "jobs.view")
    assert_job_access(_user, int(job_id))
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_tables(con)
        return _get_training_overview(con, org_id, int(job_id))


@router.get("/training-products")
def list_training_products(
    include_inactive: bool = Query(default=False),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.view")
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_tables(con)
        return {"items": _list_training_products(con, org_id, include_inactive=include_inactive)}


@router.post("/training-products")
def create_training_product(body: dict = Body(...), _user: dict[str, str] = Depends(_current_user)):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    values = _build_product_values(body)
    if not values["product_name"]:
        raise HTTPException(status_code=400, detail="product_name is required")
    with get_conn() as con:
        _ensure_tables(con)
        con.execute(
            """
            INSERT INTO training_products (
              org_id, product_code, product_name, description, default_hours, default_delivery_mode,
              default_capacity, default_min_attendees, certificate_policy, default_documents_json,
              is_active, created_by, updated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                org_id,
                values["product_code"],
                values["product_name"],
                values["description"],
                values["default_hours"],
                values["default_delivery_mode"],
                values["default_capacity"],
                values["default_min_attendees"],
                values["certificate_policy"],
                values["default_documents_json"],
                values["is_active"],
                actor,
                actor,
            ],
        )
        row = con.execute(
            """
            SELECT training_product_id, org_id, product_code, product_name, description, default_hours,
                   default_delivery_mode, default_capacity, default_min_attendees, certificate_policy,
                   default_documents_json, is_active, created_at, created_by, updated_at, updated_by
            FROM training_products
            WHERE org_id = ? AND training_product_id = (
              SELECT MAX(training_product_id) FROM training_products WHERE org_id = ?
            )
            """,
            [org_id, org_id],
        ).fetchone()
        return _product_payload(row)


@router.put("/training-products/{training_product_id}")
def update_training_product(
    training_product_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    values = _build_product_values(body)
    with get_conn() as con:
        _ensure_tables(con)
        exists = con.execute(
            "SELECT 1 FROM training_products WHERE training_product_id = ? AND org_id = ?",
            [int(training_product_id), org_id],
        ).fetchone()
        if not exists:
            raise HTTPException(status_code=404, detail="Training product not found")
        con.execute(
            """
            UPDATE training_products
            SET product_code = ?, product_name = ?, description = ?, default_hours = ?, default_delivery_mode = ?,
                default_capacity = ?, default_min_attendees = ?, certificate_policy = ?, default_documents_json = ?,
                is_active = ?, updated_at = NOW(), updated_by = ?
            WHERE training_product_id = ? AND org_id = ?
            """,
            [
                values["product_code"],
                values["product_name"],
                values["description"],
                values["default_hours"],
                values["default_delivery_mode"],
                values["default_capacity"],
                values["default_min_attendees"],
                values["certificate_policy"],
                values["default_documents_json"],
                values["is_active"],
                actor,
                int(training_product_id),
                org_id,
            ],
        )
        row = con.execute(
            """
            SELECT training_product_id, org_id, product_code, product_name, description, default_hours,
                   default_delivery_mode, default_capacity, default_min_attendees, certificate_policy,
                   default_documents_json, is_active, created_at, created_by, updated_at, updated_by
            FROM training_products
            WHERE training_product_id = ? AND org_id = ?
            """,
            [int(training_product_id), org_id],
        ).fetchone()
        return _product_payload(row)


@router.get("/jobs/{job_id}/training-course-runs")
def list_job_training_course_runs(job_id: int, _user: dict[str, str] = Depends(_current_user)):
    assert_permission(_user, "jobs.view")
    assert_job_access(_user, int(job_id))
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_tables(con)
        return {"items": _get_course_run_rows(con, org_id, int(job_id))}


@router.post("/jobs/{job_id}/training-course-runs")
def create_job_training_course_run(
    job_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        product_row = None
        product_id = _clean_int(body.get("training_product_id"))
        if product_id is not None:
            product_row = _resolve_training_product(con, org_id, product_id)
            if product_row is None:
                raise HTTPException(status_code=404, detail="Training product not found")
        values = _build_run_values(body, product_row)
        con.execute(
            """
            INSERT INTO training_course_runs (
              org_id, job_id, training_product_id, run_name, course_code, total_hours, delivery_mode,
              capacity, min_attendees, status, workflow_stage_key, start_date, end_date, venue_name,
              venue_address, online_meeting_url, online_meeting_id, online_passcode, notes,
              created_by, updated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                org_id,
                int(job_id),
                values["training_product_id"],
                values["run_name"],
                values["course_code"],
                values["total_hours"],
                values["delivery_mode"],
                values["capacity"],
                values["min_attendees"],
                values["status"],
                values["workflow_stage_key"],
                values["start_date"],
                values["end_date"],
                values["venue_name"],
                values["venue_address"],
                values["online_meeting_url"],
                values["online_meeting_id"],
                values["online_passcode"],
                values["notes"],
                actor,
                actor,
            ],
        )
        run_row = con.execute(
            """
            SELECT r.training_course_run_id, r.org_id, r.job_id, r.training_product_id, p.product_name,
                   r.run_name, r.course_code, r.total_hours, r.delivery_mode, r.capacity, r.min_attendees,
                   r.status, r.workflow_stage_key, r.start_date, r.end_date, r.venue_name, r.venue_address,
                   r.online_meeting_url, r.online_meeting_id, r.online_passcode, r.notes, 0, 0,
                   r.created_at, r.created_by, r.updated_at, r.updated_by
            FROM training_course_runs r
            LEFT JOIN training_products p ON p.training_product_id = r.training_product_id
            WHERE r.org_id = ? AND r.job_id = ?
            ORDER BY r.training_course_run_id DESC
            LIMIT 1
            """,
            [org_id, int(job_id)],
        ).fetchone()
        if not run_row:
            raise HTTPException(status_code=500, detail="Training course run creation failed")
        return _run_payload(run_row, [])


@router.put("/training-course-runs/{training_course_run_id}")
def update_training_course_run(
    training_course_run_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_run_access(_user, con, int(training_course_run_id), org_id)
        product_row = None
        product_id = _clean_int(body.get("training_product_id"))
        if product_id is not None:
            product_row = _resolve_training_product(con, org_id, product_id)
            if product_row is None:
                raise HTTPException(status_code=404, detail="Training product not found")
        values = _build_run_values(body, product_row)
        con.execute(
            """
            UPDATE training_course_runs
            SET training_product_id = ?, run_name = ?, course_code = ?, total_hours = ?, delivery_mode = ?,
                capacity = ?, min_attendees = ?, status = ?, workflow_stage_key = ?, start_date = ?,
                end_date = ?, venue_name = ?, venue_address = ?, online_meeting_url = ?,
                online_meeting_id = ?, online_passcode = ?, notes = ?, updated_at = NOW(), updated_by = ?
            WHERE training_course_run_id = ? AND org_id = ?
            """,
            [
                values["training_product_id"],
                values["run_name"],
                values["course_code"],
                values["total_hours"],
                values["delivery_mode"],
                values["capacity"],
                values["min_attendees"],
                values["status"],
                values["workflow_stage_key"],
                values["start_date"],
                values["end_date"],
                values["venue_name"],
                values["venue_address"],
                values["online_meeting_url"],
                values["online_meeting_id"],
                values["online_passcode"],
                values["notes"],
                actor,
                int(training_course_run_id),
                org_id,
            ],
        )
        rows = _get_course_run_rows(con, org_id, job_id)
        for run in rows:
            if run["training_course_run_id"] == int(training_course_run_id):
                return run
        raise HTTPException(status_code=500, detail="Training course run update failed")


@router.post("/training-course-runs/{training_course_run_id}/bookings")
def create_training_booking(
    training_course_run_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_run_access(_user, con, int(training_course_run_id), org_id)
        values = _build_booking_values(body)
        if not values["person_name"]:
            raise HTTPException(status_code=400, detail="person_name is required")
        con.execute(
            """
            INSERT INTO training_bookings (
              org_id, training_course_run_id, client_db_id, contact_id, participant_type, booking_source,
              person_name, person_email, person_phone, billing_status, attendance_status,
              special_requirements, consent_status, notes, entitlement_id, created_by, updated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                org_id,
                int(training_course_run_id),
                values["client_db_id"],
                values["contact_id"],
                values["participant_type"],
                values["booking_source"],
                values["person_name"],
                values["person_email"],
                values["person_phone"],
                values["billing_status"],
                values["attendance_status"],
                values["special_requirements"],
                values["consent_status"],
                values["notes"],
                None,
                actor,
                actor,
            ],
        )
        booking_row = con.execute(
            """
            SELECT b.training_booking_id, b.org_id, b.training_course_run_id, b.client_db_id, b.contact_id,
                   b.participant_type, b.booking_source, b.person_name, b.person_email, b.person_phone,
                   b.billing_status, b.attendance_status, b.special_requirements, b.consent_status,
                   b.notes, b.entitlement_id, c.client_name, e.source_job_number,
                   e.status, COALESCE(b2.person_name, ''),
                   b.created_at, b.created_by, b.updated_at, b.updated_by
            FROM training_bookings b
            LEFT JOIN clients c ON c.db_id = b.client_db_id
            LEFT JOIN training_entitlements e ON e.training_entitlement_id = b.entitlement_id
            LEFT JOIN training_bookings b2 ON b2.training_booking_id = e.allocated_to_booking_id
            WHERE b.org_id = ? AND b.training_booking_id = (
              SELECT MAX(training_booking_id) FROM training_bookings WHERE org_id = ? AND training_course_run_id = ?
            )
            """,
            [org_id, org_id, int(training_course_run_id)],
        ).fetchone()
        if values["entitlement_id"] is not None:
            _sync_booking_entitlement(con, int(booking_row[0]), int(values["entitlement_id"]), actor, org_id)
            booking_row = con.execute(
                """
                SELECT b.training_booking_id, b.org_id, b.training_course_run_id, b.client_db_id, b.contact_id,
                       b.participant_type, b.booking_source, b.person_name, b.person_email, b.person_phone,
                       b.billing_status, b.attendance_status, b.special_requirements, b.consent_status,
                       b.notes, b.entitlement_id, c.client_name, e.source_job_number,
                       e.status, COALESCE(b2.person_name, ''),
                       b.created_at, b.created_by, b.updated_at, b.updated_by
                FROM training_bookings b
                LEFT JOIN clients c ON c.db_id = b.client_db_id
                LEFT JOIN training_entitlements e ON e.training_entitlement_id = b.entitlement_id
                LEFT JOIN training_bookings b2 ON b2.training_booking_id = e.allocated_to_booking_id
                WHERE b.training_booking_id = ? AND b.org_id = ?
                """,
                [int(booking_row[0]), org_id],
            ).fetchone()
        return _booking_payload(booking_row)


@router.put("/training-bookings/{training_booking_id}")
def update_training_booking(
    training_booking_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_booking_access(_user, con, int(training_booking_id), org_id)
        values = _build_booking_values(body)
        if not values["person_name"]:
            raise HTTPException(status_code=400, detail="person_name is required")
        con.execute(
            """
            UPDATE training_bookings
            SET client_db_id = ?, contact_id = ?, participant_type = ?, booking_source = ?, person_name = ?,
                person_email = ?, person_phone = ?, billing_status = ?, attendance_status = ?,
                special_requirements = ?, consent_status = ?, notes = ?, updated_at = NOW(), updated_by = ?
            WHERE training_booking_id = ? AND org_id = ?
            """,
            [
                values["client_db_id"],
                values["contact_id"],
                values["participant_type"],
                values["booking_source"],
                values["person_name"],
                values["person_email"],
                values["person_phone"],
                values["billing_status"],
                values["attendance_status"],
                values["special_requirements"],
                values["consent_status"],
                values["notes"],
                actor,
                int(training_booking_id),
                org_id,
            ],
        )
        _sync_booking_entitlement(con, int(training_booking_id), values["entitlement_id"], actor, org_id)
        row = con.execute(
            """
            SELECT b.training_booking_id, b.org_id, b.training_course_run_id, b.client_db_id, b.contact_id,
                   b.participant_type, b.booking_source, b.person_name, b.person_email, b.person_phone,
                   b.billing_status, b.attendance_status, b.special_requirements, b.consent_status,
                   b.notes, b.entitlement_id, c.client_name, e.source_job_number,
                   e.status, COALESCE(b2.person_name, ''),
                   b.created_at, b.created_by, b.updated_at, b.updated_by
            FROM training_bookings b
            LEFT JOIN clients c ON c.db_id = b.client_db_id
            LEFT JOIN training_entitlements e ON e.training_entitlement_id = b.entitlement_id
            LEFT JOIN training_bookings b2 ON b2.training_booking_id = e.allocated_to_booking_id
            WHERE b.training_booking_id = ? AND b.org_id = ?
            """,
            [int(training_booking_id), org_id],
        ).fetchone()
        return _booking_payload(row)


@router.get("/training-course-runs/{training_course_run_id}/sessions")
def list_training_course_sessions(
    training_course_run_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.view")
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_run_access(_user, con, int(training_course_run_id), org_id)
        return {
            "job_id": job_id,
            "training_course_run_id": int(training_course_run_id),
            "items": _get_sessions_for_run(con, org_id, int(training_course_run_id)),
        }


@router.post("/training-course-runs/{training_course_run_id}/sessions")
def create_training_course_session(
    training_course_run_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_run_access(_user, con, int(training_course_run_id), org_id)
        values = _build_session_values(body)
        con.execute(
            """
            INSERT INTO training_course_sessions (
              org_id, training_course_run_id, session_title, session_date, start_time, end_time, session_hours,
              delivery_mode, venue_name, venue_address, online_meeting_url, online_meeting_id, online_passcode,
              status, notes, created_by, updated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                org_id,
                int(training_course_run_id),
                values["session_title"],
                values["session_date"],
                values["start_time"],
                values["end_time"],
                values["session_hours"],
                values["delivery_mode"],
                values["venue_name"],
                values["venue_address"],
                values["online_meeting_url"],
                values["online_meeting_id"],
                values["online_passcode"],
                values["status"],
                values["notes"],
                actor,
                actor,
            ],
        )
        sessions = _get_sessions_for_run(con, org_id, int(training_course_run_id))
        if not sessions:
            raise HTTPException(status_code=500, detail="Training session creation failed")
        return sessions[0]


@router.put("/training-course-sessions/{training_course_session_id}")
def update_training_course_session(
    training_course_session_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_session_access(_user, con, int(training_course_session_id), org_id)
        values = _build_session_values(body)
        con.execute(
            """
            UPDATE training_course_sessions
            SET session_title = ?, session_date = ?, start_time = ?, end_time = ?, session_hours = ?,
                delivery_mode = ?, venue_name = ?, venue_address = ?, online_meeting_url = ?,
                online_meeting_id = ?, online_passcode = ?, status = ?, notes = ?,
                updated_at = NOW(), updated_by = ?
            WHERE training_course_session_id = ? AND org_id = ?
            """,
            [
                values["session_title"],
                values["session_date"],
                values["start_time"],
                values["end_time"],
                values["session_hours"],
                values["delivery_mode"],
                values["venue_name"],
                values["venue_address"],
                values["online_meeting_url"],
                values["online_meeting_id"],
                values["online_passcode"],
                values["status"],
                values["notes"],
                actor,
                int(training_course_session_id),
                org_id,
            ],
        )
        sessions = _get_training_course_sessions(con, org_id, job_id)
        for session in sessions:
            if session["training_course_session_id"] == int(training_course_session_id):
                return session
        raise HTTPException(status_code=500, detail="Training session update failed")


@router.put("/training-course-sessions/{training_course_session_id}/attendance")
def upsert_training_session_attendance(
    training_course_session_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _, job_id = _assert_session_access(_user, con, int(training_course_session_id), org_id)
        items = _build_session_attendance_items(body)
        if not items:
            raise HTTPException(status_code=400, detail="items is required")
        for item in items:
            booking_row = con.execute(
                "SELECT 1 FROM training_bookings WHERE training_booking_id = ? AND org_id = ?",
                [int(item["training_booking_id"]), org_id],
            ).fetchone()
            if not booking_row:
                raise HTTPException(status_code=404, detail=f"Training booking {item['training_booking_id']} not found")
            existing = con.execute(
                """
                SELECT training_session_attendance_id
                FROM training_session_attendance
                WHERE org_id = ? AND training_course_session_id = ? AND training_booking_id = ?
                """,
                [org_id, int(training_course_session_id), int(item["training_booking_id"])],
            ).fetchone()
            if existing:
                con.execute(
                    """
                    UPDATE training_session_attendance
                    SET attendance_status = ?, attendance_minutes = ?, notes = ?, updated_at = NOW(), updated_by = ?
                    WHERE training_session_attendance_id = ? AND org_id = ?
                    """,
                    [
                        item["attendance_status"],
                        item["attendance_minutes"],
                        item["notes"],
                        actor,
                        int(existing[0]),
                        org_id,
                    ],
                )
            else:
                con.execute(
                    """
                    INSERT INTO training_session_attendance (
                      org_id, training_course_session_id, training_booking_id, attendance_status,
                      attendance_minutes, notes, created_by, updated_by
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    [
                        org_id,
                        int(training_course_session_id),
                        int(item["training_booking_id"]),
                        item["attendance_status"],
                        item["attendance_minutes"],
                        item["notes"],
                        actor,
                        actor,
                    ],
                )
        sessions = _get_training_course_sessions(con, org_id, job_id)
        for session in sessions:
            if session["training_course_session_id"] == int(training_course_session_id):
                return session
        raise HTTPException(status_code=500, detail="Training attendance update failed")


@router.get("/training-entitlements")
def list_training_entitlements(
    status: str | None = Query(default=None),
    source_job_id: int | None = Query(default=None),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.view")
    org_id = require_org(_user)
    with get_conn() as con:
        _ensure_tables(con)
        params: list[Any] = [org_id]
        sql = """
            SELECT e.training_entitlement_id, e.org_id, e.source_job_id,
                   COALESCE(e.source_job_number, j.job_number),
                   e.source_client_db_id, e.entitlement_type, e.status, e.allocated_to_booking_id,
                   e.reserved_at, e.consumed_at, e.expires_at, e.notes,
                   c.client_name, COALESCE(b.person_name, ''),
                   e.created_at, e.created_by, e.updated_at, e.updated_by
            FROM training_entitlements e
            LEFT JOIN jobs j ON j.job_id = e.source_job_id
            LEFT JOIN clients c ON c.db_id = e.source_client_db_id
            LEFT JOIN training_bookings b ON b.training_booking_id = e.allocated_to_booking_id
            WHERE e.org_id = ?
        """
        if status:
            sql += " AND e.status = ?"
            params.append(status)
        if source_job_id is not None:
            sql += " AND e.source_job_id = ?"
            params.append(int(source_job_id))
        sql += " ORDER BY e.status, e.training_entitlement_id DESC"
        rows = con.execute(sql, params).fetchall()
        return {"items": [_entitlement_payload(row) for row in rows]}


@router.post("/training-entitlements")
def create_training_entitlement(
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        values = _build_entitlement_values(body, con, org_id)
        con.execute(
            """
            INSERT INTO training_entitlements (
              org_id, source_job_id, source_job_number, source_client_db_id, entitlement_type, status,
              allocated_to_booking_id, reserved_at, consumed_at, expires_at, notes, created_by, updated_by
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                org_id,
                values["source_job_id"],
                values["source_job_number"],
                values["source_client_db_id"],
                values["entitlement_type"],
                values["status"],
                None,
                None,
                None,
                values["expires_at"],
                values["notes"],
                actor,
                actor,
            ],
        )
        row = con.execute(
            """
            SELECT e.training_entitlement_id, e.org_id, e.source_job_id,
                   COALESCE(e.source_job_number, j.job_number),
                   e.source_client_db_id, e.entitlement_type, e.status, e.allocated_to_booking_id,
                   e.reserved_at, e.consumed_at, e.expires_at, e.notes,
                   c.client_name, COALESCE(b.person_name, ''),
                   e.created_at, e.created_by, e.updated_at, e.updated_by
            FROM training_entitlements e
            LEFT JOIN jobs j ON j.job_id = e.source_job_id
            LEFT JOIN clients c ON c.db_id = e.source_client_db_id
            LEFT JOIN training_bookings b ON b.training_booking_id = e.allocated_to_booking_id
            WHERE e.org_id = ? AND e.training_entitlement_id = (
              SELECT MAX(training_entitlement_id) FROM training_entitlements WHERE org_id = ?
            )
            """,
            [org_id, org_id],
        ).fetchone()
        return _entitlement_payload(row)


@router.put("/training-entitlements/{training_entitlement_id}")
def update_training_entitlement(
    training_entitlement_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    with get_conn() as con:
        _ensure_tables(con)
        _assert_entitlement_access(_user, con, int(training_entitlement_id), org_id)
        values = _build_entitlement_values(body, con, org_id)
        con.execute(
            """
            UPDATE training_entitlements
            SET source_job_id = ?, source_job_number = ?, source_client_db_id = ?, entitlement_type = ?,
                status = ?, expires_at = ?, notes = ?, updated_at = NOW(), updated_by = ?
            WHERE training_entitlement_id = ? AND org_id = ?
            """,
            [
                values["source_job_id"],
                values["source_job_number"],
                values["source_client_db_id"],
                values["entitlement_type"],
                values["status"],
                values["expires_at"],
                values["notes"],
                actor,
                int(training_entitlement_id),
                org_id,
            ],
        )
        row = con.execute(
            """
            SELECT e.training_entitlement_id, e.org_id, e.source_job_id,
                   COALESCE(e.source_job_number, j.job_number),
                   e.source_client_db_id, e.entitlement_type, e.status, e.allocated_to_booking_id,
                   e.reserved_at, e.consumed_at, e.expires_at, e.notes,
                   c.client_name, COALESCE(b.person_name, ''),
                   e.created_at, e.created_by, e.updated_at, e.updated_by
            FROM training_entitlements e
            LEFT JOIN jobs j ON j.job_id = e.source_job_id
            LEFT JOIN clients c ON c.db_id = e.source_client_db_id
            LEFT JOIN training_bookings b ON b.training_booking_id = e.allocated_to_booking_id
            WHERE e.training_entitlement_id = ? AND e.org_id = ?
            """,
            [int(training_entitlement_id), org_id],
        ).fetchone()
        return _entitlement_payload(row)


@router.put("/training-entitlements/{training_entitlement_id}/consume")
def consume_training_entitlement(
    training_entitlement_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    assert_permission(_user, "jobs.edit")
    org_id = require_org(_user)
    actor = _actor(_user)
    booking_id = _clean_int(body.get("booking_id"))
    if booking_id is None:
        raise HTTPException(status_code=400, detail="booking_id is required")
    with get_conn() as con:
        _ensure_tables(con)
        _assert_entitlement_access(_user, con, int(training_entitlement_id), org_id)
        _assert_booking_access(_user, con, int(booking_id), org_id)
        _sync_booking_entitlement(con, int(booking_id), int(training_entitlement_id), actor, org_id)
        row = con.execute(
            """
            SELECT e.training_entitlement_id, e.org_id, e.source_job_id,
                   COALESCE(e.source_job_number, j.job_number),
                   e.source_client_db_id, e.entitlement_type, e.status, e.allocated_to_booking_id,
                   e.reserved_at, e.consumed_at, e.expires_at, e.notes,
                   c.client_name, COALESCE(b.person_name, ''),
                   e.created_at, e.created_by, e.updated_at, e.updated_by
            FROM training_entitlements e
            LEFT JOIN jobs j ON j.job_id = e.source_job_id
            LEFT JOIN clients c ON c.db_id = e.source_client_db_id
            LEFT JOIN training_bookings b ON b.training_booking_id = e.allocated_to_booking_id
            WHERE e.training_entitlement_id = ? AND e.org_id = ?
            """,
            [int(training_entitlement_id), org_id],
        ).fetchone()
        return _entitlement_payload(row)
