from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Body, Depends, File, HTTPException, Query, Response, UploadFile

from api.auth import _current_user
from api.job_scope_data_routes import _lookup_factor_from_reference, _safe_float, _safe_int
from core.database import get_conn
from openpyxl import load_workbook
from services.business_travel_upload_template import generate_business_travel_upload_template
from services.emission_register_template import build_emission_register_workbook
from services.audit_log import record_audit_event

router = APIRouter()


def _ensure_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emission_groups (
          group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          scope VARCHAR NOT NULL,
          category VARCHAR,
          group_type VARCHAR NOT NULL DEFAULT 'asset',
          group_name VARCHAR NOT NULL,
          site_id INTEGER REFERENCES client_sites(site_id),
          rollup_method VARCHAR NOT NULL DEFAULT 'sum',
          dataset_id INTEGER REFERENCES datasets(dataset_id),
          factor_db_id INTEGER REFERENCES factor_lookup(db_id),
          original_id VARCHAR,
          factor NUMERIC,
          ghg_unit VARCHAR,
          uom VARCHAR,
          notes TEXT,
          enabled BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS job_emission_groups_job_type_name_uidx
        ON job_emission_groups (job_id, group_type, group_name)
        WHERE COALESCE(enabled, TRUE) = TRUE
        """
    )
    con.execute("ALTER TABLE job_emission_groups ADD COLUMN IF NOT EXISTS dataset_id INTEGER REFERENCES datasets(dataset_id)")
    con.execute("ALTER TABLE job_emission_groups ADD COLUMN IF NOT EXISTS factor_db_id INTEGER REFERENCES factor_lookup(db_id)")
    con.execute("ALTER TABLE job_emission_groups ADD COLUMN IF NOT EXISTS original_id VARCHAR")
    con.execute("ALTER TABLE job_emission_groups ADD COLUMN IF NOT EXISTS factor NUMERIC")
    con.execute("ALTER TABLE job_emission_groups ADD COLUMN IF NOT EXISTS ghg_unit VARCHAR")
    con.execute("ALTER TABLE job_emission_groups ADD COLUMN IF NOT EXISTS uom VARCHAR")
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_groups_factor_idx
        ON job_emission_groups (job_id, group_type, factor_db_id, enabled)
        """
    )
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_emission_sources (
          source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          group_id INTEGER REFERENCES job_emission_groups(group_id) ON DELETE SET NULL,
          scope VARCHAR NOT NULL,
          category VARCHAR,
          source_type VARCHAR NOT NULL DEFAULT 'asset',
          source_subtype VARCHAR,
          site_id INTEGER REFERENCES client_sites(site_id),
          source_name VARCHAR NOT NULL,
          asset_identifier VARCHAR,
          employee_name VARCHAR,
          dataset_id INTEGER REFERENCES datasets(dataset_id),
          factor_db_id INTEGER REFERENCES factor_lookup(db_id),
          original_id VARCHAR,
          qty NUMERIC,
          uom VARCHAR,
          factor NUMERIC,
          ghg_unit VARCHAR,
          apply_pct NUMERIC DEFAULT 100,
          data_source VARCHAR DEFAULT 'Source Register',
          data_confidence VARCHAR DEFAULT 'M',
          notes TEXT,
          detail_json JSONB DEFAULT '{}'::jsonb,
          calc_tco2e NUMERIC,
          enabled BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_sources_job_type_enabled_idx
        ON job_emission_sources (job_id, source_type, enabled)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_emission_sources_group_idx
        ON job_emission_sources (group_id, enabled)
        """
    )
    con.execute(
        """
        UPDATE job_emission_groups g
        SET dataset_id = COALESCE(g.dataset_id, s.dataset_id),
            factor_db_id = COALESCE(g.factor_db_id, s.factor_db_id),
            original_id = COALESCE(g.original_id, s.original_id),
            factor = COALESCE(g.factor, s.factor),
            ghg_unit = COALESCE(g.ghg_unit, s.ghg_unit),
            uom = COALESCE(g.uom, s.uom),
            updated_at = NOW()
        FROM (
            SELECT DISTINCT ON (job_id, group_id)
              job_id, group_id, dataset_id, factor_db_id, original_id, factor, ghg_unit, uom
            FROM job_emission_sources
            WHERE group_id IS NOT NULL
              AND COALESCE(enabled, TRUE) = TRUE
              AND (
                dataset_id IS NOT NULL OR factor_db_id IS NOT NULL OR original_id IS NOT NULL
                OR factor IS NOT NULL OR ghg_unit IS NOT NULL OR uom IS NOT NULL
              )
            ORDER BY job_id, group_id, source_id
        ) s
        WHERE g.group_id = s.group_id
          AND g.job_id = s.job_id
          AND (
            g.dataset_id IS NULL OR g.factor_db_id IS NULL OR g.original_id IS NULL
            OR g.factor IS NULL OR g.ghg_unit IS NULL OR g.uom IS NULL
          )
        """
    )


def _calc_tco2e(qty: Any, factor: Any, apply_pct: Any, ghg_unit: Any) -> float:
    qty_val = float(qty or 0)
    factor_val = float(factor or 0)
    pct_val = float(apply_pct or 100)
    value = qty_val * factor_val * (pct_val / 100.0)
    if "kg" in str(ghg_unit or "kgCO2e").lower():
        value /= 1000.0
    return float(value)


def _job_exists(con, job_id: int) -> bool:
    return bool(con.execute("SELECT 1 FROM jobs WHERE job_id=%s", [int(job_id)]).fetchone())


def _resolve_site_id(con, site_name: str | None) -> int | None:
    name = str(site_name or "").strip()
    if not name:
        return None
    row = con.execute(
        """
        SELECT site_id
        FROM client_sites
        WHERE lower(site_name) = lower(%s)
        ORDER BY site_id
        LIMIT 1
        """,
        [name],
    ).fetchone()
    return _safe_int(row[0]) if row else None


def _resolve_previous_register_job_id(con, job_id: int) -> dict[str, Any] | None:
    current_job = con.execute(
        """
        SELECT client_db_id, reporting_period_start, reporting_period_end, reporting_year
        FROM jobs
        WHERE job_id=%s
        """,
        [int(job_id)],
    ).fetchone()
    if not current_job:
        return None

    client_db_id = _safe_int(current_job[0])
    if client_db_id is None:
        return None

    current_start = current_job[1]
    current_end = current_job[2]
    current_year = _safe_int(current_job[3])

    prior = con.execute(
        """
        SELECT job_id, job_number, title, reporting_period_start, reporting_period_end, reporting_year
        FROM jobs
        WHERE client_db_id=%s
          AND job_id <> %s
          AND (
            (%s IS NOT NULL AND reporting_period_end IS NOT NULL AND reporting_period_end < %s)
            OR (%s IS NOT NULL AND reporting_period_start IS NOT NULL AND reporting_period_start < %s)
            OR (%s IS NOT NULL AND reporting_year IS NOT NULL AND reporting_year < %s)
          )
        ORDER BY COALESCE(reporting_period_end, DATE '1900-01-01') DESC, COALESCE(reporting_year, 0) DESC, job_id DESC
        LIMIT 1
        """,
        [client_db_id, int(job_id), current_start, current_start, current_start, current_end, current_year, current_year],
    ).fetchone()
    if not prior:
        return None
    return {
        "job_id": _safe_int(prior[0]),
        "job_number": prior[1],
        "title": prior[2],
        "reporting_period_start": prior[3],
        "reporting_period_end": prior[4],
        "reporting_year": _safe_int(prior[5]),
    }


_GROUP_HEADER_ALIASES = {
    "group name": "group_name",
    "group": "group_name",
    "scope": "scope",
    "category": "category",
    "group type": "group_type",
    "type": "group_type",
    "site": "site_name",
    "site name": "site_name",
    "site id": "site_id",
    "rollup": "rollup_method",
    "rollup method": "rollup_method",
    "dataset id": "dataset_id",
    "factor db id": "factor_db_id",
    "factor db": "factor_db_id",
    "original id": "original_id",
    "factor": "factor",
    "ghg unit": "ghg_unit",
    "uom": "uom",
    "unit": "uom",
    "notes": "notes",
}

_SOURCE_HEADER_ALIASES = {
    "asset group": "group_name",
    "assets": "group_name",
    "group name": "group_name",
    "group": "group_name",
    "source name": "source_name",
    "asset name": "source_name",
    "asset": "source_name",
    "source": "source_name",
    "source type": "source_type",
    "type": "source_type",
    "source subtype": "source_subtype",
    "asset subtype": "source_subtype",
    "site": "site_name",
    "site name": "site_name",
    "site id": "site_id",
    "asset identifier": "asset_identifier",
    "employee name": "employee_name",
    "scope": "scope",
    "category": "category",
    "original id": "original_id",
    "factor db id": "factor_db_id",
    "factor": "factor",
    "qty": "qty",
    "quantity": "qty",
    "uom": "uom",
    "unit": "uom",
    "apply": "apply_pct",
    "apply pct": "apply_pct",
    "apply percent": "apply_pct",
    "data source": "data_source",
    "data confidence": "data_confidence",
    "notes": "notes",
}


def _sheet_rows(ws, alias_map: dict[str, str]) -> list[dict[str, Any]]:
    headers: list[str | None] = []
    for cell in next(ws.iter_rows(min_row=1, max_row=1, values_only=True), []):
        headers.append(alias_map.get(_norm_text(cell), _norm_text(cell) or None))

    rows: list[dict[str, Any]] = []
    for raw_row in ws.iter_rows(min_row=2, values_only=True):
        record: dict[str, Any] = {}
        has_value = False
        for idx, value in enumerate(raw_row):
            if idx >= len(headers):
                break
            key = headers[idx]
            if not key:
                continue
            record[key] = value
            if value is not None and str(value).strip() != "":
                has_value = True
        if has_value:
            rows.append(record)
    return rows


def _ensure_register_group(
    con,
    *,
    job_id: int,
    group_name: str,
    scope: str,
    group_type: str,
    category: str | None = None,
    site_id: int | None = None,
    rollup_method: str = "sum",
    dataset_id: int | None = None,
    factor_db_id: int | None = None,
    original_id: str | None = None,
    factor: Any | None = None,
    ghg_unit: str | None = None,
    uom: str | None = None,
    notes: str | None = None,
) -> tuple[int | None, bool]:
    normalized_name = str(group_name or "").strip()
    if not normalized_name:
        return None, False

    existing = con.execute(
        """
        SELECT group_id
        FROM job_emission_groups
        WHERE job_id=%s
          AND lower(group_name) = lower(%s)
          AND lower(group_type) = lower(%s)
          AND COALESCE(enabled, TRUE) = TRUE
        ORDER BY group_id
        LIMIT 1
        """,
        [int(job_id), normalized_name, str(group_type or "asset").strip() or "asset"],
    ).fetchone()
    if existing:
        group_id = _safe_int(existing[0])
        if group_id is not None and any(
            value is not None for value in (dataset_id, factor_db_id, original_id, factor, ghg_unit, uom)
        ):
            con.execute(
                """
                UPDATE job_emission_groups
                SET dataset_id = COALESCE(dataset_id, %s),
                    factor_db_id = COALESCE(factor_db_id, %s),
                    original_id = COALESCE(original_id, %s),
                    factor = COALESCE(factor, %s),
                    ghg_unit = COALESCE(ghg_unit, %s),
                    uom = COALESCE(uom, %s),
                    updated_at = NOW()
                WHERE group_id = %s
                """,
                [dataset_id, factor_db_id, original_id, factor, ghg_unit, uom, group_id],
            )
        return group_id, False

    row = con.execute(
        """
        INSERT INTO job_emission_groups (
            job_id, scope, category, group_type, group_name, site_id, rollup_method,
            dataset_id, factor_db_id, original_id, factor, ghg_unit, uom, notes
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING group_id
        """,
        [
            int(job_id),
            scope,
            category,
            str(group_type or "asset").strip() or "asset",
            normalized_name,
            site_id,
            str(rollup_method or "sum").strip() or "sum",
            dataset_id,
            factor_db_id,
            original_id,
            factor,
            ghg_unit,
            uom,
            notes,
        ],
    ).fetchone()
    return (_safe_int(row[0]) if row else None, True)


def _register_source_exists(
    con,
    *,
    job_id: int,
    source_type: str,
    group_id: int | None,
    source_name: str,
    site_id: int | None,
    scope: str,
    category: str | None,
    source_subtype: str | None,
    original_id: str | None,
    asset_identifier: str | None,
    employee_name: str | None,
) -> bool:
    return bool(
        con.execute(
            """
            SELECT 1
            FROM job_emission_sources
            WHERE job_id=%s
              AND lower(COALESCE(source_type, '')) = lower(%s)
              AND COALESCE(group_id, -1) = COALESCE(%s, -1)
              AND lower(COALESCE(source_name, '')) = lower(%s)
              AND COALESCE(site_id, -1) = COALESCE(%s, -1)
              AND lower(COALESCE(scope, '')) = lower(%s)
              AND lower(COALESCE(category, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(source_subtype, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(original_id, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(asset_identifier, '')) = lower(COALESCE(%s, ''))
              AND lower(COALESCE(employee_name, '')) = lower(COALESCE(%s, ''))
            LIMIT 1
            """,
            [
                int(job_id),
                source_type,
                group_id,
                source_name,
                site_id,
                scope,
                category,
                source_subtype,
                original_id,
                asset_identifier,
                employee_name,
            ],
        ).fetchone()
    )


def _resolve_factor(con, scope: str, original_id: str | None, factor_db_id: int | None, job_id: int | None = None) -> dict[str, Any]:
    out: dict[str, Any] = {
        "dataset_id": None,
        "factor_db_id": factor_db_id,
        "original_id": original_id,
        "factor": None,
        "ghg_unit": None,
        "category": None,
        "uom": None,
    }
    if factor_db_id is not None:
        row = con.execute(
            """
            SELECT db_id, dataset_id, original_id, factor, ghg_unit, category, uom
            FROM factor_lookup
            WHERE db_id=%s
            LIMIT 1
            """,
            [int(factor_db_id)],
        ).fetchone()
        if row:
            out["factor_db_id"] = _safe_int(row[0])
            out["dataset_id"] = _safe_int(row[1])
            out["original_id"] = str(row[2]).strip() if row[2] is not None else out["original_id"]
            out["factor"] = _safe_float(row[3])
            out["ghg_unit"] = str(row[4]).strip() if row[4] is not None else None
            out["category"] = str(row[5]).strip() if row[5] is not None else None
            out["uom"] = str(row[6]).strip() if row[6] is not None else None
            return out
    # Resolve the correct year's dataset for this job so we don't rely on
    # dataset_id ordering (which would pick the wrong year if datasets were
    # loaded out of chronological order).
    resolved_dataset_id: int | None = None
    if job_id is not None:
        try:
            from services.dataset_selector import resolve_dataset_resolution
            _resolution = resolve_dataset_resolution(int(job_id))
            _scope_map: dict[str, int] = {
                str(s): int(d)
                for s, d in (_resolution.get("scope_primary_datasets") or {}).items()
                if d is not None
            }
            resolved_dataset_id = _scope_map.get(str(scope))
        except Exception:
            pass
    lookup = _lookup_factor_from_reference(con, resolved_dataset_id, scope, original_id)
    if lookup:
        out["factor_db_id"] = lookup.get("db_id")
        out["factor"] = lookup.get("factor")
        out["ghg_unit"] = lookup.get("ghg_unit")
        row = con.execute(
            """
            SELECT dataset_id, original_id, category, uom
            FROM factor_lookup
            WHERE db_id=%s
            LIMIT 1
            """,
            [int(lookup["db_id"])],
        ).fetchone()
        if row:
            out["dataset_id"] = _safe_int(row[0])
            out["original_id"] = str(row[1]).strip() if row[1] is not None else out["original_id"]
            out["category"] = str(row[2]).strip() if row[2] is not None else None
            out["uom"] = str(row[3]).strip() if row[3] is not None else None
    return out


def _list_register(con, job_id: int, source_type: str | None, include_disabled: bool) -> dict[str, Any]:
    group_where = ["job_id=%s"]
    group_params: list[Any] = [int(job_id)]
    source_where = ["js.job_id=%s"]
    source_params: list[Any] = [int(job_id)]
    if source_type:
        group_where.append("group_type=%s")
        group_params.append(str(source_type))
        source_where.append("js.source_type=%s")
        source_params.append(str(source_type))
    if not include_disabled:
        group_where.append("COALESCE(enabled, TRUE) = TRUE")
        source_where.append("COALESCE(js.enabled, TRUE) = TRUE")

    groups_df = con.execute(
        f"""
        SELECT
          g.group_id, g.job_id, g.scope, g.category, g.group_type, g.group_name, g.site_id, cs.site_name,
          g.rollup_method, g.dataset_id, g.factor_db_id, g.original_id, g.factor, g.ghg_unit, g.uom,
          fl.report_label AS factor_report_label,
          g.notes, g.enabled, g.created_at, g.updated_at
        FROM job_emission_groups g
        LEFT JOIN client_sites cs ON cs.site_id = g.site_id
        LEFT JOIN factor_lookup fl ON fl.db_id = g.factor_db_id
        WHERE {" AND ".join(group_where)}
        ORDER BY g.group_name
        """,
        group_params,
    ).df()

    sources_df = con.execute(
        f"""
        SELECT
          js.source_id, js.job_id, js.group_id, g.group_name, js.scope, js.category,
          js.source_type, js.source_subtype, js.site_id, cs.site_name,
          js.source_name, js.asset_identifier, js.employee_name,
          g.dataset_id AS group_dataset_id, g.factor_db_id AS group_factor_db_id,
          g.original_id AS group_original_id, g.factor AS group_factor, g.ghg_unit AS group_ghg_unit, g.uom AS group_uom,
          COALESCE(g.dataset_id, js.dataset_id) AS dataset_id,
          COALESCE(g.factor_db_id, js.factor_db_id) AS factor_db_id,
          COALESCE(g.original_id, js.original_id) AS original_id,
          js.qty, COALESCE(g.uom, js.uom) AS uom, COALESCE(g.factor, js.factor) AS factor,
          COALESCE(g.ghg_unit, js.ghg_unit) AS ghg_unit,
          js.apply_pct, js.data_source, js.data_confidence, js.notes, js.detail_json, js.calc_tco2e,
          js.enabled, js.created_at, js.updated_at
        FROM job_emission_sources js
        LEFT JOIN job_emission_groups g ON g.group_id = js.group_id
        LEFT JOIN client_sites cs ON cs.site_id = js.site_id
        WHERE {" AND ".join(source_where)}
        ORDER BY COALESCE(g.group_name, ''), COALESCE(js.source_name, ''), js.source_id
        """,
        source_params,
    ).df()

    groups: list[dict[str, Any]] = []
    group_map: dict[int, list[dict[str, Any]]] = {}
    source_rows = [] if sources_df is None or sources_df.empty else sources_df.to_dict("records")
    for row in source_rows:
        gid = row.get("group_id")
        if gid is None:
            continue
        try:
            group_map.setdefault(int(gid), []).append(row)
        except Exception:
            pass

    if groups_df is not None and not groups_df.empty:
        for _, row in groups_df.iterrows():
            gid = _safe_int(row.get("group_id"))
            members = group_map.get(int(gid or 0), []) if gid is not None else []
            groups.append(
                {
                    "group_id": gid,
                    "job_id": _safe_int(row.get("job_id")),
                    "scope": row.get("scope"),
                    "category": row.get("category"),
                    "group_type": row.get("group_type"),
                    "group_name": row.get("group_name"),
                    "site_id": _safe_int(row.get("site_id")),
                    "site_name": row.get("site_name"),
                    "rollup_method": row.get("rollup_method"),
                    "dataset_id": _safe_int(row.get("dataset_id")),
                    "factor_db_id": _safe_int(row.get("factor_db_id")),
                    "original_id": row.get("original_id"),
                    "factor": _safe_float(row.get("factor")),
                    "ghg_unit": row.get("ghg_unit"),
                    "uom": row.get("uom"),
                    "factor_report_label": row.get("factor_report_label"),
                    "notes": row.get("notes"),
                    "enabled": bool(row.get("enabled")) if row.get("enabled") is not None else True,
                    "created_at": row.get("created_at"),
                    "updated_at": row.get("updated_at"),
                    "source_count": len(members),
                    "source_total_qty": round(sum(float(m.get("qty") or 0) for m in members), 4),
                    "source_total_tco2e": round(sum(float(m.get("calc_tco2e") or 0) for m in members), 4),
                }
            )

    sources: list[dict[str, Any]] = []
    total_tco2e = 0.0
    if source_rows:
        for row in source_rows:
            group_factor = _safe_float(row.get("group_factor"))
            factor = _safe_float(row.get("factor"))
            effective_factor = group_factor if group_factor is not None else factor
            group_ghg_unit = row.get("group_ghg_unit")
            ghg_unit = row.get("ghg_unit")
            effective_ghg_unit = group_ghg_unit if group_ghg_unit is not None else ghg_unit
            group_uom = row.get("group_uom")
            uom = row.get("uom")
            effective_uom = group_uom if group_uom is not None else uom
            calc_tco2e = _safe_float(row.get("calc_tco2e"))
            if calc_tco2e is None:
                calc_tco2e = _calc_tco2e(row.get("qty"), effective_factor, row.get("apply_pct"), effective_ghg_unit)
            total_tco2e += float(calc_tco2e or 0)
            sources.append(
                {
                    "source_id": _safe_int(row.get("source_id")),
                    "job_id": _safe_int(row.get("job_id")),
                    "group_id": _safe_int(row.get("group_id")),
                    "group_name": row.get("group_name"),
                    "group_dataset_id": _safe_int(row.get("group_dataset_id")),
                    "group_factor_db_id": _safe_int(row.get("group_factor_db_id")),
                    "group_original_id": row.get("group_original_id"),
                    "group_factor": group_factor,
                    "group_ghg_unit": group_ghg_unit,
                    "group_uom": group_uom,
                    "scope": row.get("scope"),
                    "category": row.get("category"),
                    "source_type": row.get("source_type"),
                    "source_subtype": row.get("source_subtype"),
                    "site_id": _safe_int(row.get("site_id")),
                    "site_name": row.get("site_name"),
                    "source_name": row.get("source_name"),
                    "asset_identifier": row.get("asset_identifier"),
                    "employee_name": row.get("employee_name"),
                    "dataset_id": _safe_int(row.get("dataset_id")),
                    "factor_db_id": _safe_int(row.get("factor_db_id")),
                    "original_id": row.get("original_id"),
                    "qty": _safe_float(row.get("qty")),
                    "uom": effective_uom,
                    "factor": effective_factor,
                    "ghg_unit": effective_ghg_unit,
                    "apply_pct": _safe_float(row.get("apply_pct")) or 100,
                    "data_source": row.get("data_source"),
                    "data_confidence": row.get("data_confidence"),
                    "notes": row.get("notes"),
                    "detail_json": row.get("detail_json") or {},
                    "calc_tco2e": round(float(calc_tco2e or 0), 4),
                    "enabled": bool(row.get("enabled")) if row.get("enabled") is not None else True,
                    "created_at": row.get("created_at"),
                    "updated_at": row.get("updated_at"),
                }
            )

    return {
        "job_id": int(job_id),
        "source_type": source_type,
        "summary": {
            "group_count": len(groups),
            "source_count": len(sources),
            "enabled_source_count": sum(1 for row in sources if row["enabled"]),
            "disabled_source_count": sum(1 for row in sources if not row["enabled"]),
            "ungrouped_source_count": sum(1 for row in sources if row["group_id"] is None),
            "total_tco2e": round(total_tco2e, 4),
        },
        "groups": groups,
        "sources": sources,
    }


@router.get("/jobs/{job_id}/emission-registers/template")
def download_emission_register_template(
    job_id: int,
    source_type: str = Query("asset"),
    kind: str = Query("template"),
    site_id: int | None = Query(None),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            job_row = con.execute(
                "SELECT client_db_id FROM jobs WHERE job_id=%s",
                [int(job_id)],
            ).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            if site_id is not None:
                site_row = con.execute(
                    """
                    SELECT 1
                    FROM client_sites
                    WHERE site_id=%s AND client_db_id=%s
                    LIMIT 1
                    """,
                    [int(site_id), _safe_int(job_row[0])],
                ).fetchone()
                if not site_row:
                    raise HTTPException(status_code=400, detail="Selected site does not belong to this job")
            source_type_value = str(source_type or "asset").strip() or "asset"
            if source_type_value == "business_travel":
                client_row = con.execute(
                    """
                    SELECT c.client_name, j.job_number, j.reporting_year, cs.site_name
                    FROM jobs j
                    JOIN clients c ON c.db_id = j.client_db_id
                    LEFT JOIN client_sites cs ON cs.site_id = %s
                    WHERE j.job_id=%s
                    """,
                    [_safe_int(site_id), int(job_id)],
                ).fetchone()
                payload, file_name = generate_business_travel_upload_template(
                    job_id=int(job_id),
                    client_name=str(client_row[0]) if client_row and client_row[0] is not None else "",
                    site_name=str(client_row[3]) if client_row and len(client_row) > 3 and client_row[3] is not None else "",
                    job_number=str(client_row[1]) if client_row and client_row[1] is not None else "",
                    reporting_year=str(client_row[2]) if client_row and client_row[2] is not None else "",
                    site_id=_safe_int(site_id),
                    include_prev_year=str(kind or "template").strip().lower() != "example",
                )
            else:
                payload, file_name = build_emission_register_workbook(
                    con,
                    job_id=int(job_id),
                    source_type=source_type_value,
                    kind=str(kind or "template").strip() or "template",
                    site_id=_safe_int(site_id),
                )
        return Response(
            content=payload,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{file_name}"'},
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to build emission register workbook: {e}")


@router.get("/jobs/{job_id}/emission-registers")
def get_emission_registers(
    job_id: int,
    source_type: str | None = None,
    include_disabled: bool = Query(False),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            return _list_register(con, int(job_id), source_type, include_disabled)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load emission register: {e}")


@router.post("/jobs/{job_id}/emission-registers/groups")
def create_emission_group(
    job_id: int,
    payload: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            scope = str(payload.get("scope") or "").strip()
            group_name = str(payload.get("group_name") or "").strip()
            if not scope or not group_name:
                raise HTTPException(status_code=400, detail="scope and group_name are required")
            group_type = str(payload.get("group_type") or "asset").strip() or "asset"
            factor_db_id = _safe_int(payload.get("factor_db_id"))
            original_id = str(payload.get("original_id") or "").strip() or None
            resolved = _resolve_factor(con, scope, original_id, factor_db_id, job_id=int(job_id))
            if resolved.get("factor_db_id") is None and resolved.get("original_id") is None:
                raise HTTPException(status_code=400, detail="factor_db_id or original_id is required for the group")
            row = con.execute(
                """
                INSERT INTO job_emission_groups (
                    job_id, scope, category, group_type, group_name, site_id, rollup_method,
                    dataset_id, factor_db_id, original_id, factor, ghg_unit, uom, notes
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING group_id
                """,
                [
                    int(job_id),
                    scope,
                    payload.get("category"),
                    group_type,
                    group_name,
                    _safe_int(payload.get("site_id")),
                    str(payload.get("rollup_method") or "sum"),
                    _safe_int(resolved.get("dataset_id")),
                    _safe_int(resolved.get("factor_db_id")),
                    resolved.get("original_id"),
                    resolved.get("factor"),
                    resolved.get("ghg_unit"),
                    resolved.get("uom"),
                    payload.get("notes"),
                ],
            ).fetchone()
            return {"ok": True, "group_id": int(row[0]) if row else None, "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create emission group: {e}")


@router.delete("/jobs/{job_id}/emission-registers/groups/{group_id}")
def delete_emission_group(
    job_id: int,
    group_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            con.execute(
                "UPDATE job_emission_groups SET enabled=FALSE, updated_at=NOW() WHERE group_id=%s AND job_id=%s",
                [int(group_id), int(job_id)],
            )
            return {"ok": True, "group_id": int(group_id), "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete emission group: {e}")


@router.post("/jobs/{job_id}/emission-registers/sources")
def create_emission_source(
    job_id: int,
    payload: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            group_id = _safe_int(payload.get("group_id"))
            source_name = str(payload.get("source_name") or "").strip()
            if group_id is None or not source_name:
                raise HTTPException(status_code=400, detail="group_id and source_name are required")
            source_type = str(payload.get("source_type") or "asset").strip() or "asset"
            group_row = con.execute(
                """
                SELECT
                  g.group_id, g.scope, g.category, g.site_id, g.group_type,
                  g.dataset_id, g.factor_db_id, g.original_id, g.factor, g.ghg_unit, g.uom
                FROM job_emission_groups g
                WHERE g.group_id=%s AND g.job_id=%s AND COALESCE(g.enabled, TRUE) = TRUE
                """,
                [int(group_id), int(job_id)],
            ).fetchone()
            if not group_row:
                raise HTTPException(status_code=400, detail="Selected group does not belong to this job")
            scope = str(group_row[1] or "").strip()
            if not scope:
                raise HTTPException(status_code=400, detail="Selected group is missing scope")
            category = str(group_row[2]).strip() if group_row[2] is not None else None
            site_id = _safe_int(group_row[3])
            group_type = str(group_row[4] or source_type).strip() or source_type
            dataset_id = _safe_int(group_row[5])
            factor_db_id = _safe_int(group_row[6])
            original_id = str(group_row[7]).strip() if group_row[7] is not None else None
            factor = _safe_float(group_row[8])
            ghg_unit = str(group_row[9]).strip() if group_row[9] is not None else None
            uom = str(group_row[10]).strip() if group_row[10] is not None else None
            if factor_db_id is None and original_id is None:
                raise HTTPException(status_code=400, detail="Selected group needs a factor before assets can be added")
            qty = _safe_float(payload.get("qty"))
            apply_pct = _safe_float(payload.get("apply_pct"), 100) or 100
            calc_tco2e = _calc_tco2e(qty, factor, apply_pct, ghg_unit)
            detail_json = payload.get("detail_json") or payload.get("details") or {}

            row = con.execute(
                """
                INSERT INTO job_emission_sources (
                    job_id, group_id, scope, category, source_type, source_subtype, site_id,
                    source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                    qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                    detail_json, calc_tco2e
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
                RETURNING source_id
                """,
                [
                    int(job_id),
                    group_id,
                    scope,
                    category,
                    group_type,
                    str(payload.get("source_subtype") or "").strip() or None,
                    site_id,
                    source_name,
                    str(payload.get("asset_identifier") or "").strip() or None,
                    str(payload.get("employee_name") or "").strip() or None,
                    dataset_id,
                    factor_db_id,
                    original_id,
                    qty,
                    uom,
                    factor,
                    ghg_unit,
                    apply_pct,
                    payload.get("data_source") or "Source Register",
                    payload.get("data_confidence") or "M",
                    payload.get("notes"),
                    detail_json,
                    calc_tco2e,
                ],
            ).fetchone()
            return {"ok": True, "source_id": int(row[0]) if row else None, "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create emission source: {e}")


@router.delete("/jobs/{job_id}/emission-registers/sources/{source_id}")
def delete_emission_source(
    job_id: int,
    source_id: int,
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            con.execute(
                "UPDATE job_emission_sources SET enabled=FALSE, updated_at=NOW() WHERE source_id=%s AND job_id=%s",
                [int(source_id), int(job_id)],
            )
            return {"ok": True, "source_id": int(source_id), "job_id": int(job_id)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete emission source: {e}")


@router.post("/jobs/{job_id}/emission-registers/import-workbook")
async def import_emission_register_workbook(
    job_id: int,
    file: UploadFile = File(...),
    source_type: str = Query("asset"),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        content = await file.read()
        if not content:
            raise HTTPException(status_code=400, detail="Empty workbook upload")

        workbook = load_workbook(io.BytesIO(content), data_only=True)
        if "Groups" not in workbook.sheetnames or "Sources" not in workbook.sheetnames:
            raise HTTPException(status_code=400, detail="Workbook must contain Groups and Sources sheets")

        groups_sheet = workbook["Groups"]
        sources_sheet = workbook["Sources"]
        group_rows = _sheet_rows(groups_sheet, _GROUP_HEADER_ALIASES)
        source_rows = _sheet_rows(sources_sheet, _SOURCE_HEADER_ALIASES)
        source_type_value = str(source_type or "asset").strip() or "asset"
        default_scope = "Scope 3" if source_type_value == "business_travel" else "Scope 1"
        actor = str(_user.get("email", "unknown"))

        with get_conn(autocommit=False) as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")

            group_map: dict[str, int] = {}
            inserted_groups = 0
            reused_groups = 0

            for row in group_rows:
                group_name = str(row.get("group_name") or "").strip()
                if not group_name:
                    continue
                scope = str(row.get("scope") or default_scope).strip() or default_scope
                group_type = str(row.get("group_type") or source_type_value).strip() or source_type_value
                category = str(row.get("category") or "").strip() or None
                site_id = _safe_int(row.get("site_id")) or _resolve_site_id(con, row.get("site_name"))
                rollup_method = str(row.get("rollup_method") or "sum").strip() or "sum"
                notes = str(row.get("notes") or "").strip() or None
                group_factor_db_id = _safe_int(row.get("factor_db_id"))
                group_original_id = str(row.get("original_id") or "").strip() or None
                resolved = _resolve_factor(con, scope, group_original_id, group_factor_db_id, job_id=int(job_id))
                group_id, created = _ensure_register_group(
                    con,
                    job_id=int(job_id),
                    group_name=group_name,
                    scope=scope,
                    group_type=group_type,
                    category=category,
                    site_id=site_id,
                    rollup_method=rollup_method,
                    dataset_id=_safe_int(row.get("dataset_id")) or _safe_int(resolved.get("dataset_id")),
                    factor_db_id=group_factor_db_id or _safe_int(resolved.get("factor_db_id")),
                    original_id=group_original_id or resolved.get("original_id"),
                    factor=_safe_float(row.get("factor"), resolved.get("factor")),
                    ghg_unit=str(row.get("ghg_unit") or resolved.get("ghg_unit") or "").strip() or None,
                    uom=str(row.get("uom") or resolved.get("uom") or "").strip() or None,
                    notes=notes,
                )
                if group_id is not None:
                    group_map[group_name.lower()] = int(group_id)
                if created:
                    inserted_groups += 1
                else:
                    reused_groups += 1

            inserted_sources = 0
            skipped_sources = 0
            auto_groups_created = 0

            for idx, row in enumerate(source_rows, start=2):
                source_name = str(row.get("source_name") or "").strip()
                if not source_name:
                    continue
                group_name = str(row.get("group_name") or "").strip()
                scope = str(row.get("scope") or default_scope).strip() or default_scope
                category = str(row.get("category") or "").strip() or None
                group_type = str(row.get("source_type") or source_type_value).strip() or source_type_value
                source_subtype = str(row.get("source_subtype") or "").strip() or None
                site_id = _safe_int(row.get("site_id")) or _resolve_site_id(con, row.get("site_name"))
                asset_identifier = str(row.get("asset_identifier") or "").strip() or None
                employee_name = str(row.get("employee_name") or "").strip() or None
                original_id = str(row.get("original_id") or "").strip() or None
                factor_db_id = _safe_int(row.get("factor_db_id"))
                resolved = _resolve_factor(con, scope, original_id, factor_db_id, job_id=int(job_id))
                qty = _safe_float(row.get("qty"), 0) or 0
                factor = _safe_float(row.get("factor"), resolved.get("factor"))
                apply_pct = _safe_float(row.get("apply_pct"), 100) or 100
                ghg_unit = row.get("ghg_unit") or resolved.get("ghg_unit")
                uom = str(row.get("uom") or resolved.get("uom") or "").strip() or None
                data_source = str(row.get("data_source") or "Asset Register Import").strip() or "Asset Register Import"
                data_confidence = str(row.get("data_confidence") or "M").strip() or "M"
                notes = str(row.get("notes") or "").strip() or None

                group_id = None
                if group_name:
                    group_id = group_map.get(group_name.lower())
                    if group_id is None:
                        group_id, created = _ensure_register_group(
                            con,
                            job_id=int(job_id),
                            group_name=group_name,
                            scope=scope,
                            group_type=group_type,
                            category=category,
                            site_id=site_id,
                            rollup_method="sum",
                            notes=None,
                        )
                        if group_id is not None:
                            group_map[group_name.lower()] = int(group_id)
                        if created:
                            auto_groups_created += 1

                group_factor = {
                    "dataset_id": None,
                    "factor_db_id": None,
                    "original_id": None,
                    "factor": None,
                    "ghg_unit": None,
                    "uom": None,
                    "scope": scope,
                    "category": category,
                    "site_id": site_id,
                }
                if group_id is not None:
                    group_row = con.execute(
                        """
                        SELECT dataset_id, factor_db_id, original_id, factor, ghg_unit, uom, scope, category, site_id
                        FROM job_emission_groups
                        WHERE group_id=%s
                        """,
                        [int(group_id)],
                    ).fetchone()
                    if group_row:
                        group_factor = {
                            "dataset_id": _safe_int(group_row[0]),
                            "factor_db_id": _safe_int(group_row[1]),
                            "original_id": str(group_row[2]).strip() if group_row[2] is not None else None,
                            "factor": _safe_float(group_row[3]),
                            "ghg_unit": str(group_row[4]).strip() if group_row[4] is not None else None,
                            "uom": str(group_row[5]).strip() if group_row[5] is not None else None,
                            "scope": str(group_row[6] or scope).strip() or scope,
                            "category": str(group_row[7]).strip() if group_row[7] is not None else category,
                            "site_id": _safe_int(group_row[8]) if group_row[8] is not None else site_id,
                        }
                        if (
                            group_factor["factor_db_id"] is None
                            and group_factor["original_id"] is None
                            and (resolved.get("factor_db_id") is not None or resolved.get("original_id") is not None)
                        ):
                            _ensure_register_group(
                                con,
                                job_id=int(job_id),
                                group_name=group_name,
                                scope=group_factor["scope"],
                                group_type=group_type,
                                category=group_factor["category"],
                                site_id=group_factor["site_id"],
                                rollup_method="sum",
                                dataset_id=_safe_int(resolved.get("dataset_id")),
                                factor_db_id=_safe_int(resolved.get("factor_db_id")),
                                original_id=resolved.get("original_id"),
                                factor=resolved.get("factor"),
                                ghg_unit=resolved.get("ghg_unit"),
                                uom=resolved.get("uom"),
                                notes=None,
                            )
                            group_row = con.execute(
                                """
                                SELECT dataset_id, factor_db_id, original_id, factor, ghg_unit, uom, scope, category, site_id
                                FROM job_emission_groups
                                WHERE group_id=%s
                                """,
                                [int(group_id)],
                            ).fetchone()
                            if group_row:
                                group_factor = {
                                    "dataset_id": _safe_int(group_row[0]),
                                    "factor_db_id": _safe_int(group_row[1]),
                                    "original_id": str(group_row[2]).strip() if group_row[2] is not None else None,
                                    "factor": _safe_float(group_row[3]),
                                    "ghg_unit": str(group_row[4]).strip() if group_row[4] is not None else None,
                                    "uom": str(group_row[5]).strip() if group_row[5] is not None else None,
                                    "scope": str(group_row[6] or scope).strip() or scope,
                                    "category": str(group_row[7]).strip() if group_row[7] is not None else category,
                                    "site_id": _safe_int(group_row[8]) if group_row[8] is not None else site_id,
                                }
                        scope = group_factor["scope"]
                        category = group_factor["category"]
                        site_id = group_factor["site_id"]

                if _register_source_exists(
                    con,
                    job_id=int(job_id),
                    source_type=group_type,
                    group_id=group_id,
                    source_name=source_name,
                    site_id=site_id,
                    scope=scope,
                    category=category,
                    source_subtype=source_subtype,
                    original_id=original_id,
                    asset_identifier=asset_identifier,
                    employee_name=employee_name,
                ):
                    skipped_sources += 1
                    continue

                factor = group_factor["factor"] if group_factor["factor"] is not None else _safe_float(resolved.get("factor"))
                ghg_unit = group_factor["ghg_unit"] or ghg_unit or resolved.get("ghg_unit")
                uom = group_factor["uom"] or uom or str(resolved.get("uom") or "").strip() or None
                dataset_id = group_factor["dataset_id"] if group_factor["dataset_id"] is not None else _safe_int(resolved.get("dataset_id"))
                factor_db_id = group_factor["factor_db_id"] if group_factor["factor_db_id"] is not None else _safe_int(resolved.get("factor_db_id"))
                original_id = group_factor["original_id"] or resolved.get("original_id") or original_id
                if factor_db_id is None and original_id is None:
                    raise HTTPException(status_code=400, detail=f"Row {idx} needs a factor for its group")

                calc_tco2e = _calc_tco2e(qty, factor, apply_pct, ghg_unit)
                detail_json = {
                    "import_source": "workbook",
                    "workbook_name": file.filename,
                    "source_row": idx,
                    "group_name": group_name or None,
                }
                row = con.execute(
                    """
                    INSERT INTO job_emission_sources (
                        job_id, group_id, scope, category, source_type, source_subtype, site_id,
                        source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                        qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                        detail_json, calc_tco2e
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                    )
                    RETURNING source_id
                    """,
                    [
                        int(job_id),
                        group_id,
                        scope,
                        category or resolved.get("category"),
                        group_type,
                        source_subtype,
                        site_id,
                        source_name,
                        asset_identifier,
                        employee_name,
                        dataset_id,
                        factor_db_id,
                        original_id,
                        qty,
                        uom or resolved.get("uom"),
                        factor,
                        ghg_unit,
                        apply_pct,
                        data_source,
                        data_confidence,
                        notes,
                        detail_json,
                        calc_tco2e,
                    ],
                ).fetchone()
                if row:
                    inserted_sources += 1

            record_audit_event(
                con,
                request=None,
                actor={"email": actor},
                action="create",
                entity_type="job_emission_register_import",
                entity_id=None,
                job_id=int(job_id),
                after={
                    "source_type": source_type_value,
                    "inserted_groups": inserted_groups,
                    "reused_groups": reused_groups,
                    "auto_groups_created": auto_groups_created,
                    "inserted_sources": inserted_sources,
                    "skipped_sources": skipped_sources,
                    "filename": file.filename,
                },
            )

            summary = _list_register(con, int(job_id), source_type_value, False).get("summary", {})

        return {
            "ok": True,
            "job_id": int(job_id),
            "source_type": source_type_value,
            "inserted_groups": inserted_groups,
            "reused_groups": reused_groups,
            "auto_groups_created": auto_groups_created,
            "inserted_sources": inserted_sources,
            "skipped_sources": skipped_sources,
            "summary": summary,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to import emission register workbook: {e}")


@router.post("/jobs/{job_id}/emission-registers/rollforward")
def rollforward_emission_register(
    job_id: int,
    source_type: str = Query("asset"),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        source_type_value = str(source_type or "asset").strip() or "asset"
        default_scope = "Scope 3" if source_type_value == "business_travel" else "Scope 1"
        actor = str(_user.get("email", "unknown"))

        with get_conn(autocommit=False) as con:
            _ensure_schema(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")

            previous_job = _resolve_previous_register_job_id(con, int(job_id))
            if not previous_job or previous_job.get("job_id") is None:
                raise HTTPException(status_code=400, detail="No previous job found for roll-forward")

            previous_job_id = int(previous_job["job_id"])

            # Resolve current job's active dataset per scope using the same
            # automatic year-based picker the rest of the app uses.
            try:
                from services.dataset_selector import resolve_dataset_resolution
                _resolution = resolve_dataset_resolution(int(job_id))
                current_dataset_by_scope: dict[str, int] = {
                    str(s): int(d)
                    for s, d in (_resolution.get("scope_primary_datasets") or {}).items()
                    if d is not None
                }
            except Exception:
                current_dataset_by_scope = {}

            group_rows = con.execute(
                """
                SELECT group_id, scope, category, group_type, group_name, site_id, rollup_method,
                       dataset_id, factor_db_id, original_id, factor, ghg_unit, uom, notes
                FROM job_emission_groups
                WHERE job_id=%s
                  AND lower(COALESCE(group_type, '')) = lower(%s)
                  AND COALESCE(enabled, TRUE) = TRUE
                ORDER BY group_name, group_id
                """,
                [previous_job_id, source_type_value],
            ).fetchall()

            source_rows = con.execute(
                """
                SELECT
                  source_id, group_id, scope, category, source_type, source_subtype, site_id,
                  source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                  qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes, detail_json
                FROM job_emission_sources
                WHERE job_id=%s
                  AND lower(COALESCE(source_type, '')) = lower(%s)
                  AND COALESCE(enabled, TRUE) = TRUE
                ORDER BY COALESCE(group_id, 0), source_name, source_id
                """,
                [previous_job_id, source_type_value],
            ).fetchall()

            previous_group_map: dict[int, dict[str, Any]] = {}
            new_group_map: dict[int, int] = {}
            inserted_groups = 0
            reused_groups = 0
            inserted_sources = 0
            skipped_sources = 0

            for row in group_rows or []:
                old_group_id = _safe_int(row[0])
                group_name = str(row[4] or "").strip()
                scope = str(row[1] or default_scope).strip() or default_scope
                category = str(row[2] or "").strip() or None
                group_name = group_name or f"{source_type_value} group {old_group_id}"
                site_id = _safe_int(row[5])
                rollup_method = str(row[6] or "sum").strip() or "sum"
                dataset_id = _safe_int(row[7])
                factor_db_id = _safe_int(row[8])
                original_id = str(row[9] or "").strip() or None
                factor = _safe_float(row[10])
                ghg_unit = str(row[11] or "").strip() or None
                uom = str(row[12] or "").strip() or None
                notes = str(row[13] or "").strip() or None

                # Re-lookup factor at current year's rates
                _current_ds = current_dataset_by_scope.get(scope)
                if _current_ds and original_id:
                    _refreshed = _lookup_factor_from_reference(con, _current_ds, scope, original_id)
                    if _refreshed:
                        dataset_id = _current_ds
                        factor_db_id = _refreshed["db_id"]
                        factor = _refreshed["factor"]
                        ghg_unit = _refreshed["ghg_unit"]
                    else:
                        dataset_id = _current_ds

                group_id, created = _ensure_register_group(
                    con,
                    job_id=int(job_id),
                    group_name=group_name,
                    scope=scope,
                    group_type=source_type_value,
                    category=category,
                    site_id=site_id,
                    rollup_method=rollup_method,
                    dataset_id=dataset_id,
                    factor_db_id=factor_db_id,
                    original_id=original_id,
                    factor=factor,
                    ghg_unit=ghg_unit,
                    uom=uom,
                    notes=notes,
                )
                if old_group_id is not None:
                    previous_group_map[int(old_group_id)] = {
                        "group_name": group_name,
                        "scope": scope,
                        "category": category,
                        "site_id": site_id,
                        "rollup_method": rollup_method,
                        "dataset_id": dataset_id,
                        "factor_db_id": factor_db_id,
                        "original_id": original_id,
                        "factor": factor,
                        "ghg_unit": ghg_unit,
                        "uom": uom,
                    }
                if group_id is not None:
                    new_group_map[int(old_group_id)] = int(group_id)
                if created:
                    inserted_groups += 1
                else:
                    reused_groups += 1

            for row in source_rows or []:
                old_group_id = _safe_int(row[1])
                group_id = new_group_map.get(int(old_group_id)) if old_group_id is not None else None
                group_meta = previous_group_map.get(int(old_group_id)) if old_group_id is not None else None
                scope = str(row[2] or default_scope).strip() or default_scope
                category = str(row[3] or "").strip() or None
                source_subtype = str(row[5] or "").strip() or None
                site_id = _safe_int(row[6])
                source_name = str(row[7] or "").strip()
                asset_identifier = str(row[8] or "").strip() or None
                employee_name = str(row[9] or "").strip() or None
                dataset_id = _safe_int(row[10])
                factor_db_id = _safe_int(row[11])
                original_id = str(row[12] or "").strip() or None
                qty = 0.0
                uom = str(row[14] or "").strip() or None
                factor = _safe_float(row[15])
                ghg_unit = str(row[16] or "").strip() or None
                apply_pct = _safe_float(row[17]) or 100
                data_source = "Previous Year Import"
                data_confidence = str(row[19] or "M").strip() or "M"
                notes = str(row[20] or "").strip() or None
                detail_json = row[21] if isinstance(row[21], dict) else {}
                if not source_name:
                    continue

                # Prefer source-row original_id; fall back to group-level
                effective_original_id = original_id or (group_meta or {}).get("original_id")
                effective_uom = uom or (group_meta or {}).get("uom")

                # Re-lookup factor at current year's rates using the automatic
                # year-based dataset for this scope.
                _current_ds = current_dataset_by_scope.get(scope)
                if _current_ds and effective_original_id:
                    _refreshed = _lookup_factor_from_reference(con, _current_ds, scope, effective_original_id)
                    if _refreshed:
                        effective_dataset_id = _current_ds
                        effective_factor_db_id = _refreshed["db_id"]
                        effective_factor = _refreshed["factor"]
                        effective_ghg_unit = _refreshed["ghg_unit"]
                    else:
                        effective_dataset_id = _current_ds
                        effective_factor_db_id = factor_db_id
                        effective_factor = factor
                        effective_ghg_unit = ghg_unit
                else:
                    effective_dataset_id = dataset_id
                    effective_factor_db_id = factor_db_id
                    effective_factor = factor
                    effective_ghg_unit = ghg_unit

                if _register_source_exists(
                    con,
                    job_id=int(job_id),
                    source_type=source_type_value,
                    group_id=group_id,
                    source_name=source_name,
                    site_id=site_id,
                    scope=scope,
                    category=category,
                    source_subtype=source_subtype,
                    original_id=original_id,
                    asset_identifier=asset_identifier,
                    employee_name=employee_name,
                ):
                    # Row already exists — refresh factor fields to current year
                    # rates but leave qty and user-entered data untouched.
                    con.execute(
                        """
                        UPDATE job_emission_sources
                        SET dataset_id=%s,
                            factor_db_id=%s,
                            factor=%s,
                            ghg_unit=%s,
                            calc_tco2e = CASE
                                WHEN COALESCE(qty, 0) <> 0
                                THEN qty * %s * COALESCE(apply_pct, 100) / 100.0
                                ELSE calc_tco2e
                            END
                        WHERE job_id=%s
                          AND lower(COALESCE(source_type,''))=lower(%s)
                          AND COALESCE(group_id,-1)=COALESCE(%s,-1)
                          AND lower(COALESCE(source_name,''))=lower(%s)
                          AND COALESCE(site_id,-1)=COALESCE(%s,-1)
                          AND lower(COALESCE(scope,''))=lower(%s)
                          AND lower(COALESCE(category,''))=lower(COALESCE(%s,''))
                          AND lower(COALESCE(source_subtype,''))=lower(COALESCE(%s,''))
                          AND lower(COALESCE(original_id,''))=lower(COALESCE(%s,''))
                          AND lower(COALESCE(asset_identifier,''))=lower(COALESCE(%s,''))
                          AND lower(COALESCE(employee_name,''))=lower(COALESCE(%s,''))
                        """,
                        [
                            effective_dataset_id, effective_factor_db_id,
                            effective_factor, effective_ghg_unit,
                            effective_factor,  # for calc_tco2e recalculation
                            int(job_id), source_type_value, group_id, source_name,
                            site_id, scope, category, source_subtype,
                            original_id, asset_identifier, employee_name,
                        ],
                    )
                    skipped_sources += 1
                    continue

                calc_tco2e = 0.0
                merged_detail_json = {
                    **(detail_json if isinstance(detail_json, dict) else {}),
                    "rollforward_from_job_id": previous_job_id,
                    "rollforward_from_source_id": _safe_int(row[0]),
                    "rollforward_source_type": source_type_value,
                    "rollforward_imported_at": datetime.now().isoformat(),
                }
                inserted = con.execute(
                    """
                    INSERT INTO job_emission_sources (
                        job_id, group_id, scope, category, source_type, source_subtype, site_id,
                        source_name, asset_identifier, employee_name, dataset_id, factor_db_id, original_id,
                        qty, uom, factor, ghg_unit, apply_pct, data_source, data_confidence, notes,
                        detail_json, calc_tco2e
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                    )
                    RETURNING source_id
                    """,
                    [
                        int(job_id),
                        group_id,
                        scope,
                        category or (group_meta or {}).get("category"),
                        source_type_value,
                        source_subtype,
                        site_id,
                        source_name,
                        asset_identifier,
                        employee_name,
                        effective_dataset_id,
                        effective_factor_db_id,
                        effective_original_id,
                        qty,
                        effective_uom,
                        effective_factor,
                        effective_ghg_unit,
                        apply_pct,
                        data_source,
                        data_confidence,
                        notes,
                        merged_detail_json,
                        calc_tco2e,
                    ],
                ).fetchone()
                if inserted:
                    inserted_sources += 1

            record_audit_event(
                con,
                request=None,
                actor={"email": actor},
                action="create",
                entity_type="job_emission_register_rollforward",
                entity_id=None,
                job_id=int(job_id),
                before={
                    "source_job_id": previous_job_id,
                    "source_job_number": previous_job.get("job_number"),
                },
                after={
                    "source_type": source_type_value,
                    "inserted_groups": inserted_groups,
                    "reused_groups": reused_groups,
                    "inserted_sources": inserted_sources,
                    "skipped_sources": skipped_sources,
                },
            )

            summary = _list_register(con, int(job_id), source_type_value, False).get("summary", {})

        return {
            "ok": True,
            "job_id": int(job_id),
            "source_type": source_type_value,
            "previous_job": previous_job,
            "inserted_groups": inserted_groups,
            "reused_groups": reused_groups,
            "inserted_sources": inserted_sources,
            "skipped_sources": skipped_sources,
            "summary": summary,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to roll forward emission register: {e}")
