from __future__ import annotations

from datetime import date, datetime, timedelta
import os
import re
import json
import io
from urllib import parse as urlparse
from urllib import request as urlrequest
from urllib.error import HTTPError
import html
from typing import Any

from fastapi import APIRouter, Body, Depends, File, Form, Header, HTTPException, Query, UploadFile
from fastapi.responses import PlainTextResponse, Response

from api.auth import _current_user
from core.database import get_conn
from services.company_profile import company_address_html, company_footer_text, get_company_profile
from services.messaging_templates import build_email_content, get_user_signature_html
from services.outbound_email import list_outbound_emails, send_tracked_email
from api.job_files_routes import _read_job_file_bytes
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

router = APIRouter(tags=["job-communications"])

_communications_schema_seeded: bool = False


def _actor(user: dict) -> str:
    return str(user.get("email") or user.get("user_id") or "system").strip()


def _ensure_tables(con) -> None:
    global _communications_schema_seeded
    if _communications_schema_seeded:
        return
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_communications (
          communication_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL,
          client_db_id INTEGER,
          direction VARCHAR NOT NULL DEFAULT 'internal',
          channel VARCHAR NOT NULL DEFAULT 'note',
          subject TEXT,
          message_text TEXT NOT NULL,
          scope VARCHAR,
          category VARCHAR,
          site_id INTEGER,
          site_name VARCHAR,
          from_name VARCHAR,
          from_email VARCHAR,
          to_name VARCHAR,
          to_email VARCHAR,
          status VARCHAR NOT NULL DEFAULT 'logged',
          event_at TIMESTAMP,
          requires_follow_up BOOLEAN NOT NULL DEFAULT FALSE,
          follow_up_due DATE,
          is_private BOOLEAN NOT NULL DEFAULT FALSE,
          archived BOOLEAN NOT NULL DEFAULT FALSE,
          archived_at TIMESTAMP,
          archived_by VARCHAR,
          automation_key VARCHAR,
          created_by VARCHAR NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP
        )
        """
    )
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_communication_tasks (
          task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL,
          communication_id INTEGER,
          title TEXT NOT NULL,
          details TEXT,
          assigned_to VARCHAR,
          priority VARCHAR NOT NULL DEFAULT 'normal',
          status VARCHAR NOT NULL DEFAULT 'open',
          due_date DATE,
          created_by VARCHAR NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP,
          completed_at TIMESTAMP,
          completed_by VARCHAR
        )
        """
    )
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS automation_key VARCHAR")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS event_at TIMESTAMP")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT FALSE")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS requires_follow_up BOOLEAN NOT NULL DEFAULT FALSE")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS follow_up_due DATE")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS scope VARCHAR")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS category VARCHAR")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS site_id INTEGER")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS site_name VARCHAR")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS archived_by VARCHAR")
    con.execute("ALTER TABLE job_communications ADD COLUMN IF NOT EXISTS updated_by VARCHAR")
    _communications_schema_seeded = True


def _coerce_int(value: Any) -> int | None:
    if value is None or str(value).strip() == "":
        return None
    try:
        return int(float(value))
    except Exception:
        return None


def _resolve_site_details(con, client_db_id: int | None, site_id: Any = None, site_name: Any = None) -> dict[str, Any]:
    site_id_val = _coerce_int(site_id)
    site_name_val = str(site_name or "").strip() or None

    if client_db_id is None:
        return {"site_id": site_id_val, "site_name": site_name_val}

    if site_id_val is not None:
        if not site_name_val:
            row = con.execute(
                """
                SELECT site_name
                FROM client_sites
                WHERE client_db_id = %s AND site_id = %s
                LIMIT 1
                """,
                [int(client_db_id), int(site_id_val)],
            ).fetchone()
            if row and row[0] is not None:
                site_name_val = str(row[0]).strip() or None
        return {"site_id": site_id_val, "site_name": site_name_val}

    if site_name_val:
        row = con.execute(
            """
            SELECT site_id, site_name
            FROM client_sites
            WHERE client_db_id = %s AND lower(coalesce(site_name, '')) = lower(%s)
            ORDER BY is_registered_office DESC, site_id ASC
            LIMIT 1
            """,
            [int(client_db_id), site_name_val],
        ).fetchone()
        if row:
            return {
                "site_id": int(row[0]) if row[0] is not None else None,
                "site_name": str(row[1] or site_name_val).strip() or None,
            }

    row = con.execute(
        """
        SELECT site_id, site_name
        FROM client_sites
        WHERE client_db_id = %s
        ORDER BY COALESCE(is_registered_office, FALSE) DESC, lower(coalesce(site_name, '')) ASC, site_id ASC
        LIMIT 1
        """,
        [int(client_db_id)],
    ).fetchone()
    if row:
        return {
            "site_id": int(row[0]) if row[0] is not None else None,
            "site_name": str(row[1] or "").strip() or None,
        }
    return {"site_id": None, "site_name": None}


def _milestone_status(due_date: Any, completed_at: Any) -> str:
    if completed_at:
        return "completed"
    if not due_date:
        return "green"
    if hasattr(due_date, "date"):
        try:
            due_date = due_date.date()
        except Exception:
            pass
    if isinstance(due_date, str):
        try:
            due_date = datetime.strptime(due_date[:10], "%Y-%m-%d").date()
        except Exception:
            return "green"
    if not isinstance(due_date, date):
        return "green"
    days_until_due = (due_date - date.today()).days
    if days_until_due < -1:
        return "red"
    if days_until_due <= 7:
        return "amber"
    return "green"


def _serialize_comm(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "communication_id": int(row.get("communication_id")),
        "job_id": int(row.get("job_id")),
        "client_db_id": int(row.get("client_db_id")) if row.get("client_db_id") is not None else None,
        "direction": str(row.get("direction") or "internal"),
        "channel": str(row.get("channel") or "note"),
        "subject": str(row.get("subject") or ""),
        "message_text": str(row.get("message_text") or ""),
        "scope": str(row.get("scope") or ""),
        "category": str(row.get("category") or ""),
        "site_id": int(row.get("site_id")) if row.get("site_id") is not None else None,
        "site_name": str(row.get("site_name") or ""),
        "from_name": str(row.get("from_name") or ""),
        "from_email": str(row.get("from_email") or ""),
        "to_name": str(row.get("to_name") or ""),
        "to_email": str(row.get("to_email") or ""),
        "status": str(row.get("status") or "logged"),
        "event_at": row.get("event_at").isoformat() if row.get("event_at") else None,
        "requires_follow_up": bool(row.get("requires_follow_up")) if row.get("requires_follow_up") is not None else False,
        "follow_up_due": row.get("follow_up_due").isoformat() if row.get("follow_up_due") else None,
        "is_private": bool(row.get("is_private")) if row.get("is_private") is not None else False,
        "archived": bool(row.get("archived")) if row.get("archived") is not None else False,
        "archived_at": row.get("archived_at").isoformat() if row.get("archived_at") else None,
        "archived_by": str(row.get("archived_by") or ""),
        "updated_by": str(row.get("updated_by") or "") or None,
        "automation_key": str(row.get("automation_key") or ""),
        "created_by": str(row.get("created_by") or ""),
        "created_at": row.get("created_at").isoformat() if row.get("created_at") else None,
        "updated_at": row.get("updated_at").isoformat() if row.get("updated_at") else None,
    }


def _serialize_task(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": int(row.get("task_id")),
        "job_id": int(row.get("job_id")),
        "communication_id": int(row.get("communication_id")) if row.get("communication_id") is not None else None,
        "title": str(row.get("title") or ""),
        "details": str(row.get("details") or ""),
        "assigned_to": str(row.get("assigned_to") or ""),
        "priority": str(row.get("priority") or "normal"),
        "status": str(row.get("status") or "open"),
        "due_date": row.get("due_date").isoformat() if row.get("due_date") else None,
        "created_by": str(row.get("created_by") or ""),
        "created_at": row.get("created_at").isoformat() if row.get("created_at") else None,
        "updated_at": row.get("updated_at").isoformat() if row.get("updated_at") else None,
        "completed_at": row.get("completed_at").isoformat() if row.get("completed_at") else None,
        "completed_by": str(row.get("completed_by") or ""),
    }


def _find_job_by_subject(con, subject: str) -> tuple[int | None, int | None]:
    s = str(subject or "").strip()
    if not s:
        return (None, None)
    # Match structured job numbers if present (e.g. DUMMY-2026-0001-02 or J001234).
    patterns = [
        r"([A-Z]{2,}-\d{4}-\d{3,}-\d{2,})",
        r"\b(J\d{4,})\b",
    ]
    for pattern in patterns:
        m = re.search(pattern, s, flags=re.IGNORECASE)
        if not m:
            continue
        candidate = m.group(1)
        row = con.execute(
            "SELECT job_id, client_db_id FROM jobs WHERE lower(coalesce(job_number,'')) = lower(%s) LIMIT 1",
            [candidate],
        ).fetchone()
        if row:
            return (int(row[0]), int(row[1]) if row[1] is not None else None)
    return (None, None)


def _resolve_job_client(con, job_id: int | None, client_db_id: int | None, subject: str) -> tuple[int | None, int | None]:
    if job_id is not None:
        row = con.execute(
            "SELECT job_id, client_db_id FROM jobs WHERE job_id = %s LIMIT 1",
            [int(job_id)],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Provided job_id not found")
        return (int(row[0]), int(row[1]) if row[1] is not None else None)
    if client_db_id is not None:
        return (None, int(client_db_id))
    return _find_job_by_subject(con, subject)


def _choose_followup_rule(subject: str, message_text: str) -> dict[str, Any] | None:
    txt = f"{subject or ''}\n{message_text or ''}".lower()
    urgent = ["urgent", "asap", "immediately", "critical", "today", "blocking", "blocked"]
    high = ["issue", "problem", "error", "cannot", "can't", "failed", "failure", "complaint", "escalation"]
    normal = ["please", "can you", "could you", "when", "deadline", "clarify", "confirm", "update"]
    if any(k in txt for k in urgent):
        return {"priority": "urgent", "due_days": 1, "status": "open"}
    if any(k in txt for k in high):
        return {"priority": "high", "due_days": 2, "status": "open"}
    if any(k in txt for k in normal) or "?" in txt:
        return {"priority": "normal", "due_days": 5, "status": "open"}
    return None


def _resolve_assignee(con, job_id: int) -> str | None:
    row = con.execute(
        """
        SELECT j.crm_name, c.crm_owner
        FROM jobs j
        LEFT JOIN clients c ON c.db_id = j.client_db_id
        WHERE j.job_id = %s
        """,
        [int(job_id)],
    ).fetchone()
    if not row:
        return None
    candidate_names = [str(row[0] or "").strip(), str(row[1] or "").strip()]
    candidate_names = [x for x in candidate_names if x]
    for c in candidate_names:
        u = con.execute(
            """
            SELECT email, full_name
            FROM users
            WHERE lower(coalesce(email,'')) = lower(%s) OR lower(coalesce(full_name,'')) = lower(%s)
            LIMIT 1
            """,
            [c, c],
        ).fetchone()
        if u:
            return str(u[0] or u[1] or "").strip() or None
    return candidate_names[0] if candidate_names else None


def _maybe_create_auto_followup_task(
    con,
    *,
    job_id: int,
    communication_id: int,
    from_email: str,
    subject: str,
    message_text: str,
) -> dict[str, Any] | None:
    rule = _choose_followup_rule(subject, message_text)
    if not rule:
        return None

    exists = con.execute(
        """
        SELECT 1
        FROM job_communication_tasks
        WHERE job_id = %s AND communication_id = %s
        LIMIT 1
        """,
        [int(job_id), int(communication_id)],
    ).fetchone()
    if exists:
        return None

    assignee = _resolve_assignee(con, int(job_id))
    due = date.today() + timedelta(days=int(rule["due_days"]))
    title = f"Inbound follow-up: {subject[:110] if subject else '(No subject)'}"
    details = (
        f"Auto-created from inbound email.\n"
        f"From: {from_email or '-'}\n"
        f"Subject: {subject or '(No subject)'}\n\n"
        f"{message_text[:2000]}"
    )
    row = con.execute(
        """
        INSERT INTO job_communication_tasks (
          job_id, communication_id, title, details, assigned_to, priority, status, due_date, created_by, updated_at
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, 'system:auto-inbound', NOW())
        RETURNING task_id
        """,
        [
            int(job_id),
            int(communication_id),
            title,
            details,
            assignee,
            str(rule["priority"]),
            str(rule["status"]),
            due.isoformat(),
        ],
    ).fetchone()
    return {"task_id": int(row[0]), "assigned_to": assignee, "priority": str(rule["priority"]), "due_date": due.isoformat()}


def _nzi_logo_path() -> str | None:
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    candidates = [
        os.path.join(root_dir, "frontend", "public", "uploads", "system", "nzi-logo.png"),
        os.path.join(root_dir, "assets", "netzero-logo-big-tree-64x64-1.png"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    return None


def _display_date(value: Any) -> str:
    if isinstance(value, date):
        return f"{value.day} {value.strftime('%B %Y')}"
    text = str(value or "").strip()
    if not text:
        return "-"
    try:
        parsed = date.fromisoformat(text[:10])
        return f"{parsed.day} {parsed.strftime('%B %Y')}"
    except Exception:
        return text


def _status_label(status: str) -> str:
    s = str(status or "").strip().lower()
    if s == "completed":
        return "Completed"
    if s == "red":
        return "Red"
    if s == "amber":
        return "Amber"
    return "Green"


def _get_milestone_names(con, milestone_template_id: int | None) -> list[str]:
    defaults = ["Data Collection", "First Draft", "Final Report"]
    if milestone_template_id is None:
        return defaults
    try:
        df = con.execute(
            """
            SELECT milestone_name
            FROM milestone_template_items
            WHERE template_id = %s
            ORDER BY COALESCE(sort_order, 9999), item_id
            LIMIT 3
            """,
            [int(milestone_template_id)],
        ).df()
        if df is None or df.empty:
            return defaults
        names = [str(r.get("milestone_name") or "").strip() for _, r in df.iterrows()]
        names = [x for x in names if x]
        if not names:
            return defaults
        while len(names) < 3:
            names.append(defaults[len(names)])
        return names[:3]
    except Exception:
        return defaults


def _split_address_lines(value: str) -> list[str]:
    txt = str(value or "").strip()
    if not txt:
        return []
    if "\n" in txt:
        return [line.strip() for line in txt.splitlines() if line.strip()]
    parts = [p.strip() for p in txt.split(",") if p.strip()]
    return parts


def _build_overview_letter_context(con, job_id: int) -> dict[str, Any]:
    row = con.execute(
        """
        SELECT j.job_id, j.job_number, j.title, j.start_date, j.due_date, j.reporting_period_start, j.reporting_period_end,
               j.crm_name, j.milestone_template_id, j.client_db_id,
               c.client_name, COALESCE(c.headquarters, '') AS headquarters, COALESCE(c.crm_owner, '') AS client_crm_owner,
               jp.data_collection_due, jp.data_collection_completed_at,
               jp.first_draft_due, jp.first_draft_completed_at,
               jp.final_report_due, jp.final_report_completed_at
        FROM jobs j
        LEFT JOIN clients c ON c.db_id = j.client_db_id
        LEFT JOIN job_plan jp ON jp.job_id = j.job_id
        WHERE j.job_id = %s
        LIMIT 1
        """,
        [int(job_id)],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")

    milestone_names = _get_milestone_names(con, int(row[8]) if row[8] is not None else None)
    milestone_rows = [
        {
            "name": milestone_names[0],
            "due_date": row[13],
            "status": _milestone_status(row[13], row[14]),
        },
        {
            "name": milestone_names[1],
            "due_date": row[15],
            "status": _milestone_status(row[15], row[16]),
        },
        {
            "name": milestone_names[2],
            "due_date": row[17],
            "status": _milestone_status(row[17], row[18]),
        },
    ]
    milestones = [m for m in milestone_rows if m.get("due_date")]

    primary = None
    try:
        primary = con.execute(
            """
            SELECT full_name, email, job_title
            FROM client_contacts
            WHERE client_db_id = %s
            ORDER BY COALESCE(is_primary, FALSE) DESC, contact_id ASC
            LIMIT 1
            """,
            [int(row[9]) if row[9] is not None else -1],
        ).fetchone()
    except Exception:
        primary = None

    contact_name = str(primary[0] or "").strip() if primary else ""
    contact_email = str(primary[1] or "").strip() if primary else ""
    contact_title = str(primary[2] or "").strip() if primary else ""

    context = {
        "job_id": int(row[0]),
        "job_number": str(row[1] or f"Job {job_id}"),
        "job_title": str(row[2] or "").strip(),
        "job_start_date": row[3],
        "job_end_date": row[4],
        "reporting_period_start": row[5],
        "reporting_period_end": row[6],
        "crm_name": str(row[7] or "").strip() or str(row[12] or "").strip() or "Your NZI CRM",
        "client_db_id": int(row[9]) if row[9] is not None else None,
        "client_name": str(row[10] or "Client"),
        "client_address": str(row[11] or "").strip(),
        "client_address_lines": _split_address_lines(str(row[11] or "")),
        "contact_name": contact_name,
        "contact_email": contact_email,
        "contact_title": contact_title,
        "milestones": milestones,
        "today": date.today().isoformat(),
        "company_profile": get_company_profile(con),
    }
    context["default_to_email"] = contact_email
    context["default_subject"] = f"Job Overview Letter - {context['job_number']}"
    context["default_message"] = (
        f"Dear {contact_name or context['client_name']},\n\n"
        f"Please find attached the Job Overview Letter for {context['job_number']}.\n\n"
        f"Kind regards,\n{context['crm_name']}"
    )
    return context


def _overview_letter_pdf(context: dict[str, Any]) -> bytes:
    styles = getSampleStyleSheet()
    normal = ParagraphStyle("OverviewNormal", parent=styles["Normal"], fontSize=10.5, leading=14)
    label = ParagraphStyle("OverviewLabel", parent=styles["Normal"], fontSize=10.5, leading=13, fontName="Helvetica-Bold")
    title = ParagraphStyle(
        "OverviewTitle",
        parent=styles["Title"],
        fontSize=16,
        leading=20,
        alignment=0,
        spaceAfter=2 * mm,
    )
    company_style = ParagraphStyle("OverviewCompany", parent=styles["Normal"], fontSize=9.5, leading=13, alignment=2)
    intro_heading = ParagraphStyle("OverviewHeading", parent=styles["Heading2"], fontSize=13.5, leading=16, fontName="Helvetica-Bold")

    company_profile = context.get("company_profile") or {}
    company_name = str(company_profile.get("company_display_name") or company_profile.get("company_legal_name") or "Net Zero International")
    company_legal_name = str(company_profile.get("company_legal_name") or company_name)
    company_address = company_address_html(company_profile) or "167-169 Great Portland Street<br/>London<br/>W1W 9PF<br/>United Kingdom"

    left_lines = []
    if context.get("contact_name"):
        left_lines.append(f"Attention: {context['contact_name']}")
    left_lines.append(str(context.get("client_name") or "Client"))
    left_lines.extend(context.get("client_address_lines") or [])
    left_text = "<br/>".join([x for x in left_lines if str(x or "").strip()]) or "-"

    middle_items = [
        ("Date", _display_date(context.get("today"))),
        ("Job Number", str(context.get("job_number") or "-")),
        ("Job CRM", str(context.get("crm_name") or "-")),
        (
            "Reporting Period",
            f"{_display_date(context.get('reporting_period_start'))} to {_display_date(context.get('reporting_period_end'))}",
        ),
    ]
    middle_text = "".join([f"<b>{k}</b><br/>{v}<br/><br/>" for k, v in middle_items]).strip()

    right_parts: list[Any] = []
    logo_path = _nzi_logo_path()
    if logo_path:
        logo = Image(logo_path, width=48 * mm, height=24 * mm, kind="proportional")
        logo.hAlign = "RIGHT"
        right_parts.append(logo)
        right_parts.append(Spacer(1, 1 * mm))
    right_parts.append(Paragraph(f"{company_name}<br/>{company_address}", company_style))
    right_block = Table([[right_parts]], colWidths=[50 * mm])
    right_block.setStyle(
        TableStyle(
            [
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    header = Table(
        [
            [
                [Paragraph("JOB OVERVIEW LETTER", title), Spacer(1, 2 * mm), Paragraph(left_text, normal)],
                Paragraph(middle_text, normal),
                right_block,
            ]
        ],
        colWidths=[88 * mm, 52 * mm, 50 * mm],
    )
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    intro = (
        f"This document provides an overview of the discussions we have had regarding your job "
        f"<b>{html.escape(str(context.get('job_number') or ''))}</b>. "
        f"We are working together to meet each milestone so that your required report can be delivered on time and to a high standard. "
        f"Our services are provided subject to our Standard Terms and Conditions, available on our website and in our client portal."
    )
    milestone_note = (
        "You will receive automatic system emails 7 days before each milestone date, confirming the milestone status "
        "(green/amber/red) and any required actions."
    )
    closing = (
        "We look forward to supporting you in developing your report. "
        "If you have any questions whatsoever, please do not hesitate to contact me."
    )

    details_rows = [
        ["Client", str(context.get("client_name") or "-")],
        ["Job Number", str(context.get("job_number") or "-")],
        ["Job Title", str(context.get("job_title") or "-")],
        ["Job Start Date", _display_date(context.get("job_start_date"))],
        ["Job End Date", _display_date(context.get("job_end_date"))],
        [
            "Reporting Period",
            f"{_display_date(context.get('reporting_period_start'))} to {_display_date(context.get('reporting_period_end'))}",
        ],
        ["CRM", str(context.get("crm_name") or "-")],
    ]
    details_table = Table(details_rows, colWidths=[42 * mm, 148 * mm])
    details_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.HexColor("#d6d6d6")),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )

    milestone_data: list[list[Any]] = [["Milestone", "Due Date", "Status"]]
    for row in context.get("milestones") or []:
        milestone_data.append(
            [
                Paragraph(str(row.get("name") or "-"), normal),
                Paragraph(_display_date(row.get("due_date")), normal),
                Paragraph(_status_label(str(row.get("status") or "")), normal),
            ]
        )
    milestone_table = Table(milestone_data, colWidths=[98 * mm, 48 * mm, 44 * mm])
    milestone_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f5f5f5")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.6, colors.HexColor("#999999")),
                ("LINEBELOW", (0, 1), (-1, -1), 0.3, colors.HexColor("#dfdfdf")),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )

    story: list[Any] = [
        header,
        Spacer(1, 9 * mm),
        Paragraph("Introduction", intro_heading),
        Spacer(1, 1.8 * mm),
        Paragraph(intro, normal),
        Spacer(1, 5 * mm),
        Paragraph("Job Summary", intro_heading),
        Spacer(1, 1.8 * mm),
        details_table,
        Spacer(1, 5 * mm),
        Paragraph("Milestones", intro_heading),
        Spacer(1, 1.8 * mm),
        milestone_table,
        Spacer(1, 4 * mm),
        Paragraph(milestone_note, normal),
        Spacer(1, 6 * mm),
        Paragraph(closing, normal),
        Spacer(1, 8 * mm),
        Paragraph("Kind regards,", normal),
        Spacer(1, 3 * mm),
        Paragraph(f"<b>{html.escape(str(context.get('crm_name') or 'NZI CRM'))}</b>", label),
        Paragraph("Client Relationship Manager", normal),
        PageBreak(),
        Paragraph("STANDARD TERMS SUMMARY", intro_heading),
        Spacer(1, 3 * mm),
        Paragraph(
            f"The services described in this Job Overview Letter are supplied by {html.escape(company_legal_name)} subject to our Standard Terms and Conditions.",
            normal,
        ),
        Spacer(1, 4 * mm),
        Paragraph("<b>1. Scope of Services</b>", normal),
        Paragraph("Services are provided with reasonable skill and care in accordance with the agreed scope, assumptions and timetable.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>2. Client Responsibilities</b>", normal),
        Paragraph("The Client is responsible for providing accurate, complete and timely information, records, access and instructions required for the engagement.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>3. Reliance on Information</b>", normal),
        Paragraph("NZI may rely on information supplied by the Client or third parties unless independent verification is expressly included in scope.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>4. Use of Deliverables</b>", normal),
        Paragraph("Deliverables are provided for the Client's internal business purposes only and may not be relied on by third parties without NZI's prior written consent.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>5. Intellectual Property</b>", normal),
        Paragraph("NZI retains ownership of its methodologies, tools, templates, software and underlying intellectual property. The Client receives a non-exclusive licence to use agreed deliverables for its internal business purposes, subject to payment in full.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>6. Confidentiality</b>", normal),
        Paragraph("Each party shall keep the other's confidential information confidential, except where disclosure is required by law or reasonably necessary for professional advisers, insurers or subcontractors.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>7. Data Protection</b>", normal),
        Paragraph("Each party shall comply with applicable data protection law. Depending on the nature of the services, NZI may act as controller, processor or separate controller for limited administrative, compliance and service-improvement purposes.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>8. Fees and Payment</b>", normal),
        Paragraph("Unless otherwise agreed in writing, invoices are payable within 7 days of the invoice date.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>9. Liability</b>", normal),
        Paragraph("Nothing excludes liability that cannot lawfully be excluded. Subject to that, NZI's total aggregate liability arising from the engagement shall not exceed the fees paid by the Client under the relevant engagement in the 12 months preceding the event giving rise to the claim. NZI shall not be liable for indirect or consequential loss, loss of profit, loss of revenue, loss of business or loss of goodwill.", normal),
        Spacer(1, 2 * mm),
        Paragraph("<b>10. Governing Law</b>", normal),
        Paragraph("The engagement is governed by the laws of England and Wales, and the courts of England and Wales shall have exclusive jurisdiction.", normal),
        Spacer(1, 4 * mm),
        Paragraph("A copy of NZI's full Standard Terms and Conditions is available on our website and in our client portal.", normal),
    ]

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=10 * mm,
        rightMargin=10 * mm,
        topMargin=10 * mm,
        bottomMargin=12 * mm,
        title=f"Overview Letter - {context.get('job_number') or context.get('job_id')}",
    )
    footer_text = company_footer_text(company_profile) or company_legal_name

    def _footer(canvas_obj, doc_obj) -> None:
        canvas_obj.saveState()
        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.setFillColor(colors.HexColor("#666666"))
        canvas_obj.drawCentredString(A4[0] / 2.0, 7.5 * mm, footer_text[:180])
        canvas_obj.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _ingest_inbound_email(
    con,
    *,
    from_email: str,
    from_name: str,
    to_email: str,
    subject: str,
    content: str,
    received_at: str | None,
    message_id: str,
    source_tag: str,
    job_id: int | None = None,
    client_db_id: int | None = None,
) -> dict[str, Any]:
    _ensure_tables(con)
    resolved_job_id, resolved_client_id = _resolve_job_client(con, job_id, client_db_id, subject)
    if resolved_job_id is None:
        return {"ok": True, "matched": False, "message": "Inbound email received but no job mapping found"}

    automation_key = f"inbound-email:{message_id}" if message_id else None
    if automation_key:
        exists = con.execute(
            """
            SELECT communication_id
            FROM job_communications
            WHERE job_id = %s AND automation_key = %s
            LIMIT 1
            """,
            [int(resolved_job_id), automation_key],
        ).fetchone()
        if exists:
            return {
                "ok": True,
                "matched": True,
                "deduplicated": True,
                "job_id": int(resolved_job_id),
                "communication_id": int(exists[0]),
            }

    row = con.execute(
        """
        INSERT INTO job_communications (
          job_id, client_db_id, direction, channel, subject, message_text,
          from_name, from_email, to_email, status, event_at, automation_key, created_by, updated_at
        )
        VALUES (%s, %s, 'inbound', 'email', %s, %s, %s, %s, %s, 'received', %s, %s, %s, NOW())
        RETURNING communication_id
        """,
        [
            int(resolved_job_id),
            int(resolved_client_id) if resolved_client_id is not None else None,
            subject or "(No subject)",
            content,
            from_name or None,
            from_email or None,
            to_email or None,
            received_at,
            automation_key,
            source_tag,
        ],
    ).fetchone()
    communication_id = int(row[0])
    auto_task = _maybe_create_auto_followup_task(
        con,
        job_id=int(resolved_job_id),
        communication_id=communication_id,
        from_email=from_email,
        subject=subject,
        message_text=content,
    )
    return {
        "ok": True,
        "matched": True,
        "job_id": int(resolved_job_id),
        "communication_id": communication_id,
        "auto_task": auto_task,
    }


@router.get("/jobs/{job_id}/communications")
def list_job_communications(job_id: int, _user: dict = Depends(_current_user)):
    _ = _actor(_user)
    try:
        with get_conn() as con:
            _ensure_tables(con)
            job_row = con.execute("SELECT client_db_id FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            client_db_id = int(job_row[0]) if job_row[0] is not None else None

            comm_df = con.execute(
                """
                SELECT communication_id, job_id, client_db_id, direction, channel, subject, message_text,
                       scope, category, site_id, site_name,
                       from_name, from_email, to_name, to_email, status, event_at, requires_follow_up,
                       follow_up_due, is_private, archived, archived_at, archived_by, updated_by, automation_key, created_by, created_at, updated_at
                FROM job_communications
                WHERE job_id = %s
                  AND COALESCE(archived, FALSE) = FALSE
                ORDER BY COALESCE(event_at, created_at) DESC, communication_id DESC
                LIMIT 500
                """,
                [int(job_id)],
            ).df()

            task_df = con.execute(
                """
                SELECT task_id, job_id, communication_id, title, details, assigned_to, priority, status, due_date,
                       created_by, created_at, updated_at, completed_at, completed_by
                FROM job_communication_tasks
                WHERE job_id = %s
                ORDER BY
                  CASE WHEN lower(status) IN ('open','in_progress') THEN 0 ELSE 1 END,
                  due_date ASC NULLS LAST,
                  task_id DESC
                LIMIT 500
                """,
                [int(job_id)],
            ).df()

            users_df = con.execute(
                """
                SELECT email, full_name
                FROM users
                WHERE COALESCE(status, 'Active') = 'Active'
                ORDER BY lower(full_name), lower(email)
                """
            ).df()

            contacts_df = con.execute(
                """
                SELECT contact_id, full_name, email, is_primary
                FROM client_contacts
                WHERE client_db_id = %s
                ORDER BY is_primary DESC, lower(full_name)
                """,
                [int(client_db_id)] if client_db_id is not None else [-1],
            ).df()

        communications: list[dict[str, Any]] = []
        if comm_df is not None and not comm_df.empty:
            for _, row in comm_df.iterrows():
                communications.append(_serialize_comm(row.to_dict()))

        tasks: list[dict[str, Any]] = []
        if task_df is not None and not task_df.empty:
            for _, row in task_df.iterrows():
                tasks.append(_serialize_task(row.to_dict()))

        users: list[dict[str, str]] = []
        if users_df is not None and not users_df.empty:
            for _, row in users_df.iterrows():
                users.append(
                    {
                        "email": str(row.get("email") or "").strip(),
                        "full_name": str(row.get("full_name") or "").strip(),
                    }
                )

        contacts: list[dict[str, Any]] = []
        if contacts_df is not None and not contacts_df.empty:
            for _, row in contacts_df.iterrows():
                contacts.append(
                    {
                        "contact_id": int(row.get("contact_id")),
                        "full_name": str(row.get("full_name") or ""),
                        "email": str(row.get("email") or ""),
                        "is_primary": bool(row.get("is_primary")) if row.get("is_primary") is not None else False,
                    }
                )

        open_tasks = sum(1 for t in tasks if str(t.get("status") or "").lower() in ("open", "in_progress"))
        overdue_tasks = sum(
            1
            for t in tasks
            if t.get("due_date")
            and str(t.get("status") or "").lower() in ("open", "in_progress")
            and str(t.get("due_date")) < date.today().isoformat()
        )

        return {
            "job_id": int(job_id),
            "client_db_id": client_db_id,
            "communications": communications,
            "tasks": tasks,
            "lookups": {
                "users": users,
                "contacts": contacts,
            },
            "summary": {
                "communications_count": len(communications),
                "open_tasks_count": int(open_tasks),
                "overdue_tasks_count": int(overdue_tasks),
            },
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load communications: {e}")


@router.post("/jobs/{job_id}/communications")
def create_job_communication(job_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = _actor(_user)
    message_text = str(body.get("message_text") or "").strip()
    if not message_text:
        raise HTTPException(status_code=400, detail="message_text is required")
    try:
        with get_conn() as con:
            _ensure_tables(con)
            job_row = con.execute("SELECT client_db_id FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            client_db_id = int(job_row[0]) if job_row[0] is not None else None
            resolved_site = _resolve_site_details(
                con,
                client_db_id,
                body.get("site_id"),
                body.get("site_name"),
            )
            row = con.execute(
                """
                INSERT INTO job_communications (
                  job_id, client_db_id, direction, channel, subject, message_text,
                  scope, category, site_id, site_name,
                  from_name, from_email, to_name, to_email, status, event_at,
                  requires_follow_up, follow_up_due, is_private, automation_key, created_by, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW())
                RETURNING communication_id
                """,
                [
                    int(job_id),
                    client_db_id,
                    str(body.get("direction") or "internal"),
                    str(body.get("channel") or "note"),
                    str(body.get("subject") or "").strip() or None,
                    message_text,
                    str(body.get("scope") or "").strip() or None,
                    str(body.get("category") or "").strip() or None,
                    int(resolved_site["site_id"]) if resolved_site.get("site_id") is not None else None,
                    str(resolved_site.get("site_name") or "").strip() or None,
                    str(body.get("from_name") or "").strip() or None,
                    str(body.get("from_email") or "").strip() or None,
                    str(body.get("to_name") or "").strip() or None,
                    str(body.get("to_email") or "").strip() or None,
                    str(body.get("status") or "logged"),
                    str(body.get("event_at") or "").strip() or None,
                    bool(body.get("requires_follow_up", False)),
                    str(body.get("follow_up_due") or "").strip() or None,
                    bool(body.get("is_private", False)),
                    str(body.get("automation_key") or "").strip() or None,
                    actor,
                ],
            ).fetchone()
        return {"ok": True, "communication_id": int(row[0])}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create communication: {e}")


@router.patch("/jobs/{job_id}/communications/{communication_id}")
def update_job_communication(
    job_id: int,
    communication_id: int,
    body: dict = Body(...),
    _user: dict = Depends(_current_user),
):
    actor = _actor(_user)
    try:
        with get_conn(autocommit=False) as con:
            _ensure_tables(con)
            job_row = con.execute("SELECT client_db_id FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            client_db_id = int(job_row[0]) if job_row[0] is not None else None
            exists = con.execute(
                "SELECT 1 FROM job_communications WHERE job_id = %s AND communication_id = %s",
                [int(job_id), int(communication_id)],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail="Communication not found")

            updates: list[str] = []
            params: list[Any] = []
            for key in [
                "direction",
                "channel",
                "subject",
                "message_text",
                "scope",
                "category",
                "from_name",
                "from_email",
                "to_name",
                "to_email",
                "status",
                "event_at",
                "follow_up_due",
                "automation_key",
            ]:
                if key in body:
                    updates.append(f"{key} = %s")
                    value = body.get(key)
                    if key in ("subject", "scope", "category", "from_name", "from_email", "to_name", "to_email", "automation_key", "site_name"):
                        value = str(value or "").strip() or None
                    params.append(value)
            if "site_id" in body or "site_name" in body:
                resolved_site = _resolve_site_details(
                    con,
                    client_db_id,
                    body.get("site_id"),
                    body.get("site_name"),
                )
                updates.append("site_id = %s")
                params.append(int(resolved_site["site_id"]) if resolved_site.get("site_id") is not None else None)
                updates.append("site_name = %s")
                params.append(str(resolved_site.get("site_name") or "").strip() or None)
            if "requires_follow_up" in body:
                updates.append("requires_follow_up = %s")
                params.append(bool(body.get("requires_follow_up")))
            if "is_private" in body:
                updates.append("is_private = %s")
                params.append(bool(body.get("is_private")))

            if not updates:
                return {"ok": True, "message": "No fields to update"}
            updates.append("updated_at = NOW()")
            updates.append("updated_by = %s")
            params.extend([actor, int(job_id), int(communication_id)])
            result = con.execute(
                f"UPDATE job_communications SET {', '.join(updates)} WHERE job_id = %s AND communication_id = %s",
                params,
            )
            if result.cursor.rowcount == 0:
                raise HTTPException(status_code=404, detail="Communication not found or could not be updated")
        return {"ok": True}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update communication: {e}")


@router.patch("/jobs/{job_id}/communications/{communication_id}/archive")
def archive_job_communication(
    job_id: int,
    communication_id: int,
    _user: dict = Depends(_current_user),
):
    actor = _actor(_user)
    try:
        with get_conn(autocommit=False) as con:
            _ensure_tables(con)
            job_row = con.execute("SELECT client_db_id FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            client_db_id = int(job_row[0]) if job_row[0] is not None else None
            _ = client_db_id
            exists = con.execute(
                "SELECT 1 FROM job_communications WHERE job_id = %s AND communication_id = %s",
                [int(job_id), int(communication_id)],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail="Communication not found")
            con.execute(
                """
                UPDATE job_communications
                SET archived = TRUE,
                    archived_at = NOW(),
                    archived_by = %s,
                    status = 'archived',
                    updated_at = NOW()
                WHERE job_id = %s AND communication_id = %s
                """,
                [actor, int(job_id), int(communication_id)],
            )
        return {"ok": True}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to archive communication: {e}")


@router.post("/jobs/{job_id}/communications/tasks")
def create_job_communication_task(job_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = _actor(_user)
    title = str(body.get("title") or "").strip()
    if not title:
        raise HTTPException(status_code=400, detail="title is required")
    try:
        with get_conn() as con:
            _ensure_tables(con)
            exists = con.execute("SELECT 1 FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail="Job not found")
            row = con.execute(
                """
                INSERT INTO job_communication_tasks (
                  job_id, communication_id, title, details, assigned_to, priority, status, due_date, created_by, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, NOW())
                RETURNING task_id
                """,
                [
                    int(job_id),
                    int(body.get("communication_id")) if body.get("communication_id") is not None else None,
                    title,
                    str(body.get("details") or "").strip() or None,
                    str(body.get("assigned_to") or "").strip() or None,
                    str(body.get("priority") or "normal"),
                    str(body.get("status") or "open"),
                    str(body.get("due_date") or "").strip() or None,
                    actor,
                ],
            ).fetchone()
        return {"ok": True, "task_id": int(row[0])}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create task: {e}")


@router.patch("/jobs/{job_id}/communications/tasks/{task_id}")
def update_job_communication_task(
    job_id: int,
    task_id: int,
    body: dict = Body(...),
    _user: dict = Depends(_current_user),
):
    actor = _actor(_user)
    try:
        with get_conn() as con:
            _ensure_tables(con)
            exists = con.execute(
                "SELECT 1 FROM job_communication_tasks WHERE job_id = %s AND task_id = %s",
                [int(job_id), int(task_id)],
            ).fetchone()
            if not exists:
                raise HTTPException(status_code=404, detail="Task not found")

            updates: list[str] = []
            params: list[Any] = []
            for key in ["title", "details", "assigned_to", "priority", "status", "due_date", "communication_id"]:
                if key in body:
                    updates.append(f"{key} = %s")
                    value = body.get(key)
                    if key in ("title", "details", "assigned_to", "priority", "status", "due_date"):
                        value = str(value or "").strip() or None
                    params.append(value)

            status_val = str(body.get("status") or "").strip().lower()
            if "status" in body:
                if status_val in ("done", "completed", "closed"):
                    updates.append("completed_at = NOW()")
                    updates.append("completed_by = %s")
                    params.append(actor)
                else:
                    updates.append("completed_at = NULL")
                    updates.append("completed_by = NULL")

            if not updates:
                return {"ok": True, "message": "No fields to update"}

            updates.append("updated_at = NOW()")
            params.extend([int(job_id), int(task_id)])
            con.execute(
                f"UPDATE job_communication_tasks SET {', '.join(updates)} WHERE job_id = %s AND task_id = %s",
                params,
            )
        return {"ok": True}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update task: {e}")


@router.post("/jobs/{job_id}/communications/email")
async def send_job_communication_email(
    job_id: int,
    to_email: str = Form(...),
    subject: str = Form(...),
    message_text: str = Form(...),
    cc: str = Form(default="[]"),
    bcc: str = Form(default="[]"),
    job_file_ids: str = Form(default="[]"),
    files: list[UploadFile] = File(default=[]),
    _user: dict = Depends(_current_user),
):
    actor = _actor(_user)
    to_email = str(to_email or "").strip()
    subject = str(subject or "").strip()
    message_text = str(message_text or "").strip()
    if not to_email:
        raise HTTPException(status_code=400, detail="to_email is required")
    if not subject:
        raise HTTPException(status_code=400, detail="subject is required")
    if not message_text:
        raise HTTPException(status_code=400, detail="message_text is required")

    def _parse_addr_json(raw: str) -> list[str]:
        try:
            parsed = json.loads(raw or "[]")
        except Exception:
            parsed = [e.strip() for e in str(raw or "").split(",") if e.strip()]
        if isinstance(parsed, list):
            return [str(e).strip() for e in parsed if str(e or "").strip()]
        return []

    cc_list = _parse_addr_json(cc)
    bcc_list = _parse_addr_json(bcc)

    try:
        file_id_list = [int(x) for x in json.loads(job_file_ids or "[]") if x]
    except Exception:
        file_id_list = []

    # Build attachments list from uploaded files + job file library
    attachments: list[dict] = []

    for uf in (files or []):
        if not uf or not uf.filename:
            continue
        raw = await uf.read()
        if not raw:
            continue
        mime = str(uf.content_type or "application/octet-stream")
        attachments.append({"bytes": raw, "filename": uf.filename, "mime": mime})

    try:
        with get_conn() as con:
            _ensure_tables(con)
            job_row = con.execute("SELECT client_db_id FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            if not job_row:
                raise HTTPException(status_code=404, detail="Job not found")
            client_db_id = int(job_row[0]) if job_row[0] is not None else None

            for fid in file_id_list:
                try:
                    fb, fname, fmime = _read_job_file_bytes(con, fid, int(job_id))
                    attachments.append({"bytes": fb, "filename": fname, "mime": fmime})
                except Exception as fe:
                    raise HTTPException(status_code=400, detail=f"Could not read job file {fid}: {fe}")

            signature_html = get_user_signature_html(con, actor)
            body_html = None
            if signature_html:
                body_html = f"<p>{message_text.replace(chr(10), '<br/>')}</p><br/>{signature_html}"
            send_res = send_tracked_email(
                con,
                to_email=to_email,
                subject=subject,
                body_text=message_text,
                body_html=body_html,
                created_by=actor,
                cc=cc_list or None,
                bcc=bcc_list or None,
                entity_type="job_communication",
                entity_id=None,
                job_id=int(job_id),
                client_db_id=client_db_id,
                template_key="job_communication_send",
                metadata={"channel": "job_communications", "attachment_count": len(attachments)},
                attachments=attachments if attachments else None,
                raise_on_error=False,
            )
            comm_status = "sent" if str(send_res.get("status") or "") == "sent" else "failed"
            cc_str = ", ".join(cc_list) if cc_list else None
            att_note = f"\n\nAttachments: {', '.join(a['filename'] for a in attachments)}" if attachments else ""
            con.execute(
                """
                INSERT INTO job_communications (
                  job_id, client_db_id, direction, channel, subject, message_text,
                  to_email, status, event_at, created_by, updated_at
                )
                VALUES (%s, %s, 'outbound', 'email', %s, %s, %s, %s, NOW(), %s, NOW())
                """,
                [int(job_id), client_db_id, subject,
                 message_text + (f"\n\nCC: {cc_str}" if cc_str else "") + att_note,
                 to_email, comm_status, actor],
            )
            if comm_status != "sent":
                raise HTTPException(status_code=500, detail=f"Failed to send email: {send_res.get('error') or 'Unknown error'}")
        return {"ok": True, "sent_to": to_email, "email_id": int(send_res.get("email_id") or 0), "attachments": len(attachments)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to send email: {e}")


@router.post("/jobs/{job_id}/communications/automations/milestone-alerts")
def run_milestone_alerts(job_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = _actor(_user)
    mode = str(body.get("mode") or "preview").strip().lower()
    include_amber = bool(body.get("include_amber", True))
    include_red = bool(body.get("include_red", True))
    notify_to = str(body.get("notify_to") or "").strip()
    if mode not in ("preview", "send"):
        raise HTTPException(status_code=400, detail="mode must be preview or send")

    try:
        with get_conn() as con:
            _ensure_tables(con)
            row = con.execute(
                """
                SELECT j.client_db_id, j.job_number, c.client_name,
                       jp.data_collection_due, jp.data_collection_completed_at,
                       jp.first_draft_due, jp.first_draft_completed_at,
                       jp.final_report_due, jp.final_report_completed_at
                FROM jobs j
                LEFT JOIN clients c ON c.db_id = j.client_db_id
                LEFT JOIN job_plan jp ON jp.job_id = j.job_id
                WHERE j.job_id = %s
                """,
                [int(job_id)],
            ).fetchone()
            if not row:
                raise HTTPException(status_code=404, detail="Job not found")

            client_db_id = int(row[0]) if row[0] is not None else None
            job_number = str(row[1] or f"Job {job_id}")
            client_name = str(row[2] or "Client")
            checks = [
                ("Data Collection", row[3], row[4]),
                ("First Draft", row[5], row[6]),
                ("Final Report", row[7], row[8]),
            ]

            alerts: list[dict[str, Any]] = []
            for label, due_val, done_val in checks:
                status = _milestone_status(due_val, done_val)
                if status == "amber" and not include_amber:
                    continue
                if status == "red" and not include_red:
                    continue
                if status not in ("amber", "red"):
                    continue
                due_iso = due_val.isoformat() if hasattr(due_val, "isoformat") else str(due_val or "")
                automation_key = f"milestone-{label.lower().replace(' ', '-')}-{due_iso}-{status}"
                alerts.append(
                    {
                        "milestone": label,
                        "status": status,
                        "due_date": due_iso,
                        "automation_key": automation_key,
                    }
                )

            sent_count = 0
            logged_count = 0
            for alert in alerts:
                existing = con.execute(
                    """
                    SELECT 1
                    FROM job_communications
                    WHERE job_id = %s AND automation_key = %s
                    LIMIT 1
                    """,
                    [int(job_id), alert["automation_key"]],
                ).fetchone()
                if existing:
                    continue

                subject = f"Milestone Alert ({alert['status'].upper()}): {job_number} - {alert['milestone']}"
                body_text = (
                    f"Client: {client_name}\n"
                    f"Job: {job_number}\n"
                    f"Milestone: {alert['milestone']}\n"
                    f"Status: {alert['status'].upper()}\n"
                    f"Due date: {alert['due_date']}\n"
                )
                con.execute(
                    """
                    INSERT INTO job_communications (
                      job_id, client_db_id, direction, channel, subject, message_text,
                      status, event_at, automation_key, created_by, updated_at
                    )
                    VALUES (%s, %s, 'system', 'milestone_alert', %s, %s, 'logged', NOW(), %s, %s, NOW())
                    """,
                    [int(job_id), client_db_id, subject, body_text, alert["automation_key"], actor],
                )
                logged_count += 1

                if mode == "send" and notify_to:
                    send_res = send_tracked_email(
                        con,
                        to_email=notify_to,
                        subject=subject,
                        body_text=body_text,
                        created_by=actor,
                        entity_type="milestone_alert",
                        entity_id=None,
                        job_id=int(job_id),
                        client_db_id=client_db_id,
                        template_key="milestone_alert",
                        metadata={"automation_key": alert["automation_key"], "mode": mode},
                        raise_on_error=False,
                    )
                    if str(send_res.get("status") or "") == "sent":
                        sent_count += 1

        return {
            "ok": True,
            "mode": mode,
            "alerts": alerts,
            "logged_count": int(logged_count),
            "sent_count": int(sent_count),
            "notify_to": notify_to or None,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to run milestone alerts: {e}")


@router.get("/communications/outbound-email-log")
def get_outbound_email_log(
    job_id: int | None = Query(default=None),
    client_db_id: int | None = Query(default=None),
    entity_type: str | None = Query(default=None),
    entity_id: int | None = Query(default=None),
    limit: int = Query(default=100, ge=1, le=500),
    _user: dict = Depends(_current_user),
):
    _ = _actor(_user)
    try:
        with get_conn() as con:
            items = list_outbound_emails(
                con,
                job_id=job_id,
                client_db_id=client_db_id,
                entity_type=entity_type,
                entity_id=entity_id,
                limit=limit,
            )
        return {"items": items}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load outbound email log: {e}")


@router.get("/jobs/{job_id}/overview-letter")
def get_job_overview_letter_context(job_id: int, _user: dict = Depends(_current_user)):
    _ = _actor(_user)
    try:
        with get_conn() as con:
            context = _build_overview_letter_context(con, int(job_id))
        return {
            "job_id": int(job_id),
            "job_number": context.get("job_number"),
            "client_name": context.get("client_name"),
            "contact_name": context.get("contact_name"),
            "default_to_email": context.get("default_to_email"),
            "default_subject": context.get("default_subject"),
            "default_message": context.get("default_message"),
            "crm_name": context.get("crm_name"),
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load overview letter context: {e}")


@router.get("/jobs/{job_id}/overview-letter/pdf")
def get_job_overview_letter_pdf(job_id: int, _user: dict = Depends(_current_user)):
    _ = _actor(_user)
    try:
        with get_conn() as con:
            context = _build_overview_letter_context(con, int(job_id))
        pdf_bytes = _overview_letter_pdf(context)
        file_stub = re.sub(r"[^A-Za-z0-9._-]+", "-", str(context.get("job_number") or f"job-{job_id}")).strip("-")
        filename = f"{file_stub}-overview-letter.pdf"
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"inline; filename={filename}",
                "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
                "Pragma": "no-cache",
                "Expires": "0",
            },
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate overview letter PDF: {e}")


@router.post("/jobs/{job_id}/overview-letter/email")
def email_job_overview_letter(job_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = _actor(_user)
    to_email = str(body.get("to_email") or "").strip()
    custom_subject = str(body.get("subject") or "").strip()
    custom_message = str(body.get("message_text") or "").strip()
    try:
        with get_conn() as con:
            context = _build_overview_letter_context(con, int(job_id))
            recipient = to_email or str(context.get("default_to_email") or "").strip()
            if not recipient:
                raise HTTPException(status_code=400, detail="No recipient email found. Provide to_email.")
            pdf_bytes = _overview_letter_pdf(context)

            rendered = build_email_content(
                con=con,
                template_key="job_overview_letter_send",
                context={
                    "job_number": str(context.get("job_number") or ""),
                    "client_name": str(context.get("client_name") or ""),
                    "contact_name": str(context.get("contact_name") or ""),
                    "crm_name": str(context.get("crm_name") or ""),
                    "reporting_period_start": str(context.get("reporting_period_start") or ""),
                    "reporting_period_end": str(context.get("reporting_period_end") or ""),
                    "custom_message": custom_message,
                },
                fallback_subject=custom_subject or str(context.get("default_subject") or f"Job Overview Letter - Job {job_id}"),
                fallback_body=custom_message or str(context.get("default_message") or "Please find attached the job overview letter."),
                sender_identifier=actor,
                override_subject=custom_subject or None,
                override_body=custom_message or None,
            )

            filename_stub = re.sub(r"[^A-Za-z0-9._-]+", "-", str(context.get("job_number") or f"job-{job_id}")).strip("-")
            send_res = send_tracked_email(
                con,
                to_email=recipient,
                subject=rendered["subject"],
                body_text=rendered["body_text"],
                body_html=rendered["body_html"],
                created_by=actor,
                template_key="job_overview_letter_send",
                entity_type="job_overview_letter",
                entity_id=int(job_id),
                job_id=int(job_id),
                client_db_id=int(context.get("client_db_id")) if context.get("client_db_id") is not None else None,
                metadata={"kind": "job_overview_letter"},
                attachment={
                    "bytes": pdf_bytes,
                    "filename": f"{filename_stub}-overview-letter.pdf",
                    "mime": "application/pdf",
                },
                raise_on_error=False,
            )
            comm_status = "sent" if str(send_res.get("status") or "") == "sent" else "failed"
            con.execute(
                """
                INSERT INTO job_communications (
                  job_id, client_db_id, direction, channel, subject, message_text,
                  to_name, to_email, status, event_at, created_by, updated_at
                )
                VALUES (%s, %s, 'outbound', 'email', %s, %s, %s, %s, %s, NOW(), %s, NOW())
                """,
                [
                    int(job_id),
                    int(context.get("client_db_id")) if context.get("client_db_id") is not None else None,
                    rendered["subject"],
                    rendered["body_text"],
                    str(context.get("contact_name") or "") or None,
                    recipient,
                    comm_status,
                    actor,
                ],
            )
            if comm_status != "sent":
                raise HTTPException(status_code=500, detail=f"Failed to send overview letter: {send_res.get('error') or 'Unknown error'}")
        return {"ok": True, "job_id": int(job_id), "sent_to": recipient, "email_id": int(send_res.get("email_id") or 0)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to email overview letter: {e}")


@router.post("/communications/inbound/email")
def inbound_email_webhook(
    body: dict = Body(...),
    x_webhook_token: str | None = Header(default=None, alias="X-Webhook-Token"),
):
    """
    Provider-agnostic inbound email webhook scaffold.
    Expected body: from_email, from_name, to_email, subject, text, html, received_at, message_id
    Requires INBOUND_EMAIL_WEBHOOK_TOKEN env var and matching X-Webhook-Token header.
    """
    expected = str(os.getenv("INBOUND_EMAIL_WEBHOOK_TOKEN") or "").strip()
    provided = str(x_webhook_token or "").strip()
    if not expected:
        raise HTTPException(status_code=503, detail="Inbound email webhook is not configured")
    if not provided or provided != expected:
        raise HTTPException(status_code=401, detail="Invalid webhook token")

    from_email = str(body.get("from_email") or "").strip()
    from_name = str(body.get("from_name") or "").strip()
    to_email = str(body.get("to_email") or "").strip()
    subject = str(body.get("subject") or "").strip()
    text_body = str(body.get("text") or "").strip()
    html_body = str(body.get("html") or "").strip()
    message_id = str(body.get("message_id") or "").strip()
    received_at = str(body.get("received_at") or "").strip() or None
    content = text_body or html_body
    if not content:
        raise HTTPException(status_code=400, detail="text or html content is required")

    try:
        with get_conn() as con:
            result = _ingest_inbound_email(
                con,
                from_email=from_email,
                from_name=from_name,
                to_email=to_email,
                subject=subject,
                content=content,
                received_at=received_at,
                message_id=message_id,
                source_tag="webhook:inbound-email",
                job_id=int(body["job_id"]) if body.get("job_id") is not None else None,
                client_db_id=int(body["client_db_id"]) if body.get("client_db_id") is not None else None,
            )
        return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process inbound email webhook: {e}")


def _m365_config() -> dict[str, str]:
    return {
        "tenant_id": str(os.getenv("M365_TENANT_ID") or "").strip(),
        "client_id": str(os.getenv("M365_CLIENT_ID") or "").strip(),
        "client_secret": str(os.getenv("M365_CLIENT_SECRET") or "").strip(),
        "mailbox_user": str(os.getenv("M365_MAILBOX_USER") or "").strip(),
        "client_state": str(os.getenv("M365_CLIENT_STATE") or "").strip(),
    }


def _m365_token(cfg: dict[str, str]) -> str:
    if not (cfg["tenant_id"] and cfg["client_id"] and cfg["client_secret"]):
        raise RuntimeError("M365_TENANT_ID, M365_CLIENT_ID, M365_CLIENT_SECRET must be set")
    token_url = f"https://login.microsoftonline.com/{cfg['tenant_id']}/oauth2/v2.0/token"
    payload = urlparse.urlencode(
        {
            "grant_type": "client_credentials",
            "client_id": cfg["client_id"],
            "client_secret": cfg["client_secret"],
            "scope": "https://graph.microsoft.com/.default",
        }
    ).encode("utf-8")
    req = urlrequest.Request(token_url, data=payload, method="POST")
    req.add_header("Content-Type", "application/x-www-form-urlencoded")
    with urlrequest.urlopen(req, timeout=20) as resp:
        parsed = json.loads(resp.read().decode("utf-8"))
    token = str(parsed.get("access_token") or "").strip()
    if not token:
        raise RuntimeError("Failed to obtain Microsoft Graph token")
    return token


def _m365_graph_get(token: str, url: str) -> dict[str, Any]:
    req = urlrequest.Request(url, method="GET")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/json")
    with urlrequest.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _strip_html(raw_html: str) -> str:
    txt = re.sub(r"<\s*br\s*/?\s*>", "\n", raw_html, flags=re.IGNORECASE)
    txt = re.sub(r"<[^>]+>", " ", txt)
    txt = html.unescape(txt)
    txt = re.sub(r"\s+\n", "\n", txt)
    txt = re.sub(r"\n\s+", "\n", txt)
    txt = re.sub(r"[ \t]{2,}", " ", txt)
    return txt.strip()


def _extract_message_id_from_resource(resource: str) -> str | None:
    r = str(resource or "").strip()
    m = re.search(r"/messages/([^/?]+)", r, flags=re.IGNORECASE)
    if m:
        return m.group(1)
    return None


def _m365_fetch_message(token: str, mailbox_user: str, message_id: str) -> dict[str, Any]:
    select_cols = ",".join(
        [
            "id",
            "subject",
            "receivedDateTime",
            "internetMessageId",
            "bodyPreview",
            "body",
            "from",
            "toRecipients",
            "conversationId",
        ]
    )
    url = f"https://graph.microsoft.com/v1.0/users/{urlparse.quote(mailbox_user)}/messages/{urlparse.quote(message_id)}?$select={select_cols}"
    return _m365_graph_get(token, url)


def _m365_to_inbound_payload(msg: dict[str, Any]) -> dict[str, Any]:
    from_obj = (msg.get("from") or {}).get("emailAddress") or {}
    to_recipients = msg.get("toRecipients") or []
    to_email = ""
    if to_recipients and isinstance(to_recipients, list):
        first = to_recipients[0] or {}
        to_email = str((first.get("emailAddress") or {}).get("address") or "").strip()
    raw_html = str((msg.get("body") or {}).get("content") or "")
    body_type = str((msg.get("body") or {}).get("contentType") or "").lower()
    if body_type == "html":
        content = _strip_html(raw_html) or str(msg.get("bodyPreview") or "")
    else:
        content = raw_html or str(msg.get("bodyPreview") or "")
    return {
        "from_email": str(from_obj.get("address") or "").strip(),
        "from_name": str(from_obj.get("name") or "").strip(),
        "to_email": to_email,
        "subject": str(msg.get("subject") or "").strip(),
        "text": content.strip(),
        "received_at": str(msg.get("receivedDateTime") or "").strip() or None,
        "message_id": str(msg.get("internetMessageId") or msg.get("id") or "").strip(),
    }


@router.post("/communications/inbound/m365/notifications")
def inbound_m365_notifications(
    body: dict = Body(default={}),
    validationToken: str | None = Query(default=None),
):
    """
    Microsoft Graph notification endpoint.
    - Supports subscription validation via `validationToken` query.
    - Processes Graph notifications by fetching message payload via Graph API.
    """
    if validationToken:
        return PlainTextResponse(content=validationToken)

    cfg = _m365_config()
    if not cfg["mailbox_user"]:
        raise HTTPException(status_code=503, detail="M365_MAILBOX_USER is not configured")

    value = body.get("value") or []
    if not isinstance(value, list):
        raise HTTPException(status_code=400, detail="Invalid payload")

    try:
        token = _m365_token(cfg)
        processed = 0
        matched = 0
        errors: list[str] = []
        with get_conn() as con:
            for item in value:
                try:
                    if cfg["client_state"]:
                        incoming_state = str(item.get("clientState") or "").strip()
                        if incoming_state and incoming_state != cfg["client_state"]:
                            continue
                    message_id = _extract_message_id_from_resource(str(item.get("resource") or ""))
                    if not message_id:
                        continue
                    msg = _m365_fetch_message(token, cfg["mailbox_user"], message_id)
                    payload = _m365_to_inbound_payload(msg)
                    result = _ingest_inbound_email(
                        con,
                        from_email=str(payload.get("from_email") or ""),
                        from_name=str(payload.get("from_name") or ""),
                        to_email=str(payload.get("to_email") or ""),
                        subject=str(payload.get("subject") or ""),
                        content=str(payload.get("text") or ""),
                        received_at=payload.get("received_at"),
                        message_id=str(payload.get("message_id") or ""),
                        source_tag="webhook:m365",
                    )
                    processed += 1
                    if result.get("matched"):
                        matched += 1
                except Exception as ie:
                    errors.append(str(ie))
                    continue
        return {"ok": True, "processed": processed, "matched": matched, "errors": errors[:20]}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process m365 notifications: {e}")


@router.post("/communications/inbound/m365/sync")
def inbound_m365_sync(
    body: dict = Body(default={}),
    _user: dict = Depends(_current_user),
):
    """
    Manual pull sync for recent mailbox messages from Microsoft Graph.
    Useful as a fallback while webhook subscriptions are being finalized.
    """
    _ = _actor(_user)
    cfg = _m365_config()
    if not cfg["mailbox_user"]:
        raise HTTPException(status_code=503, detail="M365_MAILBOX_USER is not configured")
    top = int(body.get("top") or 25)
    top = max(1, min(100, top))
    try:
        token = _m365_token(cfg)
        select_cols = ",".join(
            [
                "id",
                "subject",
                "receivedDateTime",
                "internetMessageId",
                "bodyPreview",
                "body",
                "from",
                "toRecipients",
            ]
        )
        # Read latest inbox messages.
        list_url = (
            f"https://graph.microsoft.com/v1.0/users/{urlparse.quote(cfg['mailbox_user'])}/mailFolders/inbox/messages"
            f"?$top={top}&$orderby=receivedDateTime desc&$select={select_cols}"
        )
        payload = _m365_graph_get(token, list_url)
        values = payload.get("value") or []
        processed = 0
        matched = 0
        with get_conn() as con:
            for msg in values:
                inbound = _m365_to_inbound_payload(msg)
                result = _ingest_inbound_email(
                    con,
                    from_email=str(inbound.get("from_email") or ""),
                    from_name=str(inbound.get("from_name") or ""),
                    to_email=str(inbound.get("to_email") or ""),
                    subject=str(inbound.get("subject") or ""),
                    content=str(inbound.get("text") or ""),
                    received_at=inbound.get("received_at"),
                    message_id=str(inbound.get("message_id") or ""),
                    source_tag="sync:m365",
                )
                processed += 1
                if result.get("matched"):
                    matched += 1
        return {"ok": True, "processed": processed, "matched": matched}
    except HTTPError as e:
        try:
            details = e.read().decode("utf-8")
        except Exception:
            details = str(e)
        raise HTTPException(status_code=500, detail=f"Microsoft Graph error: {details}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to sync inbound m365 emails: {e}")


def _ensure_m365_subscription_table(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS crm_m365_subscriptions (
          id SERIAL PRIMARY KEY,
          subscription_id VARCHAR NOT NULL UNIQUE,
          resource VARCHAR NOT NULL,
          notification_url VARCHAR NOT NULL,
          expiration_datetime TIMESTAMP NOT NULL,
          client_state VARCHAR,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          renewed_at TIMESTAMP,
          is_active BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )


def _m365_graph_post(token: str, url: str, payload: dict) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urlrequest.Request(url, data=data, method="POST")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")
    with urlrequest.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _m365_graph_patch(token: str, url: str, payload: dict) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urlrequest.Request(url, data=data, method="PATCH")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")
    with urlrequest.urlopen(req, timeout=30) as resp:
        body = resp.read()
        return json.loads(body.decode("utf-8")) if body.strip() else {}


@router.post("/communications/inbound/m365/subscription/register")
def register_m365_subscription(body: dict = Body(default={}), _user: dict = Depends(_current_user)):
    """
    Register a Microsoft Graph webhook subscription so inbound emails to the admin
    mailbox are pushed to /communications/inbound/m365/notifications in real time.

    Requires env vars: M365_TENANT_ID, M365_CLIENT_ID, M365_CLIENT_SECRET, M365_MAILBOX_USER
    Optional: M365_CLIENT_STATE (secret used to verify notifications), APP_PUBLIC_URL

    The Azure app registration needs Mail.Read application permission (admin-consented).
    Subscriptions expire after ~3 days — call /renew to extend.
    """
    cfg = _m365_config()
    if not all([cfg["tenant_id"], cfg["client_id"], cfg["client_secret"], cfg["mailbox_user"]]):
        raise HTTPException(status_code=503, detail="M365 env vars not fully configured (need TENANT_ID, CLIENT_ID, CLIENT_SECRET, MAILBOX_USER)")

    app_url = str(body.get("app_public_url") or os.getenv("APP_PUBLIC_URL") or "").strip().rstrip("/")
    if not app_url:
        raise HTTPException(status_code=400, detail="Provide app_public_url in body or set APP_PUBLIC_URL env var (e.g. https://your-app.onrender.com/api/backend)")

    notification_url = f"{app_url}/communications/inbound/m365/notifications"
    resource = f"users/{cfg['mailbox_user']}/mailFolders/inbox/messages"

    from datetime import datetime, timedelta, timezone
    expiry = datetime.now(timezone.utc) + timedelta(minutes=4200)
    expiry_str = expiry.strftime("%Y-%m-%dT%H:%M:%S.0000000Z")

    try:
        token = _m365_token(cfg)
        payload = {
            "changeType": "created",
            "notificationUrl": notification_url,
            "resource": resource,
            "expirationDateTime": expiry_str,
            "latestSupportedTlsVersion": "v1_2",
        }
        if cfg["client_state"]:
            payload["clientState"] = cfg["client_state"]

        result = _m365_graph_post(token, "https://graph.microsoft.com/v1.0/subscriptions", payload)
        subscription_id = str(result.get("id") or "").strip()
        if not subscription_id:
            raise HTTPException(status_code=500, detail=f"Graph did not return a subscription id: {result}")

        with get_conn() as con:
            _ensure_m365_subscription_table(con)
            con.execute(
                """
                INSERT INTO crm_m365_subscriptions (subscription_id, resource, notification_url, expiration_datetime, client_state, is_active)
                VALUES (%s, %s, %s, %s, %s, TRUE)
                ON CONFLICT (subscription_id) DO UPDATE
                  SET is_active = TRUE, renewed_at = NOW(), expiration_datetime = EXCLUDED.expiration_datetime
                """,
                [subscription_id, resource, notification_url, expiry.replace(tzinfo=None), cfg["client_state"] or None],
            )

        return {
            "ok": True,
            "subscription_id": subscription_id,
            "notification_url": notification_url,
            "resource": resource,
            "expires": expiry_str,
            "note": "Subscription expires in ~3 days. Call /renew before then to keep it active.",
        }
    except HTTPError as e:
        try:
            details = e.read().decode("utf-8")
        except Exception:
            details = str(e)
        raise HTTPException(status_code=500, detail=f"Graph error registering subscription: {details}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to register M365 subscription: {e}")


@router.post("/communications/inbound/m365/subscription/renew")
def renew_m365_subscription(body: dict = Body(default={}), _user: dict = Depends(_current_user)):
    """
    Renew an existing M365 Graph subscription before it expires (~3-day lifetime).
    Pass subscription_id in body, or omit to renew the most recent active one.
    """
    cfg = _m365_config()
    if not all([cfg["tenant_id"], cfg["client_id"], cfg["client_secret"]]):
        raise HTTPException(status_code=503, detail="M365 env vars not configured")

    subscription_id = str(body.get("subscription_id") or "").strip()

    try:
        with get_conn() as con:
            _ensure_m365_subscription_table(con)
            if not subscription_id:
                row = con.execute(
                    "SELECT subscription_id FROM crm_m365_subscriptions WHERE is_active = TRUE ORDER BY created_at DESC LIMIT 1"
                ).fetchone()
                if not row:
                    raise HTTPException(status_code=404, detail="No active subscription found. Register one first.")
                subscription_id = str(row[0])

            from datetime import datetime, timedelta, timezone
            expiry = datetime.now(timezone.utc) + timedelta(minutes=4200)
            expiry_str = expiry.strftime("%Y-%m-%dT%H:%M:%S.0000000Z")

            token = _m365_token(cfg)
            _m365_graph_patch(
                token,
                f"https://graph.microsoft.com/v1.0/subscriptions/{urlparse.quote(subscription_id)}",
                {"expirationDateTime": expiry_str},
            )
            con.execute(
                """
                UPDATE crm_m365_subscriptions
                SET expiration_datetime = %s, renewed_at = NOW()
                WHERE subscription_id = %s
                """,
                [expiry.replace(tzinfo=None), subscription_id],
            )

        return {"ok": True, "subscription_id": subscription_id, "renewed_until": expiry_str}
    except HTTPError as e:
        try:
            details = e.read().decode("utf-8")
        except Exception:
            details = str(e)
        raise HTTPException(status_code=500, detail=f"Graph error renewing subscription: {details}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to renew M365 subscription: {e}")


def renew_m365_subscriptions_due(threshold_hours: int = 24) -> dict:
    """
    Renew all active M365 subscriptions expiring within threshold_hours.
    Returns {"renewed": [...], "skipped": int, "errors": [...]}
    Called by the internal cron endpoint.
    """
    from datetime import datetime, timedelta, timezone

    cfg = _m365_config()
    if not all([cfg["tenant_id"], cfg["client_id"], cfg["client_secret"]]):
        return {"renewed": [], "skipped": 0, "errors": ["M365 env vars not configured"]}

    renewed = []
    errors = []

    with get_conn() as con:
        _ensure_m365_subscription_table(con)
        cutoff = datetime.now(timezone.utc) + timedelta(hours=threshold_hours)
        rows = con.execute(
            """
            SELECT subscription_id FROM crm_m365_subscriptions
            WHERE is_active = TRUE AND expiration_datetime < %s
            ORDER BY expiration_datetime ASC
            """,
            [cutoff.replace(tzinfo=None)],
        ).fetchall()

        if not rows:
            return {"renewed": [], "skipped": 0, "errors": []}

        try:
            token = _m365_token(cfg)
        except Exception as e:
            return {"renewed": [], "skipped": len(rows), "errors": [f"Token error: {e}"]}

        expiry = datetime.now(timezone.utc) + timedelta(minutes=4200)
        expiry_str = expiry.strftime("%Y-%m-%dT%H:%M:%S.0000000Z")

        for (subscription_id,) in rows:
            try:
                _m365_graph_patch(
                    token,
                    f"https://graph.microsoft.com/v1.0/subscriptions/{urlparse.quote(subscription_id)}",
                    {"expirationDateTime": expiry_str},
                )
                con.execute(
                    "UPDATE crm_m365_subscriptions SET expiration_datetime = %s, renewed_at = NOW() WHERE subscription_id = %s",
                    [expiry.replace(tzinfo=None), subscription_id],
                )
                renewed.append({"subscription_id": subscription_id, "renewed_until": expiry_str})
            except Exception as e:
                errors.append({"subscription_id": subscription_id, "error": str(e)})

    return {"renewed": renewed, "skipped": 0, "errors": errors}


@router.get("/communications/inbound/m365/subscription/status")
def m365_subscription_status(_user: dict = Depends(_current_user)):
    """List all registered M365 subscriptions and their expiry status."""
    try:
        with get_conn() as con:
            _ensure_m365_subscription_table(con)
            df = con.execute(
                """
                SELECT subscription_id, resource, notification_url, expiration_datetime,
                       is_active, created_at, renewed_at
                FROM crm_m365_subscriptions
                ORDER BY created_at DESC
                LIMIT 20
                """
            ).df()
        items = []
        if df is not None and not df.empty:
            from datetime import datetime, timezone
            now = datetime.now(timezone.utc)
            for _, r in df.iterrows():
                exp = r.get("expiration_datetime")
                exp_iso = exp.isoformat() if exp else None
                expired = (exp.replace(tzinfo=timezone.utc) < now) if exp else True
                items.append({
                    "subscription_id": str(r.get("subscription_id") or ""),
                    "resource": str(r.get("resource") or ""),
                    "notification_url": str(r.get("notification_url") or ""),
                    "expiration_datetime": exp_iso,
                    "is_active": bool(r.get("is_active")),
                    "expired": expired,
                    "created_at": r.get("created_at").isoformat() if r.get("created_at") else None,
                    "renewed_at": r.get("renewed_at").isoformat() if r.get("renewed_at") else None,
                })
        return {"items": items}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load subscription status: {e}")
