from __future__ import annotations

from datetime import datetime
from typing import Any

import io
import pandas as pd
from fastapi import APIRouter, Body, Depends, HTTPException, Query, UploadFile, File

from api.auth import _current_user
from core.database import get_conn
from services.lca_engine import STAGE_KEYS, safe_float, summarize_items

router = APIRouter(tags=["lca"])


def _actor(user: dict[str, str]) -> str:
    return str(user.get("email") or user.get("user_id") or "system").strip()


def _ensure_tables(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS lca_products (
          product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
          product_name VARCHAR NOT NULL,
          sku VARCHAR,
          description TEXT,
          functional_unit_value DOUBLE PRECISION NOT NULL DEFAULT 1,
          functional_unit_unit VARCHAR NOT NULL DEFAULT 'kg_product',
          system_boundary VARCHAR NOT NULL DEFAULT 'cradle_to_grave',
          lca_standard VARCHAR NOT NULL DEFAULT 'ISO 14040/14044',
          reference_year INTEGER,
          geography VARCHAR,
          assumptions TEXT,
          total_embedded_tco2e DOUBLE PRECISION NOT NULL DEFAULT 0,
          last_calculated_at TIMESTAMP,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute("CREATE INDEX IF NOT EXISTS ix_lca_products_job ON lca_products (job_id, product_id)")
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS lca_product_datasets (
          product_id INTEGER NOT NULL REFERENCES lca_products(product_id) ON DELETE CASCADE,
          dataset_id INTEGER NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          PRIMARY KEY (product_id, dataset_id)
        )
        """
    )
    con.execute("CREATE INDEX IF NOT EXISTS ix_lca_product_datasets_product ON lca_product_datasets (product_id)")

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS lca_inventory_items (
          item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          product_id INTEGER NOT NULL REFERENCES lca_products(product_id) ON DELETE CASCADE,
          stage_key VARCHAR NOT NULL,
          item_name VARCHAR NOT NULL,
          item_description TEXT,
          quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
          unit VARCHAR,
          allocation_pct DOUBLE PRECISION NOT NULL DEFAULT 100,
          origin_country VARCHAR,
          raw_material_origin VARCHAR,
          process_name VARCHAR,
          energy_kwh DOUBLE PRECISION,
          waste_qty DOUBLE PRECISION,
          transport_mode VARCHAR,
          distance_km DOUBLE PRECISION,
          use_phase_energy_kwh DOUBLE PRECISION,
          recycling_rate_pct DOUBLE PRECISION,
          landfill_rate_pct DOUBLE PRECISION,
          mapped_factor_db_id INTEGER,
          factor_value DOUBLE PRECISION,
          factor_unit VARCHAR,
          factor_source VARCHAR,
          lci_database_name VARCHAR,
          data_quality VARCHAR NOT NULL DEFAULT 'secondary',
          is_gap_filled BOOLEAN NOT NULL DEFAULT FALSE,
          gap_fill_method VARCHAR,
          calculation_notes TEXT,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          created_by VARCHAR,
          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_by VARCHAR
        )
        """
    )
    con.execute("CREATE INDEX IF NOT EXISTS ix_lca_items_product ON lca_inventory_items (product_id, stage_key)")
    con.execute("CREATE INDEX IF NOT EXISTS ix_lca_items_factor ON lca_inventory_items (mapped_factor_db_id)")

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS lca_result_snapshots (
          snapshot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          product_id INTEGER NOT NULL REFERENCES lca_products(product_id) ON DELETE CASCADE,
          calculated_at TIMESTAMP NOT NULL DEFAULT NOW(),
          calculated_by VARCHAR,
          total_tco2e DOUBLE PRECISION NOT NULL DEFAULT 0,
          stage_breakdown_json TEXT NOT NULL,
          hotspots_json TEXT NOT NULL,
          notes TEXT
        )
        """
    )
    con.execute("CREATE INDEX IF NOT EXISTS ix_lca_snapshots_product ON lca_result_snapshots (product_id, snapshot_id DESC)")


def _job_exists(con, job_id: int) -> bool:
    row = con.execute("SELECT 1 FROM jobs WHERE job_id = %s LIMIT 1", [int(job_id)]).fetchone()
    return bool(row)


def _product_exists(con, job_id: int, product_id: int) -> bool:
    row = con.execute(
        "SELECT 1 FROM lca_products WHERE job_id = %s AND product_id = %s LIMIT 1",
        [int(job_id), int(product_id)],
    ).fetchone()
    return bool(row)


def _table_exists(con, table_name: str) -> bool:
    row = con.execute(
        """
        SELECT EXISTS (
          SELECT 1
          FROM information_schema.tables
          WHERE table_name = %s
        )
        """,
        [str(table_name)],
    ).fetchone()
    return bool(row and row[0])


def _to_int_list(raw: Any) -> list[int]:
    if raw is None:
        return []
    if isinstance(raw, (list, tuple, set)):
        items = list(raw)
    else:
        text = str(raw).strip()
        if not text:
            return []
        items = [x.strip() for x in text.split(",")]
    out: list[int] = []
    for v in items:
        try:
            iv = int(v)
            if iv > 0:
                out.append(iv)
        except Exception:
            continue
    return sorted(set(out))


def _get_product_dataset_ids(con, product_id: int) -> list[int]:
    df = con.execute(
        "SELECT dataset_id FROM lca_product_datasets WHERE product_id = %s ORDER BY dataset_id",
        [int(product_id)],
    ).df()
    if df is None or df.empty:
        return []
    out: list[int] = []
    for _, r in df.iterrows():
        val = r.get("dataset_id")
        if val is None:
            continue
        out.append(int(val))
    return sorted(set(out))


def _set_product_dataset_ids(con, product_id: int, dataset_ids: list[int], user: dict[str, str]) -> list[int]:
    clean = sorted(set(int(x) for x in dataset_ids if int(x) > 0))
    if clean:
        ph = ",".join(["%s"] * len(clean))
        valid_df = con.execute(
            f"SELECT dataset_id FROM datasets WHERE dataset_id IN ({ph}) AND COALESCE(archived, FALSE) = FALSE",
            clean,
        ).df()
        valid_ids = sorted(set(int(r.get("dataset_id")) for _, r in valid_df.iterrows())) if valid_df is not None and not valid_df.empty else []
    else:
        valid_ids = []

    con.execute("DELETE FROM lca_product_datasets WHERE product_id = %s", [int(product_id)])
    for dsid in valid_ids:
        con.execute(
            """
            INSERT INTO lca_product_datasets (product_id, dataset_id, created_by)
            VALUES (%s, %s, %s)
            ON CONFLICT (product_id, dataset_id) DO NOTHING
            """,
            [int(product_id), int(dsid), _actor(user)],
        )
    return valid_ids


def _get_job_dataset_ids(con, job_id: int) -> list[int]:
    out: list[int] = []
    if _table_exists(con, "job_scope_config"):
        df_scope = con.execute(
            """
            SELECT DISTINCT dataset_id
            FROM job_scope_config
            WHERE job_id = %s
              AND dataset_id IS NOT NULL
            """,
            [int(job_id)],
        ).df()
        if df_scope is not None and not df_scope.empty:
            for _, r in df_scope.iterrows():
                val = r.get("dataset_id")
                if val is not None:
                    out.append(int(val))
    if _table_exists(con, "job_additional_datasets"):
        df_additional = con.execute(
            "SELECT DISTINCT dataset_id FROM job_additional_datasets WHERE job_id = %s",
            [int(job_id)],
        ).df()
        if df_additional is not None and not df_additional.empty:
            for _, r in df_additional.iterrows():
                val = r.get("dataset_id")
                if val is not None:
                    out.append(int(val))
    return sorted(set(out))


def _resolve_lca_dataset_ids(con, job_id: int, product_id: int | None = None) -> list[int]:
    selected = _get_product_dataset_ids(con, int(product_id)) if product_id is not None else []
    if selected:
        return selected
    return _get_job_dataset_ids(con, int(job_id))


def _list_available_datasets(con) -> list[dict[str, Any]]:
    df = con.execute(
        """
        SELECT dataset_id, name, analysis_type, country, year, version
        FROM datasets
        WHERE COALESCE(archived, FALSE) = FALSE
        ORDER BY year DESC NULLS LAST, name ASC
        """
    ).df()
    out: list[dict[str, Any]] = []
    if df is None or df.empty:
        return out
    for _, r in df.iterrows():
        out.append(
            {
                "dataset_id": int(r.get("dataset_id")),
                "name": str(r.get("name") or ""),
                "analysis_type": str(r.get("analysis_type") or ""),
                "country": str(r.get("country") or ""),
                "year": int(r.get("year")) if r.get("year") is not None else None,
                "version": str(r.get("version") or ""),
            }
        )
    return out


def _load_product_item_rows(con, product_id: int) -> list[dict[str, Any]]:
    df = con.execute(
        """
        SELECT item_id, stage_key, item_name, quantity, factor_value, factor_unit,
               allocation_pct, is_gap_filled, data_quality
        FROM lca_inventory_items
        WHERE product_id = %s
        ORDER BY item_id
        """,
        [int(product_id)],
    ).df()
    if df is None or df.empty:
        return []
    rows: list[dict[str, Any]] = []
    for _, r in df.iterrows():
        rows.append(
            {
                "item_id": int(r.get("item_id") or 0),
                "stage_key": str(r.get("stage_key") or "materials"),
                "item_name": str(r.get("item_name") or "Unnamed item"),
                "quantity": safe_float(r.get("quantity")),
                "factor_value": safe_float(r.get("factor_value")),
                "factor_unit": str(r.get("factor_unit") or "kgCO2e/unit"),
                "allocation_pct": safe_float(r.get("allocation_pct"), 100.0),
                "is_gap_filled": bool(r.get("is_gap_filled") or False),
                "data_quality": str(r.get("data_quality") or "secondary"),
            }
        )
    return rows


def _recalculate_product(con, product_id: int, user: dict[str, str]) -> dict[str, Any]:
    rows = _load_product_item_rows(con, int(product_id))
    summary = summarize_items(rows)
    con.execute(
        """
        UPDATE lca_products
        SET total_embedded_tco2e = %s,
            last_calculated_at = NOW(),
            updated_at = NOW(),
            updated_by = %s
        WHERE product_id = %s
        """,
        [summary["total_tco2e"], _actor(user), int(product_id)],
    )
    con.execute(
        """
        INSERT INTO lca_result_snapshots (
          product_id, calculated_by, total_tco2e, stage_breakdown_json, hotspots_json, notes
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        [
            int(product_id),
            _actor(user),
            summary["total_tco2e"],
            str(summary["stage_breakdown"]),
            str(summary["hotspots"]),
            "Auto recalculation",
        ],
    )
    return summary


def _find_factor_candidates(
    con,
    item_name: str,
    stage_key: str,
    unit: str,
    country: str | None,
    dataset_ids: list[int] | None = None,
) -> list[dict[str, Any]]:
    stage_keywords = {
        "materials": "material raw bom purchased goods",
        "manufacturing": "manufacturing electricity gas process plant",
        "logistics": "transport freight logistics delivery shipping",
        "use_end_of_life": "use lifecycle recycling landfill disposal waste",
    }
    keyword_blob = stage_keywords.get(stage_key, "")
    item_pattern = f"%{item_name.strip()}%"
    unit_pattern = str(unit or "").strip()
    country_pattern = str(country or "").strip()
    words = [w for w in keyword_blob.split() if w]
    keyword_expr = " OR ".join(
        [
            "(COALESCE(fl.report_label,'') ILIKE %s OR COALESCE(fl.column_text,'') ILIKE %s OR COALESCE(fl.level_1,'') ILIKE %s OR COALESCE(fl.level_2,'') ILIKE %s)"
            for _ in words
        ]
    )
    keyword_params: list[Any] = []
    for word in words:
        pat = f"%{word}%"
        keyword_params.extend([pat, pat, pat, pat])

    where_clause = "COALESCE(fl.factor, 0) > 0 AND (COALESCE(fl.report_label,'') ILIKE %s OR COALESCE(fl.column_text,'') ILIKE %s)"
    params: list[Any] = [item_pattern, item_pattern]
    if keyword_expr:
        where_clause = f"{where_clause} OR ({keyword_expr})"
        params.extend(keyword_params)

    selected = sorted(set(int(x) for x in (dataset_ids or []) if int(x) > 0))
    if selected:
        ph = ",".join(["%s"] * len(selected))
        where_clause = f"({where_clause}) AND fl.dataset_id IN ({ph})"
        params.extend(selected)

    df = con.execute(
        f"""
        SELECT
          fl.db_id,
          fl.report_label,
          fl.column_text,
          fl.uom,
          fl.factor,
          fl.source,
          fl.region,
          fl.country,
          (
            CASE WHEN COALESCE(fl.uom, '') <> '' AND lower(fl.uom) = lower(%s) THEN 20 ELSE 0 END +
            CASE WHEN %s <> '' AND lower(COALESCE(fl.country,'')) = lower(%s) THEN 15 ELSE 0 END +
            CASE WHEN COALESCE(fl.report_label,'') ILIKE %s OR COALESCE(fl.column_text,'') ILIKE %s THEN 25 ELSE 0 END
          ) AS score
        FROM v_factor_lookup fl
        WHERE {where_clause}
        ORDER BY score DESC, fl.year DESC NULLS LAST, fl.db_id DESC
        LIMIT 10
        """,
        [unit_pattern, country_pattern, country_pattern, item_pattern, item_pattern, *params],
    ).df()
    out: list[dict[str, Any]] = []
    if df is None or df.empty:
        return out
    for _, r in df.iterrows():
        out.append(
            {
                "db_id": int(r.get("db_id")),
                "label": str(r.get("report_label") or r.get("column_text") or f"Factor {r.get('db_id')}"),
                "uom": r.get("uom"),
                "factor": safe_float(r.get("factor")),
                "source": r.get("source"),
                "country": r.get("country"),
                "region": r.get("region"),
                "score": safe_float(r.get("score")),
            }
        )
    return out


def _estimate_gap_factor(
    con,
    stage_key: str,
    unit: str,
    dataset_ids: list[int] | None = None,
) -> tuple[float, str]:
    stage_words = {
        "materials": ["material", "raw", "bom", "ingredient", "component"],
        "manufacturing": ["manufacturing", "process", "electric", "gas", "plant"],
        "logistics": ["transport", "logistics", "freight", "delivery"],
        "use_end_of_life": ["use", "recycling", "landfill", "disposal", "waste"],
    }.get(stage_key, [])
    unit_text = str(unit or "").strip()

    base_sql = """
        SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY fl.factor) AS p50_factor
        FROM v_factor_lookup fl
        WHERE fl.factor IS NOT NULL
          AND fl.factor > 0
    """
    params: list[Any] = []
    if unit_text:
        base_sql += " AND lower(COALESCE(fl.uom,'')) = lower(%s)"
        params.append(unit_text)
    if stage_words:
        conditions: list[str] = []
        for _ in stage_words:
            conditions.append(
                "(COALESCE(fl.report_label,'') ILIKE %s OR COALESCE(fl.column_text,'') ILIKE %s OR COALESCE(fl.level_1,'') ILIKE %s OR COALESCE(fl.level_2,'') ILIKE %s)"
            )
        base_sql += f" AND ({' OR '.join(conditions)})"
        for word in stage_words:
            pat = f"%{word}%"
            params.extend([pat, pat, pat, pat])

    selected = sorted(set(int(x) for x in (dataset_ids or []) if int(x) > 0))
    if selected:
        ph = ",".join(["%s"] * len(selected))
        base_sql += f" AND fl.dataset_id IN ({ph})"
        params.extend(selected)

    row = con.execute(base_sql, params).fetchone()
    estimated = safe_float(row[0] if row else 0.0)
    if estimated > 0:
        return estimated, "median_factor_by_stage_and_unit"

    sql2 = """
        SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY fl.factor)
        FROM v_factor_lookup fl
        WHERE fl.factor IS NOT NULL
          AND fl.factor > 0
          AND (%s = '' OR lower(COALESCE(fl.uom,'')) = lower(%s))
    """
    params2: list[Any] = [unit_text, unit_text]
    if selected:
        ph2 = ",".join(["%s"] * len(selected))
        sql2 += f" AND fl.dataset_id IN ({ph2})"
        params2.extend(selected)
    row2 = con.execute(sql2, params2).fetchone()
    estimated2 = safe_float(row2[0] if row2 else 0.0)
    if estimated2 > 0:
        return estimated2, "median_factor_by_unit"
    return 0.0, "no_estimate_available"


def _normalize_col(col: Any) -> str:
    return str(col or "").strip().lower().replace("-", "_").replace(" ", "_")


@router.get("/jobs/{job_id}/lca/overview")
def lca_overview(job_id: int, _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            products_df = con.execute(
                """
                SELECT product_id, product_name, sku, functional_unit_value, functional_unit_unit,
                       system_boundary, lca_standard, total_embedded_tco2e, last_calculated_at
                FROM lca_products
                WHERE job_id = %s
                ORDER BY product_id DESC
                """,
                [int(job_id)],
            ).df()
            products: list[dict[str, Any]] = []
            portfolio_total = 0.0
            if products_df is not None and not products_df.empty:
                for _, r in products_df.iterrows():
                    product_total = safe_float(r.get("total_embedded_tco2e"))
                    portfolio_total += product_total
                    products.append(
                        {
                            "product_id": int(r.get("product_id")),
                            "product_name": r.get("product_name"),
                            "sku": r.get("sku"),
                            "functional_unit_value": safe_float(r.get("functional_unit_value"), 1.0),
                            "functional_unit_unit": r.get("functional_unit_unit"),
                            "system_boundary": r.get("system_boundary"),
                            "lca_standard": r.get("lca_standard"),
                            "total_embedded_tco2e": round(product_total, 6),
                            "last_calculated_at": str(r.get("last_calculated_at")) if r.get("last_calculated_at") else None,
                        }
                    )
            return {
                "job_id": int(job_id),
                "products_count": len(products),
                "total_embedded_tco2e": round(portfolio_total, 6),
                "products": products,
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load LCA overview: {e}")


@router.get("/jobs/{job_id}/lca/products")
def list_lca_products(job_id: int, _user: dict[str, str] = Depends(_current_user)):
    return lca_overview(job_id=job_id, _user=_user)


@router.post("/jobs/{job_id}/lca/products")
def create_lca_product(job_id: int, body: dict = Body(...), _user: dict[str, str] = Depends(_current_user)):
    try:
        name = str(body.get("product_name") or "").strip()
        if not name:
            raise HTTPException(status_code=400, detail="product_name is required")
        with get_conn() as con:
            _ensure_tables(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            row = con.execute(
                """
                INSERT INTO lca_products (
                  job_id, product_name, sku, description, functional_unit_value, functional_unit_unit,
                  system_boundary, lca_standard, reference_year, geography, assumptions, created_by, updated_by
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING product_id
                """,
                [
                    int(job_id),
                    name,
                    str(body.get("sku") or "").strip() or None,
                    str(body.get("description") or "").strip() or None,
                    safe_float(body.get("functional_unit_value"), 1.0),
                    str(body.get("functional_unit_unit") or "kg_product").strip(),
                    str(body.get("system_boundary") or "cradle_to_grave").strip(),
                    str(body.get("lca_standard") or "ISO 14040/14044").strip(),
                    int(body.get("reference_year")) if str(body.get("reference_year") or "").strip().isdigit() else None,
                    str(body.get("geography") or "").strip() or None,
                    str(body.get("assumptions") or "").strip() or None,
                    _actor(_user),
                    _actor(_user),
                ],
            ).fetchone()
            pid = int(row[0])
            requested_dataset_ids = _to_int_list(body.get("dataset_ids"))
            if requested_dataset_ids:
                _set_product_dataset_ids(con, pid, requested_dataset_ids, _user)
            return {"ok": True, "product_id": pid}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create LCA product: {e}")


@router.patch("/jobs/{job_id}/lca/products/{product_id}")
def update_lca_product(job_id: int, product_id: int, body: dict = Body(...), _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            updates = []
            params: list[Any] = []
            editable_fields = [
                "product_name", "sku", "description", "functional_unit_value", "functional_unit_unit",
                "system_boundary", "lca_standard", "reference_year", "geography", "assumptions",
            ]
            for field in editable_fields:
                if field not in body:
                    continue
                updates.append(f"{field} = %s")
                if field == "functional_unit_value":
                    params.append(safe_float(body.get(field), 1.0))
                elif field == "reference_year":
                    raw = str(body.get(field) or "").strip()
                    params.append(int(raw) if raw.isdigit() else None)
                else:
                    val = str(body.get(field) or "").strip()
                    params.append(val or None)
            if not updates:
                return {"ok": True}
            updates.extend(["updated_at = NOW()", "updated_by = %s"])
            params.append(_actor(_user))
            params.extend([int(job_id), int(product_id)])
            con.execute(f"UPDATE lca_products SET {', '.join(updates)} WHERE job_id = %s AND product_id = %s", params)
            if "dataset_ids" in body:
                _set_product_dataset_ids(con, int(product_id), _to_int_list(body.get("dataset_ids")), _user)
            summary = _recalculate_product(con, int(product_id), _user)
            return {"ok": True, "summary": summary}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update LCA product: {e}")


@router.get("/jobs/{job_id}/lca/products/{product_id}/datasets")
def get_lca_product_datasets(job_id: int, product_id: int, _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            selected = _get_product_dataset_ids(con, int(product_id))
            inherited = _get_job_dataset_ids(con, int(job_id))
            available = _list_available_datasets(con)
            return {
                "job_id": int(job_id),
                "product_id": int(product_id),
                "selected_dataset_ids": selected,
                "inherited_job_dataset_ids": inherited,
                "effective_dataset_ids": selected if selected else inherited,
                "datasets": available,
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load LCA datasets: {e}")


@router.put("/jobs/{job_id}/lca/products/{product_id}/datasets")
def update_lca_product_datasets(
    job_id: int,
    product_id: int,
    body: dict = Body(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            selected = _set_product_dataset_ids(con, int(product_id), _to_int_list(body.get("dataset_ids")), _user)
            effective = _resolve_lca_dataset_ids(con, int(job_id), int(product_id))
            return {"ok": True, "selected_dataset_ids": selected, "effective_dataset_ids": effective}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update LCA datasets: {e}")


@router.get("/jobs/{job_id}/lca/products/{product_id}/items")
def list_lca_items(job_id: int, product_id: int, _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            df = con.execute("SELECT * FROM lca_inventory_items WHERE product_id = %s ORDER BY stage_key, item_id", [int(product_id)]).df()
            items: list[dict[str, Any]] = []
            if df is not None and not df.empty:
                for _, r in df.iterrows():
                    items.append(
                        {
                            "item_id": int(r.get("item_id")),
                            "stage_key": r.get("stage_key"),
                            "item_name": r.get("item_name"),
                            "item_description": r.get("item_description"),
                            "quantity": safe_float(r.get("quantity")),
                            "unit": r.get("unit"),
                            "allocation_pct": safe_float(r.get("allocation_pct"), 100.0),
                            "origin_country": r.get("origin_country"),
                            "raw_material_origin": r.get("raw_material_origin"),
                            "process_name": r.get("process_name"),
                            "energy_kwh": safe_float(r.get("energy_kwh")),
                            "waste_qty": safe_float(r.get("waste_qty")),
                            "transport_mode": r.get("transport_mode"),
                            "distance_km": safe_float(r.get("distance_km")),
                            "use_phase_energy_kwh": safe_float(r.get("use_phase_energy_kwh")),
                            "recycling_rate_pct": safe_float(r.get("recycling_rate_pct")),
                            "landfill_rate_pct": safe_float(r.get("landfill_rate_pct")),
                            "mapped_factor_db_id": int(r.get("mapped_factor_db_id")) if r.get("mapped_factor_db_id") is not None else None,
                            "factor_value": safe_float(r.get("factor_value")),
                            "factor_unit": r.get("factor_unit"),
                            "factor_source": r.get("factor_source"),
                            "lci_database_name": r.get("lci_database_name"),
                            "data_quality": r.get("data_quality"),
                            "is_gap_filled": bool(r.get("is_gap_filled") or False),
                            "gap_fill_method": r.get("gap_fill_method"),
                            "calculation_notes": r.get("calculation_notes"),
                            "updated_at": str(r.get("updated_at")) if r.get("updated_at") else None,
                        }
                    )
            summary = _recalculate_product(con, int(product_id), _user)
            selected_dataset_ids = _get_product_dataset_ids(con, int(product_id))
            effective_dataset_ids = _resolve_lca_dataset_ids(con, int(job_id), int(product_id))
            return {
                "job_id": int(job_id),
                "product_id": int(product_id),
                "items": items,
                "summary": summary,
                "selected_dataset_ids": selected_dataset_ids,
                "effective_dataset_ids": effective_dataset_ids,
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load LCA items: {e}")


@router.post("/jobs/{job_id}/lca/products/{product_id}/items")
def create_lca_item(job_id: int, product_id: int, body: dict = Body(...), _user: dict[str, str] = Depends(_current_user)):
    try:
        stage = str(body.get("stage_key") or "").strip()
        if stage not in STAGE_KEYS:
            raise HTTPException(status_code=400, detail=f"stage_key must be one of: {', '.join(STAGE_KEYS)}")
        item_name = str(body.get("item_name") or "").strip()
        if not item_name:
            raise HTTPException(status_code=400, detail="item_name is required")
        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            row = con.execute(
                """
                INSERT INTO lca_inventory_items (
                  product_id, stage_key, item_name, item_description, quantity, unit, allocation_pct,
                  origin_country, raw_material_origin, process_name, energy_kwh, waste_qty, transport_mode,
                  distance_km, use_phase_energy_kwh, recycling_rate_pct, landfill_rate_pct,
                  mapped_factor_db_id, factor_value, factor_unit, factor_source, lci_database_name,
                  data_quality, is_gap_filled, gap_fill_method, calculation_notes, created_by, updated_by
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING item_id
                """,
                [
                    int(product_id), stage, item_name, str(body.get("item_description") or "").strip() or None,
                    safe_float(body.get("quantity")), str(body.get("unit") or "").strip() or None,
                    safe_float(body.get("allocation_pct"), 100.0), str(body.get("origin_country") or "").strip() or None,
                    str(body.get("raw_material_origin") or "").strip() or None, str(body.get("process_name") or "").strip() or None,
                    safe_float(body.get("energy_kwh")), safe_float(body.get("waste_qty")),
                    str(body.get("transport_mode") or "").strip() or None, safe_float(body.get("distance_km")),
                    safe_float(body.get("use_phase_energy_kwh")), safe_float(body.get("recycling_rate_pct")),
                    safe_float(body.get("landfill_rate_pct")),
                    int(body.get("mapped_factor_db_id")) if str(body.get("mapped_factor_db_id") or "").strip().isdigit() else None,
                    safe_float(body.get("factor_value")), str(body.get("factor_unit") or "kgCO2e/unit").strip(),
                    str(body.get("factor_source") or "").strip() or None, str(body.get("lci_database_name") or "").strip() or None,
                    str(body.get("data_quality") or "secondary").strip(), bool(body.get("is_gap_filled") or False),
                    str(body.get("gap_fill_method") or "").strip() or None, str(body.get("calculation_notes") or "").strip() or None,
                    _actor(_user), _actor(_user),
                ],
            ).fetchone()
            summary = _recalculate_product(con, int(product_id), _user)
            return {"ok": True, "item_id": int(row[0]), "summary": summary}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create LCA item: {e}")


@router.patch("/jobs/{job_id}/lca/items/{item_id}")
def update_lca_item(job_id: int, item_id: int, body: dict = Body(...), _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            item_row = con.execute(
                """
                SELECT li.product_id
                FROM lca_inventory_items li
                JOIN lca_products lp ON lp.product_id = li.product_id
                WHERE li.item_id = %s AND lp.job_id = %s
                LIMIT 1
                """,
                [int(item_id), int(job_id)],
            ).fetchone()
            if not item_row:
                raise HTTPException(status_code=404, detail="LCA item not found")
            product_id = int(item_row[0])
            edits = []
            params: list[Any] = []
            editable = [
                "stage_key", "item_name", "item_description", "quantity", "unit", "allocation_pct",
                "origin_country", "raw_material_origin", "process_name", "energy_kwh", "waste_qty",
                "transport_mode", "distance_km", "use_phase_energy_kwh", "recycling_rate_pct",
                "landfill_rate_pct", "mapped_factor_db_id", "factor_value", "factor_unit", "factor_source",
                "lci_database_name", "data_quality", "is_gap_filled", "gap_fill_method", "calculation_notes",
            ]
            for field in editable:
                if field not in body:
                    continue
                if field == "stage_key":
                    val = str(body.get(field) or "").strip()
                    if val not in STAGE_KEYS:
                        raise HTTPException(status_code=400, detail=f"Invalid stage_key: {val}")
                    edits.append(f"{field} = %s")
                    params.append(val)
                elif field in {
                    "quantity", "allocation_pct", "energy_kwh", "waste_qty", "distance_km",
                    "use_phase_energy_kwh", "recycling_rate_pct", "landfill_rate_pct", "factor_value",
                }:
                    edits.append(f"{field} = %s")
                    params.append(safe_float(body.get(field)))
                elif field == "mapped_factor_db_id":
                    raw = str(body.get(field) or "").strip()
                    edits.append(f"{field} = %s")
                    params.append(int(raw) if raw.isdigit() else None)
                elif field == "is_gap_filled":
                    edits.append(f"{field} = %s")
                    params.append(bool(body.get(field)))
                else:
                    text = str(body.get(field) or "").strip()
                    edits.append(f"{field} = %s")
                    params.append(text or None)
            if not edits:
                return {"ok": True}
            edits.extend(["updated_at = NOW()", "updated_by = %s"])
            params.append(_actor(_user))
            params.append(int(item_id))
            con.execute(f"UPDATE lca_inventory_items SET {', '.join(edits)} WHERE item_id = %s", params)
            summary = _recalculate_product(con, int(product_id), _user)
            return {"ok": True, "summary": summary}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update LCA item: {e}")


@router.delete("/jobs/{job_id}/lca/items/{item_id}")
def delete_lca_item(job_id: int, item_id: int, _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            item_row = con.execute(
                """
                SELECT li.product_id
                FROM lca_inventory_items li
                JOIN lca_products lp ON lp.product_id = li.product_id
                WHERE li.item_id = %s AND lp.job_id = %s
                LIMIT 1
                """,
                [int(item_id), int(job_id)],
            ).fetchone()
            if not item_row:
                raise HTTPException(status_code=404, detail="LCA item not found")
            product_id = int(item_row[0])
            con.execute("DELETE FROM lca_inventory_items WHERE item_id = %s", [int(item_id)])
            summary = _recalculate_product(con, int(product_id), _user)
            return {"ok": True, "summary": summary}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete LCA item: {e}")


@router.post("/jobs/{job_id}/lca/items/{item_id}/map-factor")
def map_lca_item_factor(job_id: int, item_id: int, body: dict = Body(default={}), _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            row = con.execute(
                """
                SELECT li.item_id, li.product_id, li.item_name, li.stage_key, COALESCE(li.unit, '') AS unit,
                       COALESCE(li.origin_country, '') AS origin_country
                FROM lca_inventory_items li
                JOIN lca_products lp ON lp.product_id = li.product_id
                WHERE li.item_id = %s AND lp.job_id = %s
                LIMIT 1
                """,
                [int(item_id), int(job_id)],
            ).fetchone()
            if not row:
                raise HTTPException(status_code=404, detail="LCA item not found")
            product_id = int(row[1])
            dataset_ids = _resolve_lca_dataset_ids(con, int(job_id), int(product_id))
            candidates = _find_factor_candidates(
                con=con,
                item_name=str(row[2] or ""),
                stage_key=str(row[3] or ""),
                unit=str(row[4] or ""),
                country=str(row[5] or ""),
                dataset_ids=dataset_ids,
            )
            apply_top = bool(body.get("apply_top_match", True))
            applied = None
            if candidates and apply_top:
                top = candidates[0]
                con.execute(
                    """
                    UPDATE lca_inventory_items
                    SET mapped_factor_db_id = %s, factor_value = %s, factor_unit = %s, factor_source = %s,
                        lci_database_name = %s, is_gap_filled = FALSE, gap_fill_method = NULL,
                        updated_at = NOW(), updated_by = %s
                    WHERE item_id = %s
                    """,
                    [int(top["db_id"]), safe_float(top["factor"]), str(top.get("uom") or "kgCO2e/unit"),
                     str(top.get("source") or "factor_lookup"), "factor_lookup", _actor(_user), int(item_id)],
                )
                applied = top
            summary = _recalculate_product(con, int(product_id), _user)
            return {
                "ok": True,
                "applied": applied,
                "candidates": candidates,
                "summary": summary,
                "dataset_ids_used": dataset_ids,
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to map emission factor: {e}")


@router.post("/jobs/{job_id}/lca/items/{item_id}/gap-fill")
def gap_fill_lca_item(job_id: int, item_id: int, body: dict = Body(default={}), _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            row = con.execute(
                """
                SELECT li.item_id, li.product_id, li.stage_key, COALESCE(li.unit, '') AS unit
                FROM lca_inventory_items li
                JOIN lca_products lp ON lp.product_id = li.product_id
                WHERE li.item_id = %s AND lp.job_id = %s
                LIMIT 1
                """,
                [int(item_id), int(job_id)],
            ).fetchone()
            if not row:
                raise HTTPException(status_code=404, detail="LCA item not found")
            product_id = int(row[1])
            dataset_ids = _resolve_lca_dataset_ids(con, int(job_id), int(product_id))
            estimate, method = _estimate_gap_factor(
                con,
                str(row[2] or "materials"),
                str(row[3] or ""),
                dataset_ids=dataset_ids,
            )
            apply_fill = bool(body.get("apply", True))
            if apply_fill and estimate > 0:
                con.execute(
                    """
                    UPDATE lca_inventory_items
                    SET factor_value = %s, factor_unit = COALESCE(NULLIF(factor_unit, ''), %s),
                        factor_source = 'predictive_estimate', lci_database_name = 'estimated',
                        is_gap_filled = TRUE, gap_fill_method = %s, updated_at = NOW(), updated_by = %s
                    WHERE item_id = %s
                    """,
                    [estimate, "kgCO2e/unit", method, _actor(_user), int(item_id)],
                )
            summary = _recalculate_product(con, int(product_id), _user)
            return {
                "ok": True,
                "estimated_factor": round(estimate, 8),
                "method": method,
                "applied": bool(apply_fill and estimate > 0),
                "summary": summary,
                "dataset_ids_used": dataset_ids,
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to gap-fill item: {e}")


@router.post("/jobs/{job_id}/lca/products/{product_id}/recalculate")
def recalculate_lca_product(job_id: int, product_id: int, _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            summary = _recalculate_product(con, int(product_id), _user)
            return {"ok": True, "summary": summary}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to recalculate product LCA: {e}")


@router.get("/jobs/{job_id}/lca/products/{product_id}/report")
def lca_audit_report(job_id: int, product_id: int, _user: dict[str, str] = Depends(_current_user)):
    try:
        with get_conn() as con:
            _ensure_tables(con)
            product = con.execute(
                """
                SELECT product_id, product_name, sku, description, functional_unit_value, functional_unit_unit,
                       system_boundary, lca_standard, reference_year, geography, assumptions
                FROM lca_products
                WHERE product_id = %s AND job_id = %s
                LIMIT 1
                """,
                [int(product_id), int(job_id)],
            ).fetchone()
            if not product:
                raise HTTPException(status_code=404, detail="LCA product not found")
            summary = _recalculate_product(con, int(product_id), _user)
            items_df = con.execute(
                """
                SELECT item_id, stage_key, item_name, item_description, quantity, unit, factor_value, factor_unit,
                       factor_source, lci_database_name, is_gap_filled, gap_fill_method, data_quality
                FROM lca_inventory_items
                WHERE product_id = %s
                ORDER BY stage_key, item_id
                """,
                [int(product_id)],
            ).df()
            inventory_rows: list[dict[str, Any]] = []
            if items_df is not None and not items_df.empty:
                for _, r in items_df.iterrows():
                    inventory_rows.append(
                        {
                            "item_id": int(r.get("item_id")),
                            "stage_key": r.get("stage_key"),
                            "item_name": r.get("item_name"),
                            "item_description": r.get("item_description"),
                            "quantity": safe_float(r.get("quantity")),
                            "unit": r.get("unit"),
                            "factor_value": safe_float(r.get("factor_value")),
                            "factor_unit": r.get("factor_unit"),
                            "factor_source": r.get("factor_source"),
                            "lci_database_name": r.get("lci_database_name"),
                            "is_gap_filled": bool(r.get("is_gap_filled") or False),
                            "gap_fill_method": r.get("gap_fill_method"),
                            "data_quality": r.get("data_quality"),
                        }
                    )
            gap_count = sum(1 for r in inventory_rows if bool(r.get("is_gap_filled")))
            total_rows = len(inventory_rows)

            return {
                "job_id": int(job_id),
                "product_id": int(product[0]),
                "generated_at": datetime.utcnow().isoformat(),
                "goal_scope": {
                    "product_name": product[1],
                    "sku": product[2],
                    "description": product[3],
                    "functional_unit": f"{safe_float(product[4], 1.0)} {product[5]}",
                    "system_boundary": product[6],
                    "lca_standard": product[7],
                    "reference_year": product[8],
                    "geography": product[9],
                    "assumptions": product[10],
                },
                "inventory_analysis": {"rows_count": total_rows, "rows": inventory_rows},
                "impact_assessment": {
                    "method": "Global Warming Potential (GWP 100)",
                    "unit": "tCO2e",
                    "total_embedded_tco2e": summary["total_tco2e"],
                    "stage_breakdown": summary["stage_breakdown"],
                },
                "hotspots": summary["hotspots"],
                "data_quality": {
                    "gap_filled_rows": gap_count,
                    "primary_data_rows": sum(1 for r in inventory_rows if str(r.get("data_quality") or "").lower() == "primary"),
                    "secondary_data_rows": sum(1 for r in inventory_rows if str(r.get("data_quality") or "").lower() != "primary"),
                    "gap_filled_pct": round((gap_count / total_rows * 100.0) if total_rows else 0.0, 2),
                },
                "iso_14040_14044_checklist": {
                    "goal_and_scope_defined": bool(product[1] and product[5] and product[6]),
                    "inventory_collected": total_rows > 0,
                    "impact_assessed_gwp": summary["total_tco2e"] >= 0,
                    "interpretation_hotspots_available": len(summary["hotspots"]) > 0,
                },
            }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate LCA report payload: {e}")


@router.get("/jobs/{job_id}/lca/lci-search")
def lci_search(
    job_id: int,
    q: str = Query(default=""),
    product_id: int | None = Query(default=None),
    dataset_ids: str = Query(default=""),
    unit: str = Query(default=""),
    country: str = Query(default=""),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        query = str(q or "").strip()
        if not query:
            return {"items": []}
        with get_conn() as con:
            _ensure_tables(con)
            if not _job_exists(con, int(job_id)):
                raise HTTPException(status_code=404, detail="Job not found")
            selected_ids = _to_int_list(dataset_ids)
            if not selected_ids:
                selected_ids = _resolve_lca_dataset_ids(con, int(job_id), int(product_id)) if product_id else _get_job_dataset_ids(con, int(job_id))
            candidates = _find_factor_candidates(
                con=con,
                item_name=query,
                stage_key="materials",
                unit=str(unit or ""),
                country=str(country or ""),
                dataset_ids=selected_ids,
            )
            return {"items": candidates, "dataset_ids_used": selected_ids}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to search LCI factors: {e}")


@router.post("/jobs/{job_id}/lca/products/{product_id}/bom-upload")
async def upload_bom_file(
    job_id: int,
    product_id: int,
    file: UploadFile = File(...),
    _user: dict[str, str] = Depends(_current_user),
):
    try:
        filename = str(file.filename or "").strip().lower()
        raw = await file.read()
        if not raw:
            raise HTTPException(status_code=400, detail="Uploaded file is empty")

        if filename.endswith(".csv"):
            df = pd.read_csv(io.BytesIO(raw))
        elif filename.endswith(".xlsx") or filename.endswith(".xlsm") or filename.endswith(".xls"):
            df = pd.read_excel(io.BytesIO(raw))
        else:
            raise HTTPException(status_code=400, detail="Unsupported file type. Use CSV or XLSX.")

        if df is None or df.empty:
            raise HTTPException(status_code=400, detail="No rows found in BOM file")

        norm_map = {_normalize_col(c): c for c in df.columns}

        def getv(row: Any, names: list[str], default: Any = None) -> Any:
            for name in names:
                original = norm_map.get(_normalize_col(name))
                if original is not None:
                    val = row.get(original)
                    if val is not None and str(val).strip() != "":
                        return val
            return default

        inserted = 0
        mapped = 0
        gap_filled = 0
        skipped = 0

        with get_conn() as con:
            _ensure_tables(con)
            if not _product_exists(con, int(job_id), int(product_id)):
                raise HTTPException(status_code=404, detail="LCA product not found")
            dataset_ids = _resolve_lca_dataset_ids(con, int(job_id), int(product_id))

            for _, row in df.iterrows():
                item_name = str(
                    getv(
                        row,
                        ["item_name", "material", "material_name", "component", "component_name", "name", "description"],
                        "",
                    )
                    or ""
                ).strip()
                if not item_name:
                    skipped += 1
                    continue

                stage_raw = str(getv(row, ["stage", "stage_key", "lifecycle_stage"], "materials") or "materials").strip().lower()
                stage_key = stage_raw if stage_raw in STAGE_KEYS else "materials"
                qty = safe_float(getv(row, ["quantity", "qty", "weight", "unit_weight", "mass"], 0))
                unit = str(getv(row, ["unit", "uom", "units"], "kg") or "kg").strip()
                origin_country = str(getv(row, ["origin_country", "country", "raw_material_origin_country"], "") or "").strip()
                item_description = str(getv(row, ["item_description", "description", "notes"], "") or "").strip()
                explicit_factor = safe_float(getv(row, ["factor", "factor_value", "emission_factor"], 0))
                explicit_factor_unit = str(getv(row, ["factor_unit", "emission_factor_unit"], "kgCO2e/unit") or "kgCO2e/unit").strip()

                row_insert = con.execute(
                    """
                    INSERT INTO lca_inventory_items (
                      product_id, stage_key, item_name, item_description, quantity, unit,
                      origin_country, raw_material_origin, factor_value, factor_unit,
                      data_quality, created_by, updated_by
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING item_id
                    """,
                    [
                        int(product_id),
                        stage_key,
                        item_name,
                        item_description or None,
                        qty,
                        unit or None,
                        origin_country or None,
                        origin_country or None,
                        explicit_factor,
                        explicit_factor_unit,
                        "secondary",
                        _actor(_user),
                        _actor(_user),
                    ],
                ).fetchone()
                item_id = int(row_insert[0])
                inserted += 1

                if explicit_factor > 0:
                    continue

                candidates = _find_factor_candidates(
                    con,
                    item_name=item_name,
                    stage_key=stage_key,
                    unit=unit,
                    country=origin_country,
                    dataset_ids=dataset_ids,
                )
                if candidates:
                    top = candidates[0]
                    con.execute(
                        """
                        UPDATE lca_inventory_items
                        SET mapped_factor_db_id = %s, factor_value = %s, factor_unit = %s, factor_source = %s,
                            lci_database_name = %s, is_gap_filled = FALSE, gap_fill_method = NULL,
                            updated_at = NOW(), updated_by = %s
                        WHERE item_id = %s
                        """,
                        [
                            int(top["db_id"]),
                            safe_float(top["factor"]),
                            str(top.get("uom") or "kgCO2e/unit"),
                            str(top.get("source") or "factor_lookup"),
                            "factor_lookup",
                            _actor(_user),
                            item_id,
                        ],
                    )
                    mapped += 1
                else:
                    estimate, method = _estimate_gap_factor(con, stage_key, unit, dataset_ids=dataset_ids)
                    if estimate > 0:
                        con.execute(
                            """
                            UPDATE lca_inventory_items
                            SET factor_value = %s, factor_unit = COALESCE(NULLIF(factor_unit, ''), %s),
                                factor_source = 'predictive_estimate', lci_database_name = 'estimated',
                                is_gap_filled = TRUE, gap_fill_method = %s, updated_at = NOW(), updated_by = %s
                            WHERE item_id = %s
                            """,
                            [estimate, "kgCO2e/unit", method, _actor(_user), item_id],
                        )
                        gap_filled += 1

            summary = _recalculate_product(con, int(product_id), _user)

        return {
            "ok": True,
            "rows_total": int(len(df.index)),
            "inserted": inserted,
            "mapped": mapped,
            "gap_filled": gap_filled,
            "skipped": skipped,
            "dataset_ids_used": dataset_ids,
            "summary": summary,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to import BOM file: {e}")
