import re
import json
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query

from api.auth import _current_user
from core.database import get_conn

router = APIRouter(prefix="/methodology", tags=["methodology"])

TEAM_ROLES = {"superadmin", "admin", "consultant", "readonly", "crm", "qa", "support"}
DEFAULT_COUNTRY = "UK"


def _actor_identifier(user: dict) -> str:
    return str(user.get("email") or user.get("user_id") or "").strip()


def _require_team_user(user: dict) -> str:
    actor = _actor_identifier(user)
    if not actor:
        raise HTTPException(status_code=401, detail="Missing authenticated user")

    role = str(user.get("role") or "").strip().lower()
    if role not in TEAM_ROLES:
        raise HTTPException(status_code=403, detail="Team member role required")
    return actor


def _ensure_methodology_tables(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS methodology_rows (
          methodology_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          country VARCHAR NOT NULL DEFAULT 'UK',
          scope VARCHAR,
          category VARCHAR,
          report_label TEXT,
          descriptor TEXT,
          uom VARCHAR,
          suggested_original_id TEXT,
          suggested_factor_db_id INTEGER,
          source_payload TEXT,
          notes TEXT,
          is_default BOOLEAN NOT NULL DEFAULT TRUE,
          is_active BOOLEAN NOT NULL DEFAULT TRUE,
          created_by VARCHAR NOT NULL,
          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP
        )
        """
    )
    for statement in [
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS country VARCHAR NOT NULL DEFAULT 'UK'",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS scope VARCHAR",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS category VARCHAR",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS report_label TEXT",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS descriptor TEXT",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS uom VARCHAR",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS suggested_original_id TEXT",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS suggested_factor_db_id INTEGER",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS source_payload TEXT",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT TRUE",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS created_by VARCHAR",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
        "ALTER TABLE methodology_rows ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP",
    ]:
        try:
            con.execute(statement)
        except Exception:
            pass


def _append_like_filters(where_clauses: list[str], params: list[Any], column_names: list[str], search_value: str) -> None:
    search = str(search_value or "").strip()
    if not search:
        return
    tokens = [token for token in re.split(r"\s+", search) if token]
    if not tokens:
        return
    token_clauses = []
    for token in tokens:
        like = f"%{token}%"
        token_clauses.append(
            "(" + " OR ".join([f"COALESCE({column}, '') ILIKE %s" for column in column_names]) + ")"
        )
        params.extend([like] * len(column_names))
    where_clauses.append(" AND ".join(token_clauses))


@router.get("/rows")
def list_methodology_rows(
    country: str = Query(default=""),
    scope: str = Query(default=""),
    category: str = Query(default=""),
    report_label: str = Query(default=""),
    descriptor: str = Query(default=""),
    uom: str = Query(default=""),
    query: str = Query(default=""),
    default_only: bool = Query(default=False),
    include_inactive: bool = Query(default=False),
    limit: int = Query(default=200, ge=1, le=1000),
    _user: dict = Depends(_current_user),
):
    _require_team_user(_user)
    with get_conn() as con:
        _ensure_methodology_tables(con)
        where: list[str] = []
        params: list[Any] = []

        if country.strip():
            where.append("lower(COALESCE(country, '')) = lower(%s)")
            params.append(country.strip())
        if scope.strip():
            where.append("lower(COALESCE(scope, '')) = lower(%s)")
            params.append(scope.strip())
        if category.strip():
            where.append("lower(COALESCE(category, '')) = lower(%s)")
            params.append(category.strip())
        if report_label.strip():
            where.append("report_label ILIKE %s")
            params.append(f"%{report_label.strip()}%")
        if descriptor.strip():
            where.append("descriptor ILIKE %s")
            params.append(f"%{descriptor.strip()}%")
        if uom.strip():
            where.append("lower(COALESCE(uom, '')) = lower(%s)")
            params.append(uom.strip())
        if default_only:
            where.append("COALESCE(is_default, TRUE) = TRUE")
        if query.strip():
            _append_like_filters(
                where,
                params,
                ["country", "scope", "category", "report_label", "descriptor", "uom", "suggested_original_id", "notes"],
                query.strip(),
            )
        if not include_inactive:
            where.append("COALESCE(is_active, TRUE) = TRUE")

        where_sql = f"WHERE {' AND '.join(where)}" if where else ""
        df = con.execute(
            f"""
            SELECT
              methodology_id, country, scope, category, report_label, descriptor, uom,
              suggested_original_id, suggested_factor_db_id, notes, is_default,
              is_active, created_by, created_at, updated_at, source_payload
            FROM methodology_rows
            {where_sql}
            ORDER BY
              COALESCE(is_default, TRUE) DESC,
              lower(COALESCE(country, '')),
              lower(COALESCE(scope, '')),
              lower(COALESCE(category, '')),
              lower(COALESCE(report_label, '')),
              methodology_id DESC
            LIMIT %s
            """,
            [*params, int(limit)],
        ).df()

        items: list[dict[str, Any]] = []
        countries: set[str] = set()
        scopes: set[str] = set()
        categories: set[str] = set()
        uoms: set[str] = set()
        if df is not None and not df.empty:
            # astype(object) first -- df.where(df.notna(), None) alone is a
            # no-op on float64 columns (pandas recasts None back to NaN),
            # which then blows up int(row.get("suggested_factor_db_id"))
            # below for any row with that nullable column unset.
            df = df.astype(object).where(df.notna(), None)
            for _, row in df.iterrows():
                country_val = str(row.get("country") or "").strip()
                scope_val = str(row.get("scope") or "").strip()
                category_val = str(row.get("category") or "").strip()
                uom_val = str(row.get("uom") or "").strip()
                if country_val:
                    countries.add(country_val)
                if scope_val:
                    scopes.add(scope_val)
                if category_val:
                    categories.add(category_val)
                if uom_val:
                    uoms.add(uom_val)
                items.append(
                    {
                        "methodology_id": int(row.get("methodology_id")),
                        "country": country_val,
                        "scope": scope_val,
                        "category": category_val,
                        "report_label": str(row.get("report_label") or "").strip(),
                        "descriptor": str(row.get("descriptor") or "").strip(),
                        "uom": uom_val,
                        "suggested_original_id": str(row.get("suggested_original_id") or "").strip(),
                        "suggested_factor_db_id": int(row.get("suggested_factor_db_id")) if row.get("suggested_factor_db_id") is not None else None,
                        "notes": str(row.get("notes") or "").strip(),
                        "source_payload": str(row.get("source_payload") or "").strip(),
                        "is_default": bool(row.get("is_default")) if row.get("is_default") is not None else True,
                        "is_active": bool(row.get("is_active")) if row.get("is_active") is not None else True,
                        "created_by": str(row.get("created_by") or "").strip(),
                        "created_at": row.get("created_at").isoformat() if row.get("created_at") else None,
                        "updated_at": row.get("updated_at").isoformat() if row.get("updated_at") else None,
                    }
                )

        return {
            "items": items,
            "facets": {
                "countries": sorted(list(countries), key=lambda x: x.lower()),
                "scopes": sorted(list(scopes), key=lambda x: x.lower()),
                "categories": sorted(list(categories), key=lambda x: x.lower()),
                "uoms": sorted(list(uoms), key=lambda x: x.lower()),
            },
        }


@router.post("/rows")
def create_methodology_row(body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = _require_team_user(_user)
    country = str(body.get("country") or DEFAULT_COUNTRY).strip() or DEFAULT_COUNTRY
    scope = str(body.get("scope") or "").strip()
    category = str(body.get("category") or "").strip()
    report_label = str(body.get("report_label") or "").strip()
    descriptor = str(body.get("descriptor") or "").strip()
    uom = str(body.get("uom") or "").strip()
    suggested_original_id = str(body.get("suggested_original_id") or "").strip()
    notes = str(body.get("notes") or "").strip()
    source_payload = body.get("source_payload")
    suggested_factor_db_id = body.get("suggested_factor_db_id")
    is_default = bool(body.get("is_default", True))

    if not category:
        raise HTTPException(status_code=400, detail="category is required")
    if not report_label:
        raise HTTPException(status_code=400, detail="report_label is required")

    with get_conn() as con:
        _ensure_methodology_tables(con)
        row = con.execute(
            """
            INSERT INTO methodology_rows (
              country, scope, category, report_label, descriptor, uom, suggested_original_id,
              suggested_factor_db_id, source_payload, notes, is_default, is_active, created_by, created_at, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, TRUE, %s, NOW(), NOW())
            RETURNING methodology_id
            """,
            [
                country,
                scope,
                category,
                report_label,
                descriptor,
                uom,
                suggested_original_id,
                int(suggested_factor_db_id) if suggested_factor_db_id not in (None, "", "null") else None,
                json.dumps(source_payload, ensure_ascii=False) if isinstance(source_payload, (dict, list)) else str(source_payload or "").strip() or None,
                notes,
                is_default,
                actor,
            ],
        ).fetchone()
    return {"ok": True, "message": "Methodology row saved", "methodology_id": int(row[0]) if row and row[0] is not None else None}


@router.patch("/rows/{methodology_id}")
def update_methodology_row(methodology_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    _require_team_user(_user)
    updates: list[str] = []
    params: list[Any] = []
    with get_conn() as con:
        _ensure_methodology_tables(con)
        if "country" in body:
            updates.append("country = %s")
            params.append(str(body.get("country") or DEFAULT_COUNTRY).strip() or DEFAULT_COUNTRY)
        if "scope" in body:
            updates.append("scope = %s")
            params.append(str(body.get("scope") or "").strip())
        if "category" in body:
            category = str(body.get("category") or "").strip()
            if not category:
                raise HTTPException(status_code=400, detail="category cannot be empty")
            updates.append("category = %s")
            params.append(category)
        if "report_label" in body:
            report_label = str(body.get("report_label") or "").strip()
            if not report_label:
                raise HTTPException(status_code=400, detail="report_label cannot be empty")
            updates.append("report_label = %s")
            params.append(report_label)
        if "descriptor" in body:
            updates.append("descriptor = %s")
            params.append(str(body.get("descriptor") or "").strip())
        if "uom" in body:
            updates.append("uom = %s")
            params.append(str(body.get("uom") or "").strip())
        if "suggested_original_id" in body:
            updates.append("suggested_original_id = %s")
            params.append(str(body.get("suggested_original_id") or "").strip())
        if "suggested_factor_db_id" in body:
            raw = body.get("suggested_factor_db_id")
            updates.append("suggested_factor_db_id = %s")
            params.append(int(raw) if raw not in (None, "", "null") else None)
        if "source_payload" in body:
            raw_payload = body.get("source_payload")
            updates.append("source_payload = %s")
            params.append(json.dumps(raw_payload, ensure_ascii=False) if isinstance(raw_payload, (dict, list)) else str(raw_payload or "").strip() or None)
        if "notes" in body:
            updates.append("notes = %s")
            params.append(str(body.get("notes") or "").strip())
        if "is_default" in body:
            updates.append("is_default = %s")
            params.append(bool(body.get("is_default")))
        if "is_active" in body:
            updates.append("is_active = %s")
            params.append(bool(body.get("is_active")))

        if not updates:
            return {"ok": True, "message": "No fields to update"}

        updates.append("updated_at = NOW()")
        params.append(int(methodology_id))
        con.execute(
            f"UPDATE methodology_rows SET {', '.join(updates)} WHERE methodology_id = %s",
            params,
        )
    return {"ok": True, "message": "Methodology row updated"}
