"""
Spend data collection and mapping endpoints.

Purpose:
- Capture P&L / balance-sheet spend lines per job
- Persist client-level mapping from finance codes to factor lines
- Reuse mappings year-on-year with review controls
"""

from __future__ import annotations

import io
import math
import re
from datetime import datetime
from typing import Any

import pandas as pd
from fastapi import APIRouter, Body, Depends, File, HTTPException, Query, Request, UploadFile
from fastapi.responses import Response
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.datavalidation import DataValidation

from api.auth import _current_user
from api.job_scope_data_routes import _json_safe
from core.database import get_conn
from services.audit_log import fetch_row_dict, record_audit_event
from services.dataset_selector import get_applicable_datasets, get_scope_primary_datasets
from services.portal_data_entry import get_top_spend_categories
from services.download_filenames import build_download_filename
from services.virus_scan import VirusScanError, scan_bytes

router = APIRouter()


def _job_spend_entry_snapshot(con, job_id: int, entry_id: int) -> dict[str, Any] | None:
    return fetch_row_dict(
        con,
        "SELECT * FROM job_spend_entries WHERE entry_id = %s AND job_id = %s",
        [int(entry_id), int(job_id)],
    )


def _ensure_spend_tables(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS client_spend_mappings (
          mapping_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          client_db_id INTEGER NOT NULL REFERENCES clients(db_id),
          code_type VARCHAR NOT NULL DEFAULT 'nominal_code',
          reference_code VARCHAR NOT NULL,
          normalized_description VARCHAR,
          dataset_id INTEGER,
          factor_db_id INTEGER REFERENCES factor_lookup(db_id),
          factor_original_id VARCHAR,
          scope VARCHAR,
          category VARCHAR,
          report_label VARCHAR,
          confidence VARCHAR DEFAULT 'High',
          locked BOOLEAN DEFAULT FALSE,
          valid_from DATE,
          valid_to DATE,
          is_active BOOLEAN DEFAULT TRUE,
          last_reviewed_at TIMESTAMP DEFAULT NOW(),
          last_reviewed_by VARCHAR,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS client_spend_mappings_client_code_idx
        ON client_spend_mappings (client_db_id, code_type, reference_code, is_active)
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS client_spend_mappings_client_norm_desc_idx
        ON client_spend_mappings (client_db_id, normalized_description, is_active)
        """
    )
    for statement in [
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS normalized_description VARCHAR",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS dataset_id INTEGER",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS factor_db_id INTEGER",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS factor_original_id VARCHAR",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS scope VARCHAR",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS category VARCHAR",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS report_label VARCHAR",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS confidence VARCHAR DEFAULT 'High'",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS locked BOOLEAN DEFAULT FALSE",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS valid_from DATE",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS valid_to DATE",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMP DEFAULT NOW()",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS last_reviewed_by VARCHAR",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()",
        "ALTER TABLE client_spend_mappings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()",
    ]:
        try:
            con.execute(statement)
        except Exception:
            pass

    con.execute(
        """
        CREATE TABLE IF NOT EXISTS job_spend_entries (
          entry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_id INTEGER NOT NULL REFERENCES jobs(job_id),
          site_id INTEGER,
          source_type VARCHAR NOT NULL DEFAULT 'manual',
          code_type VARCHAR NOT NULL DEFAULT 'nominal_code',
          reference_code VARCHAR,
          spend_description VARCHAR NOT NULL,
          normalized_description VARCHAR,
          currency VARCHAR NOT NULL DEFAULT 'GBP',
          conversion_currency VARCHAR NOT NULL DEFAULT 'GBP',
          conversion_rate NUMERIC NOT NULL DEFAULT 1,
          amount_net NUMERIC,
          amount_gross NUMERIC NOT NULL DEFAULT 0,
          vat_pct NUMERIC NOT NULL DEFAULT 0,
          dataset_id INTEGER,
          factor_db_id INTEGER REFERENCES factor_lookup(db_id),
          factor_original_id VARCHAR,
          mapped_scope VARCHAR,
          mapped_category VARCHAR,
          mapped_report_label VARCHAR,
          mapping_status VARCHAR NOT NULL DEFAULT 'unmapped',
          mapping_confidence VARCHAR,
          mapped_by VARCHAR,
          mapped_at TIMESTAMP,
          estimated_emissions_tco2e NUMERIC,
          notes TEXT,
          is_deleted BOOLEAN DEFAULT FALSE,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        )
        """
    )
    con.execute(
        """
        CREATE INDEX IF NOT EXISTS job_spend_entries_job_idx
        ON job_spend_entries (job_id, is_deleted, code_type, reference_code)
        """
    )
    try:
        con.execute("ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS site_id INTEGER")
    except Exception:
        # Best-effort for legacy DBs where sites FK/column state may differ.
        pass
    for statement in [
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS source_type VARCHAR NOT NULL DEFAULT 'manual'",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS code_type VARCHAR NOT NULL DEFAULT 'nominal_code'",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS reference_code VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS spend_description VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS normalized_description VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS currency VARCHAR NOT NULL DEFAULT 'GBP'",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS conversion_currency VARCHAR DEFAULT 'GBP'",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS conversion_rate NUMERIC DEFAULT 1",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS amount_net NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS amount_gross NUMERIC DEFAULT 0",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS vat_pct NUMERIC DEFAULT 0",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS dataset_id INTEGER",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS factor_db_id INTEGER",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS factor_original_id VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapped_scope VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapped_category VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapped_report_label VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapping_status VARCHAR NOT NULL DEFAULT 'unmapped'",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapping_confidence VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapped_by VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS mapped_at TIMESTAMP",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS estimated_emissions_tco2e NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()",
        # Client Portal Data Entry Phase 2: portal-submitted lines stay out of
        # sync_spend_to_scope() -- the only path into real, reported emissions
        # -- until a CRM approves them. See CLIENT_PORTAL_DATA_ENTRY_SCOPE.md.
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS submitted_by_portal BOOLEAN NOT NULL DEFAULT FALSE",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS review_status VARCHAR DEFAULT NULL",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS review_note TEXT",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ",
        # Optional monthly breakdown of amount_net -- mainly for clients whose
        # reporting year spans two calendar years. NULL unless a user has
        # opened the monthly modal for that row (matches job_scope_rows'
        # month_1..12 convention, see services/portal_data_entry.py).
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_1 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_2 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_3 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_4 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_5 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_6 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_7 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_8 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_9 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_10 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_11 NUMERIC",
        "ALTER TABLE job_spend_entries ADD COLUMN IF NOT EXISTS month_12 NUMERIC",
    ]:
        try:
            con.execute(statement)
        except Exception:
            pass


def _normalize_description(value: Any) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def _safe_float(value: Any, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        text = str(value).replace(",", "").strip()
        val = float(text) if text else default
        if math.isnan(val) or math.isinf(val):
            return default
        return val
    except Exception:
        return default


def _gross_from_net(amount_net: float, vat_pct: float) -> float:
    return float(amount_net) * (1.0 + (float(vat_pct) / 100.0))


def _net_from_gross(amount_gross: float, vat_pct: float) -> float:
    divisor = 1.0 + (float(vat_pct) / 100.0)
    if divisor == 0:
        return float(amount_gross)
    return float(amount_gross) / divisor


def _is_nan_like(value: Any) -> bool:
    if value is None:
        return True
    try:
        if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
            return True
    except Exception:
        pass
    text = str(value).strip().lower()
    return text in {"", "nan", "none", "null", "nat", "inf", "-inf", "infinity", "-infinity"}


def _safe_optional_int(value: Any) -> int | None:
    if _is_nan_like(value):
        return None
    try:
        return int(float(str(value).strip()))
    except Exception:
        return None


def _safe_optional_str(value: Any) -> str | None:
    if _is_nan_like(value):
        return None
    text = str(value).strip()
    return text or None


def _has_column(con, table_name: str, column_name: str) -> bool:
    row = con.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = %s
          AND column_name = %s
        LIMIT 1
        """,
        [str(table_name), str(column_name)],
    ).fetchone()
    return bool(row)


def _factor_label_expr(con, alias: str = "") -> str:
    prefix = f"{alias}." if alias else ""
    if _has_column(con, "factor_lookup", "report_label"):
        return f"COALESCE({prefix}report_label, {prefix}column_text)"
    return f"{prefix}column_text"


def _factor_category_expr(con, alias: str = "") -> str:
    prefix = f"{alias}." if alias else ""
    if _has_column(con, "factor_lookup", "category"):
        return f"COALESCE({prefix}category, {prefix}level_2, {prefix}level_1, 'Uncategorized')"
    return f"COALESCE({prefix}level_2, {prefix}level_1, 'Uncategorized')"


def _job_client_id(con, job_id: int) -> int:
    row = con.execute(
        "SELECT client_db_id FROM jobs WHERE job_id = %s",
        [int(job_id)],
    ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Job not found")
    return int(row[0])


def _factor_by_id(con, factor_db_id: int) -> dict[str, Any] | None:
    category_expr = _factor_category_expr(con)
    label_expr = _factor_label_expr(con)
    row = con.execute(
        f"""
        SELECT db_id, dataset_id, original_id, scope, {category_expr} AS category, {label_expr} AS report_label, factor, ghg_unit
        FROM v_factor_lookup
        WHERE db_id = %s
        LIMIT 1
        """,
        [int(factor_db_id)],
    ).fetchone()
    if not row:
        return None
    return {
        "db_id": int(row[0]),
        "dataset_id": int(row[1]) if row[1] is not None else None,
        "original_id": row[2],
        "scope": row[3],
        "category": row[4],
        "report_label": row[5],
        "factor": _safe_float(row[6], 0.0),
        "ghg_unit": str(row[7]).strip() if row[7] is not None else None,
    }


def _factor_by_original_id(con, original_id: str) -> dict[str, Any] | None:
    """Fallback lookup by original_id when db_id is stale (e.g. after dataset re-import)."""
    category_expr = _factor_category_expr(con)
    label_expr = _factor_label_expr(con)
    row = con.execute(
        f"""
        SELECT f.db_id, f.dataset_id, f.original_id, f.scope,
               {category_expr} AS category, {label_expr} AS report_label, f.factor, f.ghg_unit
        FROM v_factor_lookup f
        LEFT JOIN datasets d ON d.dataset_id = f.dataset_id
        WHERE TRIM(f.original_id) = %s
          AND (d.archived IS NULL OR d.archived = FALSE)
        ORDER BY f.db_id DESC
        LIMIT 1
        """,
        [original_id.strip()],
    ).fetchone()
    if not row:
        return None
    return {
        "db_id": int(row[0]),
        "dataset_id": int(row[1]) if row[1] is not None else None,
        "original_id": row[2],
        "scope": row[3],
        "category": row[4],
        "report_label": row[5],
        "factor": _safe_float(row[6], 0.0),
        "ghg_unit": str(row[7]).strip() if row[7] is not None else None,
    }


def _resolve_upload_mapping(
    con,
    explicit_factor_db_id: int | None,
    conversion_ref: str | None,
) -> tuple[dict[str, Any] | None, bool]:
    """Resolve the factor for an uploaded row's "Spend Conversion" cell,
    e.g. "5226 | SPEND-SIC-82 | Office administrative...".

    Excel's fill-handle auto-increments a leading integer when a cell is
    dragged down (5226 -> 5227 -> 5228...) while leaving the rest of the text
    untouched, so a dragged block of rows can end up with an id that no
    longer matches the code/description still shown in the cell. Trusting
    the id alone then silently maps each row to a different, wrong factor.

    Cross-check the id-resolved factor's original_id against the code
    segment still in the cell; if they disagree, re-resolve by that code
    instead (which stays correct across a drag-fill) rather than trusting
    the corrupted id. Returns (mapping, id_mismatch_detected).
    """
    if not explicit_factor_db_id:
        if conversion_ref and not conversion_ref.isdigit():
            return _factor_by_original_id(con, conversion_ref), False
        return None, False

    mapping = _factor_by_id(con, int(explicit_factor_db_id))
    if mapping and conversion_ref and not conversion_ref.isdigit():
        if str(mapping.get("original_id") or "").strip().lower() != conversion_ref.strip().lower():
            corrected = _factor_by_original_id(con, conversion_ref)
            if corrected:
                return corrected, True
            return None, True
    if mapping is None and conversion_ref and not conversion_ref.isdigit():
        return _factor_by_original_id(con, conversion_ref), False
    return mapping, False


def _is_kg_based_unit(ghg_unit: str | None) -> bool:
    return "kg" in str(ghg_unit or "").replace(" ", "").lower()


def _spend_factor_warning(ghg_unit: str | None) -> str | None:
    unit = str(ghg_unit or "").strip()
    if not unit:
        return "Factor unit is missing; review the mapped factor before pushing."
    if not _is_kg_based_unit(unit):
        return f"Mapped factor unit is '{unit}'. Spend rows should normally use a kg-based factor before conversion to tCO2e."
    return None


def _auto_mapping(con, client_db_id: int, code_type: str, reference_code: str, normalized_description: str) -> dict[str, Any] | None:
    if reference_code:
        row = con.execute(
            """
            SELECT factor_db_id, dataset_id, factor_original_id, scope, category, report_label, confidence
            FROM client_spend_mappings
            WHERE client_db_id = %s
              AND is_active = TRUE
              AND lower(code_type) = lower(%s)
              AND lower(reference_code) = lower(%s)
            ORDER BY locked DESC, last_reviewed_at DESC, mapping_id DESC
            LIMIT 1
            """,
            [int(client_db_id), code_type, reference_code],
        ).fetchone()
        if row:
            factor = _factor_by_id(con, int(row[0])) if row[0] is not None else None
            if factor:
                return {
                    "factor_db_id": factor["db_id"],
                    "dataset_id": factor["dataset_id"],
                    "factor_original_id": factor["original_id"],
                    "scope": factor["scope"],
                    "category": factor["category"],
                    "report_label": factor["report_label"],
                    "factor": factor["factor"],
                    "confidence": row[6] or "High",
                }

    if normalized_description:
        row = con.execute(
            """
            SELECT factor_db_id, dataset_id, factor_original_id, scope, category, report_label, confidence
            FROM client_spend_mappings
            WHERE client_db_id = %s
              AND is_active = TRUE
              AND normalized_description = %s
            ORDER BY locked DESC, last_reviewed_at DESC, mapping_id DESC
            LIMIT 1
            """,
            [int(client_db_id), normalized_description],
        ).fetchone()
        if row:
            factor = _factor_by_id(con, int(row[0])) if row[0] is not None else None
            if factor:
                return {
                    "factor_db_id": factor["db_id"],
                    "dataset_id": factor["dataset_id"],
                    "factor_original_id": factor["original_id"],
                    "scope": factor["scope"],
                    "category": factor["category"],
                    "report_label": factor["report_label"],
                    "factor": factor["factor"],
                    "confidence": row[6] or "Medium",
                }

    return None


def _upsert_client_mapping(con, client_db_id: int, code_type: str, reference_code: str, normalized_description: str, factor: dict[str, Any], actor: str, confidence: str = "High", locked: bool = False) -> None:
    existing = con.execute(
        """
        SELECT mapping_id
        FROM client_spend_mappings
        WHERE client_db_id = %s
          AND lower(code_type) = lower(%s)
          AND lower(reference_code) = lower(%s)
          AND is_active = TRUE
        ORDER BY locked DESC, last_reviewed_at DESC, mapping_id DESC
        LIMIT 1
        """,
        [int(client_db_id), code_type, reference_code],
    ).fetchone()

    if existing:
        con.execute(
            """
            UPDATE client_spend_mappings
            SET normalized_description = %s,
                dataset_id = %s,
                factor_db_id = %s,
                factor_original_id = %s,
                scope = %s,
                category = %s,
                report_label = %s,
                confidence = %s,
                locked = %s,
                last_reviewed_at = NOW(),
                last_reviewed_by = %s,
                updated_at = NOW()
            WHERE mapping_id = %s
            """,
            [
                normalized_description or None,
                factor.get("dataset_id"),
                factor.get("db_id"),
                factor.get("original_id"),
                factor.get("scope"),
                factor.get("category"),
                factor.get("report_label"),
                confidence,
                bool(locked),
                actor,
                int(existing[0]),
            ],
        )
        return

    con.execute(
        """
        INSERT INTO client_spend_mappings (
          client_db_id, code_type, reference_code, normalized_description,
          dataset_id, factor_db_id, factor_original_id, scope, category, report_label,
          confidence, locked, last_reviewed_at, last_reviewed_by
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), %s)
        """,
        [
            int(client_db_id),
            code_type,
            reference_code,
            normalized_description or None,
            factor.get("dataset_id"),
            factor.get("db_id"),
            factor.get("original_id"),
            factor.get("scope"),
            factor.get("category"),
            factor.get("report_label"),
            confidence,
            bool(locked),
            actor,
        ],
    )

def _persist_spend_row(
    con,
    job_id: int,
    client_db_id: int,
    site_id: int | None,
    source_type: str,
    code_type: str,
    reference_code: str,
    spend_description: str,
    currency: str,
    conversion_currency: str,
    conversion_rate: float,
    amount_net: float,
    vat_pct: float,
    notes: str | None,
    actor: str,
    factor_override: dict[str, Any] | None = None,
    submitted_by_portal: bool = False,
) -> dict[str, Any]:
    normalized_description = _normalize_description(spend_description)
    if factor_override:
        mapping = {
            "factor_db_id": factor_override.get("db_id"),
            "dataset_id": factor_override.get("dataset_id"),
            "factor_original_id": factor_override.get("original_id"),
            "scope": factor_override.get("scope"),
            "category": factor_override.get("category"),
            "report_label": factor_override.get("report_label"),
            "factor": factor_override.get("factor"),
            "confidence": "High",
        }
    else:
        mapping = _auto_mapping(
            con=con,
            client_db_id=int(client_db_id),
            code_type=code_type,
            reference_code=reference_code or "",
            normalized_description=normalized_description,
        )

    factor = _safe_float((mapping or {}).get("factor"), 0.0)
    effective_rate = _safe_float(conversion_rate, 1.0)
    if effective_rate <= 0:
        effective_rate = 1.0
    converted_net = float(amount_net) * float(effective_rate)
    amount_gross = _gross_from_net(converted_net, vat_pct)
    estimated_tco2e = amount_gross * factor if mapping else None

    result = con.execute(
        """
        INSERT INTO job_spend_entries (
          job_id, site_id, source_type, code_type, reference_code, spend_description, normalized_description,
          currency, conversion_currency, conversion_rate, amount_net, amount_gross, vat_pct, notes,
          dataset_id, factor_db_id, factor_original_id, mapped_scope, mapped_category, mapped_report_label,
          mapping_status, mapping_confidence, mapped_by, mapped_at, estimated_emissions_tco2e,
          submitted_by_portal, review_status
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), %s, %s, %s)
        RETURNING entry_id
        """,
        [
            int(job_id),
            int(site_id) if site_id is not None else None,
            source_type,
            code_type,
            reference_code or None,
            spend_description,
            normalized_description or None,
            (currency or "GBP").upper(),
            (conversion_currency or "GBP").upper(),
            float(effective_rate),
            float(converted_net),
            float(amount_gross),
            float(vat_pct),
            notes,
            (mapping or {}).get("dataset_id"),
            (mapping or {}).get("factor_db_id"),
            (mapping or {}).get("factor_original_id"),
            (mapping or {}).get("scope"),
            (mapping or {}).get("category"),
            (mapping or {}).get("report_label"),
            "suggested" if mapping else "unmapped",
            (mapping or {}).get("confidence"),
            actor if mapping else None,
            estimated_tco2e,
            bool(submitted_by_portal),
            # review_status stays NULL even for portal-submitted rows until the
            # client actually confirms a category (confirm-category sets it to
            # 'pending_review') -- an uncategorized row has nothing for a CRM
            # to review yet, so it shouldn't appear in that queue.
            None,
        ],
    ).fetchone()

    return {
        "entry_id": int(result[0]),
        "auto_mapped": bool(mapping),
        "mapping_confidence": (mapping or {}).get("confidence"),
    }


def _parse_upload(file_bytes: bytes, filename: str) -> pd.DataFrame:
    if filename.lower().endswith(".xlsx"):
        raw_df = pd.read_excel(io.BytesIO(file_bytes), header=None)
    else:
        raw_df = pd.read_csv(io.BytesIO(file_bytes), header=None)

    if raw_df is None or raw_df.empty:
        raise HTTPException(status_code=400, detail="Upload file contains no rows")

    header_idx = 0
    for idx, row in raw_df.head(30).iterrows():
        values = [str(v or "").strip().lower() for v in list(row.values)]
        if "spend description" in values and (
            "spend amount (net ex vat)" in values or "spend amount" in values or "amount" in values
        ):
            header_idx = int(idx)
            break

    header_values = [str(v or "").strip() for v in list(raw_df.iloc[header_idx].values)]
    data_df = raw_df.iloc[header_idx + 1 :].copy()
    data_df.columns = header_values
    data_df = data_df.dropna(how="all")

    normalized_columns = {str(c).strip().lower(): c for c in data_df.columns}

    def find_col(candidates: list[str]) -> str | None:
        for key in candidates:
            if key in normalized_columns:
                return normalized_columns[key]
        for normalized_key, original in normalized_columns.items():
            for key in candidates:
                if key in normalized_key:
                    return original
        return None

    code_col = find_col(["reference code", "nominal code", "gl code", "code"])
    desc_col = find_col(["spend description", "description", "account description"])
    currency_col = find_col(["currency", "currency code"])
    amount_col = find_col(["spend amount (net ex vat)", "spend amount", "net value (excl vat)", "net value", "amount", "net amount", "amount ex vat", "amount excl vat"])
    vat_col = find_col(["vat %", "vat pct", "vat", "vat rate"])
    conversion_currency_col = find_col(["conversion currency", "converted currency"])
    conversion_rate_col = find_col(["conversion rate", "fx rate", "exchange rate"])
    conversion_col = find_col(["spend conversion", "conversion option", "factor option"])
    factor_id_col = find_col(["factor db id", "factor_id", "factor dbid", "conversion factor id"])

    if not desc_col or not amount_col:
        raise HTTPException(status_code=400, detail="Upload must include at least: Spend Description and Spend Amount columns")

    rows = []
    for _, r in data_df.iterrows():
        description = str(r.get(desc_col) or "").strip()
        if not description:
            continue
        rows.append(
            {
                "reference_code": str(r.get(code_col) or "").strip() if code_col else "",
                "spend_description": description,
                "currency": str(r.get(currency_col) or "GBP").strip().upper() if currency_col else "GBP",
                "conversion_currency": str(r.get(conversion_currency_col) or "GBP").strip().upper() if conversion_currency_col else "GBP",
                "conversion_rate": _safe_float(r.get(conversion_rate_col), 1.0) if conversion_rate_col else 1.0,
                "amount_net": _safe_float(r.get(amount_col), 0.0),
                "vat_pct": _safe_float(r.get(vat_col), 0.0) if vat_col else 0.0,
                "factor_db_id": _safe_optional_int(r.get(factor_id_col)) if factor_id_col else _safe_optional_int(
                    re.match(r"^\s*(\d+)", str(r.get(conversion_col) or "")).group(1)
                ) if conversion_col and re.match(r"^\s*(\d+)", str(r.get(conversion_col) or "")) else None,
                "factor_conversion_ref": (lambda _cv: (
                    re.match(r"^\s*\d+\s*\|\s*(.+?)\s*\|", _cv).group(1).strip()
                    if re.match(r"^\s*\d+\s*\|\s*(.+?)\s*\|", _cv) else None
                ))(str(r.get(conversion_col) or "")) if conversion_col else None,
            }
        )

    if not rows:
        raise HTTPException(status_code=400, detail="No usable rows found in upload")

    return pd.DataFrame(rows)


def _confidence_to_hml(value: Any) -> str:
    text = str(value or "").strip().lower()
    if text.startswith("h"):
        return "H"
    if text.startswith("l"):
        return "L"
    return "M"


def _format_period_label(period_start: Any, period_end: Any) -> str:
    def _fmt(val: Any) -> str:
        if val is None:
            return "?"
        if hasattr(val, "strftime"):
            return val.strftime("%b %Y")
        txt = str(val).strip()
        try:
            dt = datetime.fromisoformat(txt[:10])
            return dt.strftime("%b %Y")
        except Exception:
            return txt

    return f"{_fmt(period_start)} - {_fmt(period_end)}"


def _reporting_year(period_start: Any, period_end: Any) -> str:
    for value in [period_end, period_start]:
        if value is None:
            continue
        if hasattr(value, "year"):
            return str(value.year)
        txt = str(value).strip()
        try:
            return str(datetime.fromisoformat(txt[:10]).year)
        except Exception:
            match = re.search(r"(20\d{2}|19\d{2})", txt)
            if match:
                return match.group(1)
    return str(datetime.now().year)


@router.get("/jobs/{job_id}/spend-data")
def list_spend_data(job_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        _ensure_spend_tables(con)
        _job_client_id(con, int(job_id))
        df = con.execute(
            """
            SELECT e.entry_id, e.site_id, s.site_name, e.source_type, e.code_type, e.reference_code, e.spend_description, e.currency,
                   e.conversion_currency, e.conversion_rate,
                   e.amount_net, e.amount_gross, e.vat_pct, e.dataset_id, e.factor_db_id, e.factor_original_id,
                   e.mapped_scope, e.mapped_category, e.mapped_report_label,
                   e.mapping_status, e.mapping_confidence, e.estimated_emissions_tco2e,
                   fl.ghg_unit AS factor_ghg_unit,
                   e.notes, e.created_at, e.updated_at
            FROM job_spend_entries e
            LEFT JOIN client_sites s ON s.site_id = e.site_id
            LEFT JOIN v_factor_lookup fl ON fl.db_id = e.factor_db_id
            WHERE e.job_id = %s AND COALESCE(e.is_deleted, FALSE) = FALSE
            ORDER BY e.entry_id DESC
            """,
            [int(job_id)],
        ).df()

    items: list[dict[str, Any]] = []
    if df is not None and not df.empty:
        for _, row in df.iterrows():
            items.append(
                {
                    "entry_id": int(row["entry_id"]),
                    "site_id": _safe_optional_int(row.get("site_id")),
                    "site_name": _safe_optional_str(row.get("site_name")),
                    "source_type": _safe_optional_str(row.get("source_type")) or "manual",
                    "code_type": _safe_optional_str(row.get("code_type")) or "nominal_code",
                    "reference_code": _safe_optional_str(row.get("reference_code")),
                    "spend_description": _safe_optional_str(row.get("spend_description")) or "",
                    "currency": _safe_optional_str(row.get("currency")) or "GBP",
                    "conversion_currency": _safe_optional_str(row.get("conversion_currency")) or "GBP",
                    "conversion_rate": _safe_float(row.get("conversion_rate"), 1.0),
                    "amount_net": _safe_float(
                        row.get("amount_net"),
                        _net_from_gross(_safe_float(row.get("amount_gross"), 0.0), _safe_float(row.get("vat_pct"), 0.0)),
                    ),
                    "amount_gross": _safe_float(row.get("amount_gross"), 0.0),
                    "vat_pct": _safe_float(row.get("vat_pct"), 0.0),
                    "dataset_id": _safe_optional_int(row.get("dataset_id")),
                    "factor_db_id": _safe_optional_int(row.get("factor_db_id")),
                    "factor_original_id": _safe_optional_str(row.get("factor_original_id")),
                    "mapped_scope": _safe_optional_str(row.get("mapped_scope")),
                    "mapped_category": _safe_optional_str(row.get("mapped_category")),
                    "mapped_report_label": _safe_optional_str(row.get("mapped_report_label")),
                    "mapping_status": _safe_optional_str(row.get("mapping_status")) or "unmapped",
                    "mapping_confidence": _safe_optional_str(row.get("mapping_confidence")),
                    "factor_ghg_unit": _safe_optional_str(row.get("factor_ghg_unit")),
                    "unit_warning": _spend_factor_warning(_safe_optional_str(row.get("factor_ghg_unit"))),
                    "estimated_emissions_kgco2e": _safe_float(row.get("estimated_emissions_tco2e"), 0.0),
                    "estimated_emissions_tco2e": _safe_float(row.get("estimated_emissions_tco2e"), 0.0) / 1000.0,
                    "notes": _safe_optional_str(row.get("notes")),
                }
            )

    return {
        "items": items,
        "summary": {
            "count": len(items),
            "mapped_exact": len([x for x in items if x.get("mapping_status") == "mapped"]),
            "suggested": len([x for x in items if x.get("mapping_status") == "suggested"]),
            "mapped": len([x for x in items if x.get("mapping_status") in {"mapped", "suggested"}]),
            "unmapped": len([x for x in items if x.get("mapping_status") == "unmapped"]),
            "total_spend_net": round(sum(_safe_float(x.get("amount_net"), 0.0) for x in items), 2),
            "total_spend_gross": round(sum(_safe_float(x.get("amount_gross"), 0.0) for x in items), 2),
            "total_estimated_kgco2e": round(sum(_safe_float(x.get("estimated_emissions_kgco2e"), 0.0) for x in items), 4),
            "total_estimated_tco2e": round(sum(_safe_float(x.get("estimated_emissions_tco2e"), 0.0) for x in items), 4),
        },
    }


@router.post("/jobs/{job_id}/spend-data/approve-suggested")
def approve_all_suggested_spend_mappings(job_id: int, _user: dict = Depends(_current_user)):
    actor = str(_user.get("email") or "system")
    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))
        rows = con.execute(
            """
            SELECT entry_id, code_type, reference_code, normalized_description, factor_db_id
            FROM job_spend_entries
            WHERE job_id=%s
              AND COALESCE(is_deleted, FALSE)=FALSE
              AND mapping_status='suggested'
              AND factor_db_id IS NOT NULL
            ORDER BY entry_id
            """,
            [int(job_id)],
        ).fetchall()

        approved = 0
        locked = 0
        for row in rows or []:
            entry_id = int(row[0])
            code_type = str(row[1] or "nominal_code")
            reference_code = str(row[2] or "").strip()
            norm_desc = str(row[3] or "")
            factor_db_id = int(row[4])
            factor = _factor_by_id(con, factor_db_id)
            if not factor:
                continue

            con.execute(
                """
                UPDATE job_spend_entries
                SET mapping_status='mapped',
                    mapping_confidence=COALESCE(mapping_confidence, 'High'),
                    mapped_by=%s,
                    mapped_at=NOW(),
                    updated_at=NOW()
                WHERE entry_id=%s
                """,
                [actor, entry_id],
            )
            approved += 1

            if reference_code:
                _upsert_client_mapping(
                    con=con,
                    client_db_id=int(client_db_id),
                    code_type=code_type,
                    reference_code=reference_code,
                    normalized_description=norm_desc,
                    factor=factor,
                    actor=actor,
                    confidence="High",
                    locked=True,
                )
                locked += 1

    return {"ok": True, "approved": int(approved), "locked_mappings": int(locked)}


@router.post("/jobs/{job_id}/spend-data/rollforward")
def rollforward_spend_structure(job_id: int, body: dict = Body(default={}), _user: dict = Depends(_current_user)):
    """
    Clone previous year's spend row structure into this job so users can fill net values quickly.
    Default behavior:
    - chooses most recent previous job for same client
    - copies rows with net/gross reset to 0
    - preserves mapping fields where present
    """
    actor = str(_user.get("email") or "system")
    source_job_id = _safe_optional_int(body.get("source_job_id"))
    overwrite_existing = bool(body.get("overwrite_existing", False))
    copy_amounts = bool(body.get("copy_amounts", False))

    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))

        if source_job_id is None:
            source = con.execute(
                """
                SELECT j2.job_id
                FROM jobs j
                JOIN jobs j2 ON j2.client_db_id = j.client_db_id
                WHERE j.job_id = %s
                  AND j2.job_id <> j.job_id
                  AND (
                        (j2.reporting_period_end IS NOT NULL AND j.reporting_period_start IS NOT NULL AND j2.reporting_period_end < j.reporting_period_start)
                        OR (j2.reporting_year IS NOT NULL AND j.reporting_year IS NOT NULL AND j2.reporting_year < j.reporting_year)
                      )
                ORDER BY COALESCE(j2.reporting_period_end, DATE '1900-01-01') DESC, COALESCE(j2.reporting_year, 0) DESC, j2.job_id DESC
                LIMIT 1
                """,
                [int(job_id)],
            ).fetchone()
            source_job_id = int(source[0]) if source else None

        if source_job_id is None:
            raise HTTPException(status_code=400, detail="No previous job found for roll-forward")

        _job_client_id(con, int(source_job_id))

        if overwrite_existing:
            con.execute(
                """
                UPDATE job_spend_entries
                SET is_deleted=TRUE, updated_at=NOW()
                WHERE job_id=%s AND COALESCE(is_deleted, FALSE)=FALSE
                """,
                [int(job_id)],
            )

        source_rows = con.execute(
            """
            SELECT site_id, source_type, code_type, reference_code, spend_description, normalized_description,
                   currency, COALESCE(amount_net, 0), COALESCE(amount_gross, 0), COALESCE(vat_pct, 0),
                   dataset_id, factor_db_id, factor_original_id, mapped_scope, mapped_category, mapped_report_label,
                   mapping_status, mapping_confidence, estimated_emissions_tco2e, notes
            FROM job_spend_entries
            WHERE job_id=%s AND COALESCE(is_deleted, FALSE)=FALSE
            ORDER BY entry_id
            """,
            [int(source_job_id)],
        ).fetchall()

        inserted = 0
        skipped = 0
        for r in source_rows or []:
            site_id = _safe_optional_int(r[0])
            code_type = str(r[2] or "nominal_code")
            reference_code = str(r[3] or "").strip()
            spend_description = str(r[4] or "").strip()
            normalized_description = str(r[5] or _normalize_description(spend_description))
            currency = str(r[6] or "GBP").upper()
            src_amount_net = _safe_float(r[7], 0.0)
            src_vat = _safe_float(r[9], 0.0)
            amount_net = src_amount_net if copy_amounts else 0.0
            amount_gross = _gross_from_net(amount_net, src_vat)
            factor_db_id = _safe_optional_int(r[11])
            factor = _factor_by_id(con, int(factor_db_id)) if factor_db_id else None
            estimated = amount_gross * _safe_float((factor or {}).get("factor"), 0.0) if factor else None
            mapped_scope = _safe_optional_str(r[13])
            mapped_category = _safe_optional_str(r[14])
            mapped_report_label = _safe_optional_str(r[15])
            mapping_status = _safe_optional_str(r[16]) or ("suggested" if factor_db_id else "unmapped")
            mapping_confidence = _safe_optional_str(r[17]) or ("High" if factor_db_id else None)
            notes = _safe_optional_str(r[19])

            existing = con.execute(
                """
                SELECT 1
                FROM job_spend_entries
                WHERE job_id=%s
                  AND COALESCE(is_deleted, FALSE)=FALSE
                  AND COALESCE(site_id, -1)=COALESCE(%s, -1)
                  AND lower(COALESCE(code_type,''))=lower(COALESCE(%s,''))
                  AND lower(COALESCE(reference_code,''))=lower(COALESCE(%s,''))
                  AND lower(COALESCE(spend_description,''))=lower(COALESCE(%s,''))
                LIMIT 1
                """,
                [int(job_id), site_id, code_type, reference_code, spend_description],
            ).fetchone()
            if existing:
                skipped += 1
                continue

            con.execute(
                """
                INSERT INTO job_spend_entries (
                  job_id, site_id, source_type, code_type, reference_code, spend_description, normalized_description,
                  currency, amount_net, amount_gross, vat_pct,
                  dataset_id, factor_db_id, factor_original_id, mapped_scope, mapped_category, mapped_report_label,
                  mapping_status, mapping_confidence, mapped_by, mapped_at, estimated_emissions_tco2e, notes,
                  is_deleted, created_at, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), %s, %s, FALSE, NOW(), NOW())
                """,
                [
                    int(job_id),
                    site_id,
                    "rollforward",
                    code_type,
                    reference_code or None,
                    spend_description,
                    normalized_description or None,
                    currency,
                    amount_net,
                    amount_gross,
                    src_vat,
                    _safe_optional_int(r[10]),
                    factor_db_id,
                    _safe_optional_str(r[12]),
                    mapped_scope,
                    mapped_category,
                    mapped_report_label,
                    mapping_status,
                    mapping_confidence,
                    actor if factor_db_id else None,
                    estimated,
                    notes,
                ],
            )
            inserted += 1

    return {
        "ok": True,
        "source_job_id": int(source_job_id),
        "inserted": int(inserted),
        "skipped": int(skipped),
        "copy_amounts": bool(copy_amounts),
    }


@router.post("/jobs/{job_id}/spend-data")
def create_spend_data(job_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = str(_user.get("email") or "system")
    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))
        saved = _persist_spend_row(
            con=con,
            job_id=int(job_id),
            client_db_id=int(client_db_id),
            site_id=_safe_optional_int(body.get("site_id")),
            source_type="manual",
            code_type=str(body.get("code_type") or "nominal_code"),
            reference_code=str(body.get("reference_code") or "").strip(),
            spend_description=str(body.get("spend_description") or "").strip(),
            currency=str(body.get("currency") or "GBP").strip().upper(),
            conversion_currency=str(body.get("conversion_currency") or body.get("currency") or "GBP").strip().upper(),
            conversion_rate=_safe_float(body.get("conversion_rate"), 1.0),
            amount_net=_safe_float(body.get("amount_net"), _safe_float(body.get("amount_gross"), 0.0)),
            vat_pct=_safe_float(body.get("vat_pct"), 0.0),
            notes=str(body.get("notes") or "").strip() or None,
            actor=actor,
        )
    return {"ok": True, **saved}

@router.patch("/jobs/{job_id}/spend-data/{entry_id}")
def update_spend_data(job_id: int, entry_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = str(_user.get("email") or "system")
    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))

        exists = con.execute(
            "SELECT 1 FROM job_spend_entries WHERE entry_id=%s AND job_id=%s AND COALESCE(is_deleted,FALSE)=FALSE",
            [int(entry_id), int(job_id)],
        ).fetchone()
        if not exists:
            raise HTTPException(status_code=404, detail="Spend row not found")

        updates: list[str] = []
        params: list[Any] = []
        for key in ["code_type", "reference_code", "spend_description", "currency", "notes", "conversion_currency"]:
            if key in body:
                updates.append(f"{key} = %s")
                params.append(str(body.get(key) or "").strip() or None)
        if "conversion_rate" in body:
            updates.append("conversion_rate = %s")
            params.append(_safe_float(body.get("conversion_rate"), 1.0))
        if "site_id" in body:
            updates.append("site_id = %s")
            params.append(_safe_optional_int(body.get("site_id")))
        if "amount_net" in body:
            updates.append("amount_net = %s")
            params.append(_safe_float(body.get("amount_net"), 0.0))
        elif "amount_gross" in body:
            updates.append("amount_gross = %s")
            params.append(_safe_float(body.get("amount_gross"), 0.0))
        if "vat_pct" in body:
            updates.append("vat_pct = %s")
            params.append(_safe_float(body.get("vat_pct"), 0.0))

        if updates:
            updates.append("normalized_description = %s")
            params.append(_normalize_description(body.get("spend_description") or ""))
            updates.append("updated_at = NOW()")
            params.extend([int(entry_id), int(job_id)])
            con.execute(f"UPDATE job_spend_entries SET {', '.join(updates)} WHERE entry_id=%s AND job_id=%s", params)

        if bool(body.get("remap", True)):
            row = con.execute(
                """
                SELECT code_type, reference_code, normalized_description, amount_gross, amount_net, vat_pct, conversion_rate
                FROM job_spend_entries
                WHERE entry_id=%s
                """,
                [int(entry_id)],
            ).fetchone()
            gross_now = _safe_float(row[3], 0.0)
            net_now = _safe_float(row[4], _net_from_gross(gross_now, _safe_float(row[5], 0.0)))
            vat_now = _safe_float(row[5], 0.0)
            rate_now = _safe_float(row[6], 1.0)
            converted_net_now = net_now
            if ("amount_net" in body) or ("vat_pct" in body) or ("conversion_rate" in body):
                net_new = _safe_float(body.get("amount_net"), net_now)
                vat_new = _safe_float(body.get("vat_pct"), vat_now)
                rate_new = _safe_float(body.get("conversion_rate"), rate_now)
                if rate_new <= 0:
                    rate_new = 1.0
                converted_net_now = net_new * rate_new
                gross_now = _gross_from_net(net_new * rate_new, vat_new)
                con.execute(
                    "UPDATE job_spend_entries SET amount_net=%s, amount_gross=%s, updated_at=NOW() WHERE entry_id=%s",
                    [converted_net_now, gross_now, int(entry_id)],
                )
            mapping = _auto_mapping(
                con=con,
                client_db_id=int(client_db_id),
                code_type=str(row[0] or "nominal_code"),
                reference_code=str(row[1] or ""),
                normalized_description=str(row[2] or ""),
            )
            if mapping:
                emissions = _safe_float(gross_now, 0.0) * _safe_float(mapping.get("factor"), 0.0)
                con.execute(
                    """
                    UPDATE job_spend_entries
                    SET dataset_id=%s, factor_db_id=%s, factor_original_id=%s,
                        mapped_scope=%s, mapped_category=%s, mapped_report_label=%s,
                        mapping_status='suggested', mapping_confidence=%s, mapped_by=%s, mapped_at=NOW(),
                        estimated_emissions_tco2e=%s, updated_at=NOW()
                    WHERE entry_id=%s
                    """,
                    [
                        mapping.get("dataset_id"),
                        mapping.get("factor_db_id"),
                        mapping.get("factor_original_id"),
                        mapping.get("scope"),
                        mapping.get("category"),
                        mapping.get("report_label"),
                        mapping.get("confidence"),
                        actor,
                        emissions,
                        int(entry_id),
                    ],
                )

    return {"ok": True}


@router.delete("/jobs/{job_id}/spend-data/{entry_id}")
def delete_spend_data(request: Request, job_id: int, entry_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        _ensure_spend_tables(con)
        _job_client_id(con, int(job_id))
        before = _job_spend_entry_snapshot(con, int(job_id), int(entry_id))
        con.execute(
            """
            UPDATE job_spend_entries
            SET is_deleted=TRUE, updated_at=NOW()
            WHERE entry_id=%s AND job_id=%s
            """,
            [int(entry_id), int(job_id)],
        )
        after = _job_spend_entry_snapshot(con, int(job_id), int(entry_id))
        record_audit_event(
            con,
            request=request,
            actor=_user,
            action="delete",
            entity_type="job_spend_entry",
            entity_id=int(entry_id),
            job_id=int(job_id),
            before=before,
            after=after,
        )
    return {"ok": True}


@router.delete("/jobs/{job_id}/spend-data")
def delete_all_spend_data(request: Request, job_id: int, _user: dict = Depends(_current_user)):
    """Delete every active spend entry for a job, then reconcile job_scope_rows
    immediately so the deletion is actually visible everywhere -- not just in
    job_spend_entries, which a prior incident showed users reasonably assume
    is the same thing as "the data is gone" on the Data Entry screen."""
    with get_conn() as con:
        _ensure_spend_tables(con)
        _job_client_id(con, int(job_id))
        entry_ids = [
            int(r[0])
            for r in con.execute(
                "SELECT entry_id FROM job_spend_entries WHERE job_id=%s AND COALESCE(is_deleted, FALSE) = FALSE",
                [int(job_id)],
            ).fetchall()
        ]
        if entry_ids:
            con.execute(
                """
                UPDATE job_spend_entries
                SET is_deleted=TRUE, updated_at=NOW()
                WHERE job_id=%s AND COALESCE(is_deleted, FALSE) = FALSE
                """,
                [int(job_id)],
            )
            record_audit_event(
                con,
                request=request,
                actor=_user,
                action="bulk_delete",
                entity_type="job_spend_entry",
                entity_id=None,
                job_id=int(job_id),
                metadata={"count": len(entry_ids), "entry_ids": entry_ids},
            )

    sync_result = sync_spend_to_scope_data(int(job_id), {}, _user) if entry_ids else None
    return {"ok": True, "deleted": len(entry_ids), "sync": sync_result}


@router.post("/jobs/{job_id}/spend-data/{entry_id}/map")
def map_spend_row(job_id: int, entry_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    actor = str(_user.get("email") or "system")
    factor_db_id = int(body.get("factor_db_id") or 0)
    confidence = str(body.get("confidence") or "High")
    lock_mapping = bool(body.get("lock_mapping", True))
    if factor_db_id <= 0:
        raise HTTPException(status_code=400, detail="factor_db_id is required")

    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))
        factor = _factor_by_id(con, factor_db_id)
        if not factor:
            raise HTTPException(status_code=404, detail="Factor not found")

        row = con.execute(
            """
            SELECT reference_code, code_type, normalized_description, amount_net, vat_pct
            FROM job_spend_entries
            WHERE entry_id=%s AND job_id=%s AND COALESCE(is_deleted,FALSE)=FALSE
            """,
            [int(entry_id), int(job_id)],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Spend row not found")

        amount = _gross_from_net(_safe_float(row[3], 0.0), _safe_float(row[4], 0.0))
        emissions = amount * _safe_float(factor.get("factor"), 0.0)
        con.execute(
            """
            UPDATE job_spend_entries
            SET dataset_id=%s, factor_db_id=%s, factor_original_id=%s,
                mapped_scope=%s, mapped_category=%s, mapped_report_label=%s,
                mapping_status='mapped', mapping_confidence=%s,
                mapped_by=%s, mapped_at=NOW(),
                estimated_emissions_tco2e=%s, updated_at=NOW()
            WHERE entry_id=%s
            """,
            [
                factor.get("dataset_id"),
                factor.get("db_id"),
                factor.get("original_id"),
                factor.get("scope"),
                factor.get("category"),
                factor.get("report_label"),
                confidence,
                actor,
                emissions,
                int(entry_id),
            ],
        )

        ref_code = str(row[0] or "").strip()
        if ref_code:
            _upsert_client_mapping(
                con=con,
                client_db_id=int(client_db_id),
                code_type=str(row[1] or "nominal_code"),
                reference_code=ref_code,
                normalized_description=str(row[2] or ""),
                factor=factor,
                actor=actor,
                confidence=confidence,
                locked=lock_mapping,
            )

    return {"ok": True}


@router.get("/jobs/{job_id}/spend-data/pending-review")
def list_pending_review_spend_rows(job_id: int, _user: dict = Depends(_current_user)):
    """Client-portal-submitted spend lines awaiting CRM approval before
    they're eligible for sync_spend_to_scope()."""
    with get_conn() as con:
        _ensure_spend_tables(con)
        df = con.execute(
            """
            SELECT entry_id, site_id, code_type, reference_code, spend_description,
                   amount_net, amount_gross, vat_pct, currency,
                   mapped_scope, mapped_category, mapped_report_label,
                   mapping_status, review_status, review_note, created_at
            FROM job_spend_entries
            WHERE job_id = %s AND COALESCE(is_deleted, FALSE) = FALSE
              AND submitted_by_portal = TRUE AND review_status IN ('pending_review', 'rejected')
            ORDER BY created_at DESC
            """,
            [int(job_id)],
        ).df()
        if df is None or df.empty:
            return {"job_id": int(job_id), "rows": []}
        df = df.where(df.notna(), None)
        rows = [{k: _json_safe(row.get(k)) for k in row.index} for _, row in df.iterrows()]
        return {"job_id": int(job_id), "rows": rows}


@router.patch("/jobs/{job_id}/spend-data/{entry_id}/review")
def review_spend_row(
    job_id: int,
    entry_id: int,
    body: dict = Body(...),
    _user: dict = Depends(_current_user),
):
    """Approve or reject a client-portal-submitted job_spend_entries row.
    Approving is the only thing that makes it eligible for
    sync_spend_to_scope() -- until then it can never become a real,
    reported emissions number, regardless of mapping_status. Approving
    also fires the client_spend_mappings memory upsert (deferred from the
    client's own category confirmation, per CLIENT_PORTAL_DATA_ENTRY_SCOPE.md
    Phase 2 decision #1), so a client's mistake can't poison next year's
    auto-suggestions before a CRM has actually looked at it."""
    decision = str(body.get("decision") or "").strip().lower()
    if decision not in ("approve", "reject"):
        raise HTTPException(status_code=400, detail="decision must be 'approve' or 'reject'")
    note = body.get("note")
    reviewer = str(_user.get("email") or _user.get("full_name") or "crm")

    with get_conn() as con:
        _ensure_spend_tables(con)
        row = con.execute(
            """
            SELECT submitted_by_portal, review_status, reference_code, code_type,
                   normalized_description, factor_db_id, mapping_confidence
            FROM job_spend_entries
            WHERE entry_id = %s AND job_id = %s AND COALESCE(is_deleted, FALSE) = FALSE
            """,
            [int(entry_id), int(job_id)],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Spend row not found")
        if not row[0]:
            raise HTTPException(status_code=400, detail="This row wasn't submitted via the client portal")
        if row[1] == "approved":
            raise HTTPException(status_code=409, detail="Already approved")

        if decision == "approve":
            factor_db_id = _safe_optional_int(row[5])
            if not factor_db_id:
                raise HTTPException(status_code=400, detail="This row has no category assigned yet and can't be approved")
            factor = _factor_by_id(con, factor_db_id)
            con.execute(
                """
                UPDATE job_spend_entries
                SET review_status = 'approved', review_note = %s, reviewed_by = %s, reviewed_at = NOW()
                WHERE entry_id = %s
                """,
                [note, reviewer, int(entry_id)],
            )
            ref_code = str(row[2] or "").strip()
            if factor and ref_code:
                client_db_id = _job_client_id(con, int(job_id))
                _upsert_client_mapping(
                    con=con,
                    client_db_id=int(client_db_id),
                    code_type=str(row[3] or "nominal_code"),
                    reference_code=ref_code,
                    normalized_description=str(row[4] or ""),
                    factor=factor,
                    actor=reviewer,
                    confidence=str(row[6] or "High"),
                    locked=True,
                )
        else:
            con.execute(
                """
                UPDATE job_spend_entries
                SET review_status = 'rejected', review_note = %s, reviewed_by = %s, reviewed_at = NOW()
                WHERE entry_id = %s
                """,
                [note, reviewer, int(entry_id)],
            )

        record_audit_event(
            con,
            request=None,
            actor=_user,
            action=f"spend_row_{decision}",
            entity_type="job_spend_entry",
            entity_id=int(entry_id),
            job_id=int(job_id),
            metadata={"decision": decision, "note": note},
        )

    return {"ok": True, "entry_id": int(entry_id), "review_status": "approved" if decision == "approve" else "rejected"}


@router.get("/jobs/{job_id}/spend-data/factors/search")
def search_spend_factors(job_id: int, q: str = Query("", min_length=0), limit: int = Query(25, ge=1, le=200), _user: dict = Depends(_current_user)):
    with get_conn() as con:
        _ensure_spend_tables(con)
        _job_client_id(con, int(job_id))
        category_expr = _factor_category_expr(con, "f")
        label_expr = _factor_label_expr(con, "f")

        # Scope to the job's own Scope 3 dataset(s) -- without this, every
        # non-archived dataset ever loaded (one row per year) shows up for
        # the same category, so e.g. "Accommodation" appeared 5x with no way
        # to tell which one actually applies to this job's reporting period.
        # Also exclude PROD-coded factors: PG&S is commercial spend (SIC),
        # not personal/household consumption.
        scope3_dataset_ids = get_applicable_datasets(int(job_id)).get("Scope 3") or []
        dataset_filter_sql = "AND f.dataset_id = ANY(%s)" if scope3_dataset_ids else ""

        params: list[Any] = []
        if scope3_dataset_ids:
            params.append(scope3_dataset_ids)
        params.append("%PROD%")
        params.extend([q, f"%{q}%", f"%{q}%", f"%{q}%", f"%{q}%", int(limit)])

        df = con.execute(
            f"""
            SELECT DISTINCT ON ({label_expr})
                   f.db_id, f.dataset_id, f.original_id, f.scope, {category_expr} AS category, {label_expr} AS report_label, f.factor, f.ghg_unit,
                   d.name AS dataset_name, d.analysis_type
            FROM v_factor_lookup f
            LEFT JOIN datasets d ON d.dataset_id = f.dataset_id
            WHERE (d.archived IS NULL OR d.archived = FALSE)
              {dataset_filter_sql}
              AND f.original_id NOT ILIKE %s
              AND (
                   %s = ''
                   OR {label_expr} ILIKE %s
                   OR {category_expr} ILIKE %s
                   OR f.column_text ILIKE %s
                   OR f.original_id ILIKE %s
              )
            ORDER BY {label_expr}, f.dataset_id DESC
            LIMIT %s
            """,
            params,
        ).df()

    items: list[dict[str, Any]] = []
    if df is not None and not df.empty:
        for _, r in df.iterrows():
            items.append(
                {
                    "db_id": int(r["db_id"]),
                    "dataset_id": int(r["dataset_id"]) if r.get("dataset_id") is not None else None,
                    "original_id": r.get("original_id"),
                    "scope": r.get("scope"),
                    "category": r.get("category"),
                    "report_label": r.get("report_label"),
                    "factor": _safe_float(r.get("factor"), 0.0),
                    "ghg_unit": _safe_optional_str(r.get("ghg_unit")),
                    "unit_warning": _spend_factor_warning(_safe_optional_str(r.get("ghg_unit"))),
                    "dataset_name": r.get("dataset_name"),
                    "analysis_type": r.get("analysis_type"),
                }
            )
    return {"items": items}


@router.get("/jobs/{job_id}/spend-data/factors/top")
def top_spend_factors(job_id: int, _user: dict = Depends(_current_user)):
    """Most-used PG&S categories for this job's client (falling back to all
    clients), shown as a quick-pick above the search box."""
    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))
        items = get_top_spend_categories(con, int(client_db_id))
    return {"items": items}


@router.get("/jobs/{job_id}/spend-data/template")
def download_spend_template(
    job_id: int,
    site_id: int = Query(..., ge=1),
    _user: dict = Depends(_current_user),
):
    with get_conn() as con:
        _ensure_spend_tables(con)
        row = con.execute(
            """
            SELECT j.job_number, j.reporting_period_start, j.reporting_period_end, c.client_name
            FROM jobs j
            JOIN clients c ON c.db_id = j.client_db_id
            WHERE j.job_id = %s
            """,
            [int(job_id)],
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Job not found")
        site_row = con.execute(
            """
            SELECT s.site_name
            FROM jobs j
            JOIN client_sites s ON s.client_db_id = j.client_db_id
            WHERE j.job_id = %s AND s.site_id = %s
            LIMIT 1
            """,
            [int(job_id), int(site_id)],
        ).fetchone()
        if not site_row:
            raise HTTPException(status_code=400, detail="Selected site is not valid for this job")

        # Derive the reporting year so we only show datasets for that year.
        reporting_period_end = row[2]
        reporting_year: int | None = None
        if reporting_period_end:
            try:
                reporting_year = int(str(reporting_period_end)[:4])
            except Exception:
                pass

        # Find the most recent prior job for the same client (for prior-year reference tab).
        prior_source = con.execute(
            """
            SELECT j2.job_id, j2.job_number,
                   j2.reporting_period_start, j2.reporting_period_end
            FROM jobs j
            JOIN jobs j2 ON j2.client_db_id = j.client_db_id
            WHERE j.job_id = %s
              AND j2.job_id <> j.job_id
              AND (
                    (j2.reporting_period_end IS NOT NULL AND j.reporting_period_start IS NOT NULL
                     AND j2.reporting_period_end < j.reporting_period_start)
                    OR (j2.reporting_year IS NOT NULL AND j.reporting_year IS NOT NULL
                        AND j2.reporting_year < j.reporting_year)
                  )
            ORDER BY COALESCE(j2.reporting_period_end, DATE '1900-01-01') DESC,
                     COALESCE(j2.reporting_year, 0) DESC, j2.job_id DESC
            LIMIT 1
            """,
            [int(job_id)],
        ).fetchone()
        prior_rows = None
        if prior_source:
            prior_rows = con.execute(
                """
                SELECT e.reference_code, e.spend_description, e.currency,
                       e.amount_net, e.vat_pct, e.conversion_currency, e.conversion_rate,
                       e.mapped_scope, e.mapped_report_label, e.factor_db_id,
                       COALESCE(NULLIF(TRIM(f.original_id), ''), CAST(f.db_id AS VARCHAR)) AS conversion_reference
                FROM job_spend_entries e
                LEFT JOIN v_factor_lookup f ON f.db_id = e.factor_db_id
                WHERE e.job_id = %s
                  AND COALESCE(e.is_deleted, FALSE) = FALSE
                ORDER BY e.mapped_scope NULLS LAST, e.spend_description
                """,
                [int(prior_source[0])],
            ).fetchall()

        label_expr = _factor_label_expr(con, "f")
        category_expr = _factor_category_expr(con, "f")
        # Scope to the datasets actually applicable to this job (matched by
        # country/period, same resolver used for factor lookups elsewhere)
        # rather than any non-archived dataset sharing the reporting year --
        # two datasets for different countries (e.g. UK and UAE) can share a
        # year, and without this filter every SPEND factor was pulled from
        # both, duplicating each conversion option in the dropdown.
        #
        # A job whose reporting period crosses a calendar-year boundary can
        # still have more than one *applicable* dataset for the same country
        # (e.g. one per year), each carrying the same conversion reference
        # with a different factor value -- rank those by preference (primary
        # dataset first) and keep only the best-ranked row per reference so
        # the dropdown doesn't offer indistinguishable duplicate options.
        primary_datasets = get_scope_primary_datasets(int(job_id))
        applicable_datasets = get_applicable_datasets(int(job_id))
        dataset_preference: list[int] = []
        for dsid in list(primary_datasets.values()) + [d for ids in applicable_datasets.values() for d in ids]:
            if dsid is not None and int(dsid) not in dataset_preference:
                dataset_preference.append(int(dsid))
        preference_rank = {dsid: idx for idx, dsid in enumerate(dataset_preference)}

        if dataset_preference:
            ids_sql = ",".join(str(dsid) for dsid in dataset_preference)
            dataset_filter = f"AND f.dataset_id IN ({ids_sql})"
        else:
            dataset_filter = f"AND d.year = {int(reporting_year)}" if reporting_year else ""
        factors_df = con.execute(
            f"""
            SELECT f.db_id, f.dataset_id,
                   COALESCE(NULLIF(TRIM(f.original_id), ''), CAST(f.db_id AS VARCHAR)) AS conversion_reference,
                   COALESCE({label_expr}, {category_expr}, CONCAT('Factor ', CAST(f.db_id AS VARCHAR))) AS conversion_label
            FROM v_factor_lookup f
            LEFT JOIN datasets d ON d.dataset_id = f.dataset_id
            WHERE (d.archived IS NULL OR d.archived = FALSE)
              AND upper(COALESCE(f.original_id, '')) LIKE 'SPEND%%'
              {dataset_filter}
            ORDER BY conversion_label
            """
        ).df()

        if factors_df is not None and not factors_df.empty and preference_rank:
            factors_df["_pref_rank"] = factors_df["dataset_id"].map(
                lambda dsid: preference_rank.get(int(dsid), len(preference_rank))
            )
            factors_df = (
                factors_df.sort_values(["conversion_reference", "_pref_rank"])
                .drop_duplicates(subset=["conversion_reference"], keep="first")
                .sort_values("conversion_label")
                .drop(columns=["_pref_rank"])
            )

    job_number = str(row[0] or f"Job-{job_id}")
    client_name = str(row[3] or "Client")
    site_label = str(site_row[0] or "Site").strip() or "Site"
    reporting_period_label = _format_period_label(row[1], row[2])

    workbook = Workbook()
    spend_sheet = workbook.active
    spend_sheet.title = "Spend Data"
    conversions_sheet = workbook.create_sheet("Spend Conversions")

    spend_sheet["A1"] = "Client Name:"
    spend_sheet["B1"] = client_name
    spend_sheet["E1"] = "Job Number:"
    spend_sheet["F1"] = job_number
    spend_sheet["A2"] = "Site Name:"
    spend_sheet["B2"] = site_label
    spend_sheet["E2"] = "Reporting Period:"
    spend_sheet["F2"] = _format_period_label(row[1], row[2])
    spend_sheet["A3"] = "Data Files:"
    spend_sheet["B3"] = "SPEND conversion factors"

    header_fill = PatternFill(start_color="E0E0E0", end_color="E0E0E0", fill_type="solid")
    for r in range(1, 4):
        for c in ["A", "C", "E"]:
            cell = spend_sheet[f"{c}{r}"]
            cell.font = Font(bold=True)
            cell.fill = header_fill

    spend_headers = [
        "Reference Code",
        "Spend Description",
        "Currency",
        "Spend Amount (Net Ex VAT)",
        "VAT %",
        "Conversion Currency",
        "Conversion Rate",
        "Spend Conversion",
    ]
    spend_sheet.append([])
    spend_sheet.append(spend_headers)
    spend_sheet.append(["4000", "Office Supplies", "GBP", 1250.00, 20, "GBP", 1, ""])
    spend_sheet.append(["4100", "IT Services", "GBP", 5400.00, 20, "GBP", 1, ""])
    for col_idx, _header in enumerate(spend_headers, start=1):
        cell = spend_sheet.cell(row=5, column=col_idx)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")

    conversions_sheet.append(["Conversion Reference", "Conversion Label", "Dropdown Option"])
    option_row_start = 2
    option_row_end = 1
    if factors_df is not None and not factors_df.empty:
        for _, factor in factors_df.iterrows():
            db_id = int(factor["db_id"])
            conversion_reference = str(factor.get("conversion_reference") or db_id)
            conversion_label = str(factor.get("conversion_label") or f"Factor {db_id}")
            option_value = f"{db_id} | {conversion_reference} | {conversion_label}"
            conversions_sheet.append([conversion_reference, conversion_label, option_value])
        option_row_end = option_row_start + len(factors_df) - 1

    conversions_sheet.column_dimensions["C"].hidden = True

    # Add prior-year reference tab if a previous job exists.
    if prior_rows:
        prior_job_label = _format_period_label(prior_source[2], prior_source[3]) if prior_source else "Prior Year"
        prior_sheet = workbook.create_sheet(f"Prior Year Spend")
        prior_header_fill = PatternFill(start_color="2E4057", end_color="2E4057", fill_type="solid")
        prior_headers = [
            "Reference Code", "Spend Description", "Currency",
            "Spend Amount (Net Ex VAT)", "VAT %",
            "Conversion Currency", "Conversion Rate",
            "Prior Spend Conversion", "Mapped Category",
        ]
        prior_sheet.append([f"Prior Year: {prior_job_label}"] + [""] * (len(prior_headers) - 1))
        prior_sheet.append([])
        prior_sheet.append(prior_headers)
        for col_idx, _ in enumerate(prior_headers, start=1):
            cell = prior_sheet.cell(row=3, column=col_idx)
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = prior_header_fill
        prior_sheet["A1"].font = Font(bold=True, color="FFFFFF")
        prior_sheet["A1"].fill = prior_header_fill
        for pr in prior_rows:
            factor_db_id_val = pr[9]
            conversion_ref = str(pr[10] or "").strip() if pr[10] else ""
            option_value = (
                f"{factor_db_id_val} | {conversion_ref}" if factor_db_id_val else ""
            )
            prior_sheet.append([
                str(pr[0] or ""),
                str(pr[1] or ""),
                str(pr[2] or "GBP"),
                _safe_float(pr[3], 0.0),
                _safe_float(pr[4], 0.0),
                str(pr[5] or "GBP"),
                _safe_float(pr[6], 1.0),
                option_value,
                str(pr[8] or ""),
            ])
        prior_sheet.column_dimensions["A"].width = 20
        prior_sheet.column_dimensions["B"].width = 42
        prior_sheet.column_dimensions["C"].width = 12
        prior_sheet.column_dimensions["D"].width = 26
        prior_sheet.column_dimensions["E"].width = 10
        prior_sheet.column_dimensions["F"].width = 20
        prior_sheet.column_dimensions["G"].width = 16
        prior_sheet.column_dimensions["H"].width = 40
        prior_sheet.column_dimensions["I"].width = 40
        prior_sheet.freeze_panes = "A4"

    spend_sheet.column_dimensions["A"].width = 20
    spend_sheet.column_dimensions["B"].width = 42
    spend_sheet.column_dimensions["C"].width = 14
    spend_sheet.column_dimensions["D"].width = 26
    spend_sheet.column_dimensions["E"].width = 10
    spend_sheet.column_dimensions["F"].width = 20
    spend_sheet.column_dimensions["G"].width = 16
    spend_sheet.column_dimensions["H"].width = 58
    spend_sheet.freeze_panes = "A6"

    if option_row_end >= option_row_start:
        validation = DataValidation(
            type="list",
            formula1=f"='Spend Conversions'!$C${option_row_start}:$C${option_row_end}",
            allow_blank=True,
        )
        spend_sheet.add_data_validation(validation)
        validation.add("H6:H5000")

    stream = io.BytesIO()
    workbook.save(stream)
    stream.seek(0)

    file_name = build_download_filename(
        job_number=job_number,
        client_name=client_name,
        descriptor="Spend Analysis",
        period_start=row[1],
        period_end=row[2],
    )
    return Response(
        content=stream.getvalue(),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={
            "Content-Disposition": f'attachment; filename="{file_name}"',
            "X-Filename": file_name,
        },
    )


@router.post("/jobs/{job_id}/spend-data/upload-preview")
async def preview_spend_upload(
    job_id: int,
    file: UploadFile = File(...),
    code_type: str = Query("nominal_code"),
    site_id: int | None = Query(None),
    _user: dict = Depends(_current_user),
):
    data = await file.read()
    if not data:
        raise HTTPException(status_code=400, detail="Empty upload file")
    try:
        scan_bytes(data, filename=file.filename or "upload.csv")
    except VirusScanError as e:
        raise HTTPException(status_code=400, detail=str(e))

    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))
        df = _parse_upload(data, file.filename or "upload.csv")

        items: list[dict[str, Any]] = []
        mapped = 0
        for _, r in df.iterrows():
            desc = str(r.get("spend_description") or "").strip()
            code = str(r.get("reference_code") or "").strip()
            explicit_factor_db_id = _safe_optional_int(r.get("factor_db_id"))
            conversion_ref = str(r.get("factor_conversion_ref") or "").strip() or None
            mapping, id_mismatch = _resolve_upload_mapping(con, explicit_factor_db_id, conversion_ref)
            mapping_source = "explicit" if mapping and (explicit_factor_db_id or conversion_ref) else "auto"
            if mapping is None:
                mapping = _auto_mapping(
                    con=con,
                    client_db_id=int(client_db_id),
                    code_type=code_type,
                    reference_code=code,
                    normalized_description=_normalize_description(desc),
                )
            if mapping:
                mapped += 1
            amount_net = _safe_float(r.get("amount_net"), 0.0)
            conversion_rate = _safe_float(r.get("conversion_rate"), 1.0)
            if conversion_rate <= 0:
                conversion_rate = 1.0
            conversion_currency = str(r.get("conversion_currency") or "GBP").strip().upper()
            converted_net = amount_net * conversion_rate
            amount = _gross_from_net(converted_net, _safe_float(r.get("vat_pct"), 0.0))
            factor = _safe_float((mapping or {}).get("factor"), 0.0)
            factor_ghg_unit = str((mapping or {}).get("ghg_unit") or "").strip() or None
            items.append(
                {
                    "reference_code": code,
                    "spend_description": desc,
                    "currency": conversion_currency,
                    "site_id": int(site_id) if site_id is not None else None,
                    "amount_net": converted_net,
                    "amount_gross": amount,
                    "vat_pct": _safe_float(r.get("vat_pct"), 0.0),
                    "conversion_currency": conversion_currency,
                    "conversion_rate": conversion_rate,
                    "mapping_status": "suggested" if mapping else "unmapped",
                    "mapping_source": mapping_source if mapping else "unmapped",
                    "mapped_scope": (mapping or {}).get("scope"),
                    "mapped_report_label": (mapping or {}).get("report_label"),
                    "factor_db_id": (mapping or {}).get("factor_db_id") or (mapping or {}).get("db_id"),
                    "factor_ghg_unit": factor_ghg_unit,
                    "unit_warning": _spend_factor_warning(factor_ghg_unit) if mapping else None,
                    "id_mismatch_warning": (
                        "Spend Conversion cell's id didn't match its code text (likely an Excel drag-fill error) "
                        "-- resolved using the code instead. Check this row's source file." if id_mismatch else None
                    ),
                    "estimated_emissions_kgco2e": amount * factor if mapping else None,
                    "estimated_emissions_tco2e": (amount * factor / 1000.0) if mapping else None,
                }
            )

    return {
        "items": items,
        "summary": {
            "count": len(items),
            "mapped": mapped,
            "unmapped": len(items) - mapped,
            "total_spend_net": round(sum(_safe_float(x.get("amount_net"), 0.0) for x in items), 2),
            "mapped_spend_net": round(sum(_safe_float(x.get("amount_net"), 0.0) for x in items if str(x.get("mapping_status") or "").lower() == "suggested"), 2),
            "unmapped_spend_net": round(sum(_safe_float(x.get("amount_net"), 0.0) for x in items if str(x.get("mapping_status") or "").lower() != "suggested"), 2),
            "warning_count": len([x for x in items if x.get("unit_warning")]),
            "id_mismatch_count": len([x for x in items if x.get("id_mismatch_warning")]),
        },
    }


@router.post("/jobs/{job_id}/spend-data/upload-commit")
async def commit_spend_upload(
    request: Request,
    job_id: int,
    file: UploadFile = File(...),
    code_type: str = Query("nominal_code"),
    replace_existing: bool = Query(False),
    site_id: int | None = Query(None),
    _user: dict = Depends(_current_user),
):
    actor = str(_user.get("email") or "system")
    data = await file.read()
    if not data:
        raise HTTPException(status_code=400, detail="Empty upload file")
    try:
        scan_bytes(data, filename=file.filename or "upload.csv")
    except VirusScanError as e:
        raise HTTPException(status_code=400, detail=str(e))

    with get_conn() as con:
        _ensure_spend_tables(con)
        client_db_id = _job_client_id(con, int(job_id))
        df = _parse_upload(data, file.filename or "upload.csv")

        if replace_existing:
            replaced_ids = [
                int(r[0])
                for r in con.execute(
                    "SELECT entry_id FROM job_spend_entries WHERE job_id=%s AND COALESCE(is_deleted, FALSE) = FALSE",
                    [int(job_id)],
                ).fetchall()
            ]
            con.execute(
                """
                UPDATE job_spend_entries
                SET is_deleted = TRUE, updated_at = NOW()
                WHERE job_id = %s AND COALESCE(is_deleted, FALSE) = FALSE
                """,
                [int(job_id)],
            )
            if replaced_ids:
                record_audit_event(
                    con,
                    request=request,
                    actor=_user,
                    action="bulk_delete",
                    entity_type="job_spend_entry",
                    entity_id=None,
                    job_id=int(job_id),
                    metadata={"reason": "replace_existing on upload", "count": len(replaced_ids), "entry_ids": replaced_ids},
                )

        inserted = 0
        auto_mapped = 0
        id_mismatches = 0
        for _, r in df.iterrows():
            explicit_factor_db_id = _safe_optional_int(r.get("factor_db_id"))
            conversion_ref = str(r.get("factor_conversion_ref") or "").strip() or None
            factor_override, id_mismatch = _resolve_upload_mapping(con, explicit_factor_db_id, conversion_ref)
            if id_mismatch:
                id_mismatches += 1
            saved = _persist_spend_row(
                con=con,
                job_id=int(job_id),
                client_db_id=int(client_db_id),
                site_id=int(site_id) if site_id is not None else None,
                source_type="upload",
                code_type=code_type,
                reference_code=str(r.get("reference_code") or "").strip(),
                spend_description=str(r.get("spend_description") or "").strip(),
                currency=str(r.get("currency") or "GBP").strip().upper(),
                conversion_currency=str(r.get("conversion_currency") or "GBP").strip().upper(),
                conversion_rate=_safe_float(r.get("conversion_rate"), 1.0),
                amount_net=_safe_float(r.get("amount_net"), 0.0),
                vat_pct=_safe_float(r.get("vat_pct"), 0.0),
                notes=(
                    "Auto-corrected: Spend Conversion cell's id didn't match its code text "
                    "(likely an Excel drag-fill error) -- resolved using the code instead."
                    if id_mismatch else None
                ),
                actor=actor,
                factor_override=factor_override,
            )
            inserted += 1
            if saved.get("auto_mapped"):
                auto_mapped += 1

        record_audit_event(
            con,
            request=request,
            actor=_user,
            action="upload",
            entity_type="job_spend_entry",
            entity_id=None,
            job_id=int(job_id),
            metadata={
                "inserted": inserted,
                "auto_mapped": auto_mapped,
                "unmapped": inserted - auto_mapped,
                "id_mismatches": id_mismatches,
                "replace_existing": replace_existing,
                "filename": file.filename,
            },
        )

    return {
        "ok": True,
        "inserted": inserted,
        "auto_mapped": auto_mapped,
        "unmapped": inserted - auto_mapped,
        "id_mismatches": id_mismatches,
    }


@router.get("/clients/{client_id}/spend-mappings")
def list_client_spend_mappings(client_id: int, _user: dict = Depends(_current_user)):
    with get_conn() as con:
        _ensure_spend_tables(con)
        df = con.execute(
            """
            SELECT mapping_id, code_type, reference_code, normalized_description,
                   dataset_id, factor_db_id, factor_original_id, scope, category, report_label,
                   confidence, locked, is_active, last_reviewed_at, last_reviewed_by
            FROM client_spend_mappings
            WHERE client_db_id = %s
            ORDER BY lower(code_type), lower(reference_code), mapping_id DESC
            """,
            [int(client_id)],
        ).df()

    items: list[dict[str, Any]] = []
    if df is not None and not df.empty:
        for _, r in df.iterrows():
            items.append(
                {
                    "mapping_id": int(r["mapping_id"]),
                    "code_type": r.get("code_type"),
                    "reference_code": r.get("reference_code"),
                    "normalized_description": r.get("normalized_description"),
                    "dataset_id": r.get("dataset_id"),
                    "factor_db_id": r.get("factor_db_id"),
                    "factor_original_id": r.get("factor_original_id"),
                    "scope": r.get("scope"),
                    "category": r.get("category"),
                    "report_label": r.get("report_label"),
                    "confidence": r.get("confidence"),
                    "locked": bool(r.get("locked")),
                    "is_active": bool(r.get("is_active")),
                    "last_reviewed_at": str(r.get("last_reviewed_at")) if r.get("last_reviewed_at") is not None else None,
                    "last_reviewed_by": r.get("last_reviewed_by"),
                }
            )
    return {"items": items}


@router.post("/jobs/{job_id}/spend-data/sync-to-scope")
def sync_spend_to_scope_data(
    job_id: int,
    body: dict = Body(default={}),
    _user: dict = Depends(_current_user),
):
    """
    Push mapped spend rows into job_scope_rows for emissions roll-up.

    Dedupe/update rule:
    - source rows are keyed as original_id = SPEND-<entry_id>
    - if an active Spend Data row already exists with same job_id/scope/original_id/site_id NULL,
      it is updated in place
    - otherwise a new scope row is inserted
    """
    actor = str(_user.get("email") or "system")
    deactivate_missing = bool(body.get("deactivate_missing", True))

    with get_conn() as con:
        _ensure_spend_tables(con)
        _job_client_id(con, int(job_id))

        # Keep schema aligned for write target.
        try:
            con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS apply_pct NUMERIC DEFAULT 100")
            con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS data_source VARCHAR DEFAULT 'Company Data'")
            con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS data_confidence VARCHAR DEFAULT 'M'")
            con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS is_custom_entry BOOLEAN DEFAULT FALSE")
            con.execute("ALTER TABLE job_scope_rows ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE")
        except Exception:
            pass

        spend_df = con.execute(
            """
            SELECT entry_id, amount_net, amount_gross, conversion_currency, currency, vat_pct, notes,
                   site_id,
                   factor_db_id, factor_original_id, dataset_id,
                   mapped_scope, mapped_category, mapped_report_label,
                   mapping_confidence
            FROM job_spend_entries
            WHERE job_id = %s
              AND COALESCE(is_deleted, FALSE) = FALSE
              AND factor_db_id IS NOT NULL
              AND mapped_scope IS NOT NULL
              AND (submitted_by_portal = FALSE OR review_status = 'approved')
            ORDER BY entry_id
            """,
            [int(job_id)],
        ).df()

        if spend_df is None or spend_df.empty:
            return {"ok": True, "created": 0, "updated": 0, "deactivated": 0, "processed": 0}

        # Aggregate by (scope, factor_db_id, site_id) → one scope row per category
        groups: dict[tuple, dict[str, Any]] = {}
        for _, row in spend_df.iterrows():
            scope = str(row.get("mapped_scope") or "").strip()
            factor_db_id = _safe_optional_int(row.get("factor_db_id"))
            if not scope or not factor_db_id:
                continue
            site_id = _safe_optional_int(row.get("site_id"))
            key = (scope, factor_db_id, site_id)
            if key not in groups:
                groups[key] = {
                    "scope": scope,
                    "factor_db_id": factor_db_id,
                    "site_id": site_id,
                    "amount_gross": 0.0,
                    "currency": str(row.get("conversion_currency") or row.get("currency") or "GBP"),
                    "mapped_report_label": str(row.get("mapped_report_label") or "").strip(),
                    "mapped_category": str(row.get("mapped_category") or "").strip(),
                    "mapping_confidence": row.get("mapping_confidence"),
                    "dataset_id": row.get("dataset_id"),
                }
            groups[key]["amount_gross"] += _safe_float(row.get("amount_gross"), 0.0)

        active_original_ids: list[str] = []
        created = 0
        updated = 0

        for (scope, factor_db_id_key, site_id), grp in groups.items():
            # original_id encodes factor (and site if present) so each category gets one row
            if site_id is not None:
                original_id = f"SPEND-F{factor_db_id_key}-S{site_id}"
            else:
                original_id = f"SPEND-F{factor_db_id_key}"
            active_original_ids.append(original_id)

            factor = _factor_by_id(con, factor_db_id_key)
            if not factor:
                continue

            amount = grp["amount_gross"]
            factor_value = _safe_float(factor.get("factor"), 0.0)
            calc_tco2e = amount * factor_value
            report_label = grp["mapped_report_label"] or factor.get("report_label") or f"Spend factor {factor_db_id_key}"
            category = grp["mapped_category"] or factor.get("category") or "Spend"
            data_conf = _confidence_to_hml(grp.get("mapping_confidence"))
            currency = grp["currency"]

            existing = con.execute(
                """
                SELECT row_id
                FROM job_scope_rows
                WHERE job_id = %s
                  AND scope = %s
                  AND original_id = %s
                  AND site_id IS NOT DISTINCT FROM %s
                  AND COALESCE(data_source, '') = 'Spend Data'
                  AND COALESCE(enabled, TRUE) = TRUE
                ORDER BY row_id
                LIMIT 1
                """,
                [int(job_id), scope, original_id, site_id],
            ).fetchone()

            if existing:
                con.execute(
                    """
                    UPDATE job_scope_rows
                    SET dataset_id = %s,
                        factor_db_id = %s,
                        category = %s,
                        report_label = %s,
                        qty = %s,
                        uom = %s,
                        factor = %s,
                        ghg_unit = %s,
                        calc_tco2e = %s,
                        apply_pct = 100,
                        data_source = 'Spend Data',
                        data_confidence = %s,
                        notes = %s,
                        is_custom_entry = TRUE,
                        enabled = TRUE,
                        updated_at = NOW()
                    WHERE row_id = %s
                    """,
                    [
                        factor.get("dataset_id"),
                        factor.get("db_id"),
                        category,
                        report_label,
                        amount,
                        currency,
                        factor_value,
                        "kgCO2e",
                        calc_tco2e,
                        data_conf,
                        None,
                        int(existing[0]),
                    ],
                )
                updated += 1
            else:
                con.execute(
                    """
                    INSERT INTO job_scope_rows (
                      job_id, scope, site_id, dataset_id, factor_db_id, original_id,
                      category, report_label, qty, uom, factor, ghg_unit, calc_tco2e, apply_pct,
                      data_source, data_confidence, notes, is_custom_entry, enabled
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 100, 'Spend Data', %s, %s, TRUE, TRUE)
                    """,
                    [
                        int(job_id),
                        scope,
                        site_id,
                        factor.get("dataset_id"),
                        factor.get("db_id"),
                        original_id,
                        category,
                        report_label,
                        amount,
                        currency,
                        factor_value,
                        "kgCO2e",
                        calc_tco2e,
                        data_conf,
                        None,
                    ],
                )
                created += 1

        deactivated = 0
        if deactivate_missing:
            spend_pattern = "SPEND-%"
            if active_original_ids:
                placeholders = ",".join(["%s"] * len(active_original_ids))
                deactivated_row = con.execute(
                    f"""
                    WITH updated_rows AS (
                      UPDATE job_scope_rows
                      SET enabled = FALSE, updated_at = NOW()
                      WHERE job_id = %s
                        AND COALESCE(data_source, '') = 'Spend Data'
                        AND original_id LIKE %s
                        AND original_id NOT IN ({placeholders})
                      RETURNING 1
                    )
                    SELECT COUNT(*) FROM updated_rows
                    """,
                    [int(job_id), spend_pattern] + active_original_ids,
                ).fetchone()
                deactivated = int(deactivated_row[0] or 0) if deactivated_row else 0
            else:
                deactivated_row = con.execute(
                    """
                    WITH updated_rows AS (
                      UPDATE job_scope_rows
                      SET enabled = FALSE, updated_at = NOW()
                      WHERE job_id = %s
                        AND COALESCE(data_source, '') = 'Spend Data'
                        AND original_id LIKE %s
                      RETURNING 1
                    )
                    SELECT COUNT(*) FROM updated_rows
                    """,
                    [int(job_id), spend_pattern],
                ).fetchone()
                deactivated = int(deactivated_row[0] or 0) if deactivated_row else 0

    return {
        "ok": True,
        "created": int(created),
        "updated": int(updated),
        "deactivated": int(deactivated),
        "processed": int(created + updated),
        "synced_at": datetime.utcnow().isoformat() + "Z",
        "synced_by": actor,
    }
