"""
Governed per-job refresh of DEFRA spend-based emission factors.

DEFRA retroactively revised its SIC-code spend factors across every year
2019-2026. The revised values were updated in place inside the existing
per-year "UK Activity & Spend {year}" datasets (same factor_lookup db_id,
just a new factor value), so every *new* job automatically picks up the
current figures with no extra step. But job_scope_rows.factor and
job_spend_entries.estimated_emissions_tco2e are frozen snapshots copied at
mapping time -- they do NOT move when the underlying factor_lookup row
changes. Because deliberately moving an *existing* job onto the revised
figures can change a client's already-reported emissions, doing so
requires a request (any staff member) and an approval (SuperAdmin only)
rather than a direct edit.
"""

from __future__ import annotations

import json
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Query

from api.auth import _current_user
from api.permissions import ADMIN_ACCESS_PERMISSION, assert_job_access, assert_permission, assert_super_admin
from core.database import get_conn
from services.audit_log import fetch_row_dict, record_audit_event

router = APIRouter()

SIC_PREFIX = "SPEND-SIC-"
FACTOR_EPSILON = 1e-9


def _ensure_spend_factor_refresh_schema(con) -> None:
    con.execute(
        """
        CREATE TABLE IF NOT EXISTS spend_factor_refresh_requests (
            request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id INTEGER NOT NULL,
            requested_by VARCHAR,
            requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            reason TEXT,
            status VARCHAR NOT NULL DEFAULT 'pending',
            decided_by VARCHAR,
            decided_at TIMESTAMPTZ,
            decision_note TEXT,
            preview_summary TEXT,
            execution_summary TEXT
        )
        """
    )
    con.execute("CREATE INDEX IF NOT EXISTS idx_sfrr_job_id ON spend_factor_refresh_requests(job_id)")
    con.execute("CREATE INDEX IF NOT EXISTS idx_sfrr_status ON spend_factor_refresh_requests(status)")


def _preview_job_spend_factor_refresh(con, job_id: int) -> dict[str, Any]:
    """Finds every job_scope_rows / job_spend_entries row on this job whose
    frozen value no longer matches the live factor_lookup value for the same
    factor_db_id (e.g. after DEFRA's in-place revision) and recomputes what
    its emissions figure would become. Nothing is written here -- this is
    also re-run fresh at approval time rather than trusting a stored
    snapshot. dataset_id/factor_db_id/original_id never change here -- the
    row already points at the right factor_lookup row, only that row's
    value did."""
    rows_out: list[dict[str, Any]] = []
    no_match: list[dict[str, Any]] = []
    current_total = 0.0
    projected_total = 0.0

    scope_rows = con.execute(
        """
        SELECT jsr.row_id, jsr.original_id, jsr.dataset_id, jsr.factor_db_id, jsr.uom, jsr.ghg_unit,
               jsr.factor, jsr.calc_tco2e, jsr.qty, jsr.apply_pct, jsr.report_label,
               fl.factor AS live_factor, fl.uom AS live_uom, fl.ghg_unit AS live_ghg_unit
        FROM job_scope_rows jsr
        JOIN factor_lookup fl ON fl.db_id = jsr.factor_db_id
        WHERE jsr.job_id = %s AND COALESCE(jsr.enabled, TRUE) = TRUE
          AND jsr.original_id ILIKE %s
        """,
        [int(job_id), f"{SIC_PREFIX}%"],
    ).fetchall()

    for (row_id, original_id, dataset_id, factor_db_id, uom, ghg_unit,
         factor, calc_tco2e, qty, apply_pct, report_label,
         live_factor, live_uom, live_ghg_unit) in scope_rows:
        # calc_tco2e is NULL on many directly-imported rows (never populated at
        # write time) -- derive the "current" figure the same way rather than
        # trusting a column that's often empty, so the preview's before/after
        # comparison is meaningful.
        if calc_tco2e is not None:
            current_val = float(calc_tco2e)
        else:
            current_val = float(qty or 0.0) * float(factor or 0.0) * (float(apply_pct if apply_pct is not None else 100.0) / 100.0)
            if "kg" in str(ghg_unit or "kgCO2e").lower():
                current_val /= 1000.0
            current_val = round(current_val, 4)
        current_total += current_val

        live_factor_val = float(live_factor or 0.0)
        if abs(float(factor or 0.0) - live_factor_val) < FACTOR_EPSILON:
            projected_total += current_val  # frozen factor already matches live -- nothing to do
            continue

        if str(uom or "").strip().lower() != str(live_uom or "").strip().lower():
            no_match.append({"kind": "job_scope_row", "row_id": row_id, "original_id": original_id, "reason": f"Unit mismatch ({uom} vs {live_uom})"})
            projected_total += current_val
            continue
        new_calc = float(qty or 0.0) * live_factor_val * (float(apply_pct if apply_pct is not None else 100.0) / 100.0)
        if "kg" in str(live_ghg_unit or ghg_unit or "kgCO2e").lower():
            new_calc /= 1000.0
        new_calc = round(new_calc, 4)
        projected_total += new_calc
        rows_out.append({
            "kind": "job_scope_row", "row_id": int(row_id), "original_id": original_id, "report_label": report_label,
            "dataset_id": int(dataset_id), "factor_db_id": int(factor_db_id) if factor_db_id is not None else None,
            "old_factor": float(factor or 0.0), "old_calc_tco2e": current_val,
            "new_ghg_unit": live_ghg_unit, "new_factor": live_factor_val, "new_calc_tco2e": new_calc,
        })

    # job_spend_entries.estimated_emissions_tco2e is computed as amount * factor
    # with no kg->tonne division (see map_spend_row in spend_data_routes.py) --
    # intentionally mirrored here rather than "fixed", so a refreshed row stays
    # internally consistent with every other spend entry in the system.
    spend_rows = con.execute(
        """
        SELECT e.entry_id, fl.original_id, e.dataset_id, e.factor_db_id, e.amount_gross,
               e.estimated_emissions_tco2e, e.mapped_report_label, fl.factor AS live_factor
        FROM job_spend_entries e
        JOIN factor_lookup fl ON fl.db_id = e.factor_db_id
        WHERE e.job_id = %s AND COALESCE(e.is_deleted, FALSE) = FALSE
          AND fl.original_id ILIKE %s
        """,
        [int(job_id), f"{SIC_PREFIX}%"],
    ).fetchall()

    for (entry_id, original_id, dataset_id, factor_db_id, amount_gross,
         estimated_emissions_tco2e, report_label, live_factor) in spend_rows:
        current_val = float(estimated_emissions_tco2e or 0.0)
        current_total += current_val
        new_calc = round(float(amount_gross or 0.0) * float(live_factor or 0.0), 4)
        projected_total += new_calc
        if abs(new_calc - current_val) < FACTOR_EPSILON:
            continue  # already matches what the live factor would produce
        rows_out.append({
            "kind": "job_spend_entry", "row_id": int(entry_id), "original_id": original_id, "report_label": report_label,
            "dataset_id": int(dataset_id), "factor_db_id": int(factor_db_id) if factor_db_id is not None else None,
            "old_calc_tco2e": current_val, "new_factor": float(live_factor or 0.0), "new_calc_tco2e": new_calc,
        })

    return {
        "rows": rows_out,
        "no_match": no_match,
        "rows_affected": len(rows_out),
        "rows_no_match": len(no_match),
        "current_total_tco2e": round(current_total, 4),
        "projected_total_tco2e": round(projected_total, 4),
        "delta_tco2e": round(projected_total - current_total, 4),
    }


@router.post("/jobs/{job_id}/spend-factor-refresh/request")
def request_spend_factor_refresh(job_id: int, body: dict = Body(default={}), _user: dict = Depends(_current_user)):
    assert_permission(_user, "jobs.edit")
    assert_job_access(_user, int(job_id))
    reason = str(body.get("reason") or "").strip()
    try:
        with get_conn() as con:
            _ensure_spend_factor_refresh_schema(con)
            existing = con.execute(
                "SELECT request_id FROM spend_factor_refresh_requests WHERE job_id = %s AND status = 'pending'",
                [int(job_id)],
            ).fetchone()
            if existing:
                raise HTTPException(status_code=409, detail="A refresh request is already pending for this job")
            preview = _preview_job_spend_factor_refresh(con, int(job_id))
            if preview["rows_affected"] == 0:
                raise HTTPException(status_code=400, detail="No spend rows on this job reference a superseded DEFRA factor")
            row = con.execute(
                """
                INSERT INTO spend_factor_refresh_requests (job_id, requested_by, reason, status, preview_summary)
                VALUES (%s, %s, %s, 'pending', %s)
                RETURNING request_id, requested_at
                """,
                [int(job_id), str(_user.get("email") or ""), reason or None, json.dumps(preview, default=str)],
            ).fetchone()
            record_audit_event(
                con, request=None, actor=_user, action="spend_factor_refresh_request",
                entity_type="job", entity_id=int(job_id), job_id=int(job_id),
                metadata={"reason": reason, "rows_affected": preview["rows_affected"], "delta_tco2e": preview["delta_tco2e"]},
            )
        return {"ok": True, "request_id": int(row[0]), "requested_at": str(row[1]), "preview": preview}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to request spend factor refresh: {e}")


@router.get("/jobs/{job_id}/spend-factor-refresh/status")
def get_spend_factor_refresh_status(job_id: int, _user: dict = Depends(_current_user)):
    assert_permission(_user, "jobs.view")
    assert_job_access(_user, int(job_id))
    try:
        with get_conn() as con:
            _ensure_spend_factor_refresh_schema(con)
            preview = _preview_job_spend_factor_refresh(con, int(job_id))
            latest = con.execute(
                """
                SELECT request_id, requested_by, requested_at, reason, status, decided_by, decided_at, decision_note
                FROM spend_factor_refresh_requests
                WHERE job_id = %s
                ORDER BY requested_at DESC
                LIMIT 1
                """,
                [int(job_id)],
            ).fetchone()
            latest_request = None
            if latest:
                latest_request = {
                    "request_id": int(latest[0]), "requested_by": latest[1],
                    "requested_at": str(latest[2]) if latest[2] else None,
                    "reason": latest[3], "status": latest[4], "decided_by": latest[5],
                    "decided_at": str(latest[6]) if latest[6] else None, "decision_note": latest[7],
                }
            job_row = con.execute("SELECT status FROM jobs WHERE job_id = %s", [int(job_id)]).fetchone()
            job_status = str(job_row[0]) if job_row and job_row[0] else None
        return {"job_status": job_status, "preview": preview, "latest_request": latest_request}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load spend factor refresh status: {e}")


@router.get("/admin/spend-factor-refresh-requests")
def list_spend_factor_refresh_requests(status: str = Query("pending"), _user: dict = Depends(_current_user)):
    assert_permission(_user, ADMIN_ACCESS_PERMISSION)
    try:
        with get_conn() as con:
            _ensure_spend_factor_refresh_schema(con)
            where = ""
            params: list[Any] = []
            if status and status != "all":
                where = "WHERE r.status = %s"
                params.append(status)
            rows = con.execute(
                f"""
                SELECT r.request_id, r.job_id, j.job_number, j.title, j.status AS job_status,
                       c.client_name, r.requested_by, r.requested_at, r.reason,
                       r.status, r.decided_by, r.decided_at, r.decision_note, r.preview_summary
                FROM spend_factor_refresh_requests r
                JOIN jobs j ON j.job_id = r.job_id
                LEFT JOIN clients c ON c.db_id = j.client_db_id
                {where}
                ORDER BY r.requested_at DESC
                LIMIT 200
                """,
                params,
            ).fetchall()
        items = []
        for r in rows:
            try:
                preview = json.loads(r[13]) if r[13] else None
            except Exception:
                preview = None
            items.append({
                "request_id": int(r[0]), "job_id": int(r[1]), "job_number": r[2], "job_title": r[3], "job_status": r[4],
                "client_name": r[5], "requested_by": r[6], "requested_at": str(r[7]) if r[7] else None, "reason": r[8],
                "status": r[9], "decided_by": r[10], "decided_at": str(r[11]) if r[11] else None, "decision_note": r[12],
                "preview_summary": preview,
            })
        return {"items": items}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load spend factor refresh requests: {e}")


@router.post("/admin/spend-factor-refresh-requests/{request_id}/decide")
def decide_spend_factor_refresh_request(request_id: int, body: dict = Body(...), _user: dict = Depends(_current_user)):
    assert_super_admin(_user)
    decision = str(body.get("decision") or "").strip().lower()
    note = str(body.get("note") or "").strip()
    if decision not in ("approve", "reject"):
        raise HTTPException(status_code=400, detail="decision must be 'approve' or 'reject'")

    try:
        job_id: int | None = None
        updated_spend_entries = 0
        execution_summary: dict[str, Any] | None = None
        with get_conn(autocommit=False) as con:
            _ensure_spend_factor_refresh_schema(con)
            req_row = con.execute(
                "SELECT job_id, status FROM spend_factor_refresh_requests WHERE request_id = %s",
                [int(request_id)],
            ).fetchone()
            if not req_row:
                raise HTTPException(status_code=404, detail="Request not found")
            job_id, current_status = int(req_row[0]), str(req_row[1])
            if current_status != "pending":
                raise HTTPException(status_code=409, detail=f"Request is already {current_status}")

            if decision == "reject":
                con.execute(
                    """
                    UPDATE spend_factor_refresh_requests
                    SET status = 'rejected', decided_by = %s, decided_at = NOW(), decision_note = %s
                    WHERE request_id = %s
                    """,
                    [str(_user.get("email") or ""), note or None, int(request_id)],
                )
                record_audit_event(
                    con, request=None, actor=_user, action="spend_factor_refresh_reject",
                    entity_type="job", entity_id=job_id, job_id=job_id,
                    metadata={"request_id": int(request_id), "note": note},
                )
                return {"ok": True, "status": "rejected"}

            # decision == "approve" -- re-run the preview fresh rather than trust
            # the (possibly stale) snapshot captured when the request was made.
            preview = _preview_job_spend_factor_refresh(con, job_id)
            if preview["rows_affected"] == 0:
                raise HTTPException(status_code=400, detail="Nothing left to refresh for this job -- it may already have been updated")

            updated_scope_rows = 0
            for row in preview["rows"]:
                if row["kind"] == "job_scope_row":
                    before = fetch_row_dict(con, "SELECT * FROM job_scope_rows WHERE row_id = %s AND job_id = %s", [row["row_id"], job_id])
                    if not before:
                        continue
                    con.execute(
                        """
                        UPDATE job_scope_rows
                        SET factor = %s, ghg_unit = %s, calc_tco2e = %s, updated_at = NOW()
                        WHERE row_id = %s AND job_id = %s
                        """,
                        [row["new_factor"], row["new_ghg_unit"], row["new_calc_tco2e"], row["row_id"], job_id],
                    )
                    after = fetch_row_dict(con, "SELECT * FROM job_scope_rows WHERE row_id = %s AND job_id = %s", [row["row_id"], job_id])
                    record_audit_event(
                        con, request=None, actor=_user, action="update", entity_type="job_scope_row",
                        entity_id=row["row_id"], job_id=job_id, before=before, after=after,
                        metadata={"operation": "spend_factor_refresh", "request_id": int(request_id)},
                    )
                    updated_scope_rows += 1
                else:
                    before = fetch_row_dict(con, "SELECT * FROM job_spend_entries WHERE entry_id = %s AND job_id = %s", [row["row_id"], job_id])
                    if not before:
                        continue
                    con.execute(
                        """
                        UPDATE job_spend_entries
                        SET estimated_emissions_tco2e = %s, updated_at = NOW()
                        WHERE entry_id = %s AND job_id = %s
                        """,
                        [row["new_calc_tco2e"], row["row_id"], job_id],
                    )
                    after = fetch_row_dict(con, "SELECT * FROM job_spend_entries WHERE entry_id = %s AND job_id = %s", [row["row_id"], job_id])
                    record_audit_event(
                        con, request=None, actor=_user, action="update", entity_type="job_spend_entry",
                        entity_id=row["row_id"], job_id=job_id, before=before, after=after,
                        metadata={"operation": "spend_factor_refresh", "request_id": int(request_id)},
                    )
                    updated_spend_entries += 1

            execution_summary = {
                "updated_scope_rows": updated_scope_rows,
                "updated_spend_entries": updated_spend_entries,
                "current_total_tco2e": preview["current_total_tco2e"],
                "projected_total_tco2e": preview["projected_total_tco2e"],
                "delta_tco2e": preview["delta_tco2e"],
            }
            con.execute(
                """
                UPDATE spend_factor_refresh_requests
                SET status = 'approved', decided_by = %s, decided_at = NOW(), decision_note = %s, execution_summary = %s
                WHERE request_id = %s
                """,
                [str(_user.get("email") or ""), note or None, json.dumps(execution_summary, default=str), int(request_id)],
            )
            record_audit_event(
                con, request=None, actor=_user, action="spend_factor_refresh_approve", entity_type="job",
                entity_id=job_id, job_id=job_id, metadata={"request_id": int(request_id), **execution_summary},
            )

        # Outside the transaction: refresh any "Spend Data"-derived scope rows
        # from the now-updated spend entries, reusing the existing tested
        # rollup (sync_spend_to_scope_data) instead of reimplementing it. A
        # failure here doesn't roll back the already-committed refresh above --
        # it's surfaced as a warning so it can be re-run manually.
        sync_warning = None
        if updated_spend_entries:
            try:
                from api.spend_data_routes import sync_spend_to_scope_data
                sync_spend_to_scope_data(int(job_id), {}, _user)
            except Exception as e:
                sync_warning = f"Spend factors were refreshed, but syncing derived scope rows failed: {e}. Run 'Push to Emissions Data' manually for this job."

        return {"ok": True, "status": "approved", "execution_summary": execution_summary, "sync_warning": sync_warning}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to decide spend factor refresh request: {e}")
